### ISSUE TITLE
Wrong information in the docs about run-sh and other io.fabric8 artifacts

### ISSUE THREAD

**Issue by grgrzybek** [eclipse/jkube#1006]
### Info

I was looking at:
* https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin
* https://www.eclipse.org/jkube/docs/openshift-maven-plugin

and I believe these are the transitioned versions of https://dmp.fabric8.io/#maven-goals

For example in the fabric8's docker-maven-plugin there's:
```
Build Plugins

This plugin supports so call dmp-plugins which are used during the build phase. dmp-plugins are enabled by just declaring a dependency in the plugin declaration:

<plugin>
  <groupId>io.fabric8</groupId>
  <artifactId>docker-maven-plugin</artifactId>

  <dependencies>
    <dependency>
      <groupId>io.fabric8</groupId>
      <artifactId>run-java-sh</artifactId>
      <version>1.2.2</version>
    </dependency>
  </dependencies>
</plugin>

These plugins contain a descriptor META-INF/maven/io.fabric8/dmp-plugin with class names, line-by-line:

io.fabric8.runsh.RunShLoader
```

While in jkube docs there's simply:
```
Build Plugins

This plugin supports so call dmp-plugins which are used during the build phase. dmp-plugins are enabled by just declaring a dependency in the plugin declaration:

<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>kubernetes-maven-plugin</artifactId>

  <dependencies>
    <dependency>
      <groupId>org.eclipse.jkube</groupId>
      <artifactId>run-java-sh</artifactId>
      <version>1.2.2</version>
    </dependency>
  </dependencies>
</plugin>

org.eclipse.jkube.runsh.RunShLoader
```

while `kubernetes-maven-plugin` artifact _was_ transitioned from `io.fabric8` to `org.eclipse.jkube` groupId, it isn't the case with `io.fabric8/run-java-sh` GA and `io.fabric8.runsh.RunShLoader` class...

**Comment by rohanKanojia** [comment]
We do have functionality ported from dmp for this. However, DMP_PLUGIN_DESCRIPTOR constant is wrongly configured due to which this functionality doesn't work at the moment. 

https://github.com/eclipse/jkube/blob/40added43dc6fbb180e2c79572628d0471be4195/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java#L101

If I change it to `META-INF/maven/io.fabric8/dmp-plugin`, it works.

I'm able to get [Run Java Sample](url) in Docker Maven Plugin working by changing maven coordinates to `org.eclipse.jkube:kubernetes-maven-plugin` and tuning Dockerfile to add assembly name.

**Comment by manusa** [comment]
Hi @grgrzybek 
We have now properly ported the "plugin"/"extensible" functionality from DMP to JKube.

The documentation has been updated and is available at: [10. JKube Plugins](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#jkube-plugin)

We've also implemented two quickstarts:
- https://github.com/eclipse/jkube/tree/master/quickstarts/maven/plugin/
- https://github.com/eclipse/jkube/tree/master/quickstarts/gradle/plugin

And a video showcasing the Maven [quickstart](https://github.com/eclipse/jkube/tree/master/quickstarts/maven/plugin/) example: https://youtu.be/pzLO-m1WyuU?t=34

**Comment by manusa** [comment]
I'm closing this issue as completed, please feel free to open a new one in case you feel there's still something missing.
