### ISSUE TITLE
UlimitConfig.java: Make the field private final static.

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1016]
### Description

The following statement is reported as a Minor Code Smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AW3z0M55L3SSO-VMZS4f&open=AW3z0M55L3SSO-VMZS4f):
 
https://github.com/eclipse/jkube/blob/053e63e095222c26994984f73a4a4603f5489ef7/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/UlimitConfig.java#L53
 
- [ ] should be changed to:
```java
    private static final Pattern ULIMIT_PATTERN = Pattern.compile("^(?<name>[^=]+)=(?<hard>[^:]*):?(?<soft>[^:]*)$");
```

### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Onyinye91-ctrl** [comment]
@manusa Can i work on this?

**Comment by mehabhalodiya** [comment]
Hey
I would like to contribute!

**Comment by manusa** [comment]
For those of you who already created a commit or tackled another first-timers-only, we really appreciate your willingness to participate, but this issues are intended for new-comers to the project.

We will be creating more `help-wanted` issues, which are intended for those who have already committed to the repo once and still want to collaborate.

**Comment by mehabhalodiya** [comment]
@manusa Yes, I am interested to contribute. I am newbie in this project.

So please do assign it to me.
Thank you.
