### ISSUE TITLE
Enable documentation auto refresh while editing adoc files.

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1034]
### Description
When editing the JKube kubernetes-maven-plugin documentation, it's painful as the writer has to rerun the command mvn -Phtml package each time and it may takes some time to perform the whole generation.

For the kubernetes maven plugin: 
- [x] https://github.com/eclipse/jkube/pull/983
- [x] https://github.com/eclipse/jkube/pull/996 (requiring CQ to be created)

For jube-kit
- [x] maybe add the same profile for https://github.com/eclipse/jkube/tree/master/jkube-kit/doc : https://github.com/eclipse/jkube/pull/1122

**Comment by manusa** [comment]
I'm not sure if the doc-watch profile is available for Gradle plugins
