### ISSUE TITLE
VertxGeneratorTest: Join multiple assertions subject to one assertion chain

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1039]
### Description

We have these two `assertThat` statements checking entries of `env` map. Sonar is reporting this as a [code smell](https://sonarcloud.io/project/issues?id=jkubeio_jkube&open=AXLgGaCDoQqyetADFyGu&resolved=false&types=CODE_SMELL#) and is asking us to combine these two assertions into one by chaining them.

https://github.com/eclipse/jkube/blob/ee2390178dcad8a9cc3a9cb6d5e8c5d70a162a04/jkube-kit/jkube-kit-vertx/src/test/java/org/eclipse/jkube/vertx/generator/VertxGeneratorTest.java#L155-L158

These assertions should be changed to:
```java
assertThat(env)
   .containsEntry("JAVA_OPTIONS", "-Dvertx.cacheDirBase=/tmp/vertx-cache -Dvertx.disableDnsResolver=true " +
        // Force IPv4
   "-Djava.net.preferIPv4Stack=true")
   .containsEntry("JAVA_ARGS", "-cluster");
```

### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by iamdebojyoti** [comment]
Hi @rohanKanojia, Can I work on this?
