### ISSUE TITLE
OpenShiftBuildTask: ocBuild Generator - Quarkus

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1048]
## Description

Child of #31 
Equivalent of and blocked by #1047

ocBuild Gradle task works with Quarkus Generator.

- S2i build works fine

**Comment by sunix** [comment]
Tested in devsandbox the following commands works perfectly on a Quarkus project generated from code.quarkus.io
```
./gradlew quarkusBuild ocBuild ocResource ocApply
```

**Comment by sunix** [comment]
https://github.com/eclipse/jkube/pull/1163 is Fixing it
