### ISSUE TITLE
Building a new image from a detected Dockerfile and podman is showing: `Built image null`

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1055]
### Description

Building a new image from a detected Dockerfile and podman is showing: Built image null
```
[INFO] --- kubernetes-maven-plugin:1.4.0:build (default-cli) @ live-stream-question ---
[INFO] k8s: Running in Kubernetes mode
[INFO] k8s: Building Docker image in Kubernetes mode
[INFO] k8s: [java/live-stream-question:1.0.0]: Created docker-build.tar in 547 milliseconds
[INFO] k8s: [java/live-stream-question:1.0.0]: Built image null
```
### Info

* Eclipse JKube version : 1.4.0
* Maven version (`mvn -v`) : 3.6.3

* Kubernetes / Red Hat OpenShift setup and version :
podman version 3.2.3

* If it's a bug, how to reproduce :

1. `git clone https://github.com/parisjug/live-stream-question.git`
2. Configure podman and start podman rest api:
  ```
export DOCKER_HOST="unix:/run/user/$(id -u)/podman/podman.sock"
podman system service --time=0 unix:/run/user/$(id -u)/podman/podman.sock &
```
3. Add the Jkube build plugin to the pom.xml
   ```
      <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>kubernetes-maven-plugin</artifactId>
        <version>1.4.0</version>
      </plugin>
   ```
4. Run the build `mvn package k8s:build`
![Selection_543](https://user-images.githubusercontent.com/650571/138071293-9fc4f8d1-1a4f-4759-8243-01ccd425755c.png)

The project contains a Dockerfile in the root folder of the repo.

* Sample Reproducer Project : *https://github.com/parisjug/live-stream-question.git*

**Comment by maxdidato** [comment]
Hi, I had the same problem and find out it is related to podmam failing to build the dockerfile. 
If you check the podman logs carefully it will tell you what went wrong. Unfortunately podman doesn't treat that as a fatal error, instead it logs is a DEBUG so JKube goes assuming everything went fine. This happen also when pushing the image to a repo you are not logged in or not have permissions. JKube will just return a green build. I guess the bug is more related to JKube not parsing the podman errors correctly. 

Regarding your situation, you have a bunch of COPY directives in your dockerfile.
Remember that JKube will build and filter your dockerfile in the target folder under a dir hierarchy based on your maven project name. I am sure your build is failing because podman cannot find the file you are asking to copy.
So you need to refer files to copy relatively to that folder (check the target/docker folder to understand what I mean). By default if you don't specify any assembly, you need to access files relatively to the maven/ folder. 

Hope this helps

**Comment by rohanKanojia** [comment]
I think @maxdidato  is right about this being podman issue. Even when I build image with jkube, I see that image isn't created correctly:
```
live-stream-question : $ podman images
REPOSITORY                                   TAG            IMAGE ID      CREATED             SIZE
<none>                                       <none>         dd1b40d14b6f  About a minute ago  1.91 GB
```
When I build image directly using podman using `podman build -t parisjug/livestreamquestion .`  image seems to be built correctly:
```
live-stream-question : $ podman build -t parisjug/livestreamquestion .

...
live-stream-question : $ podman images
REPOSITORY                                   TAG            IMAGE ID      CREATED            SIZE
localhost/parisjug/livestreamquestion        latest         d19f636172e0  2 minutes ago      557 MB
```

On Docker, I'm not able to get a successful build with `k8s:build`, I'm getting this error:
```
[INFO] k8s: Running in Kubernetes mode
[INFO] k8s: Building Docker image in Kubernetes mode
[INFO] k8s: Using Dockerfile: /home/rokumar/work/repos/live-stream-question/Dockerfile
[INFO] k8s: [java/live-stream-question:1.0.0]: Created docker-build.tar in 533 milliseconds
[ERROR] k8s: Failed to execute the build [Error while trying to build the image: Unable to build image [java/live-stream-question:1.0.0] : "The command '/bin/sh -c mvn package' returned a non-zero code: 1" ]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.992 s
[INFO] Finished at: 2021-12-31T22:20:23+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.6.0-SNAPSHOT:build (default-cli) on project live-stream-question: Failed to execute the build: Error while trying to build the image: Unable to build image [java/live-stream-question:1.0.0] : "The command '/bin/sh -c mvn package' returned a non-zero code: 1" -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

**Comment by rohanKanojia** [comment]
I was getting this error due to no maven failing due to no `pom.xml` or source files present in the default context directory chosen by jkube. I'm able to get a successful build if I add a `COPY` statement for adding `pom.xml` and modify rest of the `COPY` statements to use `maven/` prefix.
