### ISSUE TITLE
doc: remove unused asciidoctorj processor `ClasspathIncludeProcessor`

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1070]
### Description
https://github.com/eclipse/jkube/blob/master/kubernetes-maven-plugin/doc/src/main/java/org/eclipse/jkube/maven/doc/ClasspathIncludeProcessor.java#L36 seems not to be used. There is no `classpath:` includes in our doc.
Removing the classes `ClasspathIncludeExtension` and `ClasspathIncludeProcessor` would also help simplifying the dependency management of the doc projects.

- [x] check in the fabric8 maven plugin doc project and see if this is used or not and how.

If it's not used, or it was used for not-applicable features:
- [x] remove `ClasspathIncludeExtension` and `ClasspathIncludeProcessor`
- [x] move the doc projects to `pom` instead of `jar`
- [x] remove the dependencies to `kubernetes-maven-plugin-doc.jar`
- [ ] ~~use the `asciidoctorj` version that is coming as a transitive dependency of the `maven-asciidoctor-plugin`, do not override it.~~ https://github.com/eclipse/jkube/pull/1119#issuecomment-969210620

**Comment by sunix** [comment]
> check in the fabric8 maven plugin doc project and see if this is used or not and how.
It looks like the fmp doc was including doc from docker-maven-plugin
For instance:
https://github.com/fabric8io/fabric8-maven-plugin/blob/master/doc/src/main/asciidoc/inc/goals/build/_fabric8-build.adoc?plain=1#L446
```md
include::classpath:/META-INF/doc/dmp/inc/build/_overview.adoc[]
```
Was including the adoc file from the docker-maven-plugin https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/asciidoc/inc/build/_overview.adoc?plain=1

**Comment by manusa** [comment]
Yes, that's very likely.
We need to check if that doc applies to our project and if we actually migrated the affected docs from DMP too. 

For the ones you mention, I think we did.

**Comment by sunix** [comment]
In any case, if we were willing to use these kind of includes, it would make sense to have it in a separate project. Not in the doc project.

**Comment by manusa** [comment]
So basically the classpath thingy was used to include adoc from other jars. right?

If so, I think it's completely safe to remove that.

**Comment by sunix** [comment]
> So basically the classpath thingy was used to include adoc from other jars. right?
> 
> If so, I think it's completely safe to remove that.

Yes exactly

fabric8-maven-plugin/doc/src/main/asciidoc (master) >_ find -name "*.adoc" |xargs grep "classpath:"
./inc/_appendix.adoc:include::classpath:/META-INF/fabric8/kind-filename-type-mapping-default.adoc[]
./inc/goals/build/_fabric8-build.adoc:include::classpath:/META-INF/doc/dmp/inc/image/_configuration.adoc[]
./inc/goals/build/_fabric8-build.adoc:include::classpath:/META-INF/doc/dmp/inc/build/_overview.adoc[]
./inc/goals/build/_fabric8-build.adoc:include::classpath:/META-INF/doc/dmp/inc/build/_configuration.adoc[]
./inc/goals/build/_fabric8-build.adoc:include::classpath:/META-INF/doc/dmp/inc/build/_assembly.adoc[]
./inc/goals/build/_fabric8-build.adoc:include::classpath:/META-INF/doc/dmp/inc/misc/_env.adoc[]
./inc/goals/build/_fabric8-build.adoc:include::classpath:/META-INF/doc/dmp/inc/misc/_startup.adoc[]
./inc/goals/build/_fabric8-build.adoc:include::classpath:/META-INF/doc/dmp/inc/build/_buildargs.adoc[]
./inc/goals/build/_fabric8-push.adoc:include::classpath:/META-INF/doc/dmp/inc/push/_overview.adoc[]
./inc/goals/build/_fabric8-push.adoc:include::classpath:/META-INF/doc/dmp/inc/push/_configuration.adoc[]
./index.adoc:include::classpath:/META-INF/doc/dmp/inc/_registry.adoc[]
./index.adoc:include::classpath:/META-INF/doc/dmp/inc/_authentication.adoc[]
./index.adoc:// include::classpath:/META-INF/doc/dmp/inc/_docker-build.adoc[]
