### ISSUE TITLE
Create ci.eclipse.org pipeline that verifies test pass on the Jenkins agent

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1087]
### Description

During the 1.5.0 release process the release pipeline had some failing tests. The tests that check the Container image Tar archive failed due to a mismatch in the output size. There were no apparent changes on the runtime environment and the same issue cannot be reproduced locally

https://ci.eclipse.org/jkube/

- [x] Reproduce the issue
- [x] Identify the cause and fix https://github.com/eclipse/jkube/pull/1155
- [x] Create build (JDK 8) pipeline that runs on refs/heads/master change and notifies maintainers in case of failure
- [x] Remove the `-DskipTests` flag in the release pipelines

**Comment by rohanKanojia** [comment]
Can we close this issue?

I've removed `skipTests` from `simplified-downloads-eclipse-release` and `simplified-maven-central-release` pipelines.

I've also added an additional [daily build](https://ci.eclipse.org/jkube/job/daily-build/) pipeline which will be triggered by SCM changes on Eclipse JKube master branch. It would also be built periodically every day.
