### ISSUE TITLE
DockerRegistrySecretEnricherTest: Use `.hasSize()` instead of getting and comparing size of  map

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1089]
### Description

We have this usage of AssertJ where we're asserting a map's size:
https://github.com/eclipse/jkube/blob/a49aff150d4cee4cba39c2305e8096721444d0c3/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DockerRegistrySecretEnricherTest.java#L79

AssertJ already has a `hasSize()` method. This statement can be simplified to:
```java
assertThat(enrichedData).hasSize(1);
```

### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. **Pay special attention to the ECA agreement section and the requirement to sign-off your commit.**
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by abhi30996** [comment]
Hi. I would like to work on this issue. Is it still available?

**Comment by Ejaz29** [comment]
hi @rohanKanojia is this issue available? I would like to work on it.

**Comment by srivishnu2101-1** [comment]
Created a PR https://github.com/eclipse/jkube/pull/1099

**Comment by Aman-Mandal** [comment]
is this issue still there?

**Comment by manusa** [comment]
This issue was duplicated in #1161 and solved by #1166
