### ISSUE TITLE
KubernetesResourceUtil: Replace deprecated usage of JsonMappingException constructor

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1090]
### Description

In KubernetesResourceUtil.readFragment method, we're using this constructor for JsonMappingException:
https://github.com/eclipse/jkube/blob/a49aff150d4cee4cba39c2305e8096721444d0c3/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L383

This has been marked deprecated as per latest Jackson Databind documentation. We can use the static methods for creating exceptions:
```java
throw JsonMappingException.from(mapper.getDeserializationContext(), String.format("[%s] %s", file, e.getMessage()));
``` 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. **Pay special attention to the ECA agreement section and the requirement to sign-off your commit.**
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by shivkushwaha1511** [comment]
I want to contribute to this issue, could you please assign it to me

**Comment by rohanKanojia** [comment]
Sorry, while reviewing your PR I realized this issue is no longer applicable after the recent refactor in #1124 .

**Comment by rohanKanojia** [comment]
@shivkushwaha1511 : I think we can close this issue. Shall I create some other good first issue for you? Would you be willing to work on that?

**Comment by shivkushwaha1511** [comment]
Yes! Please

**Comment by rohanKanojia** [comment]
@shivkushwaha1511 : Thanks for showing interest. I'll create one issue and let you know
