### ISSUE TITLE
WildflyJARGeneratorTest: Replace `Collections.EMPTY_LIST` with `Collections.emptyList()`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1095]
### Description

Usage of `Collections.emptyList()` is preferable since it uses type-inference and therefore returns `List<T>`. These places can be updated to use `Collections.emptyList()` instead:

https://github.com/eclipse/jkube/blob/a49aff150d4cee4cba39c2305e8096721444d0c3/jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGeneratorTest.java#L60

https://github.com/eclipse/jkube/blob/a49aff150d4cee4cba39c2305e8096721444d0c3/jkube-kit/jkube-kit-wildfly-jar/src/test/java/org/eclipse/jkube/wildfly/jar/generator/WildflyJARGeneratorTest.java#L270

### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. **Pay special attention to the ECA agreement section and the requirement to sign-off your commit.**
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by anirudhbagri** [comment]
Hi, 
I would like to take up this one.. Can you assign this to me?

**Comment by anirudhbagri** [comment]
Hi @rohanKanojia, Can you add `hacktoberfest-accepted` label to this PR so that it counts towards it.

**Comment by manusa** [comment]
> Hi @rohanKanojia, Can you add `hacktoberfest-accepted` label to this PR so that it counts towards it.

Your PR is not compiling. Your change also requires removing the no longer necessary casting.

Your commits also seem to be signed by the anonymous GitHub user. This should be addressed too.

**Comment by Patralekha** [comment]
Hi I would like to take up issue #1096 .Can you assign me to this?
