### ISSUE TITLE
Docker issue - Fails to create non-root user

### ISSUE THREAD

**Issue by javastl** [eclipse/jkube#1100]
### Info

* Eclipse JKube version :
* Maven version (`mvn -v`) :Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
```

```
* Kubernetes / Red Hat OpenShift setup and version : v1.21.0

* If it's a bug, how to reproduce : pom include below
* <?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.5.4</version>
    <relativePath/> 
</parent>
<groupId>com.javastl</groupId>
<artifactId>csv-app</artifactId>
<version>1.1</version>
<name>csv</name>
<description>Demo project for Spring Boot</description>
<properties>

    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <java.version>11</java.version>
    <docker.user>bwiwebsphere</docker.user>
    
    <jkube.version>1.5.1</jkube.version>
    <jkube.namespace>csv</jkube.namespace>
    <jkube.docker.registry>docker.io</jkube.docker.registry>
    <jkube.generator.webapp.user>1000:1000:1000</jkube.generator.webapp.user>
    <jkube.createExternalUrls>true</jkube.createExternalUrls>
    <jkube.generator.webapp.path>/csv</jkube.generator.webapp.path>

    <jkube.replicas>3</jkube.replicas>
    <jkube.enricher.jkube-service.type>NodePort</jkube.enricher.jkube-service.type>

    
    <jkube.enricher.jkube-service.expose>true</jkube.enricher.jkube-service.expose>
    
    <jkube.generator.name>${docker.user}/random-generator:${project.version}</jkube.generator.name>
    
</properties>
<dependencies>
    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

    <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-test</artifactId>
        <scope>test</scope>
    </dependency>
    
    <dependency>
        <groupId>javainetlocator</groupId>
        <artifactId>inetaddresslocator</artifactId>
        <version>2.18</version>
    </dependency>

</dependencies>

<build>
    <plugins>
        <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
        </plugin>
        <plugin>
            <groupId>org.eclipse.jkube</groupId>
            <artifactId>kubernetes-maven-plugin</artifactId>
            <version>1.4.0</version>
        </plugin>
        <plugin>
            <groupId>org.eclipse.jkube</groupId>
            <artifactId>openshift-maven-plugin</artifactId>
            <version>1.4.0</version>
        </plugin>
    </plugins>
</build>

</project>

* If it's a feature request, what is your use case : Generate webapp user
* jkube.generator.webapp.user

* Sample Reproducer Project : https://github.com/javastl/csv

**Comment by javastl** [comment]
I was using the wrong property for the user
<jkube.generator.webapp.user>
Intended only for tomcat, wildly etc.   Not for setting up docker groups or user in the container

**Comment by manusa** [comment]
Hi, I think this was in scope of https://github.com/eclipse/jkube/issues/381#issuecomment-955583878.

The assembly user can be setup for images configured via XML.

Sorry for the late reply.
