### ISSUE TITLE
Add E2E test for CustomResources in JKube Integration tests

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1130]
### Description

Right now we don't seem to have any E2E test which verifies the application of Custom Resource manifests onto a Kubernetes Cluster . We need to create an E2E test in [jkube-integration-tests](https://github.com/jkubeio/jkube-integration-tests/tree/main/projects-to-be-tested) similar to [spring-boot-crd](https://github.com/eclipse/jkube/tree/master/quickstarts/maven/spring-boot-crd) quickstart where E2E test would verify the following things:
- Application gets successfully deployed into a Kubernetes Cluster and is accessible via Service
- Custom Resources applied during `k8s:apply`/`k8sApply` goals/tasks are created successfully
- On `k8s:undeploy`/`k8sUndeploy` CustomResource manifests and application resources are cleaned up from Kubernetes Server

**Comment by manusa** [comment]
Implemented in https://github.com/jkubeio/jkube-integration-tests/pull/118
