### ISSUE TITLE
Update Asciinema intro content with something more up to date

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1154]
### Description

The current Asciinema intros are very outdated.
- https://asciinema.org/a/335724
- https://asciinema.org/a/335743
- https://www.eclipse.org/jkube/demos

We should replace with something more updated (maybe Asciinema too, or just a plain YouTube video).

**Comment by rohanKanojia** [comment]
Final version:

> I've slowed down slides segments by 25%:
Kubernetes Maven Plugin https://drive.google.com/file/d/1vD62e4KuiiGHmrLXsN144190hPT2wlL-/view?usp=sharing
OpenShift Maven Plugin https://drive.google.com/file/d/1_wiIe2f3YiGYMIpgnF84m-x-wGIATfCR/view?usp=sharing
Kubernetes Gradle Plugin https://drive.google.com/file/d/1I2VFAyUOf55s-4PXImbYGjncPOKxHGbm/view?usp=sharing
OpenShift Gradle Plugin https://drive.google.com/file/d/1RYSnoBBSnAn7Qw7a6H2OLt4SvIpzQpIz/view?usp=sharing

**Comment by manusa** [comment]
https://github.com/jkubeio/jkube-website/pull/51
