### ISSUE TITLE
kubernetes gradle plugin: Should k8sBuild require kubernetes cluster to be configured ?

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1156]
### Description
I am trying to run k8sBuild and get this error with podman:
```
$ ./gradlew k8sBuild

> Task :k8sBuild
k8s: Cannot access cluster for detecting mode: Failure executing: GET at: https://XX.XX.XX.XX/apis. Message: Forbidden! User gke_eclipse-che-1-XXXXXX_europe-west1-b_eclipse-che-XXXXXX doesn't have permission. forbidden: User "system:anonymous" cannot get path "/apis".
k8s: Running in Kubernetes mode
k8s: Building container image in Kubernetes mode

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed

$ podman images
REPOSITORY  TAG         IMAGE ID    CREATED     SIZE
```
1. this is strange that it is requiring kubernetes to be configured to work.
2. it is marked as successful but no image has been built.

### Info

* Eclipse JKube version : 1.6.0-SNAPSHOT

* Sample Reproducer Project : testing with a gradle project generated from https://code.quarkus.io/

**Comment by manusa** [comment]
One option could be to make the client and clusterAccess fields in JKubeServiceHub lazy.

They would only be initialized provided that we are not offline and only when they are needed.
