### ISSUE TITLE
DockerRegistrySecretEnricherTest: Simplify AssertJ assertion for validating Map size

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1161]
### Description

We have this redundant assert statement in DockerRegistrySecretEnricherTest:
https://github.com/eclipse/jkube/blob/c494048705945b4312a77f2152b2023464567caa/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DockerRegistrySecretEnricherTest.java#L79

AssertJ `assertThat` also has a `hasSize` method which accepts a map. This method should be used instead. Also on line 82, we're using a deprecated `new JsonParser().parse` method.

https://github.com/eclipse/jkube/blob/c494048705945b4312a77f2152b2023464567caa/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DockerRegistrySecretEnricherTest.java#L82
 It should also be replaced by static `JsonParser.parseString` method like this:

```java
JsonObject auths = (JsonObject) JsonParser.parseString(new String(Base64.decodeBase64(data)));
```

So this issue consists of the following tasks:
- [x] Use `assertThat().hasSize` method instead of manually getting size and asserting it
- [x] Use `JsonParser.parseString` static method instead of `@Deprecated` `parse` method

### Before you contribute
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. **Pay special attention to the ECA agreement section and the requirement to sign-off your commit.**. I list the following steps for contributing:
1. Create an [Eclipse Account](https://accounts.eclipse.org/).
2. Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca)
3. Configure your local Git with the correct username and email (with which you registered for Eclipse):
 ```
git config user.name "Your Name"
git config user.email "your_email@example.com"
 ```
4. Do you changes locally, while committing use `git commit --signoff` instead of `git commit`. `--signoff` flag would automatically add the `Signed-Off By` footer to your commit message

#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by rohanKanojia** [comment]
@shivkushwaha1511: I've created this issue in case you're interested. Please review this and let me know if you want to work on this issue. I can assign you this issue then. If you have any questions regarding this, please feel free to reach out to our team on Gitter channel: https://gitter.im/eclipse/jkube

**Comment by shivkushwaha1511** [comment]
Yes! I like to contribute to this
