### ISSUE TITLE
Using JKube together with Cert Manager

### ISSUE THREAD

**Issue by TueDissingWork** [eclipse/jkube#1170]
### Description*
We have a K8s (1.21) cluster that uses Cert Manager and we therefore need to annotate the `Ingress` resource. This however present a small challenge as we can't create annotations using the XML configuration, which includes a slash ("/").
Here's an example of the needed annotations, which helps Cert Manager generate the needed certs:
```
annotations:
  cert-manager.io/cluster-issuer: vault-issuer
  cert-manager.io/common-name: nginx-demo.toolchain.k8s.internal
```
How can I apply these annotations without creating resource fragtments, as this makes the project configuration more complex. We also uses the `environment` feature; which then would require us to create resource fragments for each of these environments.

**Is there a smarter way?**

### Info

* Eclipse JKube version : 1.5.1
* Maven version (`mvn -v`) : 
```
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: GraalVM Community, runtime: /home/tue/.sdkman/candidates/java/21.0.0.2.r11-grl
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-19041-microsoft", arch: "amd64", family: "unix"
```
* Kubernetes / Red Hat OpenShift setup and version :
Rancher provisioned AKS cluster running with version 1.21.6

**Comment by rohanKanojia** [comment]
Umm, I had faced this problem as well. But I was able to provide `/` in annotation like this:
```xml
            <annotations>
              <all>
                <property>
                  <name>cert-manager/cluster-issuer</name>
                  <value>vault-issuer</value>
                </property>
              </all>
            </annotations>
```

**Comment by manusa** [comment]
Yes, I think this has come up a few times. I'm not sure if we even added an example for this.

**Comment by TueDissingWork** [comment]
> Umm, I had faced this problem as well. But I was able to provide `/` in annotation like this:
> 
> ```
>             <annotations>
>               <all>
>                 <property>
>                   <name>cert-manager/cluster-issuer</name>
>                   <value>vault-issuer</value>
>                 </property>
>               </all>
>             </annotations>
> ```

This does the job. Thanks a lot!
