### ISSUE TITLE
Multiple ConfigMaps in XML configuration

### ISSUE THREAD

**Issue by tipame** [eclipse/jkube#1174]
### Description
XML configuration limits number of ConfigMaps by one. There is no way to define two or more ConfigMaps with XML configuration.
I found a way to generate config map from files in directory very convenient. But where is no way to have multiple ConfigMaps created from differend directories... 

### Info
* Eclipse JKube version : 1.5.1
* Maven version : 3.6.3

**Comment by manusa** [comment]
Duplicate of #249.
@tipame, you can vote for that issue.
