### ISSUE TITLE
Add telemetry and collect anonymous information about jkube usage

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1182]
### Description
From one version to another, we would like to know if our improvements or new features are making users achieving their goals:

How far users go for each kind of project ?
Have the users managed to build, generates the k8s resources, deploy them to their cluster ? etc...
Are users giving up after the first build because it failed ?
Are users going further after we added some hints ?

These are the kind of questions we would like to have metrics to make JKube a better project.

The goal of this issue is to 
- look at how we could implement that (maybe using Red Hat developers existing infra for this with woopra or something else -> see how things were done in VSCode extensions). Using Segment + Woopra ?
- implementation:
  - ask the user to opt-in or out interactively + tell the user how to opt-out with env variable and/or java properties
  - should inform the user that these are anonymous + link where these informations are collected and avaiable
  - should ask once, and save/remember the choice for the next executions
  - detect TTY and don't ask/collect if it is executed in CI env
- informations to retrieve for each maven "call"
  - how far did the user go (build, resource, apply/deploy, etc helm) + failure or success
  - target: minikube, openshift, gcp, etc.
  - framework: quarkus, springboot, etc ...
  - build type: docker, podman, jib, dockerfile, s2i, etc...
  - zero-config ? or custom config ?
  - ingress/route?

Information we send maybe related to the "summary" issue https://github.com/eclipse/jkube/issues/1033. Possibly collect, show and send the same information.

### Alternatives
- Add a anonymous survey link when executing a command at the end
- Add a 1 questions anonymous survey link related to the executed command. for instance, executing a build command could just ask questions about the build or more generic.
- Make a weekly 1 question survey available in twitter, website, github, chat, output ,,, with a predifined hashtag

**Comment by manusa** [comment]
woopra

**Comment by sunix** [comment]
It is very difficult at the moment that third party companies collect information of a community project. At the moment the eclipse foundation do not have such services. I am closing this as won't fix for now.
