### ISSUE TITLE
Add Support for specifying multiple tags in Zero Configuration mode

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1188]
### Description

This was originally suggested by @kameshsampath in chat. I'm just creating an issue about it for reference.

Right now if user wants to provide multiple tags on container image during build/push goals. He has to provide full image configuration like this:
```xml
            <plugin>
                <groupId>org.eclipse.jkube</groupId>
                <artifactId>kubernetes-maven-plugin</artifactId>
                <version>${jkube.version}</version>
                <configuration>
                  <images>
                    <image>
                      <name>${docker.user}/random-generator:${project.version}</name>
                      <build>
                        <from>quay.io/jkube/jkube-java-binary-s2i:0.0.10</from>
                        <assembly>
                        </assembly>
                        <tags>
                          <tag>${project.version}</tag>
                          <tag>latest</tag>
                        </tags>
                      </build>
                    </image>
                  </images>
                </configuration>
            </plugin>
```

It would be nice if we could support specifying multiple tags in zero-configuration mode via specifying some property. 

I think we can implement this via adding a configuration option in BaseGenerator about comma-separated tags string:

https://github.com/eclipse/jkube/blob/bdfb00e1b02a7cbd84723ccf24a7413f940b4ebd/jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java#L59-L64

this configuration can be parsed later and tags can be added to BuildConfiguration builder, like `latest` tag is added for `-SNAPSHOT` versions here:

https://github.com/eclipse/jkube/blob/bdfb00e1b02a7cbd84723ccf24a7413f940b4ebd/jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java#L224

If we do this user would be able to specify multiple tags by just specifying generator config as property:
```xml
<jkube.generator.spring-boot.tags>tag1,tag2</jkube.generator.spring-boot.tags>
```
### Info

* Eclipse JKube version : 1.5.1
* Maven version (`mvn -v`) :
```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /opt/apache-maven
Java version: 11.0.11, vendor: Oracle Corporation, runtime: /usr/java/jdk-11.0.11
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.7-200.fc35.x86_64", arch: "amd64", family: "unix"
```
* Kubernetes / Red Hat OpenShift setup and version : N/A

* If it's a bug, how to reproduce : N/A

* If it's a feature request, what is your use case : Allow specifying multiple tags on opinionated images

* Sample Reproducer Project : N/A

**Comment by kameshsampath** [comment]
thanks @rohanKanojia  @manusa  for adding this :)

**Comment by manusa** [comment]
> thanks @rohanKanojia @manusa for adding this :)

Nice to read you :)

I'm not sure if you're still using JKube, but Your feedback is very good, and you know we really appreciate it.
If you think of any other missing features or enhancements, please don't hesitate to reach out to us ;)

**Comment by kameshsampath** [comment]
sure thing! thanks for the trust 🙂
________________________________
