### ISSUE TITLE
jkube-controller name configuration ignored when using resource fragments

### ISSUE THREAD

**Issue by petergarnaes** [eclipse/jkube#1194]
### Description

I have a vanilla Spring Initializr demo project showing the issue [here](https://github.com/petergarnaes/maven-kubernetes-plugin-bug-demo).

Two important things to notice:
 1. I use a deployment resource fragment `src/main/jkube/deployment.yaml`. This resource fragment does **not** overwrite `deployment.metadata.name`
 2. I have configured the name of the jkube-controller in the `pom.xml` to `overwrite`, as allowed in [docs](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#jkube-controller).

However, when running `mvn k8s:resource`, looking at `target/classes/META-INF/jkube/kubernetes`, I would expect the file `overwrite-deployment.yaml` with the deployment yaml `deployment.metadata.name=overwrite`, but I instead get the defaulting behavior with the file `${project.artifactId}-deployment.yaml` and yaml `deployment.metadata.name=${project.artifactId}`.

If I delete the resource fragment `src/main/jkube/deployment.yaml` I get the file `overwrite-deployment.yaml` with the deployment yaml `deployment.metadata.name=overwrite` as expected, but of course no resource fragment inserted.

I don't know if this issue applies to the other jkube-controller config elements.

### Info

* Eclipse JKube version : 1.5.1
* Maven version (`mvn -v`) :
```
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Java version: 17.0.1, vendor: Private Build, runtime: /usr/lib/jvm/java-17-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-163-generic", arch: "amd64", family: "unix"
```
### Kubernetes / Red Hat OpenShift setup and version :

Not relevant

### Sample Reproducer Project : 

*[GitHub Clone URL](https://github.com/petergarnaes/maven-kubernetes-plugin-bug-demo)*

### If it's a bug, how to reproduce :

Run `mvn k8s:resourse` in the sample reproduce project, look at output in `target/classes/META-INF/jkube/kubernetes`

**Comment by rohanKanojia** [comment]
I think maybe you're mixing two configuration options. Right now while reading resource fragments, `name` is being interpreted from file name, if it's not found opinionated name is used:

https://github.com/eclipse/jkube/blob/b66213473b17a4d4c25096fc02055ce33197797b/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L305-L308

If you rename `src/main/jkube/deployment.yml` -> `src/main/jkube/overwrite-deployment.yml` it should set your generated Deployment name to `overwrite`

**Comment by petergarnaes** [comment]
I am mixing two configuration options, which I thought was supported. During my reading of the docs I didn't see anything discouraging this, but maybe I missed something. 

In the [docs for jkube-controller](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#jkube-controller) it is stated:

> An explicit configuration always takes precedence over auto detection.

The way it is stated leads me to believe it is a general statement about configuration in the kubernetes-maven-plugin. Since the controller name setting in `pom.xml` is explicit, as opposed to the auto-detected name when using a resource fragment named `deployment.yaml`, I would expect the controller name setting in `pom.xml` to "win".

The reason I want to use the `pom.xml` configuration along with the resource fragment, is because I want the deployment name to be determined by a maven profile, while still needing the resource fragments for my particular usecase.

**Comment by rohanKanojia** [comment]
If we want to support this, this can be done by editing DeploymentBuilder during merging fragements:
```diff
diff --git a/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricher.java b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricher.java
index e2f0c564..367ba238 100644
--- a/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricher.java
+++ b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ControllerViaPluginConfigurationEnricher.java
@@ -112,6 +112,7 @@ public class ControllerViaPluginConfigurationEnricher extends BaseEnricher {
                         @Override
                         public void visit(DeploymentBuilder deploymentBuilder) {
                             deploymentBuilder.editOrNewSpec().editOrNewTemplate().editOrNewSpec().endSpec().endTemplate().endSpec();
+                            deploymentBuilder.editOrNewMetadata().withName(name).endMetadata();
                             mergeDeploymentSpec(deploymentBuilder, spec);
                         }
                     });
```

then you should be able to override with configuration like this:
```xml
<configuration>
	<enricher>
		<config>
			<jkube-controller-from-configuration>
				<name>overwrite</name>
			</jkube-controller-from-configuration>
		</config>
	</enricher>
</configuration>
```

**Comment by manusa** [comment]
I think this can be categorized as a bug.

As a workaround, your resource fragment can specify the name as
```yaml
metadata:
  name: ${propertyInPomXml}
```

Then in your `pom.xml` you can set the property value for each profile and JKube will interpolate when reading the fragment.

**Comment by rohanKanojia** [comment]
When #1455 gets merged, you should be able to change name of generated Deployment with a configuration like this:
```xml
        <configuration>
                <enricher>
                        <config>
                                <jkube-controller-from-configuration>
                                        <name>overwrite</name>
                                </jkube-controller-from-configuration>
                        </config>
                </enricher>
        </configuration>
```
