### ISSUE TITLE
kubernetes-maven-plugin - Skipped images still are pushed, which fails

### ISSUE THREAD

**Issue by Diom** [eclipse/jkube#1195]
### Description

As a dev I want to be able to skip the build and push of certain images based on property in my POM.

I can set up the build to skip certain images but it fails when being pushed as the images that were skipped do not exist. It should be possible to skip the deployment of specific images, via the same or a different configuration property.

Error:

> [ERROR] k8s: Error while trying to push the image: Unable to add tag [yyz.ocir.io/frxxxxxxxb/my-image:tf-014] to image [frxxxxxxxb/my-image:tf-014] : {"message":"No such image: frxxxxxxxb/my-image:tf-014"} (Not Found: 404) [Error while trying to push the image: Unable to add tag [yyz.ocir.io/frxxxxxxxb/my-image:tf-014] to image [frxxxxxxxb/my-image:tf-014] : {"message":"No such image: frxxxxxxxb/my-image:tf-014"} (Not Found: 404)]

### Info

* Eclipse JKube version : 1.5.1
* Maven version (`mvn -v`) : Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

Configuration is as so:

```xml
<plugin>
    <groupId>org.eclipse.jkube</groupId>
    <artifactId>kubernetes-maven-plugin</artifactId>
    <version>1.5.1</version>
    <executions>
        <execution>
            <id>docker-build</id>
            <phase>package</phase>
            <goals>
                <goal>build</goal>
            </goals>
        </execution>
        <execution>
            <id>docker-registry-push</id>
            <phase>deploy</phase>
            <goals>
                <goal>push</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <images>
            <image>
                <name>${dockerRepoPrefix}/%a:%v</name>
                <alias>aws-deployer</alias>
                <build>
                    <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                    <tags>
                        <tag>latest</tag>
                    </tags>
                    <args>
                        <terraform_version>${dkr-terraform-version}</terraform_version>
                    </args>
                </build>
            </image>
            <image>
                <name>${dockerRepoPrefix}/%a:tf-014</name>
                <alias>aws-deployer</alias>
                <build>
                    <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                    <skip>${skipTfVers}</skip>
                    <args>
                        <terraform_version>0.14.11</terraform_version>
                    </args>
                </build>
            </image>
            <image>
                <name>${dockerRepoPrefix}/%a:tf-013</name>
                <alias>aws-deployer</alias>
                <build>
                    <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                    <skip>${skipTfVers}</skip>
                    <args>
                        <terraform_version>0.13.7</terraform_version>
                    </args>
                </build>
            </image>
            <image>
                <name>${dockerRepoPrefix}/%a:tf-012</name>
                <alias>aws-deployer</alias>
                <build>
                    <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                    <skip>${skipTfVers}</skip>
                    <args>
                        <terraform_version>0.12.26</terraform_version>
                    </args>
                </build>
            </image>
        </images>
    </configuration>
</plugin>
```

#### Repro Steps

Run the above config with the following command:
`mvn deploy -D'skipTfVers=true'`

Note that the build phase correctly skips the indicated images with the particular TF versions, but it fails when the deploy is due to occur as (with a clear local reg) the images do not exist. I could find no way to specify `skipPush` at the image level (hopefully I have just missed that)

**Comment by rohanKanojia** [comment]
@Diom : Hi, Thanks for reporting the issue. I think it makes sense to add an additional field `skipPush` or use already existing `skip` field in BuildConfiguration to skip pushing.

We can filter out image configurations here which don't have `skip` enabled:

https://github.com/eclipse/jkube/blob/b66213473b17a4d4c25096fc02055ce33197797b/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/PushMojo.java#L59

**Comment by Diom** [comment]
@rohanKanojia I guess this means that there is no current way to do this.
I will definitely consider a PR based on your info above. Will look into the dev guidelines when I get a chance.

**Comment by rohanKanojia** [comment]
@Diom : Thanks a lot! Here is link to our contributing doc: https://www.eclipse.org/jkube/contributing . It's not so much different from other repositories apart from creating Eclipse Account, signing ECA and adding signed off footer.

Feel free to ask any questions regarding contributing here https://gitter.im/eclipse/jkube

**Comment by rohanKanojia** [comment]
@Diom : Since I'm working on related issue https://github.com/eclipse/jkube/issues/1197 . Do you mind if I pick up this one as well?

**Comment by Diom** [comment]
> @Diom : Since I'm working on related issue #1197 . Do you mind if I pick up this one as well?

@rohanKanojia - Sorry I had completely let this slip my mind. Thanks for picking it up 👍🏻
