### ISSUE TITLE
OpenShiftBuildTask: ocBuild Generator - WebApp

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1208]
## Description

Child of #31 
Equivalent of and blocked by #1207

ocBuild Gradle task works with WebApp Generator.

- [x] S2i build works fine (Tomcat/default) https://github.com/eclipse/jkube/pull/1405
- [x] S2i build works fine (Jetty) https://github.com/eclipse/jkube/pull/1405
- [x] S2i build works fine (WildFly AppServer):
   - https://github.com/eclipse/jkube/pull/1351
   - https://github.com/eclipse/jkube/pull/1403

**Comment by manusa** [comment]
Does your configuration change the image user, it should be 1000:1000?

**Comment by sunix** [comment]
this is strange, it's trying to use `jboss/wildfly:25.0.0.Final` as base image, but I see
```
jkube-kit/generator/webapp/target/classes/META-INF/jkube/default-images.properties
19:wildfly.upstream.docker=jboss/wildfly:25.0.0.Final
20:wildfly.upstream.s2i=quay.io/wildfly/wildfly-centos7:26.0
21:wildfly.upstream.istag=wildfly:26.0
```
should be using `quay.io/wildfly/wildfly-centos7:26.0` as it is an s2i build.

**Comment by manusa** [comment]
Are you sure you're running an S2i build and not an OpenShift Docker build?

**Comment by sunix** [comment]
with Maven it is working fine:
```
[INFO] oc: Starting Build webapp-wildfly-datasource-s2i
[INFO] oc: Waiting for build webapp-wildfly-datasource-s2i-1 to complete...
[INFO] oc: time="2022-03-08T09:10:52Z" level=info msg="Not using native diff for overlay, this may cause degraded performance for building images: kernel has CONFIG_OVERLAY_FS_REDIRECT_DIR enabled"
[INFO] oc: I0308 09:10:52.392643       1 defaults.go:102] Defaulting to storage driver "overlay" with options [mountopt=metacopy=on].
[INFO] oc: Caching blobs under "/var/cache/blobs".
[INFO] oc: Trying to pull quay.io/wildfly/wildfly-centos7:26.0...
```
And build success

**Comment by manusa** [comment]
Maybe something wrong in the gradle project setup? it looks like something is not triggering in the Generator.

**Comment by sunix** [comment]
In gradle
```
> Task :ocBuild
oc: Running in OpenShift mode
oc: Running generator webapp
oc: webapp: Using jboss/wildfly:25.0.0.Final as base image for webapp
```
I am going to debug to see the difference.

**Comment by sunix** [comment]
what is strange is that the log `Using OpenShift build with strategy S2I` is after `webapp: Using jboss/wildfly:25.0.0.Final as base image for webapp`

**Comment by sunix** [comment]
I am going to provide a fix to `OpenShiftBuildTask.java`:
```
  @Override
  protected BuildServiceConfig.BuildServiceConfigBuilder buildServiceConfigBuilder() {
    return super.buildServiceConfigBuilder()
        .jKubeBuildStrategy(getOpenShiftExtension().getBuildStrategyOrDefault())
```

**Comment by sunix** [comment]
ok finally the fix is 
```
diff --git a/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java b/gradle-plugin/kuberne>
index f2085b10..259fff03 100644
--- a/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
+++ b/gradle-plugin/kubernetes/src/main/java/org/eclipse/jkube/gradle/plugin/task/AbstractJKubeTask.java
@@ -152,6 +152,7 @@ public abstract class AbstractJKubeTask extends DefaultTask implements Kubernete
         .project(kubernetesExtension.javaProject)
         .logger(kitLogger)
         .runtimeMode(kubernetesExtension.getRuntimeMode())
+        .strategy(kubernetesExtension.getBuildStrategyOrDefault())
         .useProjectClasspath(kubernetesExtension.getUseProjectClassPathOrDefault());
   }
```
`.jKubeBuildStrategy(getOpenShiftExtension().getBuildStrategyOrDefault())` is already called in `TaskUtil`. So 

In mid term we need to see if we could avoid initializing things twice in `GeneratorContextBuilder` and `BuildServiceConfig`. Maybe the `GeneratorContextBuilder` should pick from the `BuildServiceConfig`.

**Comment by manusa** [comment]
This has probably survived after a few releases because for most of the rest of the supported frameworks ---> Generators, the image is the same for S2I and Docker-compatible builds.
This change will fix the issue for every other Generator that provides different images for Docker and S2I.
As soon as we finish with enrichers we need to start working on the E2E tests so we identify this problems earlier.

**Comment by sunix** [comment]
Now deploying `quickstarts/gradle/webapp-wildfly`:
```
[0m[0m09:17:21,123 INFO  [org.jboss.weld.Version] (MSC service thread 1-2) WELD-000900: 3.1.8 (Final)
[0m[31m09:17:21,513 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "ROOT.war")]) - failure description: {
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.jdbc-driver.h2"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => ["jboss.data-source.\"jboss.naming.context.java.jboss.datasources.JKubeCommitersDS\" is missing [jboss.jdbc-driver.h2]"]
}
[0m[0m09:17:21,630 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 36) WFLYSRV0010: Deployed "ROOT.war" (runtime-name : "ROOT.war")
[0m[0m09:17:21,631 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0184:    New missing/unsatisfied dependencies:
      service jboss.jdbc-driver.h2 (missing) dependents: [service jboss.data-source."jboss.naming.context.java.jboss.datasources.JKubeCommitersDS"]
WFLYCTL0448: 21 additional services are down due to their dependencies being missing or failed
[0m[0m09:17:21,723 INFO  [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0212: Resuming server
[0m[31m09:17:21,724 ERROR [org.jboss.as] (Controller Boot Thread) WFLYSRV0026: WildFly Full 26.0.0.Final (WildFly Core 18.0.0.Final) started (with errors) in 4602ms - Started 311 of 574 services (24 services failed or missing dependencies, 337 services are lazy, passive or on-demand)
[0m[0m09:17:21,725 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0060: Http management interface listening on http://0.0.0.0:9990/management
[0m[0m09:17:21,725 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0054: Admin console is not enabled
```
it looks like it is missing h2 drivers.
It seems it could be enabled by passing `GALEON_PROVISION_LAYERS` env variable with `datasources-web-server` to the s2i build. https://github.com/wildfly/wildfly-s2i/blob/wf-18.0/README.md

**Comment by sunix** [comment]
I managed to get rid of these errors by passing manually `GALEON_PROVISION_LAYERS=datasources-web-server` 

Now I get the JBoss Wildfly main page instead of the app :/

**Comment by sunix** [comment]
This is strange because: https://github.com/eclipse/jkube/blob/master/jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/WildFlyAppSeverHandler.java#L109

```
  @Override
  public Map<String, String> getEnv() {
    // Applicable for s2i image - ignored for Docker
    return Collections.singletonMap("GALLEON_PROVISION_LAYERS", "cloud-server,web-clustering");
  }
```
But I am not sure to see this env variable in the generated buildconfig

**Comment by sunix** [comment]
looks like it doesn't work, GALLEON_PROVISION_LAYERS", "cloud-server,web-clustering" should be passed to the build config where it looks like here it is env for the final built image.

**Comment by manusa** [comment]
Can this one be closed? @sunix
