### ISSUE TITLE
Deprecate - Remove WildFly Swarm generator

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1209]
### Description

WildFly Swarm project was superseded by Thorntail (and then by WildFly Bootable Jar).

We should remove the generator, documentation, and the tests (e2e) associated with this generator.

### AC
- [ ] Removed code
- [ ] Removed documentation
- [ ] Removed tests

**Comment by rohanKanojia** [comment]
https://thorntail.io/posts/the-end-of-an-era/
