### ISSUE TITLE
Cannot temporarily tag because target image already exists

### ISSUE THREAD

**Issue by lagivan** [eclipse/jkube#1232]
### Description
This is the same issue that was created and fixed for docker-maven-plugin several years ago - https://github.com/fabric8io/docker-maven-plugin/issues/838
Here is the fix - https://github.com/fabric8io/docker-maven-plugin/pull/1170/files
The relevant code - https://github.com/eclipse/jkube/blob/85d9fe8fd17e59eb1cdb07da194e6419201585d1/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClient.java#L661-L666

My problem is that I want to tag the image with "latest" version which already exists in the repo but pushing this new image should remove "latest" tag from an older image. This is impossible to do now.

### Info

* Eclipse JKube version : 1.5.1
* Maven version (`mvn -v`) : 3.6.2
* If it's a bug, how to reproduce :

This is my plugin configuration - using "%l" in the image name should set "latest" tag for SNAPSHOT artifacts.

            <plugin>
                <groupId>org.eclipse.jkube</groupId>
                <artifactId>kubernetes-maven-plugin</artifactId>
                <version>1.5.1</version>
                <configuration>
                    <profile>myapp</profile>
                    <access>
                        <namespace>test</namespace>
                    </access>
                    <registry>XXX.dkr.ecr.eu-west-1.amazonaws.com</registry>
                    <images>
                        <image>
                            <name>myapp:%l</name>
                            <alias>myapp</alias>
                            <build>
                                <contextDir>.</contextDir>
                            </build>
                        </image>
                    </images>
                </configuration>
            </plugin>

**Comment by rohanKanojia** [comment]
@lagivan : Thanks for reporting this. We're close to releasing a new version 1.6.0 (most probably this week) . Would it be possible for you to port this fix to JKube ?

**Comment by lagivan** [comment]
@rohanKanojia done, I'm looking forward to getting it fixed in 1.6.0
