### ISSUE TITLE
Gradle-Enricher: DependencyEnricher

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1240]
### Description

Child of #31

DependencyEnricher works with Gradle

### AC
- [x] Enricher documentation is ported to Gradle

**Comment by rohanKanojia** [comment]
Wasn't this covered in https://github.com/eclipse/jkube/pull/1060 ? I think the only thing remaining is to add documentation for this (which doesn't exist at the moment)

**Comment by manusa** [comment]
Duplicate of #1060 / #838
