### ISSUE TITLE
[feature-request] maven-plugin for Java generation from CRD

### ISSUE THREAD

**Issue by OneCricketeer** [eclipse/jkube#1247]
If it's a feature request, what is your use case :

<strike>From what I understand, this project allows building/deploying container images and applying k8s resources from Java. But can it _parse_ any resource generated from the `operator-sdk` command (specifically golang, not the `java-operator-sdk`) into POJO classes (optionally annotated with `io.fabric8.kubernetes.model.annotation` instances? 
 
I looked around in the `resource` module, and didn't find what I was interested in. 

Open to alternatives, if there are any. </strike>

---

New request - Using work mentioned in comments below, create a Maven Plugin goal that can generate Java models from CRDs.

**Comment by manusa** [comment]
Hi,
I'm not sure I'm following when you say parse.

Currently, you can include resource fragments (YAML files) of *any* kind and apiType in the `src/main/jkube` or `src/main/jkube/raw` (if you don't want them to be processed) directories.

When invoking the resource goal/task (`k8s:resource`/`k8sResource`), these resources will be taken into account and included in your `bundle`.

When invoking the apply goal/task ( `k8s:apply`/`k8sApply`), these resources will be applied to the cluster, provided that the cluster has the required CRD installed.

Is this what you're asking?

**Comment by OneCricketeer** [comment]
Thanks for responding. That's the reverse of what I want.

I'm looking for a maven plugin, something like swagger-codegen that'll read a CRD yaml definition that's been generated by operator-sdk and build a set of Java classes that represent that model structure.

E.g There's this, but it creates empty Java classes and then writes YAML

**Comment by manusa** [comment]
Understood. @andreaTP is currently working on such feature on the Fabric8 Kubernetes Client.

We'll probably be releasing this on Fabric8 Kubernetes Client 6.0.0. You can check the following related PR and issues:

- https://github.com/fabric8io/kubernetes-client/pull/3693
- https://github.com/fabric8io/kubernetes-client/issues/3642
- https://github.com/fabric8io/kubernetes-client/issues/3781
- https://github.com/fabric8io/kubernetes-client/issues/1458

**Comment by OneCricketeer** [comment]
Aha! That seems like exactly what I was looking for! We can close this, or keep it open for future work towards a plugin goal utilizing the work done there? 

Good to know I'm not the only one with the idea; we've been manually patching our java models from go crds for a while.

**Comment by OneCricketeer** [comment]
Migrating to https://github.com/fabric8io/kubernetes-client/pull/3830
