### ISSUE TITLE
Generate a preview of the jkube documentation for PR if needed.

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1251]
### Description
It would be nice to automatically generate a preview of the jkube doc for each PR if it is related to the documentation.

For instance, could be using surge.sh:
https://github.com/eclipse/jkube/blob/9be805bf66ccccde6f61a75ffef9ca72b406f6e5/devfile.yaml#L230

and have a generated doc like this:
https://jkubedoc-sunix-jkube-minikube-getting-started.surge.sh/

Could do something similar to
https://github.com/eclipse-che/che-plugin-registry/blob/main/.github/workflows/publish-content-push-main.yml#L37-L56

**Comment by manusa** [comment]
This is fine as long as the preview contains the necessary files (robots.txt, etc.) to avoid search engines crawling this content (main reason is that it would affect the main documentation SERP rank).

**Comment by manusa** [comment]
Other services to consider, vercel, netlify, etc.

**Comment by manusa** [comment]
> also if we want to go further and have a visual diff: https://github.com/danyill/htmldiff

Python :nauseated_face: :stuck_out_tongue_closed_eyes: 

IMHO, I don't think that's necessary, the git diffs in the adocs should be sufficient.

I'm happy about the generated docs deployment because it helps to see if the doc composition is OK and helps checking out the big picture (now that we're restructuring the docs). Otherwise, personally I was always happy checking the docs in the raw format.

**Comment by sunix** [comment]
I guess this is a personal preference. I like to have the diff of the final result.
Maybe I will port https://github.com/myobie/htmldiff in Java some days ;)

**Comment by rohanKanojia** [comment]
I think there is a way we might not need any temporary hosting tool/service for generated documentation. In CircleCI, we can upload the artifacts after the build. User can click on workflow > Go to Artifacts tab > Click `docs-generated/index.html`

![Screenshot from 2022-03-14 09-41-15](https://user-images.githubusercontent.com/13834498/158103591-f23cc79d-e0e6-4b71-980b-1e734cd7524b.png)


The result should look like this: https://13446-216815773-gh.circle-artifacts.com/0/docs-generated/index.html

What do you think about this?

**Comment by sunix** [comment]
@rohanKanojia this looks good to me
