### ISSUE TITLE
[kubernetes-gradle-plugin] Add example and documentation for writing and using custom enrichers

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1252]
### Description

We have a section of [Enricher API](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#_enricher_api) in our documentation on how to extend JKube API by writing your own enricher as per your use case and using it in your project. However, this also needs improvement. 

While porting Enricher docs to Kubernetes Gradle Plugin in #1246, I realized we haven't tested this with kubernetes gradle plugin. We should test this on gradle and add improved documentation to kubernetes gradle plugin.

- [ ] Port [Custom Istio Enricher](https://github.com/eclipse/jkube/tree/master/quickstarts/kit/custom-istio-enricher) quickstart to Gradle
- [ ] Add detailed documentation about using custom enrichers

**Comment by manusa** [comment]
Relates to #1336
