### ISSUE TITLE
RemoveBuildAnnotationsEnricher removal

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1263]
### Description
The [RemoveBuildAnnotationsEnricher](https://github.com/eclipse/jkube/blob/bc2a7c809087451bb49b1a62299c0bdedacbea8b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/RemoveBuildAnnotationsEnricher.java) seems to be completely outdated.

We should analyze what its initial purpose was. If it has nothing to do with Eclipse JKube, remove it.

### AC
- [x] Remove class
- [x] Remove from `enricher-default` service definitions
- [x] Remove from profiles
- [ ] ~~Remove from docs~~

**Comment by Hrushi20** [comment]
Should I remove the [RemoveBuildAnnotationsEnricher](https://github.com/eclipse/jkube/blob/bc2a7c809087451bb49b1a62299c0bdedacbea8b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/RemoveBuildAnnotationsEnricher.java) class?

**Comment by rohanKanojia** [comment]
RemoveBuildAnnotationsEnricher seems to be removing `maven.jkube.io/source-url` annotation from all resources present in KubernetesListBuilder.

This  `maven.jkube.io/source-url`  annotation seems to be getting added to all resources added via dependency in Dependency enricher:
```yaml
annotations:
    maven.jkube.io/source-url: jar:file:/home/rokumar/work/repos/jkube/gradle-plugin/it/src/it/dependency-resources/dependency/build/libs/dependency-0.0.1-SNAPSHOT.jar!/META-INF/jkube/kubernetes.yml
```

Looks like this annotation is just used for some log statements which are printed during mergeResource phase:

https://github.com/eclipse/jkube/blob/479858aa6719ffaabe8320c87ec43d129c78ffe6/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L830
https://github.com/eclipse/jkube/blob/479858aa6719ffaabe8320c87ec43d129c78ffe6/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L762-L763

Maybe we can remove these log statements and usage of `maven.jkube.io/source-url`. Or maybe we can move annotation removal logic from enricher to DependencyEnricher
