### ISSUE TITLE
GSoC 2022 proposal

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1265]
https://developers.google.com/open-source/gsoc/timeline

To be submitted before 2022-02-07

**Comment by sunix** [comment]
Ideas to be added to https://wiki.eclipse.org/Google_Summer_of_Code_2022_Ideas

**Comment by manusa** [comment]
https://wiki.eclipse.org/Google_Summer_of_Code_2022_Ideas#Eclipse_JKube:_Improve_JKube_user_experience

**Comment by ohbus** [comment]
I would like to work on the [JUnit5 project](https://wiki.eclipse.org/Google_Summer_of_Code_2022_Ideas#Eclipse_JKube.E2.84.A2:_Migrate_To_JUnit5_Testing_Framework_from_JUnit4)

Or on the [Mockito Project](https://wiki.eclipse.org/Google_Summer_of_Code_2022_Ideas#Eclipse_JKube.E2.84.A2:_Migrate_To_Mockito_for_mocking_tests), though I am very amateur in this.

@manusa would you like me to start migrating some tests already?

**Comment by manusa** [comment]
https://summerofcode.withgoogle.com/programs/2022/organizations/eclipse-foundation

**Comment by sunix** [comment]
Hello @ohbus and other students,
Here are some more details for the following steps: https://www.eclipse.org/lists/soc-dev/msg00896.html

**Comment by manusa** [comment]
The proposal is up. Next steps would involve selecting the contributor and preparing the related issues. We can track this in additional issues. Closing this one.
