### ISSUE TITLE
Enricher with type Job does not generate mandatory spec.template.spec.restartPolicy 

### ISSUE THREAD

**Issue by ammbra** [eclipse/jkube#1278]
### Description
If you configure 

`<jkube.enricher.jkube-controller.type>job</jkube.enricher.jkube-controller.type>
`

, do not set any additional YAML fragment for the Job, and run `mvn k8s:resource`, the resulted Job resource will not have a `spec.template.spec.restartPolicy`. When trying to apply the resource (`mvn k8s:apply`) you will get a message with 

`This is required Policy: Required value: valid values: "OnFailure", "Never". `

### Info

* Eclipse JKube version : 1.6.0
* Maven version (`mvn -v`) :3.8.4
```

```
* Kubernetes / Red Hat OpenShift setup and version : Kubernetes v1.23/ Red Hat OpenShift 4.8

* If it's a bug, how to reproduce : Do not use any **Job fragment** under **src/main/jkube** and run mvn k8s:resource.

* Sample Reproducer Project : *[GitHub Clone URL]*https://github.com/ammbra/cat-adoption-batch. To reproduce it, please use the jkube branch https://github.com/ammbra/cat-adoption-batch/tree/jkube

**Comment by manusa** [comment]
:pray:  Thx for reporting!

We should provide a default/configurable value in the [JobHandler](https://github.com/eclipse/jkube/blob/1ec8528f6b0acadc07dc98a308ef15488d1268e7/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/JobHandler.java).

For now, in case someone is having this problem too, the easiest workaround is to create a fragment with:

```yaml
# src/main/jkube/job.yml
spec:
  template:
    spec:
      restartPolicy: Never
```
