### ISSUE TITLE
~~Rethink~~ Remove log messages like "Running in Kubernetes mode" that don't seem to be useful

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1279]
### Description
Seeing messages like "Running in Kubernetes mode" or ""Running in Openshift mode" are confusing me as an end user.
As a user, I don't know what are the consequences of these modes. I know this is a heritage from the past. These messages are more raising questions/doubts than providing useful informations about what JKube is doing.

I propose to remove these ones.

### Info

* Eclipse JKube version : 1.6.0
* Maven version (`mvn -v`) :
```

```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :

* If it's a feature request, what is your use case :

* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by manusa** [comment]
Agreed. I can't remember if we are already loggin what kind of build we are doing.
e.g.
- Local Docker
- Local Jib
- OpenShift Docker
- OpenShift S2I
- ...

**Comment by rohanKanojia** [comment]
We used to have `fabric8.mode` in Fabric8 Maven Plugin which used to work both on Kubernetes and OpenShift. Now that we've specific plugins. I think it's safe to remove this message.

**Comment by ShivangMishra** [comment]
@manusa, I am going to work on this issue. Can you suggest what other messages should be removed ?
