### ISSUE TITLE
Kubernetes configuration not generated before tests

### ISSUE THREAD

**Issue by rdruss** [eclipse/jkube#128]
Description:
I tried migrating from FMP 4.4.0 to JKube 0.2.0 and encountered an issue with tests run by Arquillian Cube.  You can see from the gist for the output from the successful [fmp run](https://gist.github.com/rdruss/1468fd439c7cd2658d213092c363f90c) on line 140 that the Kubernetes configuration was successfully applied, while the gist for the output from the error in the [JKube run](https://gist.github.com/rdruss/f55d7291fce178e3908032b2e65e5e3a) on line 138 that the Kubernetes configuration could not be found that resulted in routes being unavailable as seen on line 163.

Reproducer:
You can use the repository at https://github.com/rdruss/vertx-http-example both to see the successful fmp run (use the master branch) as well as the errored JKube run (use the jkube branch).  I used minishift as my OpenShift cluster and ran the tests with:

mvn clean verify -Popenshift,openshift-it

**Comment by manusa** [comment]
If using latest version of Eclipse JKube (1.0.0-alpha-1) test works as expected (Had to add a small wait (`Thread.sleep(15000L)`) to `testThatWeServeAsExpected` so that application was ready on the lab cluster).

See following gist for command output: https://gist.github.com/manusa/430a9be7034c013bf46068bf41cd748d

pom.xml was modified too to use newer version:
```
<!--- ... --->
    <openshift-maven-plugin.version>1.0.0-alpha-1</openshift-maven-plugin.version>
<!--- ... --->
            <groupId>org.eclipse.jkube</groupId>
            <artifactId>openshift-maven-plugin</artifactId>
            <version>${openshift-maven-plugin.version}</version>
```

Here is a screenshot the web application deployed using Eclipse JKube:
![image](https://user-images.githubusercontent.com/488391/78354958-2512c300-75ad-11ea-8a02-55fcfe0d23f1.png)

On the other hand, warning message (`Did not find any kubernetes/openshift configuration files before starting the test execution. If you are using fabric8-maven-plugin, ensure `mvn package fabric8:resource fabric8:build` is run first to generate the resources`) is still shown (with a reference to fabric8 too :flushed:). Will use this issue to remove that.

**Comment by rdruss** [comment]
Hmmmm ... I just switched to use 1.0.0-alpha-1, changed the plugin name (openshift-maven-plugin), and tried out the sleep.  I still had the exact same issue.  I thought maybe it was that I was using minishift, so I tried it out on a shared OCP 4 cluster (Kubernetes Master Version v1.13.4+d663f00).  Still the same issue.  I'm not really sure what potential differences between our environments could be contributing to this.  Since you were using my project the dependencies were the same, so maybe either my laptop OS (MacOS 10.14.6) or Java version (AdoptOpenJDK (build 11.0.1+13) although the source and target versions are set to 1.8).  @manusa any ideas on what else to try?

**Comment by rdruss** [comment]
Ok, I've tried a few other things, but I'm not quite sure if the results help to point out where the issue is:
- I can run `mvn clean oc:deploy -Popenshift` which is successful.  I can then subsequently run `mvn verify -Popenshift,openshift-it` which successfully runs the test.
- With the application already deployed `mvn clean verify -Popenshift,openshift-it` runs successfully.  That is probably very similar to the previous case.
- With a clean project, running `mvn clean verify -Popenshift,openshift-it` errors with same result that was originally posted with this issue.

I've upgraded my oc client to 4.3.9 (latest) and I am using a shared remote OpenShift 4.1 cluster.

**Comment by manusa** [comment]
Hi @rdruss 
I think I did what you described on your first 2 steps, so that's why it probably worked for me :(.
I'll test the other scenario on Monday and see what's wrong.

**Comment by manusa** [comment]
Hi @rdruss 
I think I found the problem. I was checking your `pom.xml` plugin execution configuration and the execution configuration seems incomplete to me.

I bound `build, resource, apply` to `package` phase and everything seems to work now on a clean cluster and project running `mvn clean verify -Popenshift,openshift-it`.
```xml
<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>openshift-maven-plugin</artifactId>
  <version>${openshift-maven-plugin.version}</version>
  <executions>
    <execution>
      <id>fmp</id>
      <goals>
        <goal>apply</goal>
        <goal>resource</goal>
        <goal>build</goal>
      </goals>
      <phase>package</phase>
    </execution>
  </executions>
  <!-- ... -->
</plugin>
```

I haven't tested with FMP, but I really don't understand why it worked there (without a previous deploy). This strikes me as a bug in FMP, as the deploy goal is executed without it being configured.

**Comment by rdruss** [comment]
@manusa, this works as long as the `apply` goal is listed ***after*** `resource` and `apply`.  I think this issue can be closed now.  I'll start doing more testing on the Vert.x OpenShift examples with JKube now that I can get past this issue.  Thanks for the help.

**Comment by manusa** [comment]
Thanks a lot for trying @rdruss, please [keep us posted](https://github.com/eclipse/jkube) and let us know if you encounter any other problem or issue.
