### ISSUE TITLE
ExposeEnricher removal/update

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1309]
### Description
The [ExposeEnricher](https://github.com/eclipse/jkube/blob/bc2a7c809087451bb49b1a62299c0bdedacbea8b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ExposeEnricher.java) seems to be completely outdated.

The purpose of this Enricher seems to be just to add an `expose` label to the generated service. This label was probably consumed by one of the Fabric8 microservices. Or maybe there's an internal OpenShift feature that relies on this?

### AC
- [x] [Analyze purpose](https://github.com/eclipse/jkube/issues/1309#issuecomment-1092895078)
- [x] Remove class
- [x] Remove from `enricher-default` service definitions
- [x] Remove from profiles
- [x] Remove from docs

### Service Exposure behavior

The behavior for the exposure of Services must be preserved regardless of the removal of the enricher.

- Services with the following conditions are exposed:
  - Single port.
  - Not named `kubernetes` or `kubernetes-ro`.
  - Don't have an `expose: false` label.
- Routes:
  - Active by default. Can be deactivated **globally** by using the `jkube.openshift.generateRoute` or `jkube.enricher.jkube-openshift-route.generateRoute` properties.
  - Services with web ports (80, 443, 8080, 9080, 9090, 9443) will be automatically exposed.
  - Non web ports can be exposed by:
    - Labeling the service with `expose: true`.
    - Using the `jkube.createExternalUrls` property.
  - Can be disabled for a specific Service (**individually**) by labeling it with `expose: false`.
- Ingresses:
  - Disabled by default. Can be activated by using the `jkube.createExternalUrls` property.
  - All Services (matching the exposure conditions will be exposed)
  - Can be disabled for a specific Service (**individually**) by:
    - Labeling it with `expose: false`.
    - Providing an Ingress fragment for that Service (Ingress has the same name).

**Comment by rohanKanojia** [comment]
ExposeEnricher adds `expose: true` annotation which used to be processed by https://github.com/jenkins-x/exposecontroller which used to  automatically create and delete Ingress rules or OpenShift Routes. This repository seems to have been archived since 2020. I think it's okay to remove this enricher.

**Comment by rohanKanojia** [comment]
ExposeEnricher adds `expose: true` annotation which used to be processed by https://github.com/jenkins-x/exposecontroller which used to  automatically create and delete Ingress rules or OpenShift Routes. This repository seems to have been archived since 2020. I think it's okay to remove this enricher.

**Comment by rohanKanojia** [comment]
It looks like IngressEnricher  & RouteEnricher also consider this `expose: true` label for generating Ingress for Service. It only generates Ingress/Route for Service who have `expose: true` label:

https://github.com/eclipse/jkube/blob/ded7049e0ff253e04ebf1fddfc265bf25f1b636b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NetworkingV1IngressGenerator.java#L60
https://github.com/eclipse/jkube/blob/ded7049e0ff253e04ebf1fddfc265bf25f1b636b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java#L107

**Comment by rohanKanojia** [comment]
I've removed ExposeEnricher but there still seem to be some occurrences of `expose` annotation in codebase to decide whether Service is exposed or not:

https://github.com/eclipse/jkube/blob/33d9b739af35d203798c14c7991f7812c6e4ea9f/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/ApplyService.java#L1361

https://github.com/eclipse/jkube/blob/33d9b739af35d203798c14c7991f7812c6e4ea9f/jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java#L141

Now that we've removed ExposeEnricher, how would we decide which Service is exposed or not?

**Comment by manusa** [comment]
> It looks like IngressEnricher & RouteEnricher also consider this `expose: true` label for generating Ingress for Service. It only generates Ingress/Route for Service who have `expose: true` label:
> 
> https://github.com/eclipse/jkube/blob/ded7049e0ff253e04ebf1fddfc265bf25f1b636b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NetworkingV1IngressGenerator.java#L60
> 
> https://github.com/eclipse/jkube/blob/ded7049e0ff253e04ebf1fddfc265bf25f1b636b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/RouteEnricher.java#L107

If we remove the enricher, is there still an easy way to disable the automatic route and ingress generation?
(excluding the enricher is not easy)

**Comment by manusa** [comment]
The linked PR removes some functionality which is not replaced:
- Log the exposed service URL
- Possibility to disable the Ingress/Route generation

We need to re-evaluate how to proceed with this.
Either repurpose this Enricher, add a new one, or move the functionality elsewhere.

**Comment by rohanKanojia** [comment]
> If we remove the enricher, is there still an easy way to disable the automatic route and ingress generation?
(excluding the enricher is not easy)

I think Ingress generation can be enabled/disabled via `jkube.createExternalUrls` property (it's `false` by default)

For disabling Route generation we can use `jkube.openshift.generateRoute` property (it's `true` by default)

I checked these properties based on my branch and they still seem to enable/disable Route/Ingress generation as expected.

**Comment by rohanKanojia** [comment]
> Log the exposed service URL

Here I don't think we're logging the actual Service URL but the value of an annotation that used to be set by [Fabric8 exposecontroller](https://github.com/jenkins-x/exposecontroller) after Service creation. 

I think the method KubernetesHelper.getServiceExposeUrl is only used to print the value of Service annotation `jkube.io/exposeUrl`. This comes from Fabric8 ecosystem where actual annotation was `fabric8io/exposeUrl`. This is related to https://github.com/jenkins-x/exposecontroller#custom-annotations which is archived now. I'd advise removing it, I think it wasn't working in the first place.

**Comment by rohanKanojia** [comment]
> Log the exposed service URL

I think we were unnecessarily waiting for 5 seconds(default value of `jkube.serviceUrl.waitSeconds`) during apply goal/task polling whether exposeUrl annotation was set in created Service or not.

https://github.com/eclipse/jkube/blob/40added43dc6fbb180e2c79572628d0471be4195/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KubernetesHelper.java#L777-L780

This waiting logic is removed in #1447 which makes `k8s:apply`/`k8sApply` goal faster

1.9.0-SNAPSHOT based on #1447 

```sh
[INFO] --- kubernetes-maven-plugin:1.9.0-SNAPSHOT:apply (default-cli) @ random-generator ---
[INFO] k8s: Using Kubernetes at https://192.168.39.93:8443/ in namespace null with manifest /home/rokumar/work/repos/jkube-testing/eclipse-jkube-demo-project/target/classes/META-INF/jkube/kubernetes.yml 
[INFO] k8s: Updating Service from kubernetes.yml
[INFO] k8s: Updated Service: target/jkube/applyJson/default/service-random-generator-14.json
[INFO] k8s: Updating Deployment from kubernetes.yml
[INFO] k8s: Updated Deployment: target/jkube/applyJson/default/deployment-random-generator-14.json
[INFO] k8s: HINT: Use the command `kubectl get pods -w` to watch your pods start up
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.186 s
[INFO] Finished at: 2022-05-25T17:03:33+05:30
[INFO] ------------------------------------------------------------------------

```

1.8.0

```sh
[INFO] --- kubernetes-maven-plugin:1.8.0:apply (default-cli) @ random-generator ---
[INFO] k8s: Using Kubernetes at https://192.168.39.93:8443/ in namespace null with manifest /home/rokumar/work/repos/jkube-testing/eclipse-jkube-demo-project/target/classes/META-INF/jkube/kubernetes.yml 
[INFO] k8s: Updating Service from kubernetes.yml
[INFO] k8s: Updated Service: target/jkube/applyJson/default/service-random-generator-15.json
[INFO] k8s: Updating Deployment from kubernetes.yml
[INFO] k8s: Updated Deployment: target/jkube/applyJson/default/deployment-random-generator-15.json
[INFO] k8s: HINT: Use the command `kubectl get pods -w` to watch your pods start up
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.131 s
[INFO] Finished at: 2022-05-25T17:03:46+05:30
[INFO] ------------------------------------------------------------------------

```
