### ISSUE TITLE
should pick tomcat 10 if Jakarta EE provided api is used in the dependencies

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1324]
### Description
For webapp using jakarta ee, tomcat 10 should be used instead of 9

```
  <dependencies>
    <!-- Add servlet dependencies -->
    <dependency>
      <groupId>jakarta.servlet</groupId>
      <artifactId>jakarta.servlet-api</artifactId>
      <version>5.0.0</version>
      <scope>provided</scope>
    </dependency>
    <!-- Add jsp dependencies -->
    <dependency>
      <groupId>jakarta.servlet.jsp</groupId>
      <artifactId>jakarta.servlet.jsp-api</artifactId>
      <version>3.0.0</version>
      <scope>provided</scope>
    </dependency>
``` 

```
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
```

### Info

* Eclipse JKube version : 1.7.0
* If it's a bug, how to reproduce : I faced that while working on the demo https://github.com/sunix/hello-tomcat-kubernetes
* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by manusa** [comment]
We need to create a base Tomcat10 image.

Tomcat 10 should be used in all cases or if we want to keep Tomcat9 too, implement a new Handler for the new conditions.
