### ISSUE TITLE
JobHandlerTest : Use assertThrows instead of `@Test(expected = IllegalArgumentException.class)` annotation

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1339]
### Description
Right now we're using this `expected` annotation for verifying exception thrown in test. We should use `Assert.assertThrows` instead since it's move flexible and level returns thrown exception's object which can be asserted further if necessary

https://github.com/eclipse/jkube/blob/d5653eeaedfcda146065e1b674040114ff3be1b0/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/JobHandlerTest.java#L117-L120

- [ ] Remove `expected` annotation from test and use `assertThrows`

**Comment by Urjaswi-2655** [comment]
@rohanKanojia I want to work on it .

**Comment by Urjaswi-2655** [comment]
Just to understand what I have to do .
This would be my first PR so..
I will fork this repo.
cd Desktop (place I want to move it)
git clone 
git remote add upstream url
git branch 
git add 
git commit -m "message"
it push origin master
compare and pull request
check branches 
create pull request

**Comment by rohanKanojia** [comment]
Yeah, more or less. You have already created Eclipse Account and signed off ECA, right? Make sure you've configured your git username and email. Use `git commit --signoff` instead of `git commit`

**Comment by Urjaswi-2655** [comment]
Yes 
Ok
Thanks

**Comment by Urjaswi-2655** [comment]
@rohanKanojia What would be type of Change?

**Comment by rohanKanojia** [comment]
Since it's a cleanup task, I'll put this in chore section

**Comment by Urjaswi-2655** [comment]
@rohanKanojia I think I have done some mistake pls check

**Comment by Urjaswi-2655** [comment]
@ I think I have reverted the pull request

**Comment by rohanKanojia** [comment]
Please read doc about [assertThrows](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertThrows-java.lang.Class-org.junit.jupiter.api.function.Executable-
) for it's usage.

Have you [set up your IDE](https://www.eclipse.org/jkube/contributing#setup) for development? Did you verify build is successful with `mvn clean install` ?

**Comment by Urjaswi-2655** [comment]
No I have not done , I will try again after setting up , Thanks

**Comment by Urjaswi-2655** [comment]
@rohanKanojia Can you help me in setting up 
I am not able to do so

**Comment by Urjaswi-2655** [comment]
@rohanKanojia Can you help me in this step
Code formatting is done by the Eclipse code formatter using the configuration files found in the ide-config directory.

**Comment by Urjaswi-2655** [comment]
@rohanKanojia Done IDE Setup

**Comment by Urjaswi-2655** [comment]
@rohanKanojia  pls can you check if it is correct 
Now I have to just mvn clean install Right and then pull request.....
![Screenshot (1596)](https://user-images.githubusercontent.com/65727814/158336035-0609731d-c16a-4cc5-8a95-954b814ed3c4.png)

**Comment by Urjaswi-2655** [comment]
@rohanKanojia Please assign this issue to @anurag-rajawat
I think, I am not ready to counter this issue now , Sorry

**Comment by anurag-rajawat** [comment]
@rohanKanojia can i raise a PR?
