### ISSUE TITLE
ImageConfigurationTest : Replace `org.hamcrest..*` assertions with `org.assertj.core.api.*`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1340]
### Description

In ImageConfigurationTest, this hamcrest `assertThat` assertion should be replaced with AssertJ's `assertThat` assertion instead:

https://github.com/eclipse/jkube/blob/d5653eeaedfcda146065e1b674040114ff3be1b0/jkube-kit/config/image/src/test/java/org/eclipse/jkube/kit/config/image/ImageConfigurationTest.java#L39-L40

**Comment by anurag-rajawat** [comment]
@rohanKanojia May I work on this?
