### ISSUE TITLE
MavenUtilTest :  Replace `org.hamcrest..*` assertions with `org.assertj.core.api.*` equivalents 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1343]
### Description
MavenUtilTest seems to be using Hamcrest assertions. For example here: 

https://github.com/eclipse/jkube/blob/d5653eeaedfcda146065e1b674040114ff3be1b0/jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenUtilTest.java#L134-L138

- [x] Replace This hamcrest assertion dependency with assertj in [common-maven/pom.xml](https://github.com/eclipse/jkube/blob/master/jkube-kit/common-maven/pom.xml#L86):
```diff

-      <groupId>org.hamcrest</groupId>
-      <artifactId>hamcrest-all</artifactId>
+      <groupId>org.assertj</groupId>
+      <artifactId>assertj-core</artifactId>
     </dependency>
   </dependencies>
 ```
- [x] Replace all hamcrest assertions with assertj equivalents

**Comment by baruKreddy** [comment]
I will work on this!

**Comment by baruKreddy** [comment]
[https://github.com/eclipse/jkube/issues/1343#issuecomment-1067742444](url)
