### ISSUE TITLE
[Epic] : Refactor tests to use only `org.assertj.core.api.` Assertions

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1344]
### Description

Right now in our tests we're both using Hamcrest and AssertJ assertions. I remember we had decided to use AssertJ assertions for tests. We should refactor all tests that are still using Hamcrest assertions to use AssertJ instead:

- https://github.com/eclipse/jkube/issues/1340
- https://github.com/eclipse/jkube/issues/1341
- https://github.com/eclipse/jkube/issues/1343
- https://github.com/eclipse/jkube/issues/1345

More issues would be added as we continue refactoring tests in future.

**Comment by rohanKanojia** [comment]
@anurag-rajawat : You can raise a PR excluding files mentioned in already created issue if you want.

**Comment by anurag-rajawat** [comment]
@rohanKanojia Yes, I mean all occurrences in Jkube repo, only json assertions are remaining and as soon as possible I raise a PR for all these refactors.

If possible, can you provide some reference to change assertions such as 

`assertThat(json, JsonPathMatchers.isJson());`

`assertThat(json, JsonPathMatchers.hasJsonPath("$.spec.replicas", Matchers.equalTo(replicaCount)));`

`assertThat(builder.build().getFromExt(), allOf(
        hasEntry("kind", "ImageStreamTag"),
        hasEntry("name", "image:tag"),
        hasEntry("namespace", "my")));`

**Comment by rohanKanojia** [comment]
I think these JsonPathMatchers assertions are just to assert nested fields in an object. We're only converting object to Json string just for the sake of assertion. AssertJ has `hasFieldOrPropertyWithValue` method for comparing object fields.

For example this:

https://github.com/eclipse/jkube/blob/d5653eeaedfcda146065e1b674040114ff3be1b0/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricherTest.java#L93-L95

can be rewritten like this in assertj:
```java
assertThat(list.getItems())
            .hasSize(1)
            .first()
            .hasFieldOrPropertyWithValue("spec.replicas", replicaCount);
```

**Comment by anurag-rajawat** [comment]
@rohanKanojia if the assertion

https://github.com/eclipse/jkube/blob/d5653eeaedfcda146065e1b674040114ff3be1b0/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/ImageEnricherTest.java#L161

is rewritten like 

```java
 assertThat(list.getItems()) 
                .hasSize(1)
                .first()
                .hasFieldOrPropertyWithValue("spec.template.spec.containers[0].env[0].value", expectedValue);
```

then it gives error
```java
java.lang.AssertionError: [List check first element] 
Expecting
  <Deployment(apiVersion=apps/v1, kind=Deployment, metadata=null, spec=DeploymentSpec(minReadySeconds=null, paused=null, progressDeadlineSeconds=null, replicas=null, revisionHistoryLimit=null, selector=null, strategy=null, template=PodTemplateSpec(metadata=null, spec=PodSpec(activeDeadlineSeconds=null, affinity=null, automountServiceAccountToken=null, containers=[Container(args=[], command=[], env=[EnvVar(name=MY_KEY, value=MY_VALUE, valueFrom=null, additionalProperties={})], envFrom=[], image=busybox, imagePullPolicy=IfNotPresent, lifecycle=null, livenessProbe=null, name=busybox, ports=[], readinessProbe=null, resources=null, securityContext=null, startupProbe=null, stdin=null, stdinOnce=null, terminationMessagePath=null, terminationMessagePolicy=null, tty=null, volumeDevices=[], volumeMounts=[], workingDir=null, additionalProperties={})], dnsConfig=null, dnsPolicy=null, enableServiceLinks=null, ephemeralContainers=[], hostAliases=[], hostIPC=null, hostNetwork=null, hostPID=null, hostname=null, imagePullSecrets=[], initContainers=[], nodeName=null, nodeSelector=null, overhead=null, preemptionPolicy=null, priority=null, priorityClassName=null, readinessGates=[], restartPolicy=null, runtimeClassName=null, schedulerName=null, securityContext=null, serviceAccount=null, serviceAccountName=null, setHostnameAsFQDN=null, shareProcessNamespace=null, subdomain=null, terminationGracePeriodSeconds=null, tolerations=[], topologySpreadConstraints=[], volumes=[], additionalProperties={}), additionalProperties={}), additionalProperties={}), status=null, additionalProperties={})>
to have a property or a field named <"spec.template.spec.containers[0].env[0].value">
```

The problem occurs when you try to extract properties with indexes such as `containers[0]` or `env[0]`.
So, how do I rewrite these types of assertions with assertJ?

**Comment by rohanKanojia** [comment]
Yes, I don't think assertj supports these kinds of indexing in-field paths.

However, you can make use of assertj DSL methods like `asList()`, `element()`, `first()`, `extracting()` to extract nested fields and assert them. So the Hamcrest assertion you're pointing to can be refactored like this:

```java
    private void assertPodTemplateContainsEnv(PodTemplateSpec podTemplateSpec, String expectedKey, String expectedValue) {
        assertThat(podTemplateSpec)
            .extracting(PodTemplateSpec::getSpec)
            .extracting(PodSpec::getContainers)
            .asList()
            .first()
            .asInstanceOf(InstanceOfAssertFactories.type(Container.class))
            .extracting(Container::getEnv)
            .asList()
            .contains(new EnvVarBuilder().withName(expectedKey).withValue(expectedValue).build());
    }
```
