### ISSUE TITLE
AssemblyFileSetUtilsTest :  Replace `org.hamcrest..*` assertions with `org.assertj.core.api.*` equivalents 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1345]
### Description

AssemblyFileSetUtilsTest seems to be using Hamcrest assertions. Foe example, 

https://github.com/eclipse/jkube/blob/d5653eeaedfcda146065e1b674040114ff3be1b0/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/AssemblyFileSetUtilsTest.java#L62

- [x] Replace all occurrences of Hamcrest assertions with AssertJ equivalents

**Comment by baruKreddy** [comment]
I will work on this!
