### ISSUE TITLE
Improvement to add skipUndeploy flag for undeploy goal

### ISSUE THREAD

**Issue by guiliguili** [eclipse/jkube#1358]
### Description
While it is currently supported to skip apply through the `skipApply` flag, I would like to have the similar flags for `undeploy`.

### Info

* Eclipse JKube version : 1.5.1
* Maven version (`mvn -v`) : 
```
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /usr/local/Cellar/maven/3.8.3/libexec
Java version: 11.0.13, vendor: SAP SE, runtime: /Library/Java/JavaVirtualMachines/sapmachine-11.jdk/Contents/Home
Default locale: en_FR, platform encoding: US-ASCII
OS name: "mac os x", version: "12.2.1", arch: "x86_64", family: "mac"
```
* Kubernetes / Red Hat OpenShift setup and version : N/A

* Use case : 
  I am using multi-module project and I would like to apply/undeploy selectively certains modules based on maven configuration. The only way I can workaround is to the use the widder `skip` flag but I this would also skip build and resource goals which is not I want.

**Comment by rohanKanojia** [comment]
@guiliguili : Thanks for reporting! I think this makes sense.

I do see a `skipDeploy` flag in DeployMojo:

https://github.com/eclipse/jkube/blob/d5653eeaedfcda146065e1b674040114ff3be1b0/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/DeployMojo.java#L35-L36

But I don't see any skip flag in UnDeployMojo. Maybe we should add it there as well. Similar flags need to be added in equivalent gradle tasks too.

Would it be possible for you to submit a PR for this?

**Comment by guiliguili** [comment]
Good catch on skiDeploy. 

I am kind of busy right now but I should hopefully have some time in a few week to submit a PR on this.

**Comment by heloise-viegas** [comment]
Hi @rohanKanojia 
Can I give this a try? I'm a newbie to Open source so just wanted to start somewhere

**Comment by Devamparikh** [comment]
Hey @heloise-viegas Do you mind if we could work on this issue together??
I really need to solve some issues 😅

**Comment by heloise-viegas** [comment]
Hi @Devamparikh,
Sure we can work on this together, in any case I needed  help!

**Comment by Devamparikh** [comment]
Let me know if I could do anything to help. ;)

**Comment by heloise-viegas** [comment]
@Devamparikh Do I just add the skipDeploy flag as above in UnDeployMojo.java ? I'm really confused since its my first time..
Maybe we can connect via socials so you can guide me along ...
Thanks  :)

**Comment by Devamparikh** [comment]
Yes, You can communicate more efficiently via gitter. 
Link is available in readme of this project.

**Comment by manusa** [comment]
polite ping, is anyone of you working on this issue?

**Comment by Prathamkrishna** [comment]
Hey, I'd like to pick this up
