### ISSUE TITLE
VolumePermissionEnricher : Use `.spec.storageClassName` instead of annotation to set PersistentVolume class

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1361]
### Description
Right now we seem to be using `volume.beta.kubernetes.io/storage-class` annotation to provide the class of PersistentVolume. 

https://github.com/eclipse/jkube/blob/d5653eeaedfcda146065e1b674040114ff3be1b0/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java#L192-L194

However, as per Kubernetes docs, this annotation will be marked as deprecated:

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#class
> In the past, the annotation volume.beta.kubernetes.io/storage-class was used instead of the storageClassName attribute. This annotation is still working; however, it will become fully deprecated in a future Kubernetes release

We should refactor VolumePermissionEnricher to set `storageClassName` field in `.spec` instead of setting deprecated annotation

**Comment by manusa** [comment]
> We should refactor VolumePermissionEnricher to set storageClassName field in .spec instead of setting deprecated annotation

Or maybe keep both approaches for backwards compatibility?
