### ISSUE TITLE
VolumePermissionEnricher : Replace iteration with bulk `Collection.addAll` call

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1362]
### Description

We seem to be having this code in VolumePermissionEnricher:

https://github.com/eclipse/jkube/blob/d5653eeaedfcda146065e1b674040114ff3be1b0/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java#L127-L130

Instead of looping over the collection, we can easily replace this with one-liner by using `Collection.addAll` call.

**Comment by Simba-97** [comment]
@rohanKanojia can I work on this issue?

**Comment by Prathamkrishna** [comment]
Hey @rohanKanojia I'd like to pick this up

**Comment by rohanKanojia** [comment]
@Simba-97 : Sorry, I had created this for @Prathamkrishna . He asked me to do it on Gitter channel https://gitter.im/eclipse/jkube

**Comment by Simba-97** [comment]
No problem @rohanKanojia 😄

**Comment by Prathamkrishna** [comment]
Created the PR, @rohanKanojia lemme know if there's anything else:)
