### ISSUE TITLE
k8s:helm build archive with wrong suffix

### ISSUE THREAD

**Issue by rechandler12** [eclipse/jkube#1369]
### Description
When I build helm chart with k8s:helm i get file, eg:
gus-api-1.0.0-SNAPSHOT-helm.tar.gz

And this file is uploaded to Nexus.

When I try to download file by
```
helm install registry gus-api --version 1.0.0-SNAPSHOT
```
I get 404, because helm expected file will be at location:
```
https://registry/gus-api-1.0.0-SNAPSHOT.tar.gz
```

This classifier messes around :(
https://github.com/eclipse/jkube/blob/master/jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmService.java
```
      final File tarballFile = new File(tarballOutputDir, String.format("%s-%s-%s.%s",
          helmConfig.getChart(), helmConfig.getVersion(), helmType.getClassifier(), helmConfig.getChartExtension()));
```
line: 156 and 157

### Info

* Eclipse JKube version : 1.7.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: C:\Users\rechandler\scoop\apps\maven\current
Java version: 17.0.2, vendor: Oracle Corporation, runtime: C:\Users\rechandler\scoop\apps\openjdk\current
Default locale: en_US, platform encoding: Cp1250
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
```
* Kubernetes / Red Hat OpenShift setup and version :
 1.22

**Comment by manusa** [comment]
Maybe we can reorder the position of the classifier or just remove it. I'm not sure if it's useful.

The purpose is to differentiate charts built for Kubernetes (helm) and OpenShift (helmshift).

**Comment by rechandler12** [comment]
Here's logs from helm:
```
❯ helm upgrade --install --namespace np-dev gus-api xxx/gus-api --version 1.0.0 --debug
history.go:56: [debug] getting history for release gus-api
Error: failed to fetch https://nexus.xxx.pl/repository/helm-releases/gus-api-1.0.0.tgz : 404 Not Found
helm.go:84: [debug] failed to fetch https://nexus.xxx.pl/repository/helm-releases/gus-api-1.0.0.tgz : 404 Not Found
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).get
        helm.sh/helm/v3/pkg/getter/httpgetter.go:89
helm.sh/helm/v3/pkg/getter.(*HTTPGetter).Get
        helm.sh/helm/v3/pkg/getter/httpgetter.go:42
helm.sh/helm/v3/pkg/downloader.(*ChartDownloader).DownloadTo
        helm.sh/helm/v3/pkg/downloader/chart_downloader.go:100
helm.sh/helm/v3/pkg/action.(*ChartPathOptions).LocateChart
        helm.sh/helm/v3/pkg/action/install.go:753
main.newUpgradeCmd.func2
        helm.sh/helm/v3/cmd/helm/upgrade.go:135
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.3.0/command.go:856
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.3.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.3.0/command.go:902
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:255
runtime.goexit
        runtime/asm_amd64.s:1581
```
Code of downloader:
https://github.com/helm/helm/blob/main/pkg/downloader/chart_downloader.go

**Comment by manusa** [comment]
> Here's logs from helm:

I understand the problem. The thing is that Nexus is just ignoring the chart information contained in the archive and inferring all of the information from the filename when building the index.

The question here is to see if we can completely remove the classifier part from the filename so that it doesn't tamper with Nexus. Another option is to modify the upload filename on the fly when pushing it to Nexus (or any of the other supported registries).

**Comment by foleyw** [comment]
@manusa I'm running into this same issue.  I'm currently renaming the file after the k8s:helm goal and then running curl to upload the file as workaround.  I would like to see a solution to this in a future release so I can use the k8s:helm-push goal in my pipeline.
https://help.sonatype.com/repomanager3/nexus-repository-administration/formats/helm-repositories#HelmRepositories-UploadbyHTTPPOST

**Comment by manusa** [comment]
Thanks for your feedback.
I'll mark this as a bug and we'll try to prioritize it in our backlog.

**Comment by rohanKanojia** [comment]
Shall I remove the classifier from the chart tarball name? Or Shall we provide some property to configure the name of chart tarball?

**Comment by rohanKanojia** [comment]
I tried it on local nexus and was able to reproduce this issue.

I see the classifier is just to differentiate between openshift/kubernetes tarballs. Shall we remove classifier from name but add this in parent directory of tarball? For example, instead of generating it in `target/jkube-helm-maven-1.0.0-SNAPSHOT-helm.tar.gz` we can generate it in `target/helm-archives/kubrenetes/jkube-helm-maven-1.0.0-SNAPSHOT.tar.gz` or `target/helm-archives/openshift/jkube-helm-maven-1.0.0-SNAPSHOT.tar.gz`

**Comment by manusa** [comment]
discussed internally
