### ISSUE TITLE
ConfigsTest: Replace multiple tests with a single parameterized one

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1371]
### Description

We seem to be testing `Configs.asBoolean` method in ConfigsTest which seems kind of redundant.

https://github.com/eclipse/jkube/blob/b45facd5b3dd25a31850d2f38b96c73edf66b83a/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/ConfigsTest.java#L108-L170

[Sonar suggests](https://sonarcloud.io/project/issues?resolved=false&id=jkubeio_jkube&open=AXTUMbfd_bxDuY6CEkWA) replacing these tests with parameterized ones.

- [x] Remove these tests from ConfigsTest
- [x] Create a new parameterized test ConfigsAsBooleanTest which tests all scenarios covered by these tests

**Comment by baruKreddy** [comment]
I will take this up @rohanKanojia . Please assign it to me!

**Comment by rohanKanojia** [comment]
Yes, I meant creating a new class.

I'm slightly confused by your changes. How are you able to have access to `org.junit.jupiter.params*` classes? We don't have any JUnit5 deps in the project yet.
