### ISSUE TITLE
FileDataSecretEnricherTest: Join these multiple assertions subject to one assertion chain

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1372]
### Description
These two assertions can be joined together. Maybe we can just remove first one and just use `.containsEntry` assertion:

https://github.com/eclipse/jkube/blob/b45facd5b3dd25a31850d2f38b96c73edf66b83a/jkube-kit/enricher/generic/src/test/java/org/eclipse/jkube/enricher/generic/FileDataSecretEnricherTest.java#L82-L87

**Comment by Sohamkayal4103** [comment]
Can I work on this issue?

**Comment by Devamparikh** [comment]
Hey @Sohamkayal4103 Do you mind if we could work on this issue together??
I really need to solve some issues :sweat_smile:
