### ISSUE TITLE
EnvUtilTest : Use `.hasSize` instead of `.isEqualTo` in assertj assertion

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1373]
### Description

This assertion should be simplified to use `hasSize()` instead. Also, it should be chained together with next assertion as a single statement:

https://github.com/eclipse/jkube/blob/b45facd5b3dd25a31850d2f38b96c73edf66b83a/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java#L209-L210

**Comment by anurag-rajawat** [comment]
@rohanKanojia may i work on this?

**Comment by anurag-rajawat** [comment]
@rohanKanojia may i work on this?
