### ISSUE TITLE
GoTimeUtilTest : Use `assertThat(actual).contains(expected)` instead of fetching and comparing optional

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1378]
### Description

We seem to have this assertion in this test where we're extracting actual value from Optional<Integer> and then doing comparison.

https://github.com/eclipse/jkube/blob/79c84363daeafe4af7c3ca9fb6b5e761b9ac399b/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/GoTimeUtilTest.java#L40-L41

AssertJ already provides support for [this](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AssertionsForClassTypes.html). 

- [x] Remove all usages of `org.junit.Assert.*` assertions from this test
- [x] Simplify AssertJ assertions to use `contains` instead.

**Comment by Prathamkrishna** [comment]
I'd like to pick this up @rohanKanojia
