### ISSUE TITLE
Not able to built project

### ISSUE THREAD

**Issue by Devamparikh** [eclipse/jkube#1388]
I'm not able to built jkube project. what should I do?
![Screenshot from 2022-03-23 19-03-05](https://user-images.githubusercontent.com/60180815/159711879-8f672f5f-c577-4d71-a408-de61822bb0e6.png)

**Comment by rohanKanojia** [comment]
Error seems to be complaining about not being able to find a docker/podman daemon. You can set up docker on your machine and retry.

Usually for building I run `mvn clean install` from root directory of project

**Comment by Devamparikh** [comment]
mvn clean install command is giving build success on running also mvn k8s: build 
![Screenshot from 2022-03-24 16-43-06](https://user-images.githubusercontent.com/60180815/159904687-df80b6e9-5238-4990-b658-611c30e601d9.png)

**Comment by rohanKanojia** [comment]
strange, looks like a permission issue to me. Are you sure the folder you're working under has the right permissions?

**Comment by Devamparikh** [comment]
Yeah, right but there is some error still. can this be ignore?
![Screenshot from 2022-03-24 16-52-29](https://user-images.githubusercontent.com/60180815/159906084-f9081702-ba12-4c4d-acb8-7b01eac3a71d.png)
And yet mvn k8s:apply is failing.
![Screenshot from 2022-03-24 16-54-22](https://user-images.githubusercontent.com/60180815/159906489-be358689-6bb2-4a17-9b3e-644e80a852cc.png)

**Comment by Devamparikh** [comment]
![Screenshot from 2022-03-24 17-40-19](https://user-images.githubusercontent.com/60180815/159913613-541095ad-bb81-465b-b082-39dab51106d7.png)

**Comment by Devamparikh** [comment]
Completed build by installing minikube.
