### ISSUE TITLE
Issue: Two Quickstarts are similarly named in JKube Website 

### ISSUE THREAD

**Issue by Urjaswi-2655** [eclipse/jkube#1400]
Both Quickstarts are named the same  [JKube Website](https://www.eclipse.org/jkube/quickstarts/) here  i.e Maven:: Wildfly JAR but one is Wildfly JAR and the Other one is Wildfly JAR Slim.
![Screenshot (1658)](https://user-images.githubusercontent.com/65727814/160136047-dbfdcfe6-150a-41f3-b7f0-dfd2f8465abc.png)
But As Per naming Convention  one should be `Maven :: Wildfly JAR` and Other one should be  `Maven :: Wildfly JAR :: Slim `
Naming Convention is predicted with respect to  `Maven :: Webapp :: Wildfly` and `Maven :: Webapp :: Wildfly :: Datasource`
![Screenshot (1661)](https://user-images.githubusercontent.com/65727814/160137205-9dd589ff-06c0-41b9-8a4d-11065cd1adfd.png)

**Comment by Urjaswi-2655** [comment]
@rohanKanojia I would like to work on this issue and one on the [eclipse/jkube#1394](https://github.com/eclipse/jkube/issues/1394)

**Comment by Urjaswi-2655** [comment]
Created PR for issue #1394 [33](https://github.com/jkubeio/jkube-website/pull/33) && [34](https://github.com/jkubeio/jkube-website/pull/34)

for this issue [here](https://github.com/jkubeio/jkube-website/pulls)

**Comment by Urjaswi-2655** [comment]
Created PR for this issue  https://github.com/eclipse/jkube/pull/1401 here

**Comment by manusa** [comment]
> @manusa @rohanKanojia Created PR for this issue #1401 here

Hi @Urjaswi-2655, When you create a PR the recommended approach is to add a meaningful description of what it does, and in other pointer that might help reviewers.

In this case, something like `Fix #1400, updated WildFly Jar Slim quickstart's name to make it more specific and avoid a duplicity with the regular WildFly Jar quickstart` would be much better and would allow you to skip redundantly commenting your tasks.

**Comment by Urjaswi-2655** [comment]
> > @manusa @rohanKanojia Created PR for this issue #1401 here
> 
> Hi @Urjaswi-2655, When you create a PR the recommended approach is to add a meaningful description of what it does, and in other pointer that might help reviewers.
> 
> In this case, something like `Fix #1400, updated WildFly Jar Slim quickstart's name to make it more specific and avoid a duplicity with the regular WildFly Jar quickstart` would be much better and would allow you to skip redundantly commenting your tasks.

Sorry , it was my first PR . Will not repeat this mistake again . Thanks @manusa
