### ISSUE TITLE
MavenUtilTest : Migrate mocking framework from JMockit to mockito

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1407]
### Description

Child of #857

We have MavenUtilTest in common-maven module which seems to be using JMockit:

https://github.com/eclipse/jkube/blob/479858aa6719ffaabe8320c87ec43d129c78ffe6/jkube-kit/common-maven/src/test/java/org/eclipse/jkube/kit/common/util/MavenUtilTest.java#L105

- [ ] Migrate JMockit references to Mockito
- [ ] Remove jmockit dependency reference from [jkube-kit/common-maven/pom.xml](https://github.com/eclipse/jkube/blob/master/jkube-kit/common-maven/pom.xml#L82) module

**Comment by baruKreddy** [comment]
@rohanKanojia Please assign it to me!

**Comment by derekdunes** [comment]
@baruKreddy can you post your Merged PRs to this issue when resolved so we could learn from it

**Comment by baruKreddy** [comment]
Hi @derekdunes , This PR is currently under review.You can have a look at this. https://github.com/eclipse/jkube/pull/1410

**Comment by derekdunes** [comment]
@baruKreddy okay thanks
