### ISSUE TITLE
Additional image tags issue

### ISSUE THREAD

**Issue by Surfjoan** [eclipse/jkube#1411]
### Info

* Eclipse JKube version: 1.7.0
* Maven version (`mvn -v`): 3.5.4
* Kubernetes / Red Hat OpenShift setup and version: Openshift v3.11
* If it's a bug, how to reproduce: 
* I have set the name element to this \<name>${namespace}/%a:%v\</name>  but want to add an additional tag on the image in openshift after it is built. So i added the \<tags>\<tag>my-tag\</tag>\</tags> elements to the plugin configuration in pom. According to documentation this is the way to add additional tags to the image after it is being built. But no additional tags are created. Or am i misunderstanding the purpose of the <tags> element?

* If it's a feature request, what is your use case :

* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by manusa** [comment]
That's the purpose of these elements (tags,tag). Could you please share a reproducer pom.xml so we can see where the problem is?

**Comment by Surfjoan** [comment]
enough with plugin config?
<plugin>
                <groupId>org.eclipse.jkube</groupId>
                <artifactId>openshift-maven-plugin</artifactId>
                <version>1.7.0</version>
                <configuration>
                    <images>
                        <image>
                            <name>${openshiftnamespace}/%a:%v</name>
                            <build>
                                <fromExt>
                                    <name>${openshift-base-image}</name>
                                    <namespace>${image-namespace}</namespace>
                                    <kind>ImageStreamTag</kind>
                                </fromExt>
                                <env>
                                    <JAVA_APP_DIR>/deployments</JAVA_APP_DIR>
                                </env>
                                <tags>
                                    <tag>%v</tag>
                                    <tag>latest</tag>
                                </tags>
                            </build>
                        </image>
                    </images>
                </configuration>
            </plugin>

**Comment by Surfjoan** [comment]
Enough with plugin conf?
`<plugin>
                <groupId>org.eclipse.jkube</groupId>
                <artifactId>openshift-maven-plugin</artifactId>
                <version>1.7.0</version>
                <configuration>
                    <images>
                        <image>
                            <name>${openshiftnamespace}/%a:%v</name>
                            <build>
                                <fromExt>
                                    <name>${openshift-base-image}</name>
                                    <namespace>${image-namespace}</namespace>
                                    <kind>ImageStreamTag</kind>
                                </fromExt>
                                <env>
                                    <JAVA_APP_DIR>/deployments</JAVA_APP_DIR>
                                </env>
                                <tags>
                                    <tag>%v</tag>
                                    <tag>latest</tag>
                                </tags>
                            </build>
                        </image>
                    </images>
                </configuration>
            </plugin>`

**Comment by rohanKanojia** [comment]
@Surfjoan : I've created a PR #1639 that creates ImageStreamTags based on tags specified in `<build><tags>` section (similar to what we do with `oc tag ...` command) . Does this align with your expectations? Would be awesome if you could provide some feedback regarding this.

**Comment by Surfjoan** [comment]
Cool! I am on vacation now but going to test it once i am back

Den ons 29 juni 2022 16:51Rohan Kumar ***@***.***> skrev:
