### ISSUE TITLE
BuildServiceTest : Simplify Mockito `verify` call

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1413]
### Description

The below code is tagged as smell by Sonar:
>Mockito provides argument matchers for flexibly stubbing or verifying method calls. 
Mockito.verify(), Mockito.when(), Stubber.when() and BDDMockito.given() each have overloads with and without argument matchers.
However, the default matching behavior (i.e. without argument matchers) uses equals(). If only the matcher org.mockito.ArgumentMatchers.eq() is used, the call is equivalent to the call without matchers, i.e. the eq() is not necessary and can be omitted. The resulting code is shorter and easier to read.

https://github.com/eclipse/jkube/blob/479858aa6719ffaabe8320c87ec43d129c78ffe6/jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/BuildServiceTest.java#L97-L98

- [x] Simplify `verify()` call to remove argument matchers

**Comment by Devamparikh** [comment]
Can I take this up? I'd like to give it a shot.

**Comment by cdprete** [comment]
You can also remove `times(1)` since it's the default ;)

**Comment by MostafaMagdy55** [comment]
You can assign this to me @rohanKanojia, Thanks!

**Comment by MostafaMagdy55** [comment]
You can assign this to me @rohanKanojia, Thanks!

**Comment by Devamparikh** [comment]
Hey @cdprete Do you think this would be the correct simplification for verify( ) call? 
```
verify(mockedDockerAccess)
        .tag("image-name", "image-name:latest", true);

**Comment by cdprete** [comment]
> Hey @cdprete Do you think this would be the correct simplification for verify( ) call?
> 
> ```
> verify(mockedDockerAccess)
>         .tag("image-name", "image-name:latest", true);
> ```

Hey @Devamparikh. 
Yes, that would be OK, but that's only my personal opinion. 
Maybe the authors prefer to keep the `times(1)` even if it's the default for readability or other reasons. @rohanKanojia can tell this ;)

**Comment by manusa** [comment]
> > Hey @cdprete Do you think this would be the correct simplification for verify( ) call?
> > ```
> > verify(mockedDockerAccess)
> >         .tag("image-name", "image-name:latest", true);
> > ```
> 
> Hey @Devamparikh. Yes, that would be OK, but that's only my personal opinion. Maybe the authors prefer to keep the `times(1)` even if it's the default for readability or other reasons. @rohanKanojia can tell this ;)

I like the verbosity of times(1) since it makes the test readable despite the convention redundancy. It makes it clear for anyone who is reviewing the test what's going on.
