### ISSUE TITLE
OpenshiftHelperTest : Replace these tests with a single Parameterized one.

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1414]
### Description

These tests could be extracted into a parameterized test:

https://github.com/eclipse/jkube/blob/479858aa6719ffaabe8320c87ec43d129c78ffe6/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/OpenshiftHelperTest.java#L160-L258

- [ ] Create a new parameterized test class OpenShiftHelperStatusTest and move all these abovementioned tests

**Comment by baruKreddy** [comment]
You can assign this to me @rohanKanojia, Thanks!

**Comment by JhaSaahil** [comment]
Is anyone working on this?

**Comment by baruKreddy** [comment]
@JhaSaahil I'm working on this currently! Thanks

**Comment by derekdunes** [comment]
@baruKreddy can you post your Merged PRs to this issue when resolved so we could learn from it

**Comment by baruKreddy** [comment]
@derekdunes This issue under progress, but I have fixed a issue which is similar and you can find that changes in this PR https://github.com/eclipse/jkube/pull/1387/files. I hope this would help.

**Comment by baruKreddy** [comment]
@derekdunes I'm attaching a PR related to this issue which in under review. https://github.com/eclipse/jkube/pull/1420

**Comment by derekdunes** [comment]
@baruKreddy thanks already reviewing, if I have any questions will definitely reach out, I hope you don't mind though?
