### ISSUE TITLE
Improve issue and pull request templates

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1419]
### Description

The current template for issues is a little bit messy and has some optional fields that end up rendered as empty gray boxes. We should improve this.

### Relates to
- https://github.com/fabric8io/kubernetes-client/pull/3322

**Comment by rohanKanojia** [comment]
@manusa @sunix : I can change our current issue template to align with what we have in Fabric8 Kubernetes Client. What changes would you like to have in pull request template?
