### ISSUE TITLE
[Maven Quickstarts] : Update Micronaut quickstart to v3.4.1

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1429]
### Description
Our current micronaut maven quickstart seems to be outdated. It needs to be updated to latest version of micronaut.

https://github.com/eclipse/jkube/blob/ded7049e0ff253e04ebf1fddfc265bf25f1b636b/quickstarts/maven/micronaut/pom.xml#L24

- [ ] Update Micronaut version to latest release
- [ ] Verify Kubernetes Maven Plugin is working with the updated version by deploying an application to [minikube](https://minikube.sigs.k8s.io/docs/)
- [ ] Verify OpenShift Maven Plugin is working with updated version by deploying the application to [Red Hat Developer Sandbox](https://developers.redhat.com/developer-sandbox/get-started)

**Comment by Mohd-Farhan** [comment]
I am interested in resolving the issue.

**Comment by Mohd-Farhan** [comment]
I want to know what are the software I have to install for contribution.

**Comment by rohanKanojia** [comment]
@Mohd-Farhan : Please check out out Contributing page: https://www.eclipse.org/jkube/contributing

You can also check my blogpost which can guide you in contributing to Eclipse JKube https://rohaan.medium.com/how-to-contribute-to-eclipse-jkube-f3bc7f902bf4

**Comment by Mohd-Farhan** [comment]
thanks

**Comment by anurag-rajawat** [comment]
@Mohd-Farhan do you need help?

**Comment by Mohd-Farhan** [comment]
@anurag-rajawat congratulation for gsoc selection. 
Ok, u can help me.

**Comment by anurag-rajawat** [comment]
What problem are you facing?

**Comment by Mohd-Farhan** [comment]
I copy docker-file-simple and paste it in jkube folder and run Command "docker build ." it shows "COPY maven/target/docker-file-simple.jar /deployments/docker-file-simple.jar" is not found and in my docker desktop an image "openjdk" is build

**Comment by Mohd-Farhan** [comment]
I only change <version>3.0.0</version> to <version>3.4.1</version> . I check dependency for micronauts 3.4.1 in mvn repositories but I did not find any new dependency to add in it.

**Comment by anurag-rajawat** [comment]
First of all, why are you copying `docker-file-simple` as you only need to update the micronaut version?
And you don't need to add any new dependency, just update the version.

After upgrading, verify whether the project is deployed okay when deployed with jkube, to do so follow the instruction from 
the [README.md](https://github.com/eclipse/jkube/blob/40added43dc6fbb180e2c79572628d0471be4195/quickstarts/maven/micronaut/README.md) file.

**Comment by anurag-rajawat** [comment]
@rohanKanojia latest version of micronaut is 3.4.4, so it should be bumped to 3.4.4 or 3.4.1?

**Comment by rohanKanojia** [comment]
It should be bumped to latest version available

**Comment by Mohd-Farhan** [comment]
when i run the command " mvn clean package k8s:build k8s:resource k8s:apply" it shows error  " No plugin found for prefix 'k8s' in the current project and in the plugin groups " .
@anurag-rajawat

**Comment by anurag-rajawat** [comment]
It's because you're running the command from the project's root directory, you've to run that command from the micronaut directory

**Comment by Mohd-Farhan** [comment]
micronaut build was successful but on performing request it shows error 
curl: (28) Failed to connect to 192.168.49.2 port 32358 after 21032 ms: Timed out
i try some stackoverflow solution but it does not help

**Comment by anurag-rajawat** [comment]
> micronaut build was successful but on performing request it shows error curl: (28) Failed to connect to 192.168.49.2 port 32358 after 21032 ms: Timed out i try some stackoverflow solution but it does not help

@rohanKanojia I'm also facing this issue, and when I check for services it shows `service default/micronaut has no node port`

but when I add `<jkube.enricher.jkube-service.type>NodePort</jkube.enricher.jkube-service.type>`
 to the properties in the `pom.xml` or manually expose port with `type=NodePort` and again check for services it shows `default   | micronaut  | glrpc/9080   | http://192.168.49.2:31626 |` 
So, how to fix it?

**Comment by anurag-rajawat** [comment]
@Mohd-Farhan please update all the occurences of 
```shell
 $ curl $(minikube ip):$(kubectl get svc micronaut-customized-image -n default -o jsonpath='{.spec.ports[].nodePort}') 
```
to
```shell
 $ curl $(minikube ip):$(kubectl get svc micronaut -n default -o jsonpath='{.spec.ports[].nodePort}')
```
in the [README.md](https://github.com/eclipse/jkube/blob/40added43dc6fbb180e2c79572628d0471be4195/quickstarts/maven/micronaut/README.md) file 

@rohanKanojia correct me if I'm wrong

**Comment by Mohd-Farhan** [comment]
@anurag-rajawat after adding property it shows port but the error of connection is not resolve yet.

**Comment by Mohd-Farhan** [comment]
Sorry for delay , I was stuck in endsem.
