### ISSUE TITLE
[Gradle Quickstart] Port `quickstarts/maven/quarkus` to equivalent Gradle Quarkus quickstart 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1431]
### Description

Port [`quickstarts/maven/quarkus`](https://github.com/eclipse/jkube/tree/master/quickstarts/maven/quarkus) quickstart to Gradle

- [ ] Generate a sample Gradle application from [https://code.quarkus.io/](https://code.quarkus.io/) and make changes as done in maven quickstart
- [ ] Add Kubernetes and OpenShift Gradle Plugins
- [ ] Verify application is deployed correctly on [minikube](https://minikube.sigs.k8s.io/docs/) using Kubernetes Gradle Plugin
- [ ] Verify application is deployed correctly on [Red Hat Developer Sandbox](https://developers.redhat.com/developer-sandbox/get-started) using OpenShift Gradle Plugin

**Comment by anurag-rajawat** [comment]
@rohanKanojia may I work on this also?

**Comment by rohanKanojia** [comment]
Gradle doesn't have the concept of profiles. You can use properties to enable profile related properties. In this case, I'd say you can ignore adding these profiles.
