### ISSUE TITLE
Using a service account that already exists with openshift-maven-plugin and helm

### ISSUE THREAD

**Issue by zargarf** [eclipse/jkube#1438]
### Info

* Eclipse JKube version : 1.7.0
* Maven version (`mvn -v`) : 3.8.1

Hi. I'm having some issues trying with the openshift-maven-plugin when it comes to trying to reference using a serviceAccount that already exists. If I add into the configuration section of the openshift-maven-plugin in my pom.xml (1.7.0) the following (as per the docs):

```xml
<build>
  <plugins>
    <plugin>
        <groupId>org.eclipse.jkube</groupId>
        <artifactId>openshift-maven-plugin</artifactId>
        <version>1.7.0</version>
        <configuration>
          <resources>
            <serviceAccount>a-service-account-that-exists</serviceAccount>
          </resources>
        </configuration>
    </plugin>
  </plugins>
</build>
```

and then in my src/main/jkube/deployment.yml snippet file I have:
```
metatdata:
  name: some-deployment
spec:
  template:
    spec:
      serviceAccountName: a-service-account-that-exists
```

If I run `mvn clean install oc:resource` on the project, I end up with a some-deployment-serviceaccount.yml file under target/classes/META-INF/jkube/openshift. However I would have expected no service account config to be created, as I just want to use a service account that already exists. Am I doing something wrong ?
We're trying to use jkube with helm (via oc:helm), but after creating the chart using `oc:resource oc:helm` and then trying to apply it, helm fails because the service account already exists and cannot be imported into the release due to differing metadata.
We basically want to use a service account that already exists and therefore not have the helm chart try and create it. 

Can somebody please advise?
Thanks

**Comment by manusa** [comment]
We should improve the current ServiceAccountEnricher or break it into 2 different enrichers.
If improving the current enricher, we should add an additional property `skipCreate`to avoid the creation of the YAML.
