### ISSUE TITLE
JKube Kit : Add unit test for KindFilenameMapperUtil

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1440]
### Description

[KindFilenameMapperUtil](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/KindFilenameMapperUtil.java) doesn't seem to be covered by any unit tests.

- [ ] Write unit test to verify all required kind to filename mappings are loaded

**Comment by Devamparikh** [comment]
I will work on this.

**Comment by MMajd** [comment]
@rohanKanojia Hi Rohan, I wrote a unit test for this util class if it's ok with you I could make a PR 

[KindFilenameUtilTest](https://github.com/MMajd/jkube/blob/3c2fa787cd73f0a9287b142ead5b2fd12da42a30/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KindFilenameMapperUtilTest.java)

**Comment by rohanKanojia** [comment]
@Devamparikh : polite ping, are you still working on this issue?

**Comment by Devamparikh** [comment]
If @MMajd had already written unit tests, please let him complete this :smile:

**Comment by manusa** [comment]
Hi @MMajd, your PR has request changes, please address them.
