### ISSUE TITLE
JKube Kit : Add unit test for ProjectEnricher

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1441]
### Description

[ProjectEnricher](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/openshift/ProjectEnricher.java) doesn't seem to be covered by unit tests

- [x] Add a unit test to verify Project is generated as expected

**Comment by Devamparikh** [comment]
Assign this to me I will work on this.

**Comment by Devamparikh** [comment]
Assign this to me I will work on this.
