### ISSUE TITLE
DockerHealthCheckEnricherTest performs a redundant KubernetesList to JSON conversion

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1450]
### Description

Refactor [DockerHealthCheckEnricherTest](https://github.com/eclipse/jkube/blob/053e63e095222c26994984f73a4a4603f5489ef7/jkube-kit/enricher/specific/src/test/java/org/eclipse/jkube/kit/enricher/specific/DockerHealthCheckEnricherTest.java#L220) to remove the redundant conversion of the resulting KubernetesList into a JSON string that is parsed again further on within the test assertions.

### Relates to
- https://github.com/eclipse/jkube/issues/1344
- https://github.com/eclipse/jkube/issues/1448
- https://github.com/eclipse/jkube/issues/1449

**Comment by anurag-rajawat** [comment]
@rohanKanojia I want to work on this
