### ISSUE TITLE
SpringBootHealthCheckEnricher : Add `/actuator/startup` as startup probe if enabled

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1467]
### Description

Related to #1322 

[Spring Boot actuator](https://docs.spring.io/spring-boot/docs/2.5.6/reference/html/actuator.html) provides a `startup` endpoint which shows startup data. Here is a sample response

```json
{
  "springBootVersion": "2.5.6",
  "timeline": {
    "startTime": "2022-04-22T10:47:05.426341763Z",
    "events": [
      {
        "endTime": "2022-04-22T10:47:05.520464398Z",
        "duration": "PT0.062466167S",
        "startupStep": {
          "name": "spring.boot.application.starting",
```

I think this endpoint can be used by SpringBootHealthCheckEnricher as a startup probe. SpringBootHealthCheckEnricher should check whether startup is enabled or not; If enabled, it should add this endpoint as a startup probe in controller's PodTemplateSpec.

**Comment by Prathamkrishna** [comment]
I think i could pick this up if no one else has plans

**Comment by manusa** [comment]
We need to check if this is also supported in SpringBoot 1.x

**Comment by Prathamkrishna** [comment]
yep, it is is supported in SpringBoot 1.x

**Comment by rohanKanojia** [comment]
Hi guys, I revisited this and realized I had a misunderstanding regarding `/actuator/startup` endpoint. It's not related to Kubernetes probes.

In [Spring Boot Kubernetes probes](https://docs.spring.io/spring-boot/docs/2.7.x/reference/htmlsingle/#actuator.endpoints.kubernetes-probes) documentation, it's clearly stated there is no explicit startup endpoint supported:

> If an application takes longer to start than the configured liveness period, Kubernetes mentions the "startupProbe" as a possible solution. The "startupProbe" is not necessarily needed here, as the "readinessProbe" fails until all startup tasks are done.

Really sorry for the noise.
