### ISSUE TITLE
Filesystem-based tests fail because of non-english locale

### ISSUE THREAD

**Issue by cdprete** [eclipse/jkube#1469]
Hi.
I was running the tests from the cdprete:pr/issue1338#5001b3e2d8db5f05bd2d0b8ac092c581e3e27b7f version of the project and I've realized that some tests fail because they explicitly check the error message returned into the exception that doesn't match the expected one since the former is (automatically translated) in the system locale (Italian on my current machine) and the latter is in English:

For example
```
Expecting throwable message:
  <"Error reading fragment [C:\Users\41784\IdeaProjects\jkube\jkube-kit\enricher\api\target\test-classes\kubernetes-resource-util\I-Dont-EXIST.yaml] C:\Users\41784
\IdeaProjects\jkube\jkube-kit\enricher\api\target\test-classes\kubernetes-resource-util\I-Dont-EXIST.yaml (Impossibile trovare il file specificato)">
to contain:
  <"The system cannot find the file specified">
but did not.

Throwable that failed the check:

java.io.IOException: Error reading fragment [C:\Users\41784\IdeaProjects\jkube\jkube-kit\enricher\api\target\test-classes\kubernetes-resource-util\I-Dont-EXIST.yam
l] C:\Users\41784\IdeaProjects\jkube\jkube-kit\enricher\api\target\test-classes\kubernetes-resource-util\I-Dont-EXIST.yaml (Impossibile trovare il file specificato
)
```

Surefire and Failsafe should be configured to run the tests against the English locale as system locale or the messages should be loaded from the system resource bundle.

**Comment by rohanKanojia** [comment]
This failure is caused by this statement:

https://github.com/eclipse/jkube/blob/b57c09cc9e05e25a0e10281201ccbf4563a3854c/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java#L182

I checked with setting Italian locale on my system. If I remove this `.hasMessageContaining` assertion build succeeds.

I'm trying to configure surefire to run tests with English locale but it doesn't seem to be working. I've tried adding `<argLine>-Duser.language=en -Duser.country=US</argLine>`to my surefire plugin configuration. I've also tried setting locale programmatically `Locale.setDefault(new Locale("en", "US"))`  in test but that also doesn't seem to be working for me.

**Comment by cdprete** [comment]
@rohanKanojia the problem is that there are other of these assertions around as well. Given that the messages are translated, I would expect a ResourceBundle defined somewhere in the JDK, but I didn't find any on a rapid look.

Ideally we could load the message from such bundle (in the user's language) and compare it with the received one.

**Comment by rohanKanojia** [comment]
> the problem is that there are other of these assertions around as well.

Umm, that's strange. I'm able to get build to succeed by just removing this assertion. I'm on this locale at the moment:
```
jkube : $ locale
LANG=it_IT.UTF-8
LC_CTYPE="it_IT.UTF-8"
LC_NUMERIC="it_IT.UTF-8"
LC_TIME="it_IT.UTF-8"
LC_COLLATE="it_IT.UTF-8"
LC_MONETARY="it_IT.UTF-8"
LC_MESSAGES="it_IT.UTF-8"
LC_PAPER="it_IT.UTF-8"
LC_NAME="it_IT.UTF-8"
LC_ADDRESS="it_IT.UTF-8"
LC_TELEPHONE="it_IT.UTF-8"
LC_MEASUREMENT="it_IT.UTF-8"
LC_IDENTIFICATION="it_IT.UTF-8"
LC_ALL=
```

For now, I think we can just remove this assertion

**Comment by sunix** [comment]
@rohanKanojia maybe try to set the environment variable in pom.xml: https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#environmentVariables

**Comment by rohanKanojia** [comment]
@sunix : Thanks a lot, I was earlier trying `<systemPropertyVariables>` but setting `<environmentVariables>` seems to work:

```xml
            <environmentVariables>
              <LC_ALL>en_EN.UTF-8</LC_ALL>
           </environmentVariables>
```
