### ISSUE TITLE
WildflyJARHealthCheckEnricher : Add `/health/started` as startup probe if enabled

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1474]
### Description

Blocked by https://github.com/eclipse/jkube/issues/1322

[Wildfly Microprofile Health Subsystem](https://github.com/wildfly/wildfly/blob/main/docs/src/main/asciidoc/_admin-guide/subsystem-configuration/MicroProfile_Health.adoc#http-endpoints) configuration defines three HTTP endpoints:

- `/health/live` to test the liveness of the application server

- `/health/ready` to test the readiness of the application server.

- `/health/started` to test the startup of the application server.

WildflyJARHealthCheckEnricher seems to be adding `/health/live` and `/health/ready` for liveness and readiness probes. We need to add support for startup probe in that as well.

- [x] Add `/health/started` as startup probe in WildflyJARHealthCheckEnricher
- [x] UpdateWildflyJARHealthCheckEnricher  documentation about new probe

**Comment by anurag-rajawat** [comment]
@rohanKanojia may I work on this one?
