### ISSUE TITLE
Should detect and warn the user if `jkube.createExternalUrl=true` and ingress/route controller not available

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1478]
### Description
Basically when the ingress controller is not installed. JKube should detect it if it is creating an ingress that won't work. Cherry in the cake would be to tell which commands to run (for minikube: `minikube addons enable ingress`)

### Info

* Eclipse JKube version : 1.7.0

**Comment by manusa** [comment]
This should be applicable only to the apply mojo, and probably only for specific Kubernetes platforms (such as Minikube).
For example, in regular clusters you might not have access to the kube-system namespace.

**Comment by rohanKanojia** [comment]
I've created PR for detecting Ingress controllers on Kubernets clusters #1984 . 

However, I don't know if it's possible to disable Route Controller on OpenShift. I think it comes preinstalled with the OpenShift cluster.

Shall we also print some hint for user if he's using Ingress on OpenShift cluster and suggest using routes instead?

**Comment by manusa** [comment]
OpenShift supports Ingresses too.
In fact we might want to create some logic to create ingresses instead of routes in case an `Ingress` fragment is provided. Or even some flag to switch to `Ingress` generation instead of `Route` (similar to `jkube.build.switchToDeployment`).

**Comment by rohanKanojia** [comment]
> In fact we might want to create some logic to create ingresses instead of routes in case an Ingress fragment is provided. Or even some flag to switch to Ingress generation instead of Route (similar to jkube.build.switchToDeployment).

Shall I create a new issue for this?

**Comment by manusa** [comment]
Yes, please. However, we still need to investigate if we can switch completely to ingresses and see if OpenShift creates the routes for us (IIRC this was the behavior I saw but not 100% sure).
