### ISSUE TITLE
BaseGenerator: Verify & Align configuration options work to with properties

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1489]
### Description
Related to #1462 

BaseGenerator seems to have some common configuration options which are applicable to all generators:

https://github.com/eclipse/jkube/blob/0401297d4bcea783a94fc178af376c7a8a5a185d/jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java#L59-L79

Since these are generator configuration fields, they should be accessible via regular generator configuration properties i.e `jkube.generator.$generatorName.name`.

However, these fields are also accessible via these properties:

-  name `jkube.generator.name`
- alias `jkube.generator.alias`
- from `jkube.generator.from`
- fromMode `jkube.generator.fromMode`
- registry `jkube.generator.registry`

This is due to a method `getConfigWithFallback` which checks system and project properties with given key for config field value:

https://github.com/eclipse/jkube/blob/0401297d4bcea783a94fc178af376c7a8a5a185d/jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java#L185

There is one field `add` which doesn't seem to be accessible via this method. We need to decide whether we want to align it with rest of the options or remove these additional properties.

**Comment by manusa** [comment]
This should be applicable too for the new `tags` config option, unless it gets directly addressed in #1462 (not at the moment).
