### ISSUE TITLE
[Blog post]: Write a follow up blogpost to "Generate Helm charts for your Java application using JKube, Part 1"

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1493]
We recently submitted a blog post [Generate Helm charts for your Java application using JKube, Part 1](https://developers.redhat.com/articles/2022/04/14/generate-helm-charts-your-java-application-using-jkube-part-1) showcasing how well Eclipse JKube integrates with helm.

The blog post is good for beginner users, but we also need to provide a follow-up blog post explaining more advanced and real-world use cases.

**Comment by manusa** [comment]
Ready for review, should be published in a few days

**Comment by manusa** [comment]
https://developers.redhat.com/articles/2022/08/01/how-configure-helm-charts-using-jkube-part-2
