### ISSUE TITLE
no docker container created for hello-world

### ISSUE THREAD

**Issue by codezork** [eclipse/jkube#150]
If you try to run the hello-world sample with `mvn clean install k8s:build k8s:resource k8s:apply` the pod's status will show `helloworld-5f9d89f5c4-npjz9   0/1     ImagePullBackOff   0          17h` as there is no docker image in the repository. The log says: `Error from server (BadRequest): container "hello-world" in pod "helloworld-5f9d89f5c4-npjz9" is waiting to start: trying and failing to pull image`.
[pom.txt](https://github.com/eclipse/jkube/files/4473752/pom.txt)

**Comment by manusa** [comment]
If you are running with Minikube, remember to `eval $(minikube docker-env)` so that the Docker local image registry is shared with the cluster.

If running a regular K8s cluster, you need to push the image to repository so that the cluster can actually download the image.

**Comment by codezork** [comment]
Yep. This did the trick. Thank you. Why not mentioning at Readme.md? Fantastic job BTW, fabric8 and jkube!

**Comment by rohanKanojia** [comment]
@codezork : umm, Would you like to create a quick PR to fix our doc :wink: ?

**Comment by codezork** [comment]
LOL - why not? What about ISTIO? Do you have plans?

**Comment by rohanKanojia** [comment]
Umm, not so sure about Istio. I think we should definitely consider it. There was an issue filed on FMP regarding this https://github.com/fabric8io/fabric8-maven-plugin/issues/1164 . Maybe we should consider it after releasing JKube 1.0.0

**Comment by codezork** [comment]
hmm. Didn't sound like a show-stopper. Would be nice for a canary-release option.

**Comment by codezork** [comment]
PR done
