### ISSUE TITLE
[Quickstarts] : Update Custom Istio Enricher (Maven) quickstart to use Fabric8 Istio Extension

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1505]
### Description

When we created this quickstart we were using Snowdrop Istio Extension for manipulating Istio objects. This extension was recently migrated to Fabric8: https://github.com/fabric8io/kubernetes-client/issues/3493

https://github.com/eclipse/jkube/blob/7e849a7dd04466ea10684e0c493c3e5dcd5db1ea/quickstarts/kit/custom-istio-enricher/pom.xml#L58-L62

This dependency should be available under fabric8 groupId on [maven central](https://search.maven.org/artifact/io.fabric8/istio-client/5.12.2/bundle):

```xml
<dependency>
  <groupId>io.fabric8</groupId>
  <artifactId>istio-client</artifactId>
  <version>5.12.2</version>
</dependency>
```

- [x] Change dependency Maven coordinates and version
- [x] Update code to use updated package names (`me.snowdrop.istio.*` -> `io.fabric8.istio.*`)
- [ ] Make sure quickstart is working correctly as per instructions provided in README

**Comment by MMajd** [comment]
Hey @rohanKanojia, I have made a pull request that addresses this chore
