### ISSUE TITLE
A double inverse of the `skip` flag in AbstractJKubeMojo

### ISSUE THREAD

**Issue by Prathamkrishna** [eclipse/jkube#1510]
### Description

In the class `AbstractJKubeMojo`, if we see the overridden method `execute()`; the if block, there is a double inverse on the `!canExecute()` call, which reciprocates to a `!(!skip)`. I don't really think it is needed for a double inverse, so it should be changed to a `skip`.

### Info

* Eclipse JKube version :
* Maven version (`mvn -v`) :
```
Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
Maven home: /opt/homebrew/Cellar/maven/3.8.5/libexec
Java version: 18.0.1, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/18.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_IN, platform encoding: UTF-8
OS name: "mac os x", version: "12.3", arch: "aarch64", family: "mac"
```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :

* If it's a feature request, what is your use case :

* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by manusa** [comment]
Should probably be renamed to `shouldSkip()`

**Comment by Devamparikh** [comment]
I'd work on this.
