### ISSUE TITLE
k8s:watch - cannot be established due to java.lang.ClassNotFoundException: okhttp3.internal.ws.WebSocketProtocol

### ISSUE THREAD

**Issue by ZoltanMozes** [eclipse/jkube#153]
**Operating System**
$ uname -a
Linux zoltan-VirtualBox 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Eclipse JKube version**
<groupId>org.eclipse.jkube</groupId>
<artifactId>kubernetes-maven-plugin</artifactId>
<version>1.0.0-alpha-1</version>

**Java version**
$ java -version
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

**Maven version**
mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/zoltan/.sdkman/candidates/maven/current
Java version: 13.0.2, vendor: Oracle Corporation, runtime: /home/zoltan/dev/java/jdk-13.0.2
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-46-generic", arch: "amd64", family: "unix"

**Target cluster version (Kubernetes, OpenShift, Minikube, CRC, etc.)**
$ minikube version
minikube version: v1.9.1
commit: d8747aec7ebf8332ddae276d5f8fb42d3152b5a1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T20:08:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

**Symptom:**

`k8s:watch `

fails due to  

> [INFO] <<< kubernetes-maven-plugin:1.0.0-alpha-1:watch (default-cli) < :deploy @ shopping-cart <<<
> [INFO] 
> [INFO] 
> [INFO] --- kubernetes-maven-plugin:1.0.0-alpha-1:watch (default-cli) @ shopping-cart ---
> [INFO] k8s: Running generator spring-boot
> [INFO] k8s: spring-boot: Using Docker image fabric8/java-centos-openjdk11-jdk as base / builder
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.bouncycastle.jcajce.provider.drbg.DRBG (file:/home/zoltan/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.61/bcprov-jdk15on-1.61.jar) to constructor sun.security.provider.Sun()
> WARNING: Please consider reporting this to the maintainers of org.bouncycastle.jcajce.provider.drbg.DRBG
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> [INFO] k8s: Running watcher spring-boot
> [INFO] k8s: spring-boot: Watching pods with selector LabelSelector(matchExpressions=[], matchLabels={app=shopping-cart, provider=jkube, group=hu.egroup}, additionalProperties={}) waiting for a running pod...
> [INFO] k8s:[NEW] shopping-cart-685dbc5cc5-q8qr9 status: Running Ready
> [INFO] k8s:[NEW] Tailing log of pod: shopping-cart-685dbc5cc5-q8qr9
> [INFO] k8s:[NEW] Press Ctrl-C to stop tailing the log
> [INFO] k8s:[NEW] 
> [INFO] k8s: spring-boot: exec java -javaagent:/opt/agent-bond/agent-bond.jar=jolokia{{host=0.0.0.0}},jmx_exporter{{9779:/opt/agent-bond/jmx_exporter_config.yml}} -XX:+ExitOnOutOfMemoryError -cp . -jar /deployments/shopping-cart-0.0.1-SNAPSHOT.jar
> [INFO] k8s: spring-boot: I> No access restrictor found, access to any MBean is allowed
> [INFO] k8s: spring-boot: Jolokia: Agent started with URL http://172.18.0.12:8778/jolokia/
> [INFO] k8s: spring-boot: 
> [INFO] k8s: spring-boot:   .   ____          _            __ _ _
> [INFO] k8s: spring-boot:  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> [INFO] k8s: spring-boot: ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
> [INFO] k8s: spring-boot:  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
> [INFO] k8s: spring-boot:   '  |____| .__|_| |_|_| |_\__, | / / / /
> [INFO] k8s: spring-boot:  =========|_|==============|___/=/_/_/_/
> [INFO] k8s: spring-boot:  :: Spring Boot ::        (v2.2.6.RELEASE)
> [INFO] k8s: spring-boot: 
> [INFO] k8s: spring-boot: 2020-04-15 12:41:45.805  INFO 1 --- [           main] h.e.shopping.ShoppingServiceApplication  : Starting ShoppingServiceApplication v0.0.1-SNAPSHOT on shopping-cart-685dbc5cc5-q8qr9 with PID 1 (/deployments/shopping-cart-0.0.1-SNAPSHOT.jar started by jboss in /deployments)
> [INFO] k8s:[NEW] shopping-cart-685dbc5cc5-q8qr9 status: Running Ready
> [INFO] k8s: spring-boot: 2020-04-15 12:41:45.809  INFO 1 --- [           main] h.e.shopping.ShoppingServiceApplication  : No active profile set, falling back to default profiles: default
> [INFO] k8s: spring-boot: 2020-04-15 12:41:45.961  INFO 1 --- [           main] .e.DevToolsPropertyDefaultsPostProcessor : Devtools property defaults active! Set 'spring.devtools.add-properties' to 'false' to disable
> [INFO] k8s: spring-boot: 2020-04-15 12:41:45.962  INFO 1 --- [           main] .e.DevToolsPropertyDefaultsPostProcessor : For additional web related logging consider setting the 'logging.level.web' property to 'DEBUG'
> [INFO] k8s: spring-boot: 2020-04-15 12:41:48.413  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
> [INFO] k8s: spring-boot: 2020-04-15 12:41:48.428  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
> [INFO] k8s: spring-boot: 2020-04-15 12:41:48.428  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.33]
> [INFO] k8s: spring-boot: 2020-04-15 12:41:48.578  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
> [INFO] k8s: spring-boot: 2020-04-15 12:41:48.579  INFO 1 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2617 ms
> [INFO] k8s: spring-boot: 2020-04-15 12:41:48.888  WARN 1 --- [           main] .s.b.d.a.RemoteDevToolsAutoConfiguration : Listening for remote restart updates on /.~~spring-boot!~/restart
> [INFO] k8s: spring-boot: 2020-04-15 12:41:49.724  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
> [INFO] k8s: spring-boot: 2020-04-15 12:41:50.209  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
> [INFO] k8s: spring-boot: 2020-04-15 12:41:50.216  INFO 1 --- [           main] h.e.shopping.ShoppingServiceApplication  : Started ShoppingServiceApplication in 5.539 seconds (JVM running for 7.221)
> [INFO] k8s: spring-boot: No exposed service found for connecting the dev tools
> [INFO] k8s: Starting port-forward to pod shopping-cart-685dbc5cc5-q8qr9
> [INFO] k8s: spring-boot: Running RemoteSpringApplication against endpoint: http://localhost:65338
> [ERROR] k8s: An error has occurred while while trying to watch the resources [null]
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  24.655 s
> [INFO] Finished at: 2020-04-15T14:41:51+02:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.0.0-alpha-1:watch (default-cli) on project shopping-cart: An error has occurred while while trying to watch the resources: NullPointerException -> [Help 1]
> [ERROR] 
> [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
> [ERROR] Re-run Maven using the -X switch to enable full debug logging.
> [ERROR] 
> [ERROR] For more information about the errors and possible solutions, please read the following articles:
> [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
> Exception in thread "Thread-17" java.lang.NoClassDefFoundError: okhttp3/internal/ws/WebSocketProtocol
>         at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:415)
>         at okhttp3.internal.ws.RealWebSocket.close(RealWebSocket.java:411)
>         at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.closeWebSocket(WatchConnectionManager.java:374)
>         at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager.close(WatchConnectionManager.java:348)
>         at org.eclipse.jkube.ki[INFO] k8s: Port forwarding to port 8080 on pod shopping-cart-685dbc5cc5-q8qr9 using command /snap/bin/kubectl
> t.config.service.PortForwardService.lambda$forwardPortAsync$0(PortForwardService.java:166)
>         at org.eclipse.jkube.kit.config.service.PortForwardService$3.run(PortForwardService.java:177)
> Caused by: java.lang.ClassNotFoundException: okhttp3.internal.ws.WebSocketProtocol
>         at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
>         at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:271)
>         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:247)
>         at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:239)
>         ... 6 more

**Comment by manusa** [comment]
I'm currently working on a PR that fixes this issue #148 .

Additionally (once fixed) the application doesn't seem to reload once mvn package is run again.
