### ISSUE TITLE
UserConfigurationCompareTest : Use diamond operator `<>` for generics

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1536]
### Description
UserConfigurationCompareTest seems to have some places where we're doing raw declaration (i.e. collection type without any information of the element type). 

https://github.com/eclipse/jkube/blob/8df189ce4f331b7677251f653606c9e2cc899324/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompareTest.java#L68-L69

https://github.com/eclipse/jkube/blob/8df189ce4f331b7677251f653606c9e2cc899324/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompareTest.java#L81-L82

Also, we could use type safe `Collections.emptyMap()` here:
https://github.com/eclipse/jkube/blob/8df189ce4f331b7677251f653606c9e2cc899324/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompareTest.java#L56

### AC
- [x] Use diamond operator in `new HashMap()` constructor
- [x] Replace `Collections.EMPTY_MAP` with `Collections.emptyMap()`

**Comment by rohanKanojia** [comment]
@nabeelkhan10 : Could you please check if you can work on this?

**Comment by nabeelkhan10** [comment]
I know basics of java (currently studying sorting) I haven't studied data structure yet.
How much should I study before contributing?

**Comment by rohanKanojia** [comment]
This is a simple search/replace issue. I don't think you require knowledge of data structures in this.

**Comment by nabeelkhan10** [comment]
Yes got it

**Comment by nabeelkhan10** [comment]
I will do this

**Comment by nabeelkhan10** [comment]
I have forked

**Comment by nabeelkhan10** [comment]
I don't know what is happening when I open the repo it says that I made commit 30 min ago.
But anyways I have made a PR.
