### ISSUE TITLE
[EPIC] Migrate To JUnit5 Testing Framework from JUnit4

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1546]
### Description

Our current test suites are based on JUnit4. The goal of this epic is to migrate all of them to JUnit5.

### Goals
- Remove JUnit4 dependency
  - JUnit4 annotations should be replaced by JUnit5
  - JUnit4 rules should be replaced by applicable JUnit5 replacements
- Assertions should be replaced by AssertJ
- Tests should be evaluated and refactored if applicable

### Tasks
- Eclipse JKube (jkube)
  JKube Kit :: Parent (jkube-kit-parent)
  https://github.com/eclipse/jkube/issues/1547
- JKube Kit :: Common :: Test (jkube-kit-common-test)
  https://github.com/eclipse/jkube/issues/1548
- JKube Kit :: Common (jkube-kit-common)
  https://github.com/eclipse/jkube/issues/1549
- JKube Kit :: Common Maven (jkube-kit-common-maven)
  https://github.com/eclipse/jkube/issues/1551
- JKube Kit :: Config :: Image (jkube-kit-config-image)
  https://github.com/eclipse/jkube/issues/1552
- JKube Kit :: Config :: Resource (jkube-kit-config-resource)
  https://github.com/eclipse/jkube/issues/1553
- JKube Kit :: Build :: API (jkube-kit-build-api)
  https://github.com/eclipse/jkube/issues/1554
- JKube Kit :: Build :: Service :: Docker (jkube-kit-build-service-docker)
  https://github.com/eclipse/jkube/issues/1555
- JKube Kit :: Build :: Service :: JIB (jkube-kit-build-service-jib)
  https://github.com/eclipse/jkube/issues/1556
- JKube Kit :: Enricher :: API (jkube-kit-enricher-api)
  https://github.com/eclipse/jkube/issues/1557
- JKube Kit :: Resource :: Helm (jkube-kit-resource-helm)
  https://github.com/eclipse/jkube/issues/1558
- JKube Kit :: Config :: Service (jkube-kit-config-service)
  https://github.com/eclipse/jkube/issues/1559
- JKube Kit :: Generator :: API (jkube-kit-generator-api)
  https://github.com/eclipse/jkube/issues/1560
- JKube Kit :: Generator :: Java Exec (jkube-kit-generator-java-exec)
  https://github.com/eclipse/jkube/issues/1561
- JKube Kit :: Generator :: Karaf (jkube-kit-generator-karaf)
  https://github.com/eclipse/jkube/issues/1562
- JKube Kit :: Generator :: WebApp (jkube-kit-generator-webapp)
  https://github.com/eclipse/jkube/issues/1563
- JKube Kit :: Enricher :: Generic (jkube-kit-enricher-generic)
  https://github.com/eclipse/jkube/issues/1564
- JKube Kit :: Enricher :: Specific (jkube-kit-enricher-specific)
  https://github.com/eclipse/jkube/issues/1565
- JKube Kit :: Profile (jkube-kit-profiles)
  https://github.com/eclipse/jkube/issues/1566
- JKube Kit :: Resource :: Service (jkube-kit-resource-service)
  https://github.com/eclipse/jkube/issues/1567
- JKube Kit :: Watcher :: API (jkube-kit-watcher-api)
  https://github.com/eclipse/jkube/issues/1568
- JKube Kit :: Watcher :: Standard (jkube-kit-watcher-standard)
  https://github.com/eclipse/jkube/issues/1569
- JKube Kit :: Spring-Boot (jkube-kit-spring-boot)
  https://github.com/eclipse/jkube/issues/1570
- JKube Kit :: Thorntail (jkube-kit-thorntail)
  https://github.com/eclipse/jkube/issues/1571
- JKube Kit :: Vert.x (jkube-kit-vertx)
  https://github.com/eclipse/jkube/issues/1572
- JKube Kit :: Quarkus (jkube-kit-quarkus)
  https://github.com/eclipse/jkube/issues/1573
- JKube Kit :: Micronaut (jkube-kit-micronaut)
  https://github.com/eclipse/jkube/issues/1574
- JKube Kit :: Open Liberty (jkube-kit-openliberty)
  https://github.com/eclipse/jkube/issues/1575
- JKube Kit :: WildFly JAR (jkube-kit-wildfly-jar)
  https://github.com/eclipse/jkube/issues/1576
- Kubernetes Maven Plugin :: Plugin (kubernetes-maven-plugin)
  https://github.com/eclipse/jkube/issues/1577
- Kubernetes Maven Plugin :: Integration Tests (kubernetes-maven-plugin-it)
  https://github.com/eclipse/jkube/issues/1578
- OpenShift Maven Plugin :: Plugin (openshift-maven-plugin)
  https://github.com/eclipse/jkube/issues/1579
- OpenShift Maven Plugin :: Integration Tests (openshift-maven-plugin-it)
  https://github.com/eclipse/jkube/issues/1580
- Gradle Plugin :: Kubernetes (org.eclipse.jkube.kubernetes.gradle.plugin)
  https://github.com/eclipse/jkube/issues/1581
- Gradle Plugin :: OpenShift (org.eclipse.jkube.openshift.gradle.plugin)
  https://github.com/eclipse/jkube/issues/1582
- Gradle Plugin :: Integration Tests (gradle-plugin-it)
  https://github.com/eclipse/jkube/issues/1583
- ~JKube Kit (jkube-kit-build)~
- ~JKube Kit :: Documentation (jkube-kit-doc)~
- ~Kubernetes Maven Plugin :: Parent (kubernetes-maven-plugin-parent)~
- ~Kubernetes Maven Plugin :: Documentation (kubernetes-maven-plugin-doc)~
- ~OpenShift Maven Plugin:: Parent (openshift-maven-plugin-parent)~
- ~Gradle Plugin :: Parent (gradle-plugin)~
- ~Gradle Plugin :: Documentation (gradle-plugin-doc)~

**Comment by anurag-rajawat** [comment]
@manusa please assign this to me

**Comment by anurag-rajawat** [comment]
@manusa this epic is completed, we can close this 🚀

**Comment by rohanKanojia** [comment]
@anurag-rajawat : Congratulations on successfully completing the project :tada: . ! Nice work :star:

**Comment by manusa** [comment]
Congrats, you made it :rocket: 
Anurag, you did an awesome job, thanks a lot for your contributions.
I hope this marks the start of a successful career and that you keep contributing to free software and its community.

**Comment by anurag-rajawat** [comment]
I am very grateful to have mentors like both of you and this was not possible without your support and regular feedback.
Thanks a lot 🙏
