### ISSUE TITLE
(kubernetes-maven-plugin): Replace JUnit4 with JUnit5 

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1577]
### Component

kubernetes-maven-plugin

### Task description

Child of #1546

- Remove JUnit4 dependencies
- Add JUnit5 dependencies
- Refactor tests

**Comment by anurag-rajawat** [comment]
@rohanKanojia please assign this to me.

**Comment by anurag-rajawat** [comment]
@rohanKanojia assign this to me not to yourself.

**Comment by rohanKanojia** [comment]
lol, sorry for the noise :laughing:
