### ISSUE TITLE
(openshift-maven-plugin-it): Replace JUnit4 with JUnit5 

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1580]
### Component

openshift-maven-plugin-it

### Task description

Child of #1546

- Remove JUnit4 dependencies
- Add JUnit5 dependencies
- Refactor tests

**Comment by anurag-rajawat** [comment]
@manusa these are integration tests, not unit tests so we can close this issue.

**Comment by manusa** [comment]
These tests are executed through the maven-invoker-plugin not JUnit.
