### ISSUE TITLE
(jkube-kit/config/image/) : Migrate tests from JMockit to Mockito

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1584]
### Component

JKube Kit

### Description

Child of https://github.com/eclipse/jkube/issues/857

Migrate the following tests to use [Mockito](https://site.mockito.org/)  instead of [JMockit](https://jmockit.github.io/):

- ImageConfigurationTest
- BuildConfigurationTest

### Expected Behavior
All tests in the abovementioned need to be migrated to mockito. All references to [jmockit](https://jmockit.github.io/) should be removed or replaced with [Mockito](https://site.mockito.org/) equivalents.

### Acceptance Criteria
- [x] tests should be migrated to mockito
- [x] Dependency `org.jmockit:jmockit` should be removed from `pom.xml`
- [ ] Assertions should be replaced by AssertJ
- [ ] Tests should be evaluated and refactored if applicable (optional)

**Comment by baruKreddy** [comment]
@rohanKanojia please assign this to me.

**Comment by manusa** [comment]
I left this one open because the 3rd point of the AC (Assertions should be replaced by AssertJ) was not addressed

**Comment by rohanKanojia** [comment]
@baruKreddy : Could you please address AC which Marc just pointed out?

**Comment by baruKreddy** [comment]
Sure, will work on it!
