### ISSUE TITLE
DOC: Update Red Hat Developer Introduction to Eclipse JKube post

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#159]
## Description

Eclipse JKube Introduction blog post is outdated with current status of the project and API (version numbers and artifact ids).

https://developers.redhat.com/blog/2020/01/28/introduction-to-eclipse-jkube-java-tooling-for-kubernetes-and-red-hat-openshift/

**Comment by rohanKanojia** [comment]
I will update this blog with updated screenshots once `1.0.0-alpha-2` is released. We also need to update the demo GIFs in README

**Comment by manusa** [comment]
Agreed.

Ideally we should try to provide something with less weight. They are > 2.5 MiB each and it's not a very good idea to embed so big-sized images in a landing page. > https://github.com/nbedos/termtosvg

**Comment by rohanKanojia** [comment]
I have submitted a revision for the blogpost for review.

**Comment by rohanKanojia** [comment]
The revision has been approved and changes can be seen online: https://developers.redhat.com/blog/2020/01/28/introduction-to-eclipse-jkube-java-tooling-for-kubernetes-and-red-hat-openshift/
