### ISSUE TITLE
(jkube-kit/enricher/specific/) : Migrate tests from JMockit to Mockito

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1592]
### Component

JKube Kit

### Description

Child of https://github.com/eclipse/jkube/issues/857

Migrate the following tests to use [Mockito](https://site.mockito.org/)  instead of [JMockit](https://jmockit.github.io/):

- AbstractHealthCheckEnricherTest
- DockerHealthCheckEnricherTest
- PrometheusEnricherTest
- ServiceDiscoveryEnricherTest
- WebAppHealthCheckEnricherTest

### Expected Behavior
All tests in the abovementioned need to be migrated to mockito. All references to [jmockit](https://jmockit.github.io/) should be removed or replaced with [Mockito](https://site.mockito.org/) equivalents.

### Acceptance Criteria
- [x] tests should be migrated to mockito
- [x] Dependency `org.jmockit:jmockit` should be removed from `pom.xml`
- [x] Assertions should be replaced by AssertJ
- [ ] Tests should be evaluated and refactored if applicable (optional)

**Comment by baruKreddy** [comment]
@rohanKanojia Please assign this to me!
