### ISSUE TITLE
(jkube-kit/watcher/standard) : Migrate tests from JMockit to Mockito

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1606]
### Component

JKube Kit

### Description
Child of https://github.com/eclipse/jkube/issues/857

Migrate the following tests to use [Mockito](https://site.mockito.org/)  instead of [JMockit](https://jmockit.github.io/):

- DockerImageWatcherTest
- PodExecutorTest

### Expected Behavior
All tests in the abovementioned need to be migrated to mockito. All references to [jmockit](https://jmockit.github.io/) should be removed or replaced with [Mockito](https://site.mockito.org/) equivalents.

### Acceptance Criteria
- [x] tests should be migrated to mockito
- [x] Dependency `org.jmockit:jmockit` should be removed from `pom.xml`
- [ ] Assertions should be replaced by AssertJ
- [ ] Tests should be evaluated and refactored if applicable (optional)

**Comment by MMajd** [comment]
@rohanKanojia if this issue is open for community, I would like to work on it

**Comment by rohanKanojia** [comment]
Sorry, it's created for GSoC project.

**Comment by baruKreddy** [comment]
@rohanKanojia As agreed we need to refactor PodExecutorTest source code. Parking it for now.Thanks!
