### ISSUE TITLE
 (kubernetes-maven-plugin/plugin) : Migrate tests from JMockit to Mockito

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1607]
### Component

Kubernetes Maven Plugin

### Description

Child of https://github.com/eclipse/jkube/issues/857

Migrate the following tests to use [Mockito](https://site.mockito.org/)  instead of [JMockit](https://jmockit.github.io/):

- BuildMojoTest
- HelmMojoTest
- HelmPushMojoTest
- UndeployMojoTest

### Expected Behavior
All tests in the abovementioned need to be migrated to mockito. All references to [jmockit](https://jmockit.github.io/) should be removed or replaced with [Mockito](https://site.mockito.org/) equivalents.

### Acceptance Criteria
- [x] tests should be migrated to mockito
- [x] Dependency `org.jmockit:jmockit` should be removed from `pom.xml`
- [x] Assertions should be replaced by AssertJ
- [ ] Tests should be evaluated and refactored if applicable (optional)

**Comment by rohanshankar** [comment]
I can take this up if it is still an issue

**Comment by manusa** [comment]
> I can take this up if it is still an issue

These issues are part of the GSoC program, not meant to be taken by other members of the community (at least until the GSoC period ends)
