### ISSUE TITLE
property `jkube.enricher.jkube-controller.pullPolicy` is not taken into account if a `deployment` resource fragment is defined

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1619]
### Describe the bug

Trying to use `jkube.enricher.jkube-controller.pullPolicy` to set the image pull policy to `Always`. It works. However, once I added a `deployment` resource fragment, even not related, it stopped working.

### Eclipse JKube version

1.8.0

### Component

Kubernetes Maven Plugin

### Steps to reproduce

1. Create a spring boot app from 
2. Add the kubernetes maven plugin
3. Add in the pom.xml properties `<jkube.enricher.jkube-controller.pullPolicy>Always</jkube.enricher.jkube-controller.pullPolicy>`
4. `mvn k8s:resource`, the generated configuration with a pullpolicy to `Always` for the container image.
5. Add the file `src/main/jkube/deployment.yml`
  ```
  spec:
    replicas: 2
  ```
7.  `mvn k8s:resource`, the generated configuration with a pullpolicy to `IfNotPresent` for the container image.

### Expected behavior

it should keep the pull policy to `Always`

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

**Comment by manusa** [comment]
So apparently we have at least 4 ways to control the pull policy (fragment, XML configuration, and 2 enricher peroperties).

We need to centralize where this configuration is computed and make sure it just works. (IIRC we did something similar for at least one other property).
