### ISSUE TITLE
[JKube Kit] : Unable to build project on JDK8

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1630]
### Component

JKube Kit

## Description

I'm not able to build a project on JDK8. I've tried both Sun and Temurin JDKs, but I'm constantly getting this error:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project jkube-kit-common-test: Compilation failure
[ERROR] /home/rokumar/work/repos/jkube/jkube-kit/common-test/src/main/java/org/eclipse/jkube/maven/it/Verify.java:[21,33] cannot access com.consol.citrus.context.TestContext
[ERROR]   bad class file: /home/rokumar/.m2/repository/com/consol/citrus/citrus-api/3.2.1/citrus-api-3.2.1.jar(com/consol/citrus/context/TestContext.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```

I can compile only after reverting https://github.com/eclipse/jkube/commit/c700e1cfa8063477e0883a2fe257e7d43bc84e9b and https://github.com/eclipse/jkube/commit/55f8b1dc06afb2e9e90cb89c556f0255aa5a6fce

I'm seeing the same error on [Eclipse CI](https://ci.eclipse.org/jkube/job/daily-build/) (which is based on JDK8) as well. It's failing since June 15 (when Eclipse JGit changes got merged). Here are a few sample logs:
- https://ci.eclipse.org/jkube/job/daily-build/291/console
- https://ci.eclipse.org/jkube/job/daily-build/290/console
- https://ci.eclipse.org/jkube/job/daily-build/289/console
- https://ci.eclipse.org/jkube/job/daily-build/288/console
- https://ci.eclipse.org/jkube/job/daily-build/287/console
- https://ci.eclipse.org/jkube/job/daily-build/286/console
- https://ci.eclipse.org/jkube/job/daily-build/285/console
- https://ci.eclipse.org/jkube/job/daily-build/284/console
- https://ci.eclipse.org/jkube/job/daily-build/273/console

**Comment by manusa** [comment]
#1620 **requires** Java 11 to be able to run as stated in the PRs description. However, those modules won't be included in the build unless a valid JDK 11 is detected.

I assume that the problem then is JGit then, but that's odd because the build in its PR (#1611) worked out in Java 8. (<---- Is it possible that non of the CircleCI builds is running on Java 8?)

**Comment by manusa** [comment]
> (<---- Is it possible that non of the CircleCI builds is running on Java 8?)

Considering this, the verify related classes should be moved to another module which requires Java 11.

**Comment by manusa** [comment]
Hi @rohanKanojia 
Regarding #1637, this is not the way to proceed.
Let's split this task
- Revert JGit to the latest version with JDK 8 support. This is a core feature of JKube, so it cannot be based on Java 11.
- CircleCI pipeline to build on Java 8. We already have 3 pipelines doing more or less the same (build, sonar, test). The build pipeline should be based on JDK 8, the rest can be based on JDK 11 or 17 (latest LTS). This pipeline should have an initial check to make sure that it's running on a Java 8 compatible JVM (java -version grep), to make sure this won't happen again.
- Reorganize the common-test module.

If you agree, maybe you can take care of the first two tasks and I can check the last one.

**Comment by manusa** [comment]
> I've extracted Verify to common-it module. After reverting JGit changes, it should look a bit cleaner. Shall I take care of all three? Or perhaps you were referring to something else with reorganizing common-test module?

I'm referring to something else. Properly analyze its usages and see if it makes sense to still have the extra-module or not. I'll take care of that one. If you want to reuse #1637, then it should include one commit for the JGit "reversion" and another for pipeline refactor.
