### ISSUE TITLE
VertxHealthCheckEnricher should also check Vertx Gradle Plugin in `isApplicable()`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1633]
### Component

JKube Kit

### Description
VertxHealthCheckEnricher has this `isApplicable` method which is used for checking whether we should apply this enricher on a project or not. 

https://github.com/eclipse/jkube/blob/61345823be63c73cf334649e33e9c5146f9d5f7a/jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/enricher/VertxHealthCheckEnricher.java#L104-L107

We should also add logic to check Vertx Gradle Plugin here as well, just like we have it in [VertxGenerator](https://github.com/eclipse/jkube/blob/master/jkube-kit/jkube-kit-vertx/src/main/java/org/eclipse/jkube/vertx/generator/VertxGenerator.java#L52)

### Acceptance Criteria
- [x] VertxHealthCheckEnricher should also consider Vertx Gradle Plugin in `isApplicable`
- [x] VertxHealthCheckEnricher documentation is ported to Gradle

**Comment by Devamparikh** [comment]
Let me take this up.

**Comment by ayushdubey755** [comment]
is this issue has to be made some changes?

**Comment by rohanKanojia** [comment]
No, there will be fixed via https://github.com/eclipse/jkube/pull/1636
