### ISSUE TITLE
MicronautHealthCheckEnricher should also consider Micronaut Gradle Plugin in `isApplicable`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1634]
### Component

JKube Kit

### Description

MicronautHealthCheckEnricher has `isApplicable` method to check whether we should apply this enricher or not based on project dependencies:

https://github.com/eclipse/jkube/blob/61345823be63c73cf334649e33e9c5146f9d5f7a/jkube-kit/jkube-kit-micronaut/src/main/java/org/eclipse/jkube/micronaut/enricher/MicronautHealthCheckEnricher.java#L75-L79

It is not considering Micronaut Gradle Plugin. We should refactor this to use `MicronautUtils.hasMicronautPlugin` method which considers both cases:
```diff
-    if (!getContext().hasPlugin("io.micronaut.build", "micronaut-maven-plugin")) {
+    if (!hasMicronautPlugin(getContext().getProject())) {
```

### Acceptance Criteria
- [ ] Refactor `isApplicable` method to consider Micronaut Gradle Plugin
- [ ] Port [Micronaut health check](https://raw.githubusercontent.com/eclipse/jkube/master/jkube-kit/doc/src/main/asciidoc/inc/_enricher.adoc) documentation to gradle

**Comment by Prathamkrishna** [comment]
hey rohan, I'll like to pick this up
