### ISSUE TITLE
[Quickstarts] : Update Quarkus Customized Image Maven quickstart to latest version

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1638]
### Description

[Quarkus Customized Image](https://github.com/eclipse/jkube/tree/master/quickstarts/maven/quarkus-customized-image) quickstart seems to be using quite an old version of Quarkus. It should be updated to the latest version.

Also it's also using JKube's old `<inline>` format which has been deprecated in favor of `<layers> ..<layer></layer> </layers>`:

https://github.com/eclipse/jkube/blob/61345823be63c73cf334649e33e9c5146f9d5f7a/quickstarts/maven/quarkus-customized-image/pom.xml#L99

### Acceptance Criteria
- [ ] Update Quickstart to use latest version of Quarkus
- [ ] Replace deprecated configuration `<inline>` syntax with `<layers>` element

**Comment by ayushdubey755** [comment]
in the pom.xml the version can i change 2.11.0.Final @rohanKanojia

**Comment by rohanKanojia** [comment]
@ayushdubey755 : I don't think we have any rule regarding branch names. For more information about getting started with contributing to JKube, you can  read my blogpost[0]

[0] https://rohaan.medium.com/how-to-contribute-to-eclipse-jkube-f3bc7f902bf4
