### ISSUE TITLE
Spring Boot Generator should utilize the layered jar if present and use it as Docker layers

### ISSUE THREAD

**Issue by friedeas** [eclipse/jkube#1674]
### Is your enhancement related to a problem? Please describe

Using Spring Boots “fat jar” in the Dockerfile instead of the layers provided in the layered jar gives away the potential for an optimized image.

### Describe the solution you'd like

If a layered Spring Boot jar is detected the layers returned from the command
`java -Djarmode=layertools -jar target/sample-app.jar list`
should be used as layers in the generated Dockerfile

**Comment by ayushdubey755** [comment]
@friedeas can you please specify the file in which changes has to be made?

**Comment by manusa** [comment]
The context for this issue is here: https://gitter.im/eclipse/jkube?at=62dfd33c76cd751a2f86b25f

A refactor of the Spring Boot generator is needed prior to changing its behavior. We will be taking care of these tasks.

**Comment by ayushdubey755** [comment]
@manusa i just want to contribute so some other issue i have taged you there can you assign me those issue?

**Comment by friedeas** [comment]
@manusa is there any chance that the Spring Boot generator will be refactored in the near future to address this issue?

**Comment by manusa** [comment]
Duplicate of #763
