### ISSUE TITLE
Service YAML is missing selector

### ISSUE THREAD

**Issue by TooDissing** [eclipse/jkube#1706]
### Describe the bug

We have been using JKube with Openshift for at while now. And now we are going to migrate to a new AKS based setup, so "vanilla kubernetes" instead of open shift. This migration are causing some problems.
It seems that the `Deployment` and `Service` object isn't linked together correctly. They `Service` selector is missing.
For the `Deployment` it is something like this:
```
  selector:
    app: elastic-apm-upgrade-tester-dev
    provider: jkube
    group: dk.ufst.test
```
but it is absent in the `Service` object.

We are using the `jkube-project-label` enricher to set a custom `app` value.

Can't seem to figure out what goes wrong - works fine with OpenShift, but not with the Kubernetes plugin.

### Eclipse JKube version

1.8.0

### Component

Kubernetes Maven Plugin

### Apache Maven version

3.6.3

### Steps to reproduce

Call `mvn clean process-resources k8s:resource`

### Expected behavior

Selector part added to the `Service` yaml

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.21.6

### Environment

Linux

**Comment by rohanKanojia** [comment]
I'm not sure I fully understand. We have integration tests to verify resource generation. I can see selector element being present both in Deployment and Service:

https://github.com/eclipse/jkube/blob/06916b680800ea74123ae40e696065536062612e/kubernetes-maven-plugin/it/src/it/spring-boot/expected/kubernetes.yml#L29-L51

Or are you referring to selector not being specified in `matchLabels`?

**Comment by TueDissingWork** [comment]
Well it isn't there....I will try to dig a little in the test code, to see what makes that work and not my config.

**Comment by TueDissingWork** [comment]
this part is missing somehow - hopefully just config error
```     selector: 
       app: jkube-maven-sample-spring-boot 
       provider: jkube 
       group: org.eclipse.jkube 
```

**Comment by TueDissingWork** [comment]
After some further testing I have narrowed it down a bit. When I add the `jkube-project-label` enricher to my config things go wrong - i.e. no selector. When running the build without this enricher everything works as expected.

```
<enricher>
     <includes>
          <include>jkube-project-label</include>
     </includes>
</enricher>
```

I can try to write a test for this, using the above as expected result.

**Comment by TueDissingWork** [comment]
Strangely I am having problems running the IT tests - it seems I have to add several runtime dependencies to the validator (running the Groovy verify script).
Will see how far I get.

**Comment by rohanKanojia** [comment]
Hmm, I usually do `mvn clean install` to run all tests or `mvn clean install -Dinvoker.test=test-name` to run a single one in `it/` directory.

If you're having problems with integration tests, you can also try my demo repository which is showing same behavior: https://github.com/rohanKanojia/eclipse-jkube-demo-project

**Comment by manusa** [comment]
>  When I add the jkube-project-label enricher to my config things go wrong - i.e. no selector. 

This is odd, since this Enricher is part of the [default Enrichers](https://github.com/eclipse/jkube/blob/55f0e9863a0a265a19fbc8b2e4649bbe1b9a50ff/kubernetes-maven-plugin/plugin/src/main/resources/META-INF/jkube/profiles-default.yml#L30) (This means that unless you're using a different profile, this Enricher should already be part of your build).

Your issue is probably related to the order of execution of the Enrichers once you explicitly add this one. Are you really sure you need to add this Enricher to the `<includes>` configuration? If so, could you tell us which profile are you using instead of the default so we can try to reproduce?

**Comment by TueDissingWork** [comment]
When removing the above mentioned `<include/>`  element everything works as expected. So we have a working solution, but still think this is a regression, as this type of config should not cause a difference, but maybe I am missing something here.

Will commit a test showing this soonish.

**Comment by manusa** [comment]
This configuration is used to override the profile settings, so it should indeed cause a difference.

See [Profiles](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#profiles) documentation.

> 9.1 Generator and Enricher definitions -> includes -> List of generators or enrichers to include. The order in the list determines the order in which the processors are applied.

**Comment by TueDissingWork** [comment]
Thanks. Will re-read the documentation 😊

added a test case here:
https://github.com/eclipse/jkube/compare/master...TueDissingWork:jkube:master
