### ISSUE TITLE
Add HelidonGenerator to add opinionated container image for Helidon applications

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1714]
### Component

JKube Kit

### Description
Child of #1475 

Just like other frameworks, we need to add opinionated container image creation support for Helidon. For that, we need to add HelidonGenerator in a new module `jkube-kit-helidon` that would get activated when `io.helidon.build-tools:helidon-maven-plugin` is present in project.

### Expected Behavior
Use should be able to generate container images in zero configuration with Helidon framework

### Acceptance Criteria
- [ ] Add HelidonGenerator which would extend JavaExecGenerator
- [ ] Add unit tests to verify HelidonGenerator works as expected
- [ ] Add documentation for this new generator

**Comment by vaishnavi-ramanujapuram** [comment]
Hi, I would like to contribute to the above issue. I'm a first time contributor and this is mandatory for my course work. I'm willing to learn the concepts related to it while solving it. Could you please assign it to me.

**Comment by rohanKanojia** [comment]
@vaishnavi-ramanujapuram : I'm afraid this might not be an issue for newcomers. But if you want to try it I won't stop you.

In order to work on this, you'd need to learn about Helidon, Docker, and JKube. You need to add a module similar to https://github.com/eclipse/jkube/tree/master/jkube-kit/jkube-kit-micronaut
