### ISSUE TITLE
Not include Imagestream tags in Deployment Config

### ISSUE THREAD

**Issue by mwinzie** [eclipse/jkube#1742]
### Discussed in https://github.com/eclipse/jkube/discussions/1741

<div type='discussions-op-text'>

<sup>Originally posted by **mwinzie** September  6, 2022</sup>
I am using the openshift maven plugin to generate resources oc:resource. I however would not want to have imagestream tags included. Any idea how to go about this?</div>

**Comment by manusa** [comment]
The discussion appears to be resolved, is this issue still applicable?

**Comment by mwinzie** [comment]
Yes this was resolved.
