### ISSUE TITLE
Re-enable tests on Jenkins Release pipelines

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1753]
### Component

JKube Kit

### Task description

I had to temporarily disable test in the release pipelines because the tests related to the remote resource fragments features are failing:

```
Caused by: java.io.IOException: Failed to download URL https://gist.githubusercontent.com/lordofthejars/ac2823cec7831697d09444bbaa76cd50/raw/e4b43f1b6494766dfc635b5959af7730c1a58a93/deployment.yaml to  /tmp/jkube6633473296172234022/deployment.yaml: java.util.concurrent.ExecutionException: java.net.UnknownHostException: gist.githubusercontent.com
...
[ERROR] Errors: 
[ERROR]   KubernetesHelperTest.testGetResourceFragmentFromSourceWithNullResourceDirAndSomeRemotes:115 » IllegalArgument
[ERROR]   KubernetesHelperTest.testGetResourceFragmentFromSourceWithSomeResourceDirAndSomeRemotes:130 » IllegalArgument
[ERROR]   KubernetesHelperTest.testResourceFragmentsWithRemotes:82 » IllegalArgument jav...
```

We need to refactor these tests so that the fragments are downloaded from a temporary localhost web server.

Once these tests are replaced, the pipelines should be modified again to re-enable the tests.

- [x] Refactor tests
- [x] Re-enable tests in pipelines

**Comment by rohanKanojia** [comment]
It's not just KubernetesHelperTest that's failing on jenkins. Ever since https://github.com/eclipse/jkube/pull/1878 got merged our [daily jenkins build](https://ci.eclipse.org/jkube/job/daily-build/) has been failing :

```
[ERROR] Failures: 
[ERROR]   DebugServiceTest.debugWithApplicableEntities:212 
[ERROR]   DebugServiceTest.debugWithApplicableEntitiesAndSuspend
```

**Comment by manusa** [comment]
Tests still need to be reenabled in release pipeline

**Comment by sunix** [comment]
we could reenable the tests together next time we release JKube

**Comment by manusa** [comment]
Tests have been re-enabled.
