### ISSUE TITLE
Autoscaling not working as expected

### ISSUE THREAD

**Issue by mwinzie** [eclipse/jkube#1764]
### Discussed in https://github.com/eclipse/jkube/discussions/1763

<div type='discussions-op-text'>

<sup>Originally posted by **mwinzie** September 21, 2022</sup>
I have hpa.yaml already defined but pods are spining to the maximum amount of replicas. For example my minimum can be one and maximum 2 but 2 pods gets created when it should just be one to begin with. 

I included the jkube.enricher.jkube-controller.replicaCount and set it to 1 but with maximum replicas of 3, 2 pods get deployed instead of 3
</div>

**Comment by manusa** [comment]
Hi @mwinzie 
Did the `jkube.replicas` configuration fix your issue (https://github.com/eclipse/jkube/discussions/1763#discussioncomment-3734112)?
Is there something else you need us to fix?

**Comment by mwinzie** [comment]
Hi @manusa yes it did, thanks
