### ISSUE TITLE
[Hacktoberfest] AssemblyFiles.entries may be 'final'

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1782]
### Description
The following statement is reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/892ba7092627a7f0712ff68427361fb2d9cd976d/jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyFiles.java#L32
 
- [x] should be changed to:
```java
    private final List<AssemblyFileEntry> entries = new ArrayList<>();
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by ishu-thakur** [comment]
Hi @manusa can you assign that to me :) ?

**Comment by manusa** [comment]
Hi @ishu-thakur 
You've already contributed to the project, issues labeled with `first-timers-only` are limited to first time contributors to the project (and at most one).
The whole point of these very simple issues is for people to get acquainted with the project, with the Eclipse Foundation processes, and in general with free open source software. Consider that it takes longer for me to create the issue than to create the actual fix. We believe that these kind of issues help the community and this is why we put an extra-effort submitting them, if a single contributor was to tackle all of these issues, our effort would be wasted.

**Comment by manish-singh-bisht** [comment]
Hey @manusa can I do this.
