### ISSUE TITLE
[Hacktoberfest] AuthConfigFactory fields may be 'final'

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1783]
### Description
The following statement is reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/17ada413b53017ce446da3326ef1a5ff31d48e43/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactory.java#L638
 
- [x] should be changed to:
```java
        private final String configMapKey;
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by shubhamrawat090** [comment]
hey @manusa is anyone working on this? please assign it to me if not

**Comment by ishu-thakur** [comment]
Hi @manusa can you assign that to me :) ?

**Comment by DevPJ9** [comment]
Hello @manusa I would like to work on this one please assign this to me.

**Comment by Gairick52** [comment]
Hello @manusa i would love to work on this one please assign this to me

**Comment by manusa** [comment]
> Hello @manusa i would love to work on this one please assign this to me

Hi @Gairick52 
This one is already taken, but you can find similar issues labeled with [hacktoberfest](https://github.com/eclipse/jkube/labels/Hacktoberfest) still available.

**Comment by DevPJ9** [comment]
Hey, @manusa I have raised a PR. Can you please review it?

**Comment by Pawank06** [comment]
Hey, @manusa can you please assign me this issue?

**Comment by itsAfnanAlam** [comment]
Hi, is somebody working on this?
