### ISSUE TITLE
[Hacktoberfest] Dependency fields may be 'final'

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1806]
### Description
The following statements are reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/bc2a7c809087451bb49b1a62299c0bdedacbea8b/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/model/Dependency.java#L24-L33
 
- [x] should be changed to:
```java
    private final GroupArtifactVersion gav;

    // Dependency type ("jar", "war", ...)
    private final String type;

    // Scope of the dependency ("compile", "runtime", ...)
    private final String scope;

    // Location where the dependent jar is located
    private final File location;
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by sanmay321** [comment]
@manusa i would like to do this , assign me plaese

**Comment by sanmay321** [comment]
@manusa please check my PR #1810
