### ISSUE TITLE
[Hacktoberfest] DockerFileOption fields may be 'final'

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1808]
### Description
The following statement is reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/c15c4bb8b7cc4ea7502f8314b1e067b27f9a1dda/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/DockerFileOption.java#L26
 
- [x] should be changed to:
```java
    private final String key;
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by PriyanshuAhlawat** [comment]
I will like to work on it, pls assign

**Comment by PriyanshuAhlawat** [comment]
@manusa I was cloning repo but there seems to be an issue, pls help
![Screenshot (157)](https://user-images.githubusercontent.com/84102724/194916035-3d8da579-874c-4461-91e4-771f778744e7.png)

**Comment by rohanKanojia** [comment]
It seems like a windows specific issue for  not allowing too long file name. @baruKreddy  Have you faced this issue on Windows?

**Comment by manusa** [comment]
You need to modify some settings in your git config to allow long filenames. I'll check tomorrow the exact setting.

**Comment by baruKreddy** [comment]
@rohanKanojia I did face this issue, you should be able to proceed with git config --system core.longpaths true

**Comment by baruKreddy** [comment]
<img width="532" alt="image" src="https://user-images.githubusercontent.com/96629790/195001259-c9236e02-bd78-4774-8b86-3f74da5c71a9.png">
Try to follow this otherwise

**Comment by PriyanshuAhlawat** [comment]
@baruKreddy thanks for the help, issue solved🙂
