### ISSUE TITLE
[Hacktoberfest] IoUtil fields may be 'final'

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1815]
### Description
The following statement is reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/f7521fe52e886fa3a4abaee28b66809c828dc22d/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/IoUtil.java#L135
 
- [x] should be changed to:
```java
    private static final int PROGRESS_LENGTH = 50;
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by jhonDoe15** [comment]
Hi! can you assign me to this issue?

**Comment by manusa** [comment]
We use the code-style and minor smells to create this kind of issues for the community to solve and get acquainted with the project.

However, there are other more Sonar reported critical issues that can be tackled: https://sonarcloud.io/summary/overall?id=jkubeio_jkube

Also, adding valuable test coverage ---> behavioral tests, for the untested areas of the code-base is something that can be done ;)
