### ISSUE TITLE
[Hacktoberfest] JKubeBuildTarArchiver fields may be 'final'

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1816]
### Description
The following statements are reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/2dcaf6dd695ad18c767f8e8132c5e0f30cbccb44/jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/JKubeBuildTarArchiver.java#L31-L33
 
- [x] should be changed to:
```java
    private final Map<File, String> filesToIncludeNameMap = new HashMap<>();
    private final Map<File, String> fileModeMap = new HashMap<>();
    private final List<String> filesNamesToExclude = new ArrayList<>();
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Mohd-Farhan** [comment]
Can I do this. This will my second issue if i u assign me.

**Comment by GriffinAnnshual** [comment]
Hey can you assign it to me ?

**Comment by Mohd-Farhan** [comment]
@rohanKanojia why you didn't assign this to me?

**Comment by rohanKanojia** [comment]
@Mohd-Farhan : because this issue is tagged with `first-timers-only`. It's only targeted towards new contributors. If you want to contribute you can work on some other issue.

**Comment by Mohd-Farhan** [comment]
Ok

**Comment by GriffinAnnshual** [comment]
@rohanKanojia I have compeled the task. Kindly check my PR.

**Comment by rohanKanojia** [comment]
@GriffinAnnshual : Could you please link this issue in your PR description?

**Comment by GriffinAnnshual** [comment]
> @GriffinAnnshual : Could you please link this issue in your PR description?

Done
