### ISSUE TITLE
[Hacktoberfest] LogOutputSpecFactory fields may be 'final'

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1833]
### Description
The following statements are reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/053e63e095222c26994984f73a4a4603f5489ef7/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/LogOutputSpecFactory.java#L31-L33
 
- [x] should be changed to:
```java
    private final boolean useColor;
    private final boolean logStdout;
    private final String logDate;
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by sam2611** [comment]
Hi, Plz assign this issue to me.

**Comment by haseeb-xd** [comment]
Kindly, Review the PR

**Comment by manusa** [comment]
> Kindly, Review the PR

Your PR is not passing the **ECA** checks, please see the issue description especially the following point:

> **Before you start**

> Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

**Comment by git-zaidism** [comment]
Hi @manusa, can you please assign this issue to me?

**Comment by git-zaidism** [comment]
@rohanKanojia  I am getting this error while pushing the changes:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/68467966/209284304-1b1aaa9e-50ce-4ed6-97c7-828a520356ed.png">

**Comment by rohanKanojia** [comment]
You need to fork https://github.com/eclipse/jkube repository to your own account and push there. 

Please see my [blogpost](https://rohaan.medium.com/how-to-contribute-to-eclipse-jkube-f3bc7f902bf4) explaining contribution steps in detail

**Comment by git-zaidism** [comment]
@rohanKanojia Raised PR https://github.com/eclipse/jkube/pull/1975
