### ISSUE TITLE
[Hacktoberfest] RegistryAuthConfig fields may be 'final'

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1864]
### Description
The following statement is reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/6f3697a9e68e89082ab1a3c193114957eeb93f08/jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/auth/RegistryAuthConfig.java#L38
 
- [x] should be changed to:
```java
    private final String propertyPrefix;
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by PrathIam** [comment]
Hi @manusa , I am new here looking for my first contribution. Can I look into this?

**Comment by manusa** [comment]
Hi, I just assigned you 1863, you may only work on a single first-timers-only issue

**Comment by PrathIam** [comment]
@manusa Sure, Thanks!

**Comment by pwnb0y** [comment]
Hey, @manusa this is my first-time code contribution can I go through it?
