### ISSUE TITLE
[Hacktoberfest] ResourceValidator fields may be 'final'

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1866]
### Description
The following statements are reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/e4782b525d314ecb03d5d24932b60c3140e40aab/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/validator/ResourceValidator.java#L56-L58
 
- [x] should be changed to:
```java
    private final File[] resources;
    private ResourceClassifier target = ResourceClassifier.KUBERNETES;
    private final List<ValidationRule> ignoreValidationRules = new ArrayList<>();
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by javamultiplex** [comment]
@manusa  - I would like to work on this. Can you please assign this to me?

**Comment by manusa** [comment]
Hi @javamultiplex 
You already got 1865 assugbed, you may only work on a single first-timers-only issue

**Comment by NehaDadhich** [comment]
Hi @javamultiplex 
can I please work on this?

**Comment by NehaDadhich** [comment]
Hi @rohanKanojia I created a fork of this repository and made the changes but I am unable to push to my fork. Do I need any permissions?

**Comment by manusa** [comment]
> Hi @rohanKanojia I created a fork of this repository and made the changes but I am unable to push to my fork. Do I need any permissions?

No you don't need special permissions to push to your fork. Make sure you're git setup is OK and contains the valid SSH keys or access token.

**Comment by sam2611** [comment]
Hi @javamultiplex
May I please work on this?

**Comment by chambora1312** [comment]
can i work on this?

**Comment by manusa** [comment]
Hi @chambora1312 

> can i work on this?

I've assigned the issue to you since Neha hasn't worked on this.

**Comment by chambora1312** [comment]
Ok cool, thanks. Since I didn't work on a project in a long time and i forgot most of the steps, can you recommend a tutorial or something to get me started?

**Comment by Pawank06** [comment]
Hey, I had already resolved this problem in my local setup please assigned me this issue. so that I can make a pull request.

**Comment by rohanKanojia** [comment]
@Pawank06 : This issue is already assigned to someone else.
