### ISSUE TITLE
[Hacktoberfest] RunService fields may be 'final'

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#1867]
### Description
The following statements are reported as a code style issue:
 
https://github.com/eclipse/jkube/blob/880d1b3b3de91a0684dbb1d7dd1ebcd3b57af1fb/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/RunService.java#L70-L78
 
- [x] should be changed to:
```java
    private final KitLogger log;

    // Action to be used when doing a shutdown
    private final ContainerTracker tracker;

    // DAO for accessing the docker daemon
    private final DockerAccess docker;

    private final QueryService queryService;
```
 
### Before you start
 
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by javamultiplex** [comment]
@manusa - I would like to work on this. Can you please assign this to me?

**Comment by manusa** [comment]
Hi @javamultiplex 
You already got 1865 assugbed, you may only work on a single first-timers-only issue

**Comment by javamultiplex** [comment]
Sure thanks @manusa

**Comment by bhanutejabt** [comment]
Hi @manusa  ,
I can fix this issue. Can u pls assign this to me?
