### ISSUE TITLE
JKube should not pick the Dockerfile where the podman daemon is executed

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#1870]
### Describe the bug

In Dockerfile mode with podman, if podman daemon is executed in a directory that is not the project folder and that contains a Dockerfile, the build task/goal is picking the Dockerfile in the podman daemon directory and not the project one.

### Eclipse JKube version

SNAPSHOT

### Component

JKube Kit

### Apache Maven version

3.6.3

### Steps to reproduce

1. Create/Clone a project with a Dockerfile in the root directory of the project
2. Create another Dockerfile in your home directory
3. Start the podman daemon in your home directory, and keep it running
    ```
    cd /home/sunix && podman system service --time=0 unix:/run/user/$(id -u)/podman.sock
    ```
5. in another terminal, tell jkube to use podman by referencing the podman.sock file
    ```
    export DOCKER_HOST="unix:/run/user/$(id -u)/podman.sock"
    ```
6. go to the project folder and run the build task or goal
   ```
   mvn package k8s:build
   ```
   
I managed to figure out it wasn't picking the right Dockerfile in debug mode:
![Selection_724](https://user-images.githubusercontent.com/650571/196991429-62936b8d-1726-4efc-a266-80df6dd29bb0.png)

### Expected behavior

Dockermode should pick the Dockerfile located in the project.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Linux

**Comment by sunix** [comment]
probably related to https://github.com/containers/podman/issues/13293#issuecomment-1066319581

**Comment by manusa** [comment]
> probably related to [containers/podman#13293 (comment)](https://github.com/containers/podman/issues/13293#issuecomment-1066319581)

Yes, from your description and internal discussion, this seems more like a Podman related issue. Since we're sending the container build configuration and files through the Docker-compatible REST API.

**Comment by sunix** [comment]
TODO @sunix try with newer version of podman

**Comment by sunix** [comment]
I just upgraded podman to version 4.3.1 and I cannot reproduce anymore. Closing this issue.
