### ISSUE TITLE
katacoda course link in getting started section of README  not working

### ISSUE THREAD

**Issue by coding-cosmos** [eclipse/jkube#1879]
when we click on link of katacoda course in getting started here https://github.com/eclipse/jkube#getting-started  we see something like this:
![katacoda](https://user-images.githubusercontent.com/115341188/197333451-05021353-7d41-4fcd-8d4d-158ee1de62ad.png)

**Comment by sunix** [comment]
Thanks for reporting @coding-cosmos 

TODO: for now remove the link to katacoda

**Comment by manusa** [comment]
This link is still visible in other places

**Comment by coding-cosmos** [comment]
Sorry....what does that mean ?

**Comment by manusa** [comment]
It means that this link is yet visible in other parts of our code-base(s) and I'm keeping this issue open so that we can track their removal.

**Comment by coding-cosmos** [comment]
Yeah.. link is still  present in readme and on  website also
I will remove link from readme but what about website 
can I help in removing them from website also?

**Comment by rohanKanojia** [comment]
We removed katakoda from website in https://github.com/jkubeio/jkube-website/pull/57 . Is it okay to close this issue?

**Comment by manusa** [comment]
If we don't have traces of Katacoda elsewhere, please go ahead.

**Comment by rohanKanojia** [comment]
I have checked the website and GitHub repository. Katakoda is not present.
