### ISSUE TITLE
Create Apache Karaf Maven Quick start

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#188]
## Description

Create a Quick start that enables us to test/develop `KarafGenerator`.

The quick start should also include some documentation describing how to run, configure, etc. This will allow users to see what's the recommended approach when integration Eclipse JKube with Apache Karaf related projects.

**c.c.**: @anandrkskd

**Comment by rohanKanojia** [comment]
There is one karaf based sample using FMP: https://github.com/fabric8-quickstarts/karaf-camel-log

**Comment by manusa** [comment]
TIL: https://github.com/fabric8-quickstarts

**Comment by manusa** [comment]
https://github.com/eclipse/jkube/tree/master/quickstarts/maven/karaf-camel-log
