### ISSUE TITLE
boolean org.fusesource.jansi.AnsiConsole.isInstalled()

### ISSUE THREAD

**Issue by weihubeats** [eclipse/jkube#1915]
### Describe the bug

Execute the command mvn clean k8s:resource and get an error:
```java
boolean org.fusesource.jansi.AnsiConsole.isInstalled()
```

### Eclipse JKube version

1.10.0

### Component

Kubernetes Maven Plugin

### Apache Maven version

3.6.1

### Steps to reproduce

mvn clean k8s:resource

### Expected behavior

Run correctly

### Runtime

minikube

### Kubernetes API Server version

1.22.15

### Environment

macOS

**Comment by manusa** [comment]
Could you please provide the complete stacktrace for the error? (append -X to the mvn command)

**Comment by manusa** [comment]
Also, moving to a newer maven version (if possible) would help

**Comment by weihubeats** [comment]
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/42484192/202178976-8400bf01-ffef-4e5b-9cbb-72c63b24d591.png">

**Comment by manusa** [comment]
[Maven 3.6.3](https://github.com/apache/maven/blob/cecedd343002696d0abb50b32b541b8a6ba2883f/pom.xml#L294) uses org.fusesource.jansi:jansi:1.17.1

[Maven >=3.8.2](https://github.com/apache/maven/blob/ea98e05a04480131370aa0c110b8c54cf726c06f/pom.xml#L294) has bumped to uses org.fusesource.jansi:jansi:2.x

[AnsiConsole 1.17](https://github.com/fusesource/jansi/blob/jansi-project-1.17/jansi/src/main/java/org/fusesource/jansi/AnsiConsole.java) didn't have this method.

This commit: https://github.com/eclipse/jkube/commit/a55f8629e062cb16ec521753490f78d4b62c92f8
has very likely introduced the problem.

**Comment by manusa** [comment]
v1.10.1 with the fix was just released, could you please confirm that the latest 1.10.1 works OK?

- https://github.com/eclipse/jkube/releases/tag/v1.10.1
- https://repo1.maven.org/maven2/org/eclipse/jkube/kubernetes-maven-plugin/1.10.1/

**Comment by rohanKanojia** [comment]
@weihubeats : Could you please provide some feedback about the project?

**Comment by weihubeats** [comment]
I can use the old version to package the image and upload minikube successfully, but the pod status is not running, and the package docker image does not start properly, I don't know what the problem is, so I'm going to package the image manually

**Comment by rohanKanojia** [comment]
@weihubeats : Is this the project you're working on https://github.com/weihubeats/weihubeats_demos ?

Shall I try to clone it and test it on my minikube instance? Maybe it could be due to health checks not getting satisfied (just a guess)

**Comment by weihubeats** [comment]
I used [spring-boot-docker](https://github.com/weihubeats/weihubeats_demos/tree/master/spring-boot-demos/spring-boot-docker)
 to package the docker image locally and successfully accessed it on minikube, which is the same project as [spring-boot-kubernetes-maven-plugin](https://github.com/weihubeats/weihubeats_demos/tree/master/spring-boot-demos/spring-boot-kubernetes-maven-plugin) is basically the same

**Comment by rohanKanojia** [comment]
@weihubeats : You're right. I just cloned your repository and tested on minikube. You sample seems to be working okay on my machine:

```
spring-boot-kubernetes-maven-plugin : $ eval $(minikube -p minikube docker-env)
spring-boot-kubernetes-maven-plugin : $ mvn package  k8s:apply
spring-boot-kubernetes-maven-plugin : $ kubectl get svc
NAME          TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kubernetes    ClusterIP   10.96.0.1       <none>        443/TCP    41h
mysql         ClusterIP   10.110.171.39   <none>        3306/TCP   41h
zou-fabric8   ClusterIP   10.104.165.55   <none>        9004/TCP   7s
spring-boot-kubernetes-maven-plugin : $ minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ curl 10.104.165.55:9004/health
OK$ 
$ curl 10.104.165.55:9004/hello 
Hello, 2022-11-20 06:24:42$ 
```

**Comment by weihubeats** [comment]
But running the plug-in auto-deployment seems to be a failure, so it should be the plug-in problem

**Comment by rohanKanojia** [comment]
@weihubeats : Sorry, I don't understand what auto-deployment means? Could you please share steps you performed to deploy the application?

**Comment by weihubeats** [comment]
<img width="1388" alt="image" src="https://user-images.githubusercontent.com/42484192/202889955-1b3ddf4e-067e-45ef-9b41-9282f0ecb983.png">

<img width="792" alt="image" src="https://user-images.githubusercontent.com/42484192/202889677-c2dc6338-dfd6-4b39-b770-b84099caf187.png">
It seems that you have to configure the docker account password

**Comment by rohanKanojia** [comment]
@weihubeats : It looks like image is not present in minikube cluster. Did you run this command in the same bash session you were deploying the app ?:

```
$ eval $(minikube -p minikube docker-env)
```

**Comment by weihubeats** [comment]
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/42484192/202972926-70412c1f-dd09-497e-96f3-1efb791e1170.png">

**Comment by rohanKanojia** [comment]
@weihubeats : strange, it should work. Could you please try pushing image to some remote registry (Docker Hub/ Quay.io) and see if behavior changes?

**Comment by anurag-rajawat** [comment]
@weihubeats we have checked your demo project on all three OSs Windows, Mac and Linux and it is working fine on all of them.

`1. Windows`
![Screenshot 2022-11-21 143710](https://user-images.githubusercontent.com/94977678/203021359-ea44275a-d2d8-4011-b05f-c3a2651de537.png)

![Screenshot 2022-11-21 143830](https://user-images.githubusercontent.com/94977678/203021637-5dfa3b71-0ce3-461a-8169-591ef79a6b48.png)

![Screenshot 2022-11-21 144001](https://user-images.githubusercontent.com/94977678/203021770-ac4c7ac3-1d56-4017-a7c6-7980ed5932ba.png)
![Screenshot 2022-11-21 144127](https://user-images.githubusercontent.com/94977678/203021851-27ff6c91-9ee5-45ec-93ba-f0e1aed61638.png)

`2. Mac`

<img width="1328" alt="Screenshot 2022-11-21 at 3 18 50 PM" src="https://user-images.githubusercontent.com/94977678/203022423-1449d5f1-eaff-44c7-afc8-93529efd0315.png">

<img width="1328" alt="Screenshot 2022-11-21 at 3 18 59 PM" src="https://user-images.githubusercontent.com/94977678/203022584-5bae6a76-6a35-4d78-8758-bafdf81cd853.png">

<img width="1328" alt="Screenshot 2022-11-21 at 3 19 15 PM" src="https://user-images.githubusercontent.com/94977678/203022639-ccebfba0-33d1-40f0-bf07-a46455378054.png">

<img width="1328" alt="Screenshot 2022-11-21 at 3 20 03 PM" src="https://user-images.githubusercontent.com/94977678/203024564-d207a959-3003-4540-8588-99dc066234e9.png">

[3. Linux](https://github.com/eclipse/jkube/issues/1915#issuecomment-1321050891)

**Comment by weihubeats** [comment]
Okay, here's my system information.
<img width="253" alt="image" src="https://user-images.githubusercontent.com/42484192/203029476-141af428-637b-43a4-b42b-f1ae3911fefe.png">
- docker:
<img width="448" alt="image" src="https://user-images.githubusercontent.com/42484192/203029710-d38c4464-03af-489f-984a-d0d94d83d6a9.png">

- minikube
<img width="358" alt="image" src="https://user-images.githubusercontent.com/42484192/203029613-f4492e7b-6e3a-48a8-bb49-83af3e78e5f7.png">

**Comment by weihubeats** [comment]
> 

I'll try again sometime

**Comment by weihubeats** [comment]
> @weihubeats : strange, it should work. Could you please try pushing image to some remote registry (Docker Hub/ Quay.io) and see if behavior changes?

I'll try it sometime.
