### ISSUE TITLE
DebugServiceTest failing on Eclipse CI

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1940]
### Component

JKube Kit

### Description

Related to #1753 

I was testing my fix for #1753 on Jenkins CI, I noticed that DebugServiceTest seems to be failing:
```
[ERROR]   DebugServiceTest.debugWithApplicableEntities:212 
Argument(s) are different! Wanted:
silentLogger.info(
    startsWith("Now you can start a Remote debug session by using localhost"),
    <any integer>
);
-> at org.eclipse.jkube.kit.common.KitLogger$SilentLogger.info(KitLogger.java:144)
Actual invocations have different arguments:

[ERROR]   DebugServiceTest.debugWithApplicableEntitiesAndSuspend:234 
Argument(s) are different! Wanted:
silentLogger.info(
    startsWith("Now you can start a Remote debug session by using localhost"),
    <any integer>
);
-> at org.eclipse.jkube.kit.common.KitLogger$SilentLogger.info(KitLogger.java:144)
Actual invocations have different arguments:
```

You can see complete Jenkins job logs: https://ci.eclipse.org/jkube/job/daily-build/613/console . 

 Ever since https://github.com/eclipse/jkube/pull/1878 got merged our [daily jenkins build](https://ci.eclipse.org/jkube/job/daily-build/) has been constantly failing :

```
[ERROR] Failures: 
[ERROR]   DebugServiceTest.debugWithApplicableEntities:212 
[ERROR]   DebugServiceTest.debugWithApplicableEntitiesAndSuspend
```
I'm not able to reproduce this failure on my machine. This seems to only happen on CI.

Looking at these two tests, something looks weird here. DebugServiceTest runs KubernetesMockServer in CRUD mode:
https://github.com/eclipse/jkube/blob/997629eb072c4aa69134dcca93650e6f772c02fe/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/DebugServiceTest.java#L70

However, these two tests are adding their own expectations 
https://github.com/eclipse/jkube/blob/997629eb072c4aa69134dcca93650e6f772c02fe/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/DebugServiceTest.java#L199-L203

On CI, it looks like tests are getting stuck on portfoward (which is the API call that's getting mocked in expectations mode)

### Expected Behavior
DebugServiceTest should pass on all environments

### Acceptance Criteria
- [ ] DebugServiceTest should pass in all environments

**Comment by manusa** [comment]
It's likely that this is picking up a wrong KubernetesClient config that is available in the Jenkins-CI cluster (not sure why).

**Comment by rohanKanojia** [comment]
I've moved these two tests to a separate class where I use mockito. This seems to make jenkins ci pass

**Comment by manusa** [comment]
Yes, but that's reverting the test from a behavioral one to a one using mocks which was the point of the original refactor.
This is not OK. We need to figure out what's going on on the Jenkins-CI so that we can keep these tests that are much more reliable now that the MockServer CRUD mode is more stable and can be mixed with expectations.
I also refactored some tests for the watch service. The new remote-dev should also include some tests based on this philosophy.

So the point here would be to understand what's going on on Jenkins.

**Comment by rohanKanojia** [comment]
I think DebugServiceTest is failing due to localPort not being free that's requested for portforward.

In `jkube-kit/config/service` module, We're using portforward in two tests:
- [PortForwardServicePortOrderTest.java](https://github.com/eclipse/jkube/blob/master/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServicePortOrderTest.java#L47)
- [DebugServiceTest.java](https://github.com/eclipse/jkube/blob/master/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/DebugServiceTest.java#L203)

It looks like we don't close the localPortForward used in PortForwardServicePortOrderTest (which seems to keep ports `1337`, `8080`):

https://github.com/eclipse/jkube/blob/83bebcc7418f0fe2e44a619e4df6e5646d031b13/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServicePortOrderTest.java#L52

This seems to cause failures when later DebugServiceTest tries to port forward for same port (`1337`)

https://github.com/eclipse/jkube/blob/83bebcc7418f0fe2e44a619e4df6e5646d031b13/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/DebugServiceTest.java#L232
