### ISSUE TITLE
Add support for Gitpod

### ISSUE THREAD

**Issue by anurag-rajawat** [eclipse/jkube#1946]
### Is your enhancement related to a problem? Please describe

As a contributor, I want to work on projects from different environments. It would be nice to have a prebuilt dev environment such as [Gitpod](https://www.gitpod.io) to spin up the prebuilt dev environment.

This would allow contributors to contribute without worrying about their OS, project dependencies, installing tools, etc.

### Describe the solution you'd like

One solution to this is add a `.gitpod.yml` file to support [Gitpod](https://www.gitpod.io)

### Additional context
https://gitter.im/eclipse/jkube?at=62daeee522c53438bcc84411
https://gitter.im/eclipse/jkube?at=62de88f48fe56a38b5d8e46c

**Comment by manusa** [comment]
This sounds like a very useful addition for contributors, do you want to work on this?

**Comment by anurag-rajawat** [comment]
> This sounds like a very useful addition for contributors, do you want to work on this?

@manusa yes
