### ISSUE TITLE
Support for CronJob controller resources

### ISSUE THREAD

**Issue by vishalrijhwani** [eclipse/jkube#1954]
Hi like job in jkube, we can create directly job, such thing is not available for cron job. can you please create for cronjob like job. there should be jkube.enricher.jkube-controller.type for cronjob too

**Comment by rohanKanojia** [comment]
Just like [JobHandler](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/JobHandler.java), we need to implement CronJobHandler as well. How should the schedule be provided?

**Comment by manusa** [comment]
This is one of the improvements that should be completed to simplify the configuration of projects such as: https://github.com/ammbra/cat-adoption-batch

**Comment by anurag-rajawat** [comment]
@rohanKanojia I tried to add support for cronjob but was not able to provide schedule can you take a look?
https://github.com/anurag-rajawat/jkube/commit/b25b83a6629e307bdfff588d165150df2cee6af3

**Comment by rohanKanojia** [comment]
@anurag-rajawat : I can see you provided `schedule` in ResourceConfig. Is it not setting the schedule as expected? What error are you getting?

**Comment by anurag-rajawat** [comment]
I'm sorry for not being clear, I want to know how can we provide schedule in `pom.xml` file?

**Comment by anurag-rajawat** [comment]
When I run 
```shell
$ mvn k8s:resource -Djkube.enricher.jkube-controller.type=cronjob
```
or add configuration in pom file like
```xml
                <configuration>
                    <enricher>
                        <config>
                            <jkube-controller>
                                <type>CronJob</type>
                                <schedule>"* * * * *"</schedule>
                            </jkube-controller>
                        </config>
                    </enricher>
                </configuration>
```

I get 
```java
 Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.11-SNAPSHOT:resource (default-cli) on project random-generator: Execution default-cli of goal org.eclipse.jkube:kubernetes-maven-plugin:1.11-SNAPSHOT:resource failed: No schedule is specified!
```

So how to pass cronjob specs?

**Comment by rohanKanojia** [comment]
I think you have defined expectation for schedule to be like this:
```xml
<configuration>
   <resources>
      <schedule>"* * * * *"</schedule
   </resources>
</configuration>
```

**Comment by rohanKanojia** [comment]
In order to define it in enricher configuration, you need to add it here:

https://github.com/eclipse/jkube/blob/3204f60e4ddc2715516bde496a54908a3875416e/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultControllerEnricher.java#L80-L84

**Comment by anurag-rajawat** [comment]
Thank you! 
The only change is that we have to provide schedule without any quotes.

**Comment by anurag-rajawat** [comment]
Where should we define expectations for the `schedule`, `concurrencyPolicy`, and `failedJobsHistoryLimit` in resources or in enricher configuration, or in both?

And do we need to validate the corn schedule expression or leave it to Kubernetes?

**Comment by sunix** [comment]
Hi there,
I don't know if we already have one, but before going deeper into this, I would first setup a sample Java project that could be used as a `cronjob`. Does it make sense ?

**Comment by sunix** [comment]
> And do we need to validate the cron schedule expression or leave it to Kubernetes?

In my opinion, we should leave it to Kubernetes.

**Comment by manusa** [comment]
> Where should we define expectations for the schedule, concurrencyPolicy, and failedJobsHistoryLimit in resources or in enricher configuration, or in both?

For this first iteration we can define all of the configuration params in the Enricher configuration.

We can later on move some of them to the resource configuration if it makes sense. There are still some changes (I think yet to be merged) to refactor the resource configuration class in order to have a more structured and organized configuration.

**Comment by anurag-rajawat** [comment]
> For this first iteration we can define all of the configuration params in the Enricher configuration.


How to do that without defining those params in resource configuration class?

If we don't define those params in resource configuration then how can we add them in cronjob specs?

https://github.com/anurag-rajawat/jkube/blob/b25b83a6629e307bdfff588d165150df2cee6af3/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/CronJobHandler.java#L55-L59
