### ISSUE TITLE
Remove unused methods from KubernetesResourceUtil

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1974]
### Component

JKube Kit

### Description
While working on #1316, I noticed there are  many methods in [KubernetesResourceUtil](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java) that are not used anywhere. Maybe they were used in past but lost references during refactors.
- [KubernetesResourceUtil.removeLabel
](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L728)
- [KubernetesResourceUtil.containsLabelInMetadata](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L720)
- [KubernetesResourceUtil.isAppCatalogResource](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L691)
- [KubernetesResourceUtil.isNewerResource](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L496)
- [KubernetesResourceUtil.getDockerContainerID](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L475)
- [KubernetesResourceUtil.podHasContainerImage
](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L458)
- [KubernetesResourceUtil.getBuildStatusPhase
](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L427)
- [KubernetesResourceUtil.removeVersionSelector](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L391)

I think we should remove these unused methods.

### Expected Behavior
We shouldn't have that many unused methods in KubernetesResourceUtil

### Acceptance Criteria
- [ ] Clean up KubernetesResourceUtil to remove unused methods

**Comment by anurag-rajawat** [comment]
@rohanKanojia can I work on this?

**Comment by anurag-rajawat** [comment]
@rohanKanojia there is one more unused method

[KubernetesResourceUtil.getCreationTimestamp](https://github.com/eclipse/jkube/blob/8078bdc3f220ba8a9ccbf448e22f192b23a47a31/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L434)

do we need it or remove it?

**Comment by rohanKanojia** [comment]
You can remove this as well.
