### ISSUE TITLE
KubernetesResourceUtil : Rename variable to not match a restricted identifier

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1981]
### Component

JKube Kit

### Description

Java 10 introduced a `var` keyword[0] which infers types from context.

Although, our codebase is currently at JDK8. This can be problematic once we upgrade to JDK10+

https://github.com/eclipse/jkube/blob/8078bdc3f220ba8a9ccbf448e22f192b23a47a31/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L655

[0] https://docs.oracle.com/javase/10/language/toc.htm#JSLAN-GUID-7D5FDD65-ACE4-4B3C-80F4-CC01CBD211A4

### Expected Behavior
variable should be renamed to something that's not a reserved keyword.

### Acceptance Criteria
- [x] variable name is modified to not match any java keyword and is matching our coding conventions.

**Comment by chambora1312** [comment]
Can I try this? is there any naming convention I have to use?

**Comment by rohanKanojia** [comment]
@chambora1312 : We follow standard java camelCase naming

**Comment by omjikush09** [comment]
Hi, Can I work on this...

**Comment by rohanKanojia** [comment]
@omjikush09 : It's already assigned to someone else

**Comment by rohanKanojia** [comment]
@chambora1312 : Hi, are you still working on this issue?
