### ISSUE TITLE
Update change in `kubernetesClient.customResource` in spring-boot-crd Quickstart

### ISSUE THREAD

**Issue by Prathamkrishna** [eclipse/jkube#1985]
### Describe the bug

Running the spring-boot-crd project throws an error of Kubernetes not found.
mvn version: 3.8.6
minikube version: 1.37.1

### Eclipse JKube version

1.10.0

### Component

Kubernetes Maven Plugin

### Apache Maven version

other (please specify in additional context)

### Gradle version

None

### Steps to reproduce

run `mvn spring-boot:run` once you move into the project.

### Expected behavior

The project has to run.

### Runtime

Kubernetes (vanilla), minikube

### Kubernetes API Server version

other (please specify in additional context)

### Environment

macOS

### Eclipse JKube Logs

```shell
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project spring-boot-crd: Compilation failure
[ERROR] {path-to-project}/jkube/quickstarts/maven/spring-boot-crd/src/main/java/org/eclipse/jkube/quickstart/springboot/crd/FrameworkResource.java:[41,56] cannot find symbol
[ERROR]   symbol:   method customResource(io.fabric8.kubernetes.client.dsl.base.CustomResourceDefinitionContext)
[ERROR]   location: variable kubernetesClient of type io.fabric8.kubernetes.client.KubernetesClient
```

**Comment by rohanKanojia** [comment]
Gradle equivalent quickstart doesn't seem to be affected by this since it's explicitly importing kubernetes-client dependency:

https://github.com/eclipse/jkube/blob/8078bdc3f220ba8a9ccbf448e22f192b23a47a31/quickstarts/gradle/spring-boot-crd/build.gradle#L21

However, we should think about updating in there as well (maybe in a separate issue)
