### ISSUE TITLE
PortMapping : Rename variable to not match a restricted identifier

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#1994]
### Component

JKube Kit

### Description

Java 10 introduced a `var` keyword[0] which infers types from context.

Although, our codebase is currently at JDK8. This can be problematic once we upgrade to JDK10+

https://github.com/eclipse/jkube/blob/3204f60e4ddc2715516bde496a54908a3875416e/jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/model/PortMapping.java#L372

[0] https://docs.oracle.com/javase/10/language/toc.htm#JSLAN-GUID-7D5FDD65-ACE4-4B3C-80F4-CC01CBD211A4

### Expected Behavior
the variable should be renamed to something that's not a reserved keyword (`key`,`entryKey`) 

### Acceptance Criteria
- [x] variable name is modified to not match any java keyword and is matching our coding conventions.

**Comment by rohanKanojia** [comment]
@omjikush09 : Could you please check this? It's same as #1981 but in a different file

**Comment by omjikush09** [comment]
Ya got it, will work on it. Thanks for it.
