### ISSUE TITLE
Remove deprecated fields from _controller_resource_generation.adoc

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2057]
### Description

#1970 introduced a `src/main/asciidoc/inc/resource-generation/_controller_resource_generation.adoc` documentation page that contains a table with mostly deprecated fields.

For users transitioning from one version to the other this might be useful. However, it is extremely confusing and it might lead to opposite results, especially for newcomers.

This should be removed as soon as 1.11.0 is out and the documentation is regenerated.

**Comment by rohanKanojia** [comment]
Are you talking about this table? There are only two fields that are not deprecated in that table. 

![Screenshot from 2023-02-16 15-44-48](https://user-images.githubusercontent.com/13834498/219336479-680236ab-b20b-44e4-8761-5f9260a36d60.png)

**Comment by manusa** [comment]
yup
