### ISSUE TITLE
Credentials from maven settings.xml for Helm repositories

### ISSUE THREAD

**Issue by robinroos** [eclipse/jkube#2064]
### Component

OpenShift Maven Plugin

### Is your enhancement related to a problem? Please describe

Credentials for push to my organization's Helm repo are not available to the Developer community and may not exist in source code or build plan properties.

### Describe the solution you'd like

It should be possible to have credentials set in a normal `<server>` element within maven `settings.xml`.  That would be done by our Linux team on the build agents.

Developer teams would then configure the juke open shift-maven-plugin, providing an `<id>` in the declaration for the helm `<snapshotRepository>` and `<stableRepository>`.

In the absence of explicit credentials within that plugin configuration block, and in the absence of values for the properties `juke.helm.snapshotRepository.username/password` and `juke.helm.stableRepository.username/password`, the plugin would use the provided `<id>` to index into the `<server>` declarations in maven `settings.xml` and use credentials from there.

### Describe alternatives you've considered

We successfully push if we set properties as mentioned above, but that can only be done short-term because my personal developer account has push permissions.  Those permissions must be withdrawn so that only formal Bamboo builds may push anything, snapshot or release, to the repos.

We successfully push if we declare values for the above mentioned properties in maven `settings.xml`.  However those property values are inherently jkube-specific.  The Linux team is wary of starting down the slippery slope of adding plugin-specific items to production `settings.xml` files, and are quick to point out that those files "have not changed in years".

### Additional context

For this activity our maven goals are:

`mvn clean resources:resources oc:resource oc:helm oc:helm-push`

**Comment by robinroos** [comment]
All my careful XML tags were removed from the description.  Aaagghhh!

**Comment by robinroos** [comment]
I updated the description so the XML tags are now visible.

**Comment by rohanKanojia** [comment]
@robinroos : Looks like we already have got support for this. We are considering servers from settings while generating helm auth configuration:
https://github.com/eclipse/jkube/blob/33a72d2d99817924a3a67c5caf12df8d176c7f75/jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtil.java#L249

I provided helm repository configuration in pom like this:
```xml
            <plugin>
                <groupId>org.eclipse.jkube</groupId>
                <artifactId>kubernetes-maven-plugin</artifactId>
                <version>${jkube.version}</version>
                <configuration>
                    <helm>
                        <stableRepository>
                            <name>ChartMuseum</name>
                            <url>http://localhost:8080/api/charts</url>
                            <type>CHARTMUSEUM</type>
                        </stableRepository>
                    </helm>
                </configuration>
            </plugin>
```

My ChartMuseum credentials were present in `~/.m2/settings.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

  <servers>
    <server>
      <id>ChartMuseum</id>
      <username>admin</username>
      <password>secret</password>  
    </server>
  </servers>
</settings>
```

Upon running `mvn k8s:helm k8s:helm-push`, I was able to push chart to my local helm repo:

```sh
eclipse-jkube-demo-project : $ mvn k8s:helm k8s:helm-push
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< meetup:random-generator >-----------------------
[INFO] Building random-generator 0.0.1
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- kubernetes-maven-plugin:1.11.0:helm (default-cli) @ random-generator ---
[INFO] k8s: Creating Helm Chart "random-generator" for Kubernetes
[INFO] 
[INFO] --- kubernetes-maven-plugin:1.11.0:helm-push (default-cli) @ random-generator ---
[INFO] k8s: Creating Helm Chart "random-generator" for Kubernetes
[WARNING] artifact meetup:random-generator:tar.gz:helm:0.0.1 already attached, replace previous instance
[INFO] k8s: Uploading Helm Chart "random-generator" to ChartMuseum
[INFO] k8s: 201 - {"saved":true}
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.417 s
[INFO] Finished at: 2023-03-22T22:03:00+05:30
[INFO] ------------------------------------------------------------------------
```

**Comment by rohanKanojia** [comment]
@robinroos : Could you please check if you're able to push with the abovementioned configuration?

**Comment by rohanKanojia** [comment]
I think we can improve our documentation to mention that repository credentials can be provided from `~/.m2/settings.xml` as well.
