### ISSUE TITLE
Increase Unit test coverage for jkube-kit/common (achieve 45% code coverage)

### ISSUE THREAD

**Issue by anandrkskd** [eclipse/jkube#207]
# Description
Increase current unit test coverage for the following directory https://github.com/eclipse/jkube/tree/master/jkube-kit/common 

# Acceptance Criteria
- [ ] 45% Code coverage for the [specified module](https://sonarcloud.io/component_measures?id=jkubeio_jkube&metric=coverage&selected=jkubeio_jkube%3Ajkube-kit%2Fcommon%2Fsrc)
- [ ] It should cover complex scenario
- [ ] Scenario test should be passed, otherwise, issues will re-reported

/kind user-story

**Comment by manusa** [comment]
https://sonarcloud.io/component_measures?id=jkubeio_jkube&metric=coverage&selected=jkubeio_jkube%3Ajkube-kit%2Fcommon

**Comment by manusa** [comment]
outdated, no longer applicable. Also, current metric is at 56%.
