### ISSUE TITLE
Jib mode ignore registry settings for "from" image name section while building

### ISSUE THREAD

**Issue by Osmyslitelny** [eclipse/jkube#2077]
### Component

JKube Kit

### Is your enhancement related to a problem? Please describe

Exec command: 
> mvn k8s:build "-Djkube.build.strategy=jib"

or

> mvn k8s:build "-Djkube.build.strategy=jib" "-Djkube.docker.registry=myRegistry"

Settings:
```xml
<configuration>
   <registry>myRegistry</registry>
   <images>
      <image>
         <name>imageName</name>
         <registry>myRegistry</registry>
         <build>
            <from>baseImageFromMyRegistry:tag</from>
         </build>
          ...
      </image>
   </images>
</configuration>
```

Current Behave:
Try to pull baseImageFromMyRegistry from default docker registry.
Expected Behave:
Try to pull baseImageFromMyRegistry from myRegistry registry

### Describe the solution you'd like

Make the same behave of getting registry information as
> mvn k8s:build

Like: https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin/#registry for example.

### Describe alternatives you've considered

Set full image name to "from" section is workaround.

```xml
<configuration>
   <images>
      <image>
         <name>imageName</name>
         <build>
            <from>myRegistry/baseImageFromMyRegistry:tag</from>
         </build>
          ...
      </image>
   </images>
</configuration>
```

**Comment by rohanKanojia** [comment]
Thanks for reporting, looks like we're not considering this in jib build. Would it be possible for you to create a PR for this? Code for jib image build is here:

https://github.com/eclipse/jkube/blob/d1c6c7aad47823609f737f91a99319939abcea5c/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildService.java#L83

**Comment by manusa** [comment]
Neither the fix nor the suggestion seem to be appropriate. 
The `JibBuildService` already contains multiple logic to handle the pull registry (including auth).

**Comment by manusa** [comment]
Probably because this was evaluated before #2198

**Comment by rohanKanojia** [comment]
I tried this on v1.13.1 and was able to reproduce this issue. However I'm not able to reproduce the issue on master 1.14-SNAPSHOT

**Comment by manusa** [comment]
The mentioned PR targets 1.14.
I will add some tests to ensure we don't get a future regression in the user's PR.
