### ISSUE TITLE
Helm: Support for Chart.yaml fragments

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2092]
As a user I would like to provide a fragment for my JKube-generated `Chart.yaml` file. The contents of this fragment file should be merged with the final `Chart.yaml` after it has been generated, overriding any matching values.

Relates to:
- https://github.com/fabric8io/kubernetes-client/pull/4930
  Some of the types that were added in scope of this PR could be used for this purpose.

**Comment by rohanKanojia** [comment]
I couldn't find a direct mapping of Chart.yaml object in Kustomize model. 

However, I was able to find a struct in helm repository : [Metadata.go](https://github.com/helm/helm/blob/main/pkg/chart/metadata.go#L46)

**Comment by DominikBasnerSotec** [comment]
@manusa @rohanKanojia Is it possible to get more information on this? I havent found kustomize in the doc, how do I use it?

**Comment by manusa** [comment]
Hey Dominik,
The issue had some internal relation with Kustomize during its inception because some of the types are now exposed through the Fabric8 Kubernetes Client model. However, this is completely unrelated now.

This feature allows you to add a `chart.helm.yaml` file to the `src/main/jkube` directory. JKube will gather the fields declared in this file and merge them with the ones JKube generates to create a final `Chart.yaml` file. You can check the following integration test project for more details: https://github.com/eclipse/jkube/tree/ed628ab7274088a66143d9c040bd6c862a531dd4/gradle-plugin/it/src/it/helm-fragment/src/main/jkube

**Comment by DominikBasnerSotec** [comment]
Thx, will give it a try
