### ISSUE TITLE
Support for Spring Boot Native Image

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2138]
### Component

JKube Kit

### Description
SpringBoot 3 introduces the support for creating GraalVM native images. SpringBootGenerator should detect whether it's a native build and create a native assembly based on some minimal image.

SpringBootGenerator should detect the presence of `org.graalvm.buildtools:native-maven-plugin` plugin in project to detect whether it's a native build or not. See Spring Boot documentation[0] for more details.

[0] https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html

### Expected Behavior
Just like QuarkusGenerator, SpringBootGenerator should create a native container image using the generated native artifact.

### Acceptance Criteria
- [ ] SpringBootGenerator should detect whether it's a normal JDK build or native build
- [ ] SpringBootGenerator should build a container image including native executable

**Comment by anurag-rajawat** [comment]
Hi @rohanKanojia 
Can I try this one?

**Comment by rohanKanojia** [comment]
@anurag-rajawat : Umm, not sure. This issue requires refactoring SpringBootGenerator in order to support legacy jar, layered jar and native mode assembly types.

**Comment by ArnauAregall** [comment]
Congrats for this one! 👏  @rohanKanojia

**Comment by rohanKanojia** [comment]
@ArnauAregall : Thanks, Were you waiting for this one to get merged? 

Could you please try out whether the feature is working for your pipeline on `1.15-SNAPSHOT`? You would need to add this to your `pom.xml` in order to enable SNAPSHOTs:

```xml
  <pluginRepositories>
    <pluginRepository>
      <id>oss.sonatype.org</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>
```

**Comment by manusa** [comment]
That's sounds awesome. Thanks, Arnau!
