### ISSUE TITLE
Unstable build on MacOS: No pod is running yet. Are you sure you deployed your app using Eclipse JKube apply/deploy mechanism

### ISSUE THREAD

**Issue by geyuqiu** [eclipse/jkube#2145]
### Describe the bug

Kubernetes pods do not start properly on Mac, this does not occur on Windows system. At the beginning I thought that it was about special characters (e.g. ~) that appeared in *.yaml file: spec.hostPath.path. But these are all replaced now. And if I restart Mac or docker desktop, this error will still come up. Do you know why does it not run smoothly on MacOS ?

### Eclipse JKube version

1.12.0

### Component

Kubernetes Maven Plugin

### Apache Maven version

3.8.5

### Gradle version

None

### Steps to reproduce

not able to do this because of data security reasons

### Expected behavior

should work on MacOS as it does on windows

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.4

### Environment

macOS

### Eclipse JKube Logs

```shell
f1b5933fe4b5: Layer already exists
[INFO] k8s: 1.0.15-SNAPSHOT: digest: sha256:fa5be859f4fc9ceba1808840539a147eefefa96b34db8e4f18f4e0eb89fb45cf size: 3258
[INFO] k8s: Temporary image tag skipped. Target image 'localhost:5000/***-SNAPSHOT' already has registry set or no registry is available
[INFO]
[INFO] --- k8s:1.6.0:resource (default-cli) @ myifco-activemq-artemis ---
[INFO] k8s: Using resource templates from ***/src/main/jkube
[INFO] k8s: jkube-controller: Adding a default Deployment
[INFO] k8s: jkube-service-discovery: Using first mentioned service port '8161'
[INFO] k8s: jkube-revision-history: Adding revision history limit to 2
[INFO]
[INFO] --- k8s:1.6.0:apply (default-cli) @ myifco-activemq-artemis ---
[INFO] k8s: Using Kubernetes at https://127.0.0.1:6443/ in namespace null with manifest ***/target/classes/META-INF/jkube/kubernetes.yml
[INFO] k8s: Updating Service from kubernetes.yml
[INFO] k8s: Updated Service: ***/target/jkube/applyJson/default/service-***.json
[INFO] k8s: Creating a Deployment from kubernetes.yml namespace default name ***
[INFO] k8s: Created Deployment: ***/target/jkube/applyJson/default/***.json
[INFO] k8s: HINT: Use the command `kubectl get pods -w` to watch your pods start up
[INFO]
[INFO] --- k8s:1.6.0:log (default-cli) @ myifco-activemq-artemis ---
[INFO] k8s: Using Kubernetes at https://127.0.0.1:6443/ in namespace null with manifest ***/target/classes/META-INF/jkube/kubernetes.yml
[INFO] k8s: Watching pods with selector LabelSelector(matchExpressions=[], matchLabels={app=***, provider=jkube, group=com.ifco.container}, additionalProperties={}) waiting for a running pod...
[WARNING] k8s: No pod is running yet. Are you sure you deployed your app using Eclipse JKube apply/deploy mechanism?
[WARNING] k8s: Or did you undeploy it? If so try running the Eclipse JKube apply/deploy tasks again.
[INFO] k8s:  [NEW] *** status: Pending
[INFO] k8s:  [NEW] *** status: Pending
[INFO] k8s:  [NEW] myifco-activemq-artemis-6fb9998dcd-xpckb status: Running Ready
[INFO] k8s:  [NEW] Tailing log of pod: ***-6fb9998dcd-xpckb
```

### Additional context

- Docker desktop with Kubernetes enabled
- Java 8

**Comment by rohanKanojia** [comment]
@geyuqiu : What's the status of pods when you do `kubectl get pods` on your machine?

Is is possible to give example of the special characters you're talking about? Probably some example artifactId?

Your logs show you're using `1.6.0`, but you specified in form that you're using `1.12.0`..Which version is the one you're using?

**Comment by geyuqiu** [comment]
It was a problem that was only visible on [kubernetes dashboard](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/) during error hunting. On the getting started guide, I missed the point that the path with special characters like `~` should be avoided inside `.yaml` files on unix/linux systems.

**Comment by rohanKanojia** [comment]
@geyuqiu : So you mean basically it was a configuration issue?
