### ISSUE TITLE
[BLOG] - Create blog post

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#215]
We should create at least a Blog post every Sprint.

Placeholder issue to be discussed during Backlog Grooming session.

**Comment by manusa** [comment]
- Webapp functionality (Just tomcat)
- The JKube way vs. the Normal way (JKube simplifies the developer's workflow)

**Comment by kuldeep8979** [comment]
Hy , we want to build a blog .I m a beginner .. please support me I having many queries please sir keep support my email id is kuldeepazad8979@gmail.com

**Comment by rohanKanojia** [comment]
@kuldeep8979 : Not sure how we can help you. Our issue is about blogs for this project.

**Comment by manusa** [comment]
Outdated.
We might want to create new issues with specific blog posts we want to publish and address/plan those individually.
