### ISSUE TITLE
Fix javadoc warnings across codebase for non lombok generated code

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2210]
### Component

None

### Description
There are some warning generated by javadoc plugin while generating javadocs. Although most warnings are generated due to lombok generated code not containing complete javadocs for getters, setters and builder methods. There are still  a few places where warnings can be easily fixed.

The warnings with class names and line numbers and corresponding warnings are listed below:
| Location  | Warning  |
|---|---|
| [BuildReferenceDateUtil.java:44](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/BuildReferenceDateUtil.java#L44)  | `no @throws for java.io.IOException`  |
| [MapUtil.java:93](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/MapUtil.java#L93) | `no @param for source` |
| [MapUtil.java:117](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/MapUtil.java#L117) | `no @param for flattenedMap` |

**Comment by asingh2295** [comment]
Please assign this issue to me.

**Comment by rohanKanojia** [comment]
@asingh2295 : Thanks for showing interest. Make sure you read https://eclipse.dev/jkube/contributing/#legal

**Comment by asingh2295** [comment]
Thanks @rohanKanojia!!
This is my first open source contribution. Please let me know the changes in case of issue.
Please review PR. 
https://github.com/eclipse/jkube/pull/2256
