### ISSUE TITLE
Create E2E test to verify that OpenShiftBuilds (and other operations) can be logged

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2211]
## Description 

Create an [E2E test](https://github.com/jkubeio/jkube-integration-tests) to ensure that running our goals with `-Dorg.slf4j.simpleLogger.defaultLogLevel=trace` work as expected (+ log the HTTP conversation).

Relates to:
- #1950 
- #2000 
- https://github.com/fabric8io/kubernetes-client/issues/5251
- https://github.com/fabric8io/kubernetes-client/pull/5250

**Comment by manusa** [comment]
Blocked due to issues with CI environment

**Comment by rohanKanojia** [comment]
I think https://github.com/jkubeio/jkube-integration-tests/pull/353 fixed this issue
