### ISSUE TITLE
`k8s:resource` doesn't automatically pick up port from Quarkus `application.properties`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2239]
### Describe the bug

In a Quarkus project, when I specify port via application.properties:
```properties
quarkus.http.port=9000
```
`k8s:build` does pick up this port and exposes `9000` port in container image. However, `k8s:resource` doesn't seem to add `9000` port in generated Kubernetes liveness, readiness and startup probes.

If I add extra jkube-healthcheck-quarkus enricher configuration for port, it works:
```xml
      <plugin>
          <groupId>org.eclipse.jkube</groupId>
          <artifactId>kubernetes-maven-plugin</artifactId>
          <version>${jkube.version}</version>              
          <configuration>
            <enricher>
              <config>
                  <jkube-healthcheck-quarkus>
                      <port>9000</port>
                  </jkube-healthcheck-quarkus>
              </config>
            </enricher>  
          </configuration>
      </plugin>
```

### Eclipse JKube version

1.13.1

### Component

Kubernetes Maven Plugin

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

1. Enable health support in Quarkus project
2. Override default HTTP port via properties
3. Run `k8s:resource`, generated manifests contains probes containing `8080` port

### Expected behavior

Port should be automatically detected from properties while generating health checks

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3

### Environment

Linux

**Comment by asingh2295** [comment]
@rohanKanojia 
Please assign this issue to me.

**Comment by rohanKanojia** [comment]
@asingh2295 : Thanks for showing interest. 

You need to make changes in [QuarkusHealthCheckEnricher](https://github.com/eclipse/jkube/blob/master/jkube-kit/jkube-kit-quarkus/src/main/java/org/eclipse/jkube/quarkus/enricher/QuarkusHealthCheckEnricher.java)

I've done same changes for Helidon in #2235
