### ISSUE TITLE
feat(jkube-kit/generator): Provide guidance when the final project packaged file is not found in Quarkus projects

### ISSUE THREAD

**Issue by ShivangMishra** [eclipse/jkube#2257]
### Component

JKube Kit

### Is your enhancement related to a problem? Please describe

If the user forgets to run mvn package before mvn k8s:build, the project artifact is not generated. The generator cannot find the artifact (for example quarkus-app directory in quarkus quickstart), so the plugin fails to generate a build through k8s:build.  

![image](https://github.com/eclipse/jkube/assets/35092323/32dd9fcb-2d50-43e2-b28a-84c30dab0a82)

### Describe the solution you'd like

We should give a hint to the user that they may have forgotten to run mvn package.
Currently, the hint is given only in webapp quickstart. Now, we should do it for all generators.

![image](https://github.com/eclipse/jkube/assets/35092323/569f8bcc-2971-4539-bbad-3709a2a3bd73)

### Additional context

Completes the fix initially https://github.com/eclipse/jkube/pull/1408 that was done only for webapp generator and not Quarkus projects.

#### Scenario: Ensure users are guided to repackage their projects if the artifact is missing

**Given:**  
- The user has freshly cloned a Quarkus Maven project.
- The project includes the kubernetes-maven-plugin.

**When:**  
- The user executes the command `mvn oc:build oc:resource oc:apply` to deploy the application, encountering a missing package issue.

**Then:**  
- The plugin fails to generate a build.
- The log displays an instructive message: "HINT: try compiling and packaging your application before initiating the container image build task."

**Objective:**  
Ensure users receive a clear prompt to compile and package their applications before running the container image build task using the Kubernetes Maven Plugin within Quarkus projects.

**Comment by ShivangMishra** [comment]
@rohanKanojia @sunix I'll work on this issue once I'm done with my current issues. I'll try to fix it by making changes in the parent of all generators. But If you have any other suggestions for this issue, do let me know. Thanks.

**Comment by manusa** [comment]
How is this different from #2070 ?

**Comment by ShivangMishra** [comment]
@manusa  in #2070, 
1. user types mvn package oc:build oc:resource oc:apply to deploy the application.
2. user makes modifications.
3. user types mvn oc:build oc:resource oc:apply to deploy the app (missing package).
4. user does not see any changes in the deployed app.

In #2257,
1. user types mvn oc:build oc:resource oc:apply to deploy the app (missing package).
2. The plugin fails to generate a build.

In the first case, there are no errors because mvn package was run at least once and mvn clean was not run afterwards, so **old artifact will be there**. So, the plugin **won't give an error** while trying to generate the build.

Here, the plugin **gives an error** (because the user has not run mvn package even once, so there won't be any sourceFile / artifact to begin with).

**Comment by ShivangMishra** [comment]
PR #2244 fixes this.
