### ISSUE TITLE
JKube tasks not executed with Gradle 8.2.1

### ISSUE THREAD

**Issue by sunix** [eclipse/jkube#2299]
### Describe the bug

It looks like JKube tasks are broken with Gradle 8.2.1.
Nothing is executed, and it is showing BUILD SUCCESSFUL

### Eclipse JKube version

SNAPSHOT

### Component

Kubernetes Gradle Plugin

### Apache Maven version

None

### Gradle version

other (please specify in additional context)

### Steps to reproduce

1. Go to `quickstarts/gradle/webapp`
2. Use Gradle 8.2.1
    ```
    $ sdk use gradle 8.2.1
    Using gradle version 8.2.1 in this shell
    ```
3. Run k8sBuild tasks
    ```
    $ gradle build k8sBuild 
    > Task :k8sBuild
    k8s: Building container image in Kubernetes mode
    Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
    You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
    For more on this, please refer to https://docs.gradle.org/8.2.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
    BUILD SUCCESSFUL in 2s
    3 actionable tasks: 3 executed

    ```

### Expected behavior

The expected behaviour is what we have with 7.6.2:

1. Go to `quickstarts/gradle/webapp`
2. Use Gradle 7.6.2
    ```
    $ sdk use gradle 7.6.2
    Using gradle version 7.6.2 in this shell.
    ```
3. Run k8sBuild tasks
    ```
    $ gradle build k8sBuild 
    > Task :k8sBuild
    k8s: Running generator webapp
    k8s: webapp: Using quay.io/jkube/jkube-tomcat:0.0.19 as base image for webapp
    k8s: webapp: HINT: Tomcat webapps dir is set to `webapps-javaee` by default for retrocompatibility. If your project is already JakartaEE compliant, set `jkube.generator.webapp.env` to `TOMCAT_WEBAPPS_DIR=webapps` for a faster startup.
    k8s: Building container image in Kubernetes mode
    k8s: [kubernetes/webapp:latest] "webapp": Created docker-build.tar in 63 milliseconds
    locking FileBasedConfig[/home/sunix/.config/jgit/config] failed after 5 retries
    > Task :k8sBuild
    k8s: [kubernetes/webapp:latest] "webapp": Built image sha256:740ba
    k8s: [kubernetes/webapp:latest] "webapp": Tag with latest
    BUILD SUCCESSFUL in 6s
    3 actionable tasks: 3 executed
    ```

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3

### Environment

Linux

### Sample Reproducer Project

/quickstarts/gradle/webapp

**Comment by asingh2295** [comment]
@sunix Can you please asign this to me?

**Comment by rohanKanojia** [comment]
@asingh2295 : This might not be a good first issue. Are you sure you want to work on this?

**Comment by asingh2295** [comment]
Yes. I'm using gradle since past one year. let me give a try.

**Comment by manusa** [comment]
We need to make sure that this is a problem with API compatibility. Please make sure to see if the issue is reproducible with former versions of Gradle 8 and also with both plugins. We want to rule out that this is a problem with API compatibility since this requires some extra work to make the APIs/dependencies available for a Maven project

**Comment by rohanKanojia** [comment]
While bumping gradle distribution version used in integration tests, I tried bumping it to v8.2.1. I observed that not all integration tests seem to be failing. Only these test cases are failing:

- HelidonPropertiesIT
- ProbesGroovyDSLIT
- SmallRyeIT
- VertxIT
- SpringBootWithFragmentIT
- SpringBootIT
- HelidonIT
- ConfigMapIT
- SimpleIT
- ResourceValidationIT
- DependencyResourcesIT
- KubernetesExtensionIT
- OpenLibertyIT
Could this be something specific to the underlying framework?

**Comment by manusa** [comment]
> While bumping gradle distribution version used in integration tests, I tried bumping it to v8.2.1. I observed that not all integration tests seem to be failing. Only these test cases are failing:
> 
> * HelidonPropertiesIT
> * ProbesGroovyDSLIT
> * SmallRyeIT
> * VertxIT
> * SpringBootWithFragmentIT
> * SpringBootIT
> * HelidonIT
> * ConfigMapIT
> * SimpleIT
> * ResourceValidationIT
> * DependencyResourcesIT
> * KubernetesExtensionIT
> * OpenLibertyIT
> 
> Could this be something specific to the underlying framework?

These failures might have more to do with the plugins applied in the sample projects
