### ISSUE TITLE
Add support for configuring  nodeSelector spec for controller via xml/groovy DSL configuration

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2335]
### Discussed in https://github.com/eclipse/jkube/discussions/2334

<div type='discussions-op-text'>

<sup>Originally posted by **maodia** August 21, 2023</sup>
Hi, i get a small problem that i am going to deploy my image to some particular k8s node (use nodeSelector spec in the deployment yaml) but i do not know how to configure it in my xml configuration file.  I searched it in the docs and found nothing about this.

</div>

- `ControllerResourceConfig`

**Comment by Adityaturkhade** [comment]
I would like to pick this issue but I need  some help and elaboration

**Comment by rohanKanojia** [comment]
@Adityaturkhade You would need to add a new field `Map<String, String> nodeSelectors` in ControllerResourceConfig.

This field would be read in [PodTemplateHandler](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandler.java#L60) that would set `.withNodeSelector()` builder method in `createPodSpec` with value set in this field.

A similar field `schedule` was added to ControllerResourceConfig in this pull request https://github.com/eclipse/jkube/pull/2012

Apart from making these changes, you would need to:
- [ ] Add unit tests verifying your change is working
- [ ] Add documentation for this new field
- [ ] Add integration test verifying setting `nodeSelector` in Groovy DSL config is modifying resources . See similar pull request https://github.com/eclipse/jkube/pull/2121
