### ISSUE TITLE
Not able to run native executable bundled with default native container image

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2433]
### Describe the bug

At the moment, we're using `registry.access.redhat.com/ubi8/ubi-minimal:8.7` as default base image for native executable applications.

When I'm trying to do a native compilation and then build a container image out of it, I'm getting this error on running the image:
```
./jkube-spring-boot3-native-image-demo: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./jkube-spring-boot3-native-image-demo)
./jkube-spring-boot3-native-image-demo: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./jkube-spring-boot3-native-image-demo)
```

I've tried overriding base image to `registry.access.redhat.com/ubi8/ubi-minimal:8.8` but I get the same error.

If I change the base image either to `debian:stable-slim` or `fedora:latest`, I'm able to run the container image as expected. 

Not sure whether there is something wrong with my GraalVM installation or our default base native executable image is missing something.

I can reproduce the issue on GitHub actions as well. I've created [this](https://github.com/rohankanojia-forks/jkube-spring-boot3-native-image-demo) reproducer project. You can check the [failed GitHub action](https://github.com/rohankanojia-forks/jkube-spring-boot3-native-image-demo/actions/runs/6784034704/job/18439511776) that seems to reproduce the error I'm facing.

### Eclipse JKube version

SNAPSHOT

### Component

JKube Kit

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

1. Clone https://github.com/rohankanojia-forks/jkube-spring-boot3-native-image-demo
2. `gradle clean build`
3. Do native build and build container image `gradle nativeCompile k8sBuild`
4. Try to Run image with `docker run --rm demos/jkube-spring-boot3-native-image-demo:latest`

### Expected behavior

Our default base image should work with native artifacts.

### Runtime

Kubernetes (vanilla)

### Kubernetes API Server version

1.25.3

### Environment

Linux

### Eclipse JKube Logs

```shell
./jkube-spring-boot3-native-image-demo: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ./jkube-spring-boot3-native-image-demo)
./jkube-spring-boot3-native-image-demo: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by ./jkube-spring-boot3-native-image-demo)
```

### Sample Reproducer Project

https://github.com/rohankanojia-forks/jkube-spring-boot3-native-image-demo

**Comment by manusa** [comment]
My gut feeling is that the base image we're using to package the native binaries is not compatible with the latest glibc version you have in your system.

I think that if we switch from ubi8 to ubi9 we might be able to fix it.

**Comment by rohanKanojia** [comment]
> I think that if we switch from ubi8 to ubi9 we might be able to fix it.

You're right. Updating base image to `registry.access.redhat.com/ubi9/ubi:9.3-1361` seems to fix the issue.

I'm going to create PR to update this
