### ISSUE TITLE
Buildpacks CLI (pack) controller

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2453]
## Description

Part of #439 

As a JKube developer, I want to be able to control the Buildpacks CLI (pack) command-line tool from Java, so that I can invoke pack commands easily while making sure they execute correctly and that any error or problem gets properly reported.

## Acceptance criteria
- [ ] Command execution output is returned for each command
- [ ] Errors (non-zero exit codes for the CLI) get propagated as `Exceptions`.
  The exception contains stderr and stdout as the exception message for the user to analyze.
- [x] `version` method returns the pack version
- [ ] `build` method to invoke the build command with buildOptions
   - the builder image to use
   - project binaries
   - ...

**Comment by rohanKanojia** [comment]
>  Errors (non-zero exit codes for the CLI) get propagated as Exceptions.
The exception contains stderr and stdout as the exception message for the user to analyze.

To achieve this, we need to make some changes in [ExternalCommand](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/ExternalCommand.java) class to expose error stream manipulation logic (maybe similar to what we're doing while reading the command output.)
