### ISSUE TITLE
[TBD] BuildPackConfiguration fields should be exposed via properties

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2458]
### Component

JKube Kit

### Task description

Part of https://github.com/eclipse/jkube/issues/439

Related to https://github.com/eclipse/jkube/issues/2457

As a user, I should be able to provide buildpack configuration options via properties. It should be similar to how we've exposed [helm configuration](https://eclipse.dev/jkube/docs/kubernetes-maven-plugin/#jkube:helm) via properties. 

We can expose primitive fields of BuildPackConfiguration as properties.

### Expected Behavior
User can just override any buildpack specific option via property like this:

```
mvn k8s:build -Djkube.build.strategy=buildpacks -Djkube.buildpacks.builderImage=foo/builder:base
```

### Acceptance Criteria
- [ ] BuildPackConfiguration fields are exposed via properties (at least for primitive types)

**Comment by manusa** [comment]
Duplicate of #2457 

We should discuss both and tailor a more specific approach

**Comment by rohanKanojia** [comment]
As discussed in meeting we're not going to expose all options. It doesn't make sense to have a separate issue to expose configuration options via properties.
