### ISSUE TITLE
Spring-Boot LayeredJarGenerator no longer working with Spring Boot 3.2

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2477]
## Description

Eclipse JKube is not compatible with Spring Boot 3.2.

```
Error: Could not find or load main class org.springframework.boot.loader.JarLauncher
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.JarLauncher
```

Starting from Spring Boot 3.2 the JarLauncher class has moved to `org.springframework.boot.loader.launch.JarLauncher`

**Comment by edeandrea** [comment]
Description should be `Spring-Boot LayeredJarGenerator no longer working with Spring Boot 3.2` (not Spring Boot 3 - Spring Boot 3.0.x & 3.1.x are fine).

**Comment by manusa** [comment]
As a **temporary** workaround, users can disable layered jar generation in the [Spring Boot Maven Plugin](https://docs.spring.io/spring-boot/docs/current/maven-plugin/reference/htmlsingle/#packaging.layers) (I guess Gradle Plugin too):

```xml
<project>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <layers>
                        <enabled>false</enabled>
                    </layers>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```
