### ISSUE TITLE
Update Documentation on how to handle properties with slashes as names with a human readable example

### ISSUE THREAD

**Issue by DominikBasnerSotec** [eclipse/jkube#2505]
### Component

None

### Expected Behavior
Documentation contains information on how to handle properties with slashes as names with a human readable example like:
```
          <resources>
              <annotations>
                <service>
                  <property>
                    <name>cloud.google.com/neg</name>
                    <value>{"ingress":true}</value>
                  </property>
                </service>
              </annotations>
          </resources>
        </configuration>
```

### Acceptance Criteria
- [ ] Documentation is updated

**Comment by rohanKanojia** [comment]
@DominikBasnerSotec : Thanks for creating the issue. Would it be possible for you to provide a PR to improve our docs?

**Comment by DominikBasnerSotec** [comment]
> @DominikBasnerSotec : Thanks for creating the issue. Would it be possible for you to provide a PR to improve our docs?

https://github.com/eclipse/jkube/pull/2506
