### ISSUE TITLE
The class CommandLine shouldn't implement Cloneable

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2520]
### Description

The class [CommandLine](https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/CommandLine.java) implements the `Cloneable` interface despite being a simple utility class with a single static method.

The following line:

https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/CommandLine.java#L23

- [x] should be changed to:
```java
public class CommandLine {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by l3002** [comment]
Hi @manusa, I would be glad to make a contribution through this issue. Kindly assign it to me.

**Comment by rohan-2007** [comment]
please assign it to me
