### ISSUE TITLE
RegistryConfigTest uses deprecated ObjectMapper.configure method

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2529]
### Description

The class [RegistryConfigTest](https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/RegistryConfigTest.java) uses a deprecated method.

The following lines should be changed to (updating imports if necessary):

https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/RegistryConfigTest.java#L33-L34

- [x] should be changed to:
```java
    final ObjectMapper mapper = JsonMapper.builder().configure(MapperFeature.USE_ANNOTATIONS, false).build();
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Swaminathan11** [comment]
@manusa I have raised [a pull request](https://github.com/eclipse/jkube/pull/2535) for this. Let me know if you need anything else. Happy to contribute. Thanks!

**Comment by manusa** [comment]
Hi, @Swaminathan11, thanks for your contribution. As a side note for future contributors, before starting your work on an issue, it's better if you comment the issue stating that you are going to work on it. This way we can assign it to you and then there will be less chances of several folks submitting the same fix in multiple PRs.
