### ISSUE TITLE
SecretEnricher `getSecretsFromXmlConfig` should return `Collections.emptyList()` instead of `null`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2530]
### Component

JKube Kit

### Description
SecretEnricher has this private method which returns `null` that is reported by Sonar as a code smell:
https://github.com/eclipse/jkube/blob/275dc11e9bd0a268aac94f112ac2c443960d957b/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/SecretEnricher.java#L130-L135

We should refactor this method so that it always returns a list. We should return `Collections.emptyList()` instead of `null`. It would be nice to get rid of `if` block using Java'a `Optional.ofNullable`.

### Expected Behavior
`getSecretsFromXmlConfig` is refactored to return a non-null list always

### Acceptance Criteria
- [x] `getSecretsFromXmlConfig` is refactored to return a non `null` value
- [x] `getSecretsFromXmlConfig` uses `Optional.ofNullable` instead of `if` conditional to handle null case
- [x] Remove `null` check from the caller that receives list from `getSecretsFromXmlConfig` 

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by l3002** [comment]
Hi @rohanKanojia, I'm willing to pick this issue. Please assign this issue to me.

**Comment by rohanKanojia** [comment]
@l3002 : This is a slightly involved issue. It's not recommended for beginners. You can pick this once you get a PR merged with `first-timers-only` .

**Comment by l3002** [comment]
@rohanKanojia, Sure, I'm working on one right now.

**Comment by sankritimishra** [comment]
Could you please assign this to me?
