### ISSUE TITLE
Refactor ImageStreamService loop to remove use of `continue` and go to statements

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2531]
### Component

JKube Kit

### Description
This loop in ImageStreamService needs some minor refactoring. It uses multiple `continue` and even go-to statement. Perhaps it's a remnant of legacy code that was ported from Fabric8 Maven Plugin.

https://github.com/eclipse/jkube/blob/275dc11e9bd0a268aac94f112ac2c443960d957b/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/openshift/ImageStreamService.java#L178-L209

Refactor this loop not to use `continue` statements.

### Expected Behavior
Loop should not contain any `continue` statements

### Acceptance Criteria
- [x] Get rid of `continue` statements on line 190, 194, 198
- [x] Get rid of go to statement in nested loop on line 208
- [x] Move nested loop to a separate private method
- [x] ImageStreamServiceTest should pass even after refactoring code

**Comment by 724thomas** [comment]
hi, can i pick this up?

**Comment by Swaminathan11** [comment]
Is this still open? @724thomas are you still working on this or can I take it up? :)

**Comment by rohanKanojia** [comment]
@Swaminathan11 : There is already a PR to fix this issue #2547 

You can try picking up some other [good first issue that's not assigned to anyone](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+no%3Aassignee).

**Comment by 724thomas** [comment]
Hello @rohanKanojia,

I'm writing to follow up on PR #2547, which has been approved but not yet merged. Could you please let me know if there's anything more required from my side to proceed with the merge? Any additional information or steps I need to be aware of would be very helpful.

Thanks for your assistance!

Best regards, Thomas

**Comment by rohanKanojia** [comment]
@724thomas : We usually require 2 approvals in order to merge pull requests. I'll try to ping my colleague to review your pull request this week.

**Comment by 724thomas** [comment]
Hi @724thomas,

Thank you for the update. Have a great week!

**Comment by 724thomas** [comment]
> @724thomas : We usually require 2 approvals in order to merge pull requests. I'll try to ping my colleague to review your pull request this week.

Thank you for the update. Have a great week!
