### ISSUE TITLE
ImageName fails to process image with digest when digest algorithm other than `sha256`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2540]
### Describe the bug

ImageName is unable to process image when used with a digest when digest algorithm is not `sha256`.

This is happening because we're doing a hardcoded check for digest algorithm here:
https://github.com/eclipse/jkube/blob/b47fa4a9ab9a839bd4f8a093b4b0a4d8e9c88e9f/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java#L82

We should rather rely on a regexp like done by [Docker Distribution](https://github.com/distribution/reference) in[ reference.go](https://github.com/distribution/reference/blob/main/reference.go#L289)

Digest regexp pattern can be seen in [regexp.go](https://github.com/distribution/reference/blob/8507c7fcf0da9f570540c958ea7b972c30eeaeca/regexp.go#L81)
```golang
digestPat = `[A-Za-z][A-Za-z0-9]*(?:[-_+.][A-Za-z][A-Za-z0-9]*)*[:][[:xdigit:]]{32,}`
```

According to [OpenContainers Image Spec](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#registered-algorithms) it can be one of two values:
- [SHA-256](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#sha-256)
- [SHA-512](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#sha-512)

### Eclipse JKube version

SNAPSHOT

### Component

Kubernetes Maven Plugin

### Apache Maven version

None

### Gradle version

None

### Steps to reproduce

Try to invoke `new ImageName("xn--7o8h.com/myimage:xn--7o8h.com@sha512:ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff")` and you'll get exception

### Expected behavior

ImageName doesn't throw exception when digest algorithm is other than SHA256

**Comment by l3002** [comment]
@rohanKanojia, I believe this could be picked up by me. Please assign this to me if it is open for contributors.

**Comment by rohanKanojia** [comment]
@l3002 : I've already assigned you #2601 , do you want to work on multiple issues at once?

**Comment by l3002** [comment]
Hi @rohanKanojia, If a single contributor can work on multiple issues simultaneously then yeah I would like to work on this issue too.

**Comment by ShantKhatri** [comment]
Hi @rohanKanojia, if no one is working on this then Could you please assign this to me?

**Comment by ShantKhatri** [comment]
Hi @rohanKanojia In this specific bug are we expecting digest algorithm will be SHA256 or SHA512 or may be SHA1? Or it can be MD5 or anything else?

**Comment by rohanKanojia** [comment]
@ShantKhatri : According to [OpenContainers Image Specification](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#registered-algorithms) currently these algorithms are defined:
- [SHA-256](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#sha-256)
- [SHA-512](https://github.com/opencontainers/image-spec/blob/main/descriptor.md#sha-512)
