### ISSUE TITLE
TriggersAnnotationEnricher should not execute in `PlatformMode.kubernetes`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2559]
### Component

JKube Kit

### Description

According to [Red Hat OpenShift Triggering updates on ImageStream documentation](https://docs.openshift.com/container-platform/4.8/openshift_images/triggering-updates-on-imagestream-changes.html), annotation `image.openshift.io/triggers` is defined to be able to trigger updates in OpenShift Container Platform.

We have [TriggersAnnotationEnricher](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/TriggersAnnotationEnricher.java) responsible for adding this annotation. Currently, it seems to be executed in all cases. Since it's a Red Hat OpenShift Container Platform related annotation, it should be executed only when `PlatformMode.openshift` is specified.

We should add a check to return when `platformMode != PlatformMode.openshift`

https://github.com/eclipse/jkube/blob/c387c2be37561f4a07788de0ce3aa63ed2a8b4fc/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/TriggersAnnotationEnricher.java#L74

### Expected Behavior
TriggersAnnotationEnricher should not execute in `PlatformMode.kubernetes`

### Acceptance Criteria
- [x] Add a check for only executing the `enrich` method when `platformMode == PlatformMode.openshift`
- [x] Add a unit test to validate the abovementioned condition
- [x] Update integration tests which have references to `image.openshift.io/triggers` annotation in `kubernetes.yml`

**Comment by sankritimishra** [comment]
I'll pick it up, could you please assign this to me?

**Comment by manusa** [comment]
Hi @sankritimishra,
We assigned this issue to you 2 weeks ago, are you still working on this?
If you do, please provide a fix soon, if not, we'll need to assign this to someone else. It's a bug that needs to be fixed before next release.

**Comment by AmitPatil05** [comment]
Hello, 
I think I have a solution for this bug. Should I contribute and create a PR for this? I have analysed this bug. If yes, will you please assign me to this?

Thanks

**Comment by rohanKanojia** [comment]
@sankritimishra : Are you working on this issue? If not, shall I assign it to Amit?

**Comment by sankritimishra** [comment]
@rohanKanojia: ah okay, I could only partially figure it out, you shall assign it to Amit.

**Comment by AmitPatil05** [comment]
Let me know if it is ok for the comments in the new test methods are ok to stay or not. I will remove them accordingly.
