### ISSUE TITLE
Fix `jkube-kit/common` module's unit tests on Windows 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2563]
### Component

JKube Kit

### Description
Related to https://github.com/eclipse/jkube/issues/1338

:warning: A windows machine is required to reproduce and fix problems in this issue.

When running `mvn clean install` on Windows, I see the following tests failing in `jkube-kit/common` module:
- [ExternalCommandTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/ExternalCommandTest.java)
- [ArchiveDecompressorTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/ArchiveDecompressorTest.java)
- [IoUtilTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/IoUtilTest.java)
- [SerializationTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SerializationTest.java)

#### ExternalCommandTest
It tests a utility class of executing a command. We're trying to execute unix commands on Windows, which seems to cause tests to fail. We need to add `@DisabledOnOs(OS.WINDOWS)` annotation for tests executing unix commands.

#### ArchiveDecompressorTest
We seem to be passing unix file separator in expectations, this would never match a path on windows:
https://github.com/eclipse/jkube/blob/31ef8beec2b642be4a8516e425ecdad40ddfb7a8/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/archive/ArchiveDecompressorTest.java#L69
We can rely on [Apache's separatorsToSystem](https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/FilenameUtils.html#separatorsToSystem(java.lang.String)) utility method to convert it to windows file separator
```
.containsExactlyInAnyOrder(parentDir, separatorsToSystem(artifactParentDir,) separatorsToSystem(artifact)); 
```

#### IoUtilTest
This is similar to issue faced above, wrapping second argument in separatorsToSystem method should fix this issue:
https://github.com/eclipse/jkube/blob/31ef8beec2b642be4a8516e425ecdad40ddfb7a8/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/IoUtilTest.java#L143

#### SerializationTest
Here we're trying to compare file contents but we have hardcoded UNIX line separator character `\n` in string literal used in expectations:
https://github.com/eclipse/jkube/blob/31ef8beec2b642be4a8516e425ecdad40ddfb7a8/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/SerializationTest.java#L160-L164

We can rely on `String.format(` and replace `\n` by `%n` to make it work on windows:
```java
      .isEqualTo(String.format("{%n" +
        "  \"apiVersion\" : \"v1\",%n" +
        "  \"kind\" : \"ConfigMap\",%n" +
        "  \"metadata\" : {%n" +
        "    \"name\" : \"test\"%n" +
        "  },%n" +
        "  \"data\" : {%n" +
        "    \"key\" : \"value\"%n" +
        "  }%n" +
        "}"));
```

### Expected Behavior
All tests pass in `jkube-kit/common` module

### Acceptance Criteria
- [ ] `jkube-kit/common` module's build passes on windows

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by l3002** [comment]
Hi @rohanKanojia, Could you please assign this issue to me?

**Comment by rohanKanojia** [comment]
@l3002 : Do you work on a windows machine?

**Comment by l3002** [comment]
Yeah. I work on a windows machine but I make my commits through a linux virtual machine.

**Comment by l3002** [comment]
Hey @rohanKanojia, Upon investigating I've found that there are few other tests which are failing in the ExternalCommandTest and SerializationTest. Should I fix those too or a new issue will be raised for that?

**Comment by rohanKanojia** [comment]
@l3002 : Could you please see more information about these in https://github.com/eclipse/jkube/issues/2563#issue-2085885761 ?

**Comment by l3002** [comment]
@rohanKanojia: Currently I've fixed the issues mentioned above in your initial comment and also correct the other issues in the ```ExternalCommandTest``` and ```SerializationTest```. 

I am unable to understand what you wanted to convey in the last message but if you are asking for the details on the other issues then:

In ```ExternalCommandTest```:

```void execute_whenCommandCompletedSuccessfully_thenPrintResult()``` 

&

```void execute_whenWorkDirProvided_thenUseWorkDir(@TempDir File temporaryFolder)```

both of these methods were failing due as we were trying to run bash commands on windows.

In ```SerializationTest```:

```void saveJson_withConfigMap_savesFile(@TempDir Path targetDir)```

the above method was failing for the same reason as the other one due to the formatting of the string (LF was being used instead of CRLF for windows) in test.

I hope this clears the air around the matter.
