### ISSUE TITLE
KubernetesResourceUtil.ensureHasPort unnecessary 'null' check before 'equals()' call

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2580]
### Description

The method [KubernetesResourceUtil.ensureHasPort](https://github.com/eclipse/jkube/blob/56c80d92bf28e7dcd8f7b63235758e02dd9397d9/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L340) contains an unnecessary null-check.

The following line
https://github.com/eclipse/jkube/blob/56c80d92bf28e7dcd8f7b63235758e02dd9397d9/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L349

- [ ] should be changed to:
```java
            if (n1 != null && n1.equals(n2)) {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by ArunErram** [comment]
can i work on these please

**Comment by ArunErram** [comment]
can you provide a doc or any instruction of project setup and about Eclipse Contributor Agreement (https://accounts.eclipse.org/user/eca)

**Comment by manusa** [comment]
For this issue it's kind of simple.
1. Clone the repository
2. Make the required changes
3. Verify the project to ensure the tests keep passing (`mvn verify`)
