### ISSUE TITLE
Cleanup Unused properties inside Mojos 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#259]
These are some mojo `@Parameter` properties inside our mojo which are not directly used in mojo and are used across various places inside JKube Kit.

We had a discussion in https://github.com/eclipse/jkube/pull/244#discussion_r445347172 about this and we decided to revisit this and check all Mojos and remove all the properties which are not directly used in Mojos directly. An example of these kind of properties are these, which are now moved to [OpenShiftResourceMojo](https://github.com/eclipse/jkube/blob/master/openshift-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/OpenshiftResourceMojo.java):

https://github.com/eclipse/jkube/blob/48ccd83fc8ffd81e3d8716b4fa8b43177ae6755d/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java#L249-L260

**Comment by manusa** [comment]
Relates to #248
