### ISSUE TITLE
Remove `org.mockito` references from EnricherConfigTest

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2597]
### Component

JKube Kit

### Description
Related to https://github.com/eclipse/jkube/issues/2316

We have this simple test EnricherConfigTest that seems to be using mock for EnricherContext:
https://github.com/eclipse/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/EnricherConfigTest.java#L39

We are trying to make our tests more robust by replacing them with simple objects created using builders. We should refactor this test to not use mock.

This statement: 
https://github.com/eclipse/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/EnricherConfigTest.java#L39

could be rewritten like this using builders:
```java
    EnricherContext context = JKubeEnricherContext.builder()
        .project(JavaProject.builder()
            .groupId("org.eclipse.jkube")
            .artifactId("test-project")
            .version("0.0.1")
            .build())
        .processorConfig(new ProcessorConfig(null, null, configMap))
        .build();
```

Refactor this test to use builders instead of `mock` and `when` statements.

Also, this suppression doesn't seem to be applicable anymore, it's better to remove it :
https://github.com/eclipse/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/EnricherConfigTest.java#L36

### Expected Behavior
`mock` and `when` statements are replaced by builders setting actual objects inside builder methods.

### Acceptance Criteria
- [x] Use builder instead of mocking EnricherContext
- [x] Remove `@SuppressWarnings("ResultOfMethodCallIgnored")` annotation from test

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
- Create an [Eclipse Account](https://accounts.eclipse.org/)
- Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca)
- [Fork the project](https://github.com/eclipse/jkube/fork) on GitHub
- Clone the fork created on your GitHub account.
- Set up git username and email address:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"
```

**Comment by ShantKhatri** [comment]
Can I work on this? Could you please assign this to me.
