### ISSUE TITLE
Remove `org.mockito.Mockito.` references from PodTemplateHandlerTest 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2598]
### Component

JKube Kit

### Description
Related to #2316

PodTemplateHandlerTest seems to be using mock at these two places, it doesn't appear that mock is really needed in this test:
https://github.com/eclipse/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/handler/PodTemplateHandlerTest.java#L71-L72

Above line can easily be replaced by using actual object instead of mocks:
```java
probeHandler = new ProbeHandler();
project = JavaProject.builder().build();
```

### Expected Behavior
PodTemplateHandlerTest is refactor to not rely on any kind of mocks

### Acceptance Criteria
- [x] `probeHandler` and `project` are initialized with real values instead of mocks
- [x] `org.mockito.Mockito.*` imports are removed from the test

**Comment by ShantKhatri** [comment]
I want to work on this. Could you please assign this to me?
