### ISSUE TITLE
Remove `mock` statements from AssemblyManagerTest

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2599]
### Component

JKube Kit

### Description

Related to #2316

We seem to mocking just two variables here in `@BeforeEach` method of this test:
https://github.com/eclipse/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerTest.java#L56-L57

This can be refactored to use real objects using lombok builders: 
```java
    project = JavaProject.builder()
        .buildDirectory(targetDirectory)
        .build();
    configuration = JKubeConfiguration.builder()
        .project(project)
        .build()
```
To replace `when` statement for mocked object, we can edit the object created via builder to add the attribute we required for the test:
https://github.com/eclipse/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerTest.java#L72-L74
should be changed to 
```java
configuration = configuration.toBuilder().project(project.toBuilder().baseDirectory(buildDirs).build()).build();
```

### Expected Behavior
Usage of `org.mockito.Mockito.mock` is removed from AssemblyManagerTest

### Acceptance Criteria
- [ ] `mock` statements are replaced via real variables using builders
- [ ] AssemblyManagerTest should be passing even after refactoring the test

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:

Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.
- Create an [Eclipse Account](https://accounts.eclipse.org/)
- Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca)
- [Fork the project](https://github.com/eclipse/jkube/fork) on GitHub
- Clone the fork created on your GitHub account.
- Set up git username and email address:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"
```

**Comment by ShantKhatri** [comment]
I want to work on this, could you please assign this to me.
