### ISSUE TITLE
Fix `jkube-kit/build/api` module's unit tests on Windows 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2601]
### Component

JKube Kit

### Description
Related to https://github.com/eclipse/jkube/issues/1338

:warning: A windows machine is required to reproduce and fix problems in this issue.

When running `mvn clean install` on Windows, I see the following tests failing in `jkube-kit/build/api` module:

- [DockerFileUtilTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java)
- [AssemblyManagerCreateDockerTarArchiveTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerCreateDockerTarArchiveTest.java)
- [OpenShiftRegistryAuthHandlerTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/OpenShiftRegistryAuthHandlerTest.java)

### Expected Behavior
`mvn clean install` should pass with all tests on `jkube-kit/build/api`

### Acceptance Criteria
- [x] `jkube-kit/build/api` module's build passes on windows

**Comment by rohanKanojia** [comment]
DockerFileUtilTest should be easiest to fix. Here on this line we're splitting a file with hardcoded `\n` . This doesn't work as file separator on windows:
https://github.com/eclipse/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java#L122
It should be replaced to match `System.lineSeparator()`

**Comment by rohanKanojia** [comment]
OpenShiftRegistryAuthHandlerTest seems to be having some problems deleting the temporary directory created during test execution. It specifically seems to be caused by this line:
https://github.com/eclipse/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/auth/handler/OpenShiftRegistryAuthHandlerTest.java#L130

Replacing IOUtils.copy with Files.copy seemed to resolve the issue :
```java
Files.copy(new File(Objects.requireNonNull(getClass().getResource(testConfig)).getFile()).toPath(), config.toPath());
```

**Comment by rohanKanojia** [comment]
AssemblyManagerCreateDockerTarArchiveTest  should be a bit tricky to fix. I'm not 100% sure if my suggestion is the right way to fix this. 

First ArchiveAssertions needs to be fixed to accommodate windows style paths. Surround this with Apache's FilenameUtils.separatorsToSystem: 
https://github.com/eclipse/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/assertj/ArchiveAssertions.java#L129-L130
```java
      actualEntries.add(separatorsToSystem(entry.isDirectory() ?
          entry.getName().substring(0, entry.getName().length() - 1) : entry.getName()));
```

Then modify all the expectations using linux style path `/` with `File.separator`: 
https://github.com/eclipse/jkube/blob/7561af9a2b36892b6c93863584d62d732e76938a/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerCreateDockerTarArchiveTest.java#L105-L109

or surround them with FilenameUtils.separatorsToSystem
```java
    assertBuildDirectoryFileTree("modified-image").containsExactlyInAnyOrder(
        "Dockerfile",
            separatorsToSystem("jkube-generated-layer-final-artifact"),
            separatorsToSystem("jkube-generated-layer-final-artifact/maven"),
            separatorsToSystem("jkube-generated-layer-final-artifact/maven/test-0.1.0.jar"),
            "maven");
```

This needs to be done at various places in the test that have `/` in path expectations

**Comment by l3002** [comment]
Hi @rohanKanojia, I am available to work on this. If anyone else isn't already working on it then assign it to me.
