### ISSUE TITLE
ITGradleRunnerExtension.afterEach The declared Exception exception is never thrown

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2630]
### Description

The method [ITGradleRunnerExtension.afterEach](https://github.com/eclipse/jkube/blob/c60614f26ccb1a857521f06a8e8a836bedfbc32d/gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ITGradleRunnerExtension.java#L41) declares an Exception that is never thrown.

The following line
https://github.com/eclipse/jkube/blob/c60614f26ccb1a857521f06a8e8a836bedfbc32d/gradle-plugin/it/src/test/java/org/eclipse/jkube/gradle/plugin/tests/ITGradleRunnerExtension.java#L41

- [x] should be changed to:

```java
  public void afterEach(ExtensionContext context) {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Teja-11** [comment]
I would like to work on this, can you assign this to me please?
