### ISSUE TITLE
ServiceHandler : remove redundant method `getAnnotations()`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2637]
### Component

JKube Kit

### Description
ServiceHandler contains an unnecessary method that doesn't seem to be doing anything:

https://github.com/eclipse/jkube/blob/62080bfd0ce8c65245fef69723c95816d49661bb/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/handler/ServiceHandler.java#L85-L87

There are no field annotations in ServiceConfig, so it's impossible to extract any annotation-related information from ServiceConfig. We should delete this method and remove `.withAnnotations(` builder method that is calling this useless method.

### Expected Behavior
`getAnnotations()` is removed from ServiceHandler and also the builder method that's calling it is removed too.

### Acceptance Criteria
- [ ] `getAnnotations()` is removed from ServiceHandler 
- [ ] `.withAnnotations(` is initialized with an empty Map (ServiceBuilder on line 46)
- [ ] ServiceHandlerTest should pass after making these changes

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Harsh4902** [comment]
@rohanKanojia can you please assign this issue to me?

**Comment by jacobgale21** [comment]
@rohanKanojia could I be assigned this issue please?
