### ISSUE TITLE
WatchMojo : Remove child class fields shadowing parent class fields

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2638]
### Component

Kubernetes Maven Plugin

### Description

We have a mojo class WatchMojo in kubernetes-maven-plugin that extends AbstractDockerMojo
https://github.com/eclipse/jkube/blob/62080bfd0ce8c65245fef69723c95816d49661bb/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java#L67

It contains these two fields : 
https://github.com/eclipse/jkube/blob/62080bfd0ce8c65245fef69723c95816d49661bb/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojo.java#L75-L78

However, the parent class which it extends from also contains these fields, so WatchMojo should be already inheriting fields from the parent class
https://github.com/eclipse/jkube/blob/62080bfd0ce8c65245fef69723c95816d49661bb/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java#L346-L347

https://github.com/eclipse/jkube/blob/62080bfd0ce8c65245fef69723c95816d49661bb/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java#L291-L292

We need to remove child fields from child class that are same as parent class. Note that only `protected` access level fields are accessible to child class. Read [Sonar rule S2387](https://github.com/joansmith/sonar-java/blob/master/java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S2387.html) for more details

### Expected Behavior
Fields with colliding names are removed from WatchMojo

### Acceptance Criteria
- [ ] Fields with matching name in AbstractDockerMojo are removed from WatchMojo

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by arsenalzp** [comment]
Hello,
Any deadlines regarding this issue? I would like to tackle this issue, but first of all I need to figure out how everything works!

**Comment by rohanKanojia** [comment]
@arsenalzp : Don't worry about the deadline. Shall I assign it to you?

**Comment by arsenalzp** [comment]
> @arsenalzp : Don't worry about the deadline. Shall I assign it to you?

Yes, please! I take it.

**Comment by arsenalzp** [comment]
I guess fields were defined in child-class because parent-class has annotated fields, so those fields should be re-annotated in child-class due to nature of annotations - code annotations (except class annotations) aren't inherited.
Am I right?

**Comment by rohanKanojia** [comment]
I think it's a side effect of copy-paste. I had introduced these in https://github.com/eclipse/jkube/pull/1189 . At that time I didn't realize that these fields were already present in 

All protected fields in parent class should be available in child class as well. 

I checked after removing the field. I was still able to access it with `mvn k8s:watch -Djkube.namespace=foo`

I see we need to make changes in [WatchMojoTest](https://github.com/eclipse/jkube/blob/master/kubernetes-maven-plugin/plugin/src/test/java/org/eclipse/jkube/maven/plugin/mojo/develop/WatchMojoTest.java#L92) with this change.

Are you comfortable with refactoring that test or shall I take care of it?

**Comment by arsenalzp** [comment]
Hello, @rohanKanojia
Could you please share with me which JDK version do you use for this project?
I've just imported it in Eclipse IDE, and I see errors, for example:

`The method getDockerServiceHub() is undefined for the type JKubeServiceHub`

In fact, class JKubeServiceHub doesn't have method getDockerServiceHub().
That's strange...

**Comment by rohanKanojia** [comment]
@arsenalzp : JDK8 or JDK11 should work fine. I usually use IntelliJ and load the project as maven project.
