### ISSUE TITLE
Remove org.mockito.Mockito. references from AssemblyConfigurationUtilsTest

### ISSUE THREAD

**Issue by ShantKhatri** [eclipse/jkube#2657]
### Component

JKube Kit

### Description
Related to https://github.com/eclipse/jkube/issues/2316

AssemblyConfigurationUtilsTest seems to be using mock at some places, which can be refactor to use real objects.

### Expected Behavior
Usage of org.mockito.Mockito.mock is removed from AssemblyConfigurationUtilsTest

### Acceptance Criteria
- [ ] mock statements are replaced via real variables using builders
- [ ] AssemblyConfigurationUtilsTest should be passing even after refactoring the test

**Comment by ShantKhatri** [comment]
Hello @rohan and @manusa. I'm wondering if this mock should be refactored to use real objects. Would that be better?

**Comment by manusa** [comment]
> Hello @rohanKanojia and @manusa. I'm wondering if this mock should be refactored to use real objects. Would that be better?

:+1: Yes, it does seem that this test suite relies on no longer needed mocks.

**Comment by ShantKhatri** [comment]
> > Hello @rohanKanojia and @manusa. I'm wondering if this mock should be refactored to use real objects. Would that be better?
> 
> 👍 Yes, it does seem that this test suite relies on no longer needed mocks.

I might be wrong with my approach, but I've made the changes like this:
![image](https://github.com/eclipse/jkube/assets/96608160/26c297a0-9026-4e34-9286-e641cf8b33f2)
![image](https://github.com/eclipse/jkube/assets/96608160/3cf3f157-d722-431f-a6e5-368202a87bea)

**Comment by manusa** [comment]
Seems to be OK, are you working on this? shall we assign it to you?

**Comment by ShantKhatri** [comment]
Yes, Please !
