### ISSUE TITLE
KubernetesHelperTest.setUp The declared Exception exception is never thrown

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2671]
### Description

The method [KubernetesHelperTest.setUp](https://github.com/eclipse/jkube/blob/911fd4f2f5b9094163c4a3722669030aa770c80b/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java#L85) declares an Exception that is never thrown.

The following line
https://github.com/eclipse/jkube/blob/911fd4f2f5b9094163c4a3722669030aa770c80b/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/KubernetesHelperTest.java#L85

- [x] should be changed to:

```java
    public void setUp() {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by LaythonChilders** [comment]
Hi could you please assign this to me as a first issue? Thanks

**Comment by LaythonChilders** [comment]
Pull created: #2727
