### ISSUE TITLE
KubernetesLogTaskTest.setUp The declared Exception exception is never thrown

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2672]
### Description

The method [KubernetesLogTaskTest.setUp](https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesLogTaskTest.java#L43) declares an Exception that is never thrown.

The following line
https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesLogTaskTest.java#L43

- [x] should be changed to:

```java
  void setUp() {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by AjaySDwivedi1** [comment]
I made my PR. Not sure if I did it right so let me know if I need to do it again!

**Comment by rohanKanojia** [comment]
@AjaySDwivedi1 : Where have you created it? Please check this [blogpost](https://rohaan.medium.com/how-to-contribute-to-eclipse-jkube-f3bc7f902bf4) to see if you've followed same steps for contribution.

**Comment by AjaySDwivedi1** [comment]
I created created a fork, then made the changes, created a branch, and pushed to that.

**Comment by rohanKanojia** [comment]
@AjaySDwivedi1 : You need to create a pull request to merge branch that you've pushed to your fork to eclipse/jkube's master branch

**Comment by AjaySDwivedi1** [comment]
Got it! Made the PR
