### ISSUE TITLE
AssemblyManagerCreateDockerTarArchiveTest : Replace `Mockito.mock` by creating actual object

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2675]
### Component

JKube Kit

### Description
Related to https://github.com/eclipse/jkube/issues/2316

AssemblyManagerCreateDockerTarArchiveTest seems to be using mock here : 
https://github.com/eclipse/jkube/blob/cc2c8a20c541c78c26f752058dc5bf334f74ff2b/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManagerCreateDockerTarArchiveTest.java#L61

This doesn't seem to have any value, as we are not doing any behavioral mocking for the object (i.e `when`). This object is just used for logging, so maybe we can just use real object here.

Replace it with real object created via `new PrefixedLogger` constructor, you can pass any test value as prefix for first argument and `new KitLogger.SilentLogger()`  for the second argument
### Expected Behavior
Usage of `Mockito.mock` is removed from AssemblyManagerCreateDockerTarArchiveTest

### Acceptance Criteria
- [x] mock statements are replaced via real variables 
#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by erhanxyz** [comment]
hi, I'm interested in working on this one. can you assign it to me?

**Comment by rohanKanojia** [comment]
@erhanxyz : Have you contributed to the project before? 

If you'd doing it for the first time, maybe you should start with [first-timers-only](https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Afirst-timers-only) tagged issues

**Comment by erhanxyz** [comment]
oops sorry, didn't know about `first-timers-only` tag. I'll have a look at those. thanks!

**Comment by AmitPatil05** [comment]
Hello, I can work on this issue. Can you please assign this to me?
