### ISSUE TITLE
UnixSocketTest : Use try with resources while creating object

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2676]
### Component

JKube Kit

### Description
This UnixSocket class seems to be extending [Closeable](https://docs.oracle.com/javase/8/docs/api/java/io/Closeable.html) interface. 

This means we can use [try-with-resources](https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html) while creating the object.

This block of code in UnixSocketTest should be refactored to use try-with-resources: 
https://github.com/eclipse/jkube/blob/cc2c8a20c541c78c26f752058dc5bf334f74ff2b/jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/hc/unix/UnixSocketTest.java#L72-L78

It should look like this:
```java
        try (UnixSocket unixSocket = new UnixSocket()) {
            // GIVEN
            doThrow(new SocketException()).when(socket).getKeepAlive();
            doThrow(new SocketException()).when(socket).getSoTimeout();

            // WHEN & THEN
            assertThatThrownBy(unixSocket::getKeepAlive).isInstanceOf(SocketException.class);
            assertThatThrownBy(unixSocket::getSoTimeout).isInstanceOf(SocketException.class);
        }
```

We should do the same for other tests in this class as well.

### Expected Behavior
All tests are updated to use try with resources

### Acceptance Criteria
- [x] All tests in UnixSocketTest are updated to use try with resources

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by AmitPatil05** [comment]
Hello @rohanKanojia , can you please assign this issue to me?
