### ISSUE TITLE
KubernetesClientUtil : Replace `switch` with `if` statement to improve readibility

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2677]
### Component

JKube Kit

### Description
KubernetesClientUtil seems to have this simple switch clause : 

https://github.com/eclipse/jkube/blob/cc2c8a20c541c78c26f752058dc5bf334f74ff2b/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/KubernetesClientUtil.java#L122-L128

As per Sonar rule [S1301](https://github.com/joansmith/sonar-java/blob/master/java-checks/src/main/resources/org/sonar/l10n/java/rules/squid/S1301.html)

> Switch statements are useful when there are many different cases depending on the value of the same expression.
For just one or two cases, however, the code will be more readable with if statements.

There are no unit tests for this method, it would be nice to have two unit tests verifying both conditions.

### Expected Behavior
The above code should be refactored to use if else statements.

### Acceptance Criteria
- [x] Switch statements are replaced by if else statements
- [ ] Unit tests added to verify method is working as expected

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Yogeshknaik** [comment]
im interested to work on it , can you assign this to me.!?
