### ISSUE TITLE
Remove org.mockito.Mockito. references from JKubeProjectUtilTest

### ISSUE THREAD

**Issue by ShantKhatri** [eclipse/jkube#2685]
### Component

JKube Kit

### Description
Related to https://github.com/eclipse/jkube/issues/2316

JKubeProjectUtilTest seems to be using mock at some places, which can be refactor to use real objects.

### Expected Behavior
Usage of org.mockito.Mockito.mock is removed from JKubeProjectUtilTest

### Acceptance Criteria
- [x]  mock statements are replaced via real variables using builders
- [x]  JKubeProjectUtilTest should be passing even after refactoring the test

**Comment by ShantKhatri** [comment]
Hello @rohanKanojia @manusa , I'm wondering if this mock should be refactored to use real objects. Would that be better?

**Comment by ShantKhatri** [comment]
I have made some changes with the approach as:
![image](https://github.com/eclipse/jkube/assets/96608160/bedaceec-a083-470f-b3ac-97b0e37f9068)
![image](https://github.com/eclipse/jkube/assets/96608160/f6e2b0f3-1dab-4d5a-af99-d8279928bca1)
![image](https://github.com/eclipse/jkube/assets/96608160/0796be34-9a57-4fc0-8dca-d119b5685747)
![image](https://github.com/eclipse/jkube/assets/96608160/4fc4fe7a-baa9-48b2-9b6a-954c99ae9a6b)

**Comment by rohanKanojia** [comment]
@ShantKhatri : Overall your changes look good to me (apart from try catch block in setup). Please go ahead and create pull request. I'll add the comment on the pull request if I notice somethis else.
