### ISSUE TITLE
Fix Unit Tests failing for windows in `jkube-kit/helm` module

### ISSUE THREAD

**Issue by l3002** [eclipse/jkube#2696]
### Component

JKube Kit

### Description
Related to #1338

⚠️ A windows machine is required to reproduce and fix problems in this issue

When executing `mvn clean install` on Windows, The following unit test is failing in `jkube-kit/helm` module:

- [HelmServiceUtilTest](https://github.com/eclipse/jkube/blob/master/jkube-kit/helm/src/test/java/org/eclipse/jkube/kit/resource/helm/HelmServiceUtilTest.java)

![image](https://github.com/eclipse/jkube/assets/111552820/640eb502-87e3-4986-8ccd-edf8214d2329)

Issue is occurring due to the Linux file separator being used in place of Windows file separator while testing `initHelmConfig()`. See Below:

![image](https://github.com/eclipse/jkube/assets/111552820/124dfecb-a361-4580-8646-215c6a0aba1e)

TODO: Find the exact cause of this issue and fix it.

### Expected Behavior

All the unit test should pass in `jkube-kit/helm` module during execution of `mvn clean install`

### Acceptance Criteria
- [ ] All unit tests should pass in `jkube-kit/helm` module

**Comment by l3002** [comment]
@rohanKanojia, Kindly assign this issue to me.

**Comment by l3002** [comment]
Hi @rohanKanojia / @manusa : While working on this issue, I realized that in addition to the above mentioned problem with file separator, one more test was failing in `HelmServiceUploadIT`. 

Test Failure at : `HelmServiceUploadIT$OCI.withSuccessfulUpload_shouldUploadBlobsAndUpdateManifest()`

The test was returning a `BadUploadException : 404` while uploading the `chart` to the mock server. Upon investigation I found that it was occurring due to the change in message digest for `Chart.yaml`.

![image](https://github.com/eclipse/jkube/assets/111552820/17d2c168-5f89-4af0-9144-7c897eeeb1cd)

![image](https://github.com/eclipse/jkube/assets/111552820/89d4a6dd-8043-41cd-a828-052202bb895a)

I suspect when we invoke `Serialization.asJson(chart)` after creating the `Chart` Object, it actually uses the platform dependent line separator (CRLF) for creating json with the data in `Chart.yaml` due to which when we create the byteArray it actually encodes the data accordingly and therefore the change in digest.

![image](https://github.com/eclipse/jkube/assets/111552820/1eefc3c7-4de7-4a2d-9045-be60ada9e4c7)

There can be two fixes to this issue. Either we can configure this test `HelmServiceUploadIT$OCI.withSuccessfulUpload_shouldUploadBlobsAndUpdateManifest()` by adding new mockServer.expect() statement and adding a new if statement before `assertThat()` statement to check if the OS is windows or Linux/Mac as due to the change in content of chart (LF -> CRLF) the digest and the size is altered. See below:

![image](https://github.com/eclipse/jkube/assets/111552820/f5745359-3a18-4bb3-b2f6-a9d6d0054759)
![image](https://github.com/eclipse/jkube/assets/111552820/ceed146e-a5f4-48c3-a225-cf3834c880ac)


Or We can write a separate test for windows, where we will first configure mock server to expect the request with the message digest created for the windows `chart` and then add the `assertThat()` statement to test it. In this case, we will have to add `@DisabledOnOs(OS.WINDOWS)` and `@DisabledOnOs(OS.LINUX)`

I believe that the latter would be the best approach as when I tried to configure the test `HelmServiceUploadIT$OCI.withSuccessfulUpload_shouldUploadBlobsAndUpdateManifest()` to covering windows test, it seems messy and unreadable. Also, I'm not sure how to write a `assertThat()` statement for a specific platform. Just wanted to know what your thoughts are on the same.

**Comment by rohanKanojia** [comment]
> In this case, we will have to add @DisabledOnOs(OS.WINDOWS) and @DisabledOnOs(OS.LINUX)

@l3002 : I agree with you. Adding conditionals for platform specific checks might make test less readble. It's better to write it as a separate test.

**Comment by l3002** [comment]
@rohanKanojia : Got it. So, Shall I start working on the PR or wait for @manusa's thought on this matter?

**Comment by rohanKanojia** [comment]
@l3002 : Although I think Marc's opinion would also be same as yours. But it's okay to wait for a few hours until he comes back.

**Comment by manusa** [comment]
Please create a specific test for windows annotated with `@EnabledOn...` and disable the original test in windows with `@DisabledOn...`
