### ISSUE TITLE
BaseGenerator : Use Lombok `@Getter` annotation instead of getter methods

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2712]
### Component

JKube Kit

### Description

BaseGenerator has these getter methods 

https://github.com/eclipse/jkube/blob/fddd604457c98a197bd8b2f3cbb3167dde2a9b3d/jkube-kit/generator/api/src/main/java/org/eclipse/jkube/generator/api/support/BaseGenerator.java#L106-L112

Since we're already using [Lombok library](https://projectlombok.org/features/GetterSetter) to automatically generate Getters and Setters. We can replace these two methods by adding `@Getter` annotation on top of field declaration like this:
```java
    @Getter
    private final String name;
```

### Expected Behavior
The abovementioned Getter methods are removed from BaseGenerator and replaced with `lombok.Getter` annotation

### Acceptance Criteria
- [x] `lombok.Getter` annotation is added in place of getter methods
- [x] Project should compile cleanly after running `mvn clean install`

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by abhiramkarri** [comment]
Can you assign it to me?

**Comment by rohanKanojia** [comment]
@abhiramkarri : This issue is designed for contributors who have already contributed their first patch to the project.Please pick some issue with [`first-timers-only`](https://github.com/eclipse/jkube/issues?q=is%3Aopen+label%3Afirst-timers-only+sort%3Aupdated-desc) label

**Comment by ajayl83** [comment]
@rohanKanojia can i pick this?

**Comment by l3002** [comment]
@rohanKanojia, do you mind if I take this up?

**Comment by rohanKanojia** [comment]
@ajayl83 @l3002 : I'm sorry I missed this notification. 

@l3002 : Is it okay if I assign it to @ajayl83 as he requested this first?

**Comment by l3002** [comment]
sure, not a problem.
