### ISSUE TITLE
RegistryServiceTest : Replace `assertThrows` with AssertJ's

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2713]
### Component

None

### Description
We have this test in RegistryServiceTest that's getting exception returned from JUnit5's `assertThrows` and then verifying the exception message using Assertj: 

https://github.com/eclipse/jkube/blob/fddd604457c98a197bd8b2f3cbb3167dde2a9b3d/jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/RegistryServiceTest.java#L65-L72

There is nothing wrong with the test, but we're using two different assertions to verify the behavior.

AssertJ provides [assertThatIOException()](https://www.javadoc.io/doc/org.assertj/assertj-core/3.8.0/org/assertj/core/api/Assertions.html#assertThatIOException--) method to specifically handle IOException validations:

Above code can be refactored like this to be more readable:
```java
    assertThatIOException()
        .isThrownBy(() -> registryService.pullImageWithPolicy("image",
        ImagePullManager.createImagePullManager("Never", "", new Properties()), null, null))
        .withMessageStartingWith("No image 'image' found and pull policy 'Never' is set");
```

### Expected Behavior
`assertThrows` is replaced by `assertThatIOException`

### Acceptance Criteria
- [x] `assertThrows` is replaced by `assertThatIOException`
- [x] RegistryServiceTest should pass after making this change

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by ajayl83** [comment]
@rohanKanojia is anyone working on this? can i pick it up?

**Comment by rohanKanojia** [comment]
@ajayl83 : Not at the moment, Are you contributing for the first time? If yes, Please pick some issue with [`first-timers-only`](https://github.com/eclipse/jkube/issues?q=is%3Aopen+label%3Afirst-timers-only+sort%3Aupdated-desc) label

**Comment by ajayl83** [comment]
@rohanKanojia ok will take a look thanks!

**Comment by carloronconi** [comment]
@rohanKanojia can I pick this up? Already did a `first-timers-only` issue :)
