### ISSUE TITLE
KubernetesRemoteDevTaskTest.tearDown The declared Exception exception is never thrown

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#2717]
### Description

The method [KubernetesRemoteDevTaskTest.tearDown](https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesRemoteDevTaskTest.java#L61) declares an Exception that is never thrown.

The following line
https://github.com/eclipse/jkube/blob/5da6068d7756784aef9569568ee80f98da97e296/gradle-plugin/kubernetes/src/test/java/org/eclipse/jkube/gradle/plugin/task/KubernetesRemoteDevTaskTest.java#L61

- [x] should be changed to:

```java
  void tearDown() {
```

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by josh-segal** [comment]
I would like to work on this issue. Can it be assigned to me?

**Comment by josh-segal** [comment]
Hi, would someone be able to guide me to resources on manually testing my changes with minikube?

**Comment by manusa** [comment]
> Hi, would someone be able to guide me to resources on manually testing my changes with minikube?

Your changes only apply to a unit test, so the manual testing doesn't apply in this context.

**Comment by josh-segal** [comment]
> > Hi, would someone be able to guide me to resources on manually testing my changes with minikube?
> 
> Your changes only apply to a unit test, so the manual testing doesn't apply in this context.

I would like to contribute further and I am having trouble building and deploying the project.
Is there a tutorial that can help me build and deploy this project using minikube?

**Comment by manusa** [comment]
> Is there a tutorial that can help me build and deploy this project using minikube?

This is not a _deployable_ application, it's a tool to deploy other applications.

Once you build and install the application locally (`mvn clean install` or `mvn clean install -DskipTests` if on Windows -tests won't pass-), you can then use Minikube or anything else to deploy your application.

You can then follow one of the ["Getting Started" guides](https://eclipse.dev/jkube/docs/kubernetes-maven-plugin/#getting-started) in our documentation.
For Minikube: https://eclipse.dev/jkube/docs/kubernetes-maven-plugin/#minikube-gettingstarted

Now, instead of using the version showed in the documentation, you can use the current SNAPSHOT you've just built and installed (at this moment `1.17-SNAPSHOT`).
