### ISSUE TITLE
Fix failing JibBuildServiceBuildIntegrationTest in `jkube-kit/config`

### ISSUE THREAD

**Issue by carloronconi** [eclipse/jkube#2742]
### Component

JKube Kit

### Description
When working on #2713 I got [this failing test (expected: 17 actual: 18)](https://github.com/eclipse/jkube/blob/ad4233e5b4fc0d6455481fec77ccfd7b510a8e05/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildServiceBuildIntegrationTest.java#L166) breaking 2 checks, unrelated to the issue.

Reproduced the failure locally and it happened both pre and post changes, confirming that the test is not flaky but is instead broken.

### Acceptance Criteria
- [ ] Pass the failing test

**Comment by l3002** [comment]
@carloronconi, I've already raised a issue for this. @rohanKanojia, I'm not sure how should we proceed with this now. I was going to raise a PR for all the failing tests in `jkube-kit/config/service`.
