### ISSUE TITLE
PortForwardServiceTest : Remove use of `Thread.sleep`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2752]
### Component

JKube Kit

### Description

We have this code in PortForwardServiceTest which seems to be forwarding a port inside Kubernetes using [Fabric8 Kubernetes Client](https://github.com/fabric8io/kubernetes-client)

https://github.com/eclipse/jkube/blob/3afc7bf1f8dbe4452826c5ec7ec58de5c9408d53/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/PortForwardServiceTest.java#L98-L100

However, I'm not sure why we have `Thread.sleep` inside the try block after initializing port forward. We don't seem to be testing anything after this wait.

It's better to just remove this unnecessary waiting, asserting whether value returned from `forwardPortAsync` is not null should suffice.

### Expected Behavior
`Thread.sleep` is removed from PortForwardServiceTest.simpleScenario

### Acceptance Criteria
- [ ] Thread.sleep` is removed from `PortForwardServiceTest.simpleScenario`
- [ ] `PortForwardServiceTest.simpleScenario` should still pass after making these changes

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by manusa** [comment]
The sleep is probably there to force the code to pass through the asynchronous block, the test should be refactored to assert something (an open connection, a log message, etc.)

**Comment by rohanKanojia** [comment]
When I was trying this, test was passing even when I removed `Thread.sleep` ( probably because we are not checking anything after opening port forward)

**Comment by manusa** [comment]
test was passing because the test is not asserting anything (just like now).
