### ISSUE TITLE
Quickstarts : Update Micronaut version in `quickstarts/maven/micronaut` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2753]
### Component

None

### Description

Our Micronaut quickstarts are using an outdated version of [Micronaut framework](https://micronaut.io/):

https://github.com/eclipse/jkube/blob/3afc7bf1f8dbe4452826c5ec7ec58de5c9408d53/quickstarts/maven/micronaut/pom.xml#L24
https://github.com/eclipse/jkube/blob/3afc7bf1f8dbe4452826c5ec7ec58de5c9408d53/quickstarts/maven/micronaut-customized-image/pom.xml#L24

Micronaut 4 now requires Java 17 as baseline. Maybe we should not update this quickstart directly to 4.x. For now, updating it to the latest 3.x version (`3.9.7` at the time of creating this issue) would be okay.

:warning: This requires setting up some local Kubernetes Cluster ([MiniKube](https://minikube.sigs.k8s.io/docs/start/)/[Kind](https://kind.sigs.k8s.io/))

After updating Micronaut version, you should verify that quickstart is building fine and is also working as specified in their respective [README](https://github.com/eclipse/jkube/blob/master/quickstarts/maven/micronaut-customized-image/README.md) . You can take a look at this YouTube video [Sprint 192 - Eclipse JKube Micronaut integration](https://youtu.be/I3pjd0D90gA) to see how to try it out.

### Expected Behavior
Micronaut Quickstart is updated to latest `3.x` version

### Acceptance Criteria
- [ ] Micronaut Quickstarts are updated to latest `3.x` version
- [ ] Micronaut Quickstarts work as documented in their respective README.md files

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by clarenced** [comment]
Hello @rohanKanojia , I want to tackle this issue. Can I start ?
