### ISSUE TITLE
Katacoda scenario: Getting started - WebApp

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#276]
### Description

Create a Getting started with Eclipse JKube and WebApp (Java Servlet API) scenario under the [JKube](https://katacoda.com/jkubeio) Katacoda organization in the [Getting Started courses](https://katacoda.com/jkubeio/courses/getting-started).

The scenario should walk through the steps of creating a Spring project from scratch (Maven archetype, any other means to scaffold a Maven project) and guide the trainee to add the Eclipse JKube Maven plugin and deploy the application to the provided k8s cluster.

**Comment by manusa** [comment]
The scenario is now live (https://www.katacoda.com/jkubeio/courses/getting-started/spring-in-tomcat-quickstart) :rocket: 

Please @rohanKanojia @dev-gaur @anandrkskd, review it whenever you can to see if everything is fine and provide feedback on this issue. If necessary an additional commit will be performed to address these comments.

**Comment by rohanKanojia** [comment]
Just tried it out, looks good :+1:

**Comment by manusa** [comment]
I'm closing issue now. Scenario has been live for a week already, any new issue should be reported separately.
