### ISSUE TITLE
DockerFileUtilTest : Use JUnit5's `@TempDir` annotation for creating temporary directories

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2775]
### Component

JKube Kit

### Description
We are creating temporary directories for testing like this here 

https://github.com/eclipse/jkube/blob/b64915ec6090dcb0171e45b6372052278210e6f3/jkube-kit/build/api/src/test/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtilTest.java#L83-L84

We should probably refactor this code to use [`@TempDir` annotation](https://junit.org/junit5/docs/5.4.1/api/org/junit/jupiter/api/io/TempDir.html) . There are already some tests using this annotation, maybe make this a member level field.

### Expected Behavior
`Files.createTempDirectory` is replaced with `@TempDir` annotation field

### Acceptance Criteria
- [x] `Files.createTempDirectory` is replaced with `@TempDir` annotation field
- [x]  Instead of `new FileOutputStream(ret)` use `Files.newOutputStream(ret.toPath())`

**Comment by RISHIKESHk07** [comment]
@rohanKanojia would luv give it a try ?

**Comment by clarenced** [comment]
If anyone is working on this issue, I can provide some help with this one. :)
