### ISSUE TITLE
CI: Add license header check

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#281]
### Description
Need to add an automated CI task to check for license headers.

Create GH action workflow that runs the `mvn -N license:check` command.

**Comment by rohanKanojia** [comment]
Shall we do it on CircleCI instead? We've been using GH actions for integration tests only.

**Comment by manusa** [comment]
For consistency and maintenance reasons I'd rather use one platform or the other for **all** CI tasks (only drawback is that only a limited number of tasks can execute at the same time in GH Actions _free_, so some of them will be queued).

Since I like better GH Actions and we're using them for IT/E2E tests, that's why I suggested using GH instead of Circle. End goal would be to move everything to GH.

Is there any advantage to use CircleCI instead?
