### ISSUE TITLE
Update `quickstarts/maven/quarkus` to latest version

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2810]
### Component

None

### Description

Our quickstarts/maven/quarkus is using a slightly old version of Quarkus. It should be updated to the latest version (`3.8.2` at the time of writing)

https://github.com/eclipse/jkube/blob/c4ee9d4e9432297c50d9385a8c06d1fea0f75e3a/quickstarts/maven/quarkus/pom.xml#L35

After changing the version, you might face problems regarding missing imports. They just need to be moved to `jakarta` package instead:
- `javax.ws.rs.GET` -> `jakarta.ws.rs.GET`
- `javax.inject.Singleton` -> `jakarta.inject.Singleton`

:warning: A Kubernetes Cluster is required to test that JKube's Kubernetes Maven Plugin can deploy application to Kubernetes cluster

### Expected Behavior
Quarkus quickstart is updated to latest version

### Acceptance Criteria
- [ ] Quarkus quickstart builds successfully after version bump
- [ ] Quickstart is tested on a Kubernetes cluster to verify it's working as documented in README.md

**Comment by l3002** [comment]
Hi @rohanKanojia, I'm not sure why are these pending since last week. I can take this up. Please assign this to me.

**Comment by rohanKanojia** [comment]
> I'm not sure why are these pending since last week.

@l3002 : Maybe there are not many people interested in working on issues like these.

**Comment by l3002** [comment]
> > I'm not sure why are these pending since last week.
> 
> @l3002 : Maybe there are not many people interested in working on issues like these.

Well, I haven't worked on `quarkus`, I'll get a chance to check this out too. 😄 Thanks for assigning it.

**Comment by l3002** [comment]
@rohanKanojia, I need some help with testing it with a kubernetes cluster. I have a local setup but how am i supposed to add my local build as a dependency to a sample project and test kubernetes-maven-plugin with it?

I have not worked with such a big project before so, I don't know how to test individual modules.

**Comment by rohanKanojia** [comment]
@l3002 : Sorry, I was on PTO last week.

If you see Kubernetes Maven Plugin should already be added to the project. You just need to change the version of plugin to one by your local build (`1.17-SNAPSHOT`) . This issue is only for updating the existing quickstart, so testing with local build shouldn't be necessary.

**Comment by l3002** [comment]
Got it. Thanks for the help.
