### ISSUE TITLE
Update `quickstarts/maven/quarkus-customized-image` to latest version

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2811]
### Component

None

### Task description

Our quickstarts/maven/quarkus is using a slightly old version of Quarkus. It should be updated to the latest version (`3.8.2` at the time of writing)

https://github.com/eclipse/jkube/blob/c4ee9d4e9432297c50d9385a8c06d1fea0f75e3a/quickstarts/maven/quarkus-customized-image/pom.xml#L37

After changing the version, you might face problems regarding missing imports. They just need to be moved to `jakarta` package instead:
- `javax.ws.rs.GET` -> `jakarta.ws.rs.GET`
- `javax.inject.Singleton` -> `jakarta.inject.Singleton`

:warning: A Kubernetes Cluster is required to test that JKube's Kubernetes Maven Plugin can deploy application to Kubernetes cluster

### Expected Behavior
Quarkus quickstart is updated to latest version

### Acceptance Criteria
- [x] Quarkus quickstart builds successfully after version bump
- [ ] Quickstart is tested on a Kubernetes cluster to verify it's working as documented in README.md

**Comment by l3002** [comment]
Hi @rohanKanojia, Hope you're doing well. I'm ready to pick this up. Please assign this to me.
