### ISSUE TITLE
DefaultServiceEnricher : Remove expression which always evaluates to `false`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2813]
### Component

JKube Kit

### Description

DefaultServiceEnricher seems to have a redundant null check for a condition that can never happen:

https://github.com/eclipse/jkube/blob/c4ee9d4e9432297c50d9385a8c06d1fea0f75e3a/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DefaultServiceEnricher.java#L319

If you notice the definition of `getLabelWithService` method, you'd see it would always return a non `null` object.

We can safely remove the `portsFromImageLabels == null` check.

### Expected Behavior
remove the `portsFromImageLabels == null` check.

### Acceptance Criteria
- [x] Redundant null check is removed from DefaultServiceEnricher

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Troy-Butler** [comment]
Hi, I'm interested in working on this issue - could you please assign it to me?

**Comment by rohanKanojia** [comment]
@Troy-Butler : Hello, looks like someone already created a PR https://github.com/eclipse/jkube/pull/2827 for this issue
