### ISSUE TITLE
ArchiveDecompressor : Repalce raw use of parameterized class 'ArchiveInputStream' by providing type

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2838]
### Component

JKube Kit

### Description
ArchiveInputStream is a parameterized class, however we don't seem to be providing it's type while creating it here:

https://github.com/eclipse/jkube/blob/b10c54f17d33974c80c1fc4a26ce6a44ef29dcf7/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/archive/ArchiveDecompressor.java#L91

We should specify complete type parameter like this:
```java
try (ArchiveInputStream<ArchiveEntry> ais = new ArchiveStreamFactory().createArchiveInputStream(is)) {
```
### Expected Behavior
Parameterized type is provided in Generic

### Acceptance Criteria
- [ ] Raw use is replaced by providing generic type in variable declaration
- [ ] ArchiveDecompressorTest passes after making this change

### Before you start :red_circle:

:point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down: :point_down::point_down::point_down::point_down::point_down::point_down::point_down:
Make sure you read the [contributing guide](https://www.eclipse.org/jkube/contributing) first. Pay special attention to the ECA agreement section and the requirement to sign-off your commit.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by sudharsan-gitrepo** [comment]
@rohanKanojia I would like to work on this story, and this is my first time here. Could you please assign this to me?

**Comment by Jonathanlemon** [comment]
Hi @rohanKanojia I'd like to tackle this. For the parameterized type, shall I use ArchiveEntry, or should I find a different suitable type?

**Comment by manusa** [comment]
> shall I use ArchiveEntry

Yes, the relevant code changes are explained in the description. The point of this issue is for you to get familiarized with the Eclipse contribution procedure (ECA, creating a fork, pull request, and so on).
