### ISSUE TITLE
Quickstarts (quickstarts/maven/spring-boot) : Replace `org.springframework.web.bind.annotation.RequestMapping` with more specific `org.springframework.web.bind.annotation.GetMapping`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2839]
### Component

None

### Description

Our Spring Boot quickstart seems to be using generic `@RestMapping`  annotation

https://github.com/eclipse/jkube/blob/b10c54f17d33974c80c1fc4a26ce6a44ef29dcf7/quickstarts/maven/spring-boot/src/main/java/org/eclipse/jkube/maven/sample/spring/boot/HelloController.java#L27

We should use more specific `@GetMapping` annotation as specified in [Spring docs ](https://docs.spring.io/spring-framework/reference/web/webmvc/mvc-controller/ann-requestmapping.html#mvc-ann-requestmapping-annotation)

### Expected Behavior
`@RequestMapping` is replaced by `@GetMapping`

### Acceptance Criteria
- [x] `@RequestMapping` is replaced by `@GetMapping`
- [ ] `quickstarts/maven/spring-boot` compiles successfully after `mvn clean install`
- [ ] `quickstarts/maven/spring-boot` works as expected in its [README](https://github.com/eclipse/jkube/blob/master/quickstarts/maven/spring-boot/README.md)

**Comment by waynemorphic** [comment]
I can work on this @rohanKanojia
