### ISSUE TITLE
How to push to external registry when using OpenShift?

### ISSUE THREAD

**Issue by Jurrie** [eclipse/jkube#2848]
Hello,

I have an image which is meant as a base image for other images to extend. I can successfully build this image in OpenShift using `oc:build`. But because it's a base image, I want to publish it to a central registry when tagging and releasing a new version. I can not seem to figure out how to do that with `oc:push`. Because that command is giving me:

```
[WARNING] oc: Image is pushed to OpenShift's internal registry during oc:build goal. Skipping...
```
I checked the sources, and I do not see an easy way to override this behavior. I could probably pull the built image from OpenShift's registry to my local Docker instance, and then push it to the central registry again. But that's manual work; I'd like an automated way. Is there such a way using JKube?

**Comment by rohanKanojia** [comment]
@Jurrie : I think you would need to configure push secret and change `jkube.build.outputKind` to `DockerImage`.

See this [YouTube Demo](https://youtu.be/zAIARZ-efxk) for this functionality. I had also written a blogpost about [this](https://rohankanojia.github.io/articles/2023/12/15/openshift-publish-image-external-registry/).

**Comment by Jurrie** [comment]
Thank @rohanKanojia, that was the missing part of the puzzle 😀
