### ISSUE TITLE
AuthConfigFactory : provide parameterized type for the generic 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2870]
### Component

JKube Kit

### Description
We are calling this method in AuthConfigFactory that seems to be returning a value `Map<String, String>` , However we're not providing type in map that's being assigned the returned value.

https://github.com/eclipse/jkube/blob/335aa3bcd76523c4f9ee89dab46225278b3ce20d/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/AuthConfigFactory.java#L366-L368

### Expected Behavior
Parameterized type of provided for `Map`. `Map<String, String>` is used in place of `Map`. Once we use it, we won't need the type casting done on next line

### Acceptance Criteria
- [ ] Replace `Map` with `Map<String, String>`
- [ ] Remove explicit type casting due to using a raw generic Map.

**Comment by akshay11agrawal** [comment]
@rohanKanojia, Interested in picking this one up, let me know if I can work on this issue
