### ISSUE TITLE
Quickstarts (quickstarts/maven/vertx4) : Bump `vertx.version` to latest version

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#2874]
### Component

None

### Description

Our current vertx4 quickstart seems to be using slightly older version of vertex
https://github.com/eclipse/jkube/blob/335aa3bcd76523c4f9ee89dab46225278b3ce20d/quickstarts/maven/vertx4/pom.xml#L37

We should update it to latest available version (4.5.7 at the time of creating the issue)

### Expected Behavior
Vertx version is bumped to latest version

### Acceptance Criteria
- [x] Vertx version is bumped to latest available release
- [x] Quickstart works as expected as defined in its [README](https://github.com/eclipse/jkube/blob/335aa3bcd76523c4f9ee89dab46225278b3ce20d/quickstarts/maven/vertx4/README.md)

**Comment by Teja-11** [comment]
I would like to work on this. Can you assign this to me please?

**Comment by ArunErram** [comment]
can i work on these ?
@rohanKanojia

**Comment by rohanKanojia** [comment]
@ArunErram : Have you contributed to the project before? This issue is created for contributors who have already contributed to the project already.

**Comment by rohanKanojia** [comment]
@Teja-11 : Are you a first time contributor? Or have you contributed to the project already?

**Comment by Teja-11** [comment]
I have contributed to this project before.

**Comment by Teja-11** [comment]
Hi,

Just wanted to let you know that the Maven build using 'k8s:deploy' completed successfully. The Vertx4 application has been deployed to Kubernetes with out any issues. 

![Screenshot 2024-04-10 at 9 58 26 PM](https://github.com/eclipse/jkube/assets/60323760/35791750-f6db-4194-ad20-02c5411d6f18)

![Screenshot 2024-04-10 at 9 59 01 PM](https://github.com/eclipse/jkube/assets/60323760/5d705957-3caf-4dca-9af7-4c6ad1ce3c68)

Should I also test it on OpenShift?

**Comment by rohanKanojia** [comment]
@Teja-11 : You also need to check whether application is running in Kubernetes.

You can test on OpenShift using [Red Hat OpenShift Developer Sandbox](https://developers.redhat.com/developer-sandbox)

**Comment by Teja-11** [comment]
Hi @rohanKanojia

I've deployed the application on Openshift. Testing the end points returned "Hello from Vert.x!".

<img width="1186" alt="Screenshot 2024-04-11 at 3 55 56 PM" src="https://github.com/eclipse/jkube/assets/60323760/ca14b822-be8d-477f-8077-d71ea63c5c7b">

please Let me know if i am missing anything.
