### ISSUE TITLE
problem in detecting server port in application.yaml unlike application.properties  where it detect the server port when k8s:resources

### ISSUE THREAD

**Issue by AhmdFahad** [eclipse/jkube#2909]
### here when it create kubernetes manifest it did`n detect the port 
![image](https://github.com/eclipse/jkube/assets/68047377/b4ec6b00-5957-441a-b1f7-901456435b69)
### unlike  in application.properties  it detect  the port
![image](https://github.com/eclipse/jkube/assets/68047377/bc3387d7-bc1a-4d52-a302-9a2c6bbf6a86)

### Eclipse JKube version

1.16.2

### Component

Kubernetes Maven Plugin

### Apache Maven version

other (please specify in additional context)

### Gradle version

None

### Steps to reproduce

mvn clean install k8s:resource

### Expected behavior

.

### Runtime

Kubernetes (vanilla), other (please specify in additional context)

### Kubernetes API Server version

other (please specify in additional context)

### Environment

Windows

**Comment by rohanKanojia** [comment]
@AhmdFahad : Hello, do you think your problem is related to https://github.com/eclipse/jkube/issues/2832 ? Did you run `mvn package` before running `k8s:resource`?

**Comment by AhmdFahad** [comment]
yes i did , 
`mvn clean install k8s:resource`

**Comment by arsenalzp** [comment]
> yes i did , `mvn clean install k8s:resource`

You can check presence of `application.properties` in `target/classes` directory. I guess this issue is related to issue I'm working for.

**Comment by AhmdFahad** [comment]
here is the target/classes/**application.yaml** in target class 
![image](https://github.com/eclipse/jkube/assets/68047377/8176d0da-e5c3-41c3-87f9-c643735df0d0)
-----
and here is target/classes/**application.properties**  
![image](https://github.com/eclipse/jkube/assets/68047377/0a934f7d-b170-4f32-bed8-89f41081dc5a)
-----
and every time i switch the application file extension i clean and build the project 
using maven `mvn clean install k8s:resoruce`

**Comment by AhmdFahad** [comment]
It seems like the issue is related to the **.yaml** extension. But when I used **.yml**, it worked well.

**Comment by AhmdFahad** [comment]
here is the file of type **.yaml** 
here when i was using the .yaml it was not detect the port server port 
but when i used the **.yml**  it works properly
![image](https://github.com/eclipse/jkube/assets/68047377/ad417646-38de-4c20-95f9-a65ff6a2194b)
--------------------

### and here is the **.yml**

![image](https://github.com/eclipse/jkube/assets/68047377/ab22655f-9dff-4a03-8001-b66eaa69f9c6)

**Comment by AhmdFahad** [comment]
#  I think I've understood what the problem is. I hope it gets resolved soon. I'll go ahead and close this ticket, and thank you for your assistance

**Comment by AhmdFahad** [comment]
@rohanKanojia , In fact, I'm not entirely sure what the preference is, but in the documentation, YAML is referenced 45 times compared to YML, which is only mentioned 17 times.
-----
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.spring-application

![image](https://github.com/eclipse/jkube/assets/68047377/f245344d-c33e-41b4-a3ef-76bae9b6db10)

![image](https://github.com/eclipse/jkube/assets/68047377/8cfda66f-b9a1-4c35-ae50-442926ffcb17) 
---------

look at that quoted from Documentation  `**No matter what you set in the environment, Spring Boot always loads application.properties as described above. By default, if YAML is used, then files with the ‘.yaml’ and ‘.yml’ extension are also added to the list.**`


This is what I couldn't reach, but if you have the knowledge, I hope you can share it with me.

**Comment by AhmdFahad** [comment]
![image](https://github.com/eclipse/jkube/assets/68047377/16165858-4e61-4f23-b57f-b7af07385a03)

**Comment by rohanKanojia** [comment]
@AhmdFahad : I think problem is here in our code:

https://github.com/eclipse/jkube/blob/794e115ebf94b78d1f3753c8513d0b4d75264a61/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/SpringBootUtil.java#L68-L69

We only consider for `application.yml` / `application.properties`. We should update it for `application.yaml` as well.
