### ISSUE TITLE
should add prometheus.io/path

### ISSUE THREAD

**Issue by survivant** [eclipse/jkube#326]
you generate those labels

prometheus.io/port: "9779"
prometheus.io/scrape: "true"

could should add

prometheus.io/path: /metrics

to explicitly tell us where Prometheus will check for metrics

**Comment by rohanKanojia** [comment]
@survivant : Thanks for sharing feedback for `PrometheusEnricher`. Would you like to submit a PR to fix this? Just need to do required changes here:

https://github.com/eclipse/jkube/blob/68ac53f4546610f05fbced4b75b49868a58556d7/jkube-kit/enricher/specific/src/main/java/org/eclipse/jkube/kit/enricher/specific/PrometheusEnricher.java#L44-L50
