### ISSUE TITLE
k8s:helm should use values.yaml file

### ISSUE THREAD

**Issue by survivant** [eclipse/jkube#327]
k8s:helm

generate Helm artifacts.. but the content of deleployment.yaml and others doesn't use values.yaml

you should use standars values like this
```

# Kubernetes & Docker
replicaCount: 1
nameOverride: ""
fullnameOverride: ""
image: xyz
imagePullPolicy: Always
imagePullSecrets: []
```

deployment.yaml
```
spec:
  replicas: {{ .Values.replicaCount }}
```
...

**Comment by manusa** [comment]
Hi
[spring-boot-helm](https://github.com/eclipse/jkube/tree/master/quickstarts/maven/spring-boot-helm) example actually shows how you can use this for any string compatible value.
The problem with not being able to use these template values on non-string fields is related to several active issues on Kubernetes-Client:
- https://github.com/fabric8io/kubernetes-client/issues/448
- https://github.com/fabric8io/kubernetes-client/issues/1979
- https://github.com/fabric8io/kubernetes-client/issues/959
- ...

The model classes are typed, so when generating the class instance and setting the values as placeholders for variables, this will only work for string fields that can be set with a `{{ }}`.

We'll need to figure out a way to overcome this, probably by converting the class instance to an intermediate Map, setting the problematic fields on the Map, and then serializing it.

**Comment by manusa** [comment]
Besides the problems with replacing integer values, Helm mojo is not behaving correctly.

`k8s:resource` goal should replace **all** parameters  with the provided Template parameter default values.

`k8s:helm` goal should **keep** those parameter placeholders and add the values to the `values.yml` file.

## Template parameters (k8s:resource & k8s:helm)
As of now, [ReourceMojo#findTemplate](https://github.com/eclipse/jkube/blob/9ce411df9aeff2be9e072f266fe879defee1c1d7/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java#L623) locates the first resource of type `Template`.

This means that if there are several (1-first-template.yml, template.yml, etc.) only the first will be considered to gather parameters.


The List of parameters should be gathered as:
```java
(List<Parameter>)(Template) resources.getItems().stream()
          .filter(template -> template instanceof Template)
          .map(Template.class::cast)  
          .map(Template::getParameters)
          .collect(Collectors.toList())  
```

**Only** for `k8s:resource`, the place-holders in the original resources should be replaced.

## Helm Mojo
Helm should be decoupled from resource goal.

Helm should run a resource  generation but without replacing parameter placeholders.
This means that this line should be skipped only for helm chart generation:
https://github.com/eclipse/jkube/blob/9ce411df9aeff2be9e072f266fe879defee1c1d7/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ResourceMojo.java#L577-L578
