### ISSUE TITLE
BuildStrategy jib produces exception "Service hub created without a docker access to a docker daemon"

### ISSUE THREAD

**Issue by britzke** [eclipse/jkube#334]
It seems not to be possible for me to do a jib build by using the `<buildBtrategy>jib</buildStrategy>` element. An exception is raised "Service hub created without a docker access to a docker daemon". 

# Info
* Eclipse JKube version : 1.0.0-rc-1
* Maven version (`mvn -v`) : 3.6.3
```

```
* How to reproduce : create a simple empty war packed project with
```
   <plugin>
      <groupId>org.eclipse.jkube</groupId>
      <artifactId>kubernetes-maven-plugin</artifactId>
      <version>1.0.0-rc-1</version>
      <configuration>
         <buildStrategy>jib</buildStrategy>
      </configuration>
   </plugin>
```
The Documentation available could help. The only the valid values for element is described.

**Comment by manusa** [comment]
hmmm :( could you try using the property instead? seems configuration is note getting picked up
```xml
<properties>
  <jkube.build.strategy>jib</jkube.build.strategy>
</properties>
```

**Comment by manusa** [comment]
I can reproduce, with property it works, without it, it doesn't.

**Comment by britzke** [comment]
OK using the proposed property it tried to do a JIB build (telling: k8s: JIB image build started).
