### ISSUE TITLE
Eclipse JKube should ignore copying non-fat Jars inside build tarball

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#340]
### Description

In Fabric8 Maven Plugin, we only used to detect and copy the main fat jar into final build archive. Here is an example from vertx-examples:
```
~/work/repos/vertx-examples/web-api-service-example : $ tree target/docker/
target/docker/
├── build.timestamp
└── vertx
    └── web-api-service-example
        └── 3.9.0
            ├── build
            │   ├── Dockerfile
            │   └── maven
            │       └── web-api-service-example-3.9.0-fat.jar
            ├── tmp
            │   └── docker-build.tar
            └── work
```
But now with JKube, we're copying unnecessary jars into archive:
```
~/work/repos/vertx-examples/web-api-service-example : $ tree target/docker/
target/docker/
├── build.timestamp
└── vertx
    └── web-api-service-example
        └── 3.9.0
            ├── build
            │   ├── deployments
            │   │   ├── web-api-service-example-3.9.0-fat.jar
            │   │   └── web-api-service-example-3.9.0.jar
            │   └── Dockerfile
            ├── tmp
            │   └── docker-build.tar
            └── work

7 directories, 5 files
```
This creates confusion in our default opinionated image since it fails to detect which jar to run, This leads to additional configuration `JAVA_APP_JAR` environment variable and if not configured, this error:
```
/usr/local/s2i/run: line 15: /opt/jboss/container/maven/default//scl-enable-maven: No such file or directory
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
ERROR Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 2 JARs found in /deployments (1 expected)
INFO exec  java -javaagent:/usr/share/java/jolokia-jvm-agent/jolokia-jvm.jar=config=/opt/jboss/container/jolokia/etc/jolokia.properties -XX:+UseParallelOldGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:MaxMetaspaceSize=100m -XX:+ExitOnOutOfMemoryError -cp "." -jar   
Error: -jar requires jar file specification
Usage: java [options] <mainclass> [args...]
           (to execute a class)
   or  java [options] -jar <jarfile> [args...]
           (to execute a jar file)
   or  java [options] -m <module>[/<mainclass>] [args...]
       java [options] --module <module>[/<mainclass>] [args...]
           (to execute the main class in a module)
   or  java [options] <sourcefile> [args]
           (to execute a single source-file program)

```

### Info

* Eclipse JKube version :
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven
Java version: 14.0.1, vendor: Oracle Corporation, runtime: /usr/java/jdk-14.0.1
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.6.19-300.fc32.x86_64", arch: "amd64", family: "unix"

```
* Kubernetes / Red Hat OpenShift setup and version : Kubernetes 1.18.6

* If it's a bug, how to reproduce :
- Clone https://github.com/vert-x3/vertx-examples
- do `k8s:build`
- You would notice that build image fails to be run with the error specified

* If it's a feature request, what is your use case :

* Sample Reproducer Project : https://github.com/vert-x3/vertx-examples/tree/3.x/web-api-service-example

**Comment by manusa** [comment]
There is a configuration flag to for the [assembly](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#build-assembly) prevents the final artifact jar from being added to the container image (problem you are reporting now).

![image](https://user-images.githubusercontent.com/488391/89285659-10286800-d651-11ea-83a3-cdb12a5ec4a6.png)

This is already used in some generators such as [WebAppGenerator](https://github.com/eclipse/jkube/blob/389fde33fc02da9d728cf98a29543d1b9bcacce7/jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java#L166).

If you encountered this problem with Vert.x, maybe we should tune JavaExec generator a little bit.

**Comment by rohanKanojia** [comment]
In my opinion, it should work without providing any configuration as it used to in FMP

**Comment by manusa** [comment]
> In my opinion, it should work without providing any configuration as it used to in FMP

Exactly, but this needs to be done with the specified assembly configuration option (`excludeFinalOutputArtifact`). See WebAppGenerator.

The main artifact started to get included after the Maven decoupling. Since XML assembly configurations were ignored, apparently this function was added to add default artifact (which enabled many of the generators to work as usual):
https://github.com/eclipse/jkube/blob/2493bd5050b579a6c54b30500a7b9939fe14af22/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java#L163-L169

This was tuned later on so that the artifact could be excluded by using a configuration option:
https://github.com/eclipse/jkube/blob/389fde33fc02da9d728cf98a29543d1b9bcacce7/jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyManager.java#L434-L436

So now, this is the preferred way to exclude the artifact.
