### ISSUE TITLE
openshift-maven-plugin does not include annotations when using jkube-openshift-autotls enricher

### ISSUE THREAD

**Issue by sejacobsen** [eclipse/jkube#351]
### Description
Using the jkube-openshift-autotls enricher does not add service metadata annotation
```
metadata:
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: <secret-name>
```
Init container args are added.
### Info

* Eclipse JKube version : 1.0.0-rc-1
* Maven version (`mvn -v`) : 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/sej/.sdkman/candidates/maven/current
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /Users/sej/.sdkman/candidates/java/11.0.7.hs-adpt
Default locale: en_DK, platform encoding: US-ASCII
OS name: "mac os x", version: "10.15.5", arch: "x86_64", family: "mac"

```
* Kubernetes / Red Hat OpenShift setup and version :

OpenShift Master: v3.11.216 
Kubernetes Master: v1.11.0+d4cacc0 
OpenShift Web Console: >9000 

* If it's a bug, how to reproduce :

- Use the given zero-config sample. 
- Include the enricher as documented:

```
  <executions>
    <execution>
      <goals>
        <goal>resource</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <enricher>
      <includes>
        <include>jkube-openshift-autotls</include>
      </includes>
      <config>
        <jkube-openshift-autotls>
          <!-- ... -->
        </jkube-openshift-autotls>
      </config>
    </enricher>
  </configuration>
``` 
- run mvn clean oc:resource -Popenshift

Expected to have a service annotation like stated above.

I have peeked in the AutoTLSEnricher.java class. The #create method seems to have support for adding the annotation:

```
        builder.accept(new TypedVisitor<ServiceBuilder>() {
            @Override
            public void visit(ServiceBuilder service) {
                /*
                 * Set the service.alpha.openshift.io/serving-cert-secret-name annotation on your
                 * service with the value set to the name you want to use for your secret.
                 *
                 * https://docs.openshift.com/online/dev_guide/secrets.html#service-serving-certificate-secrets
                 */
                service.editOrNewMetadata()
                        .addToAnnotations(AUTOTLS_ANNOTATION_KEY, secretName)
                        .endMetadata();
            }
        });
```

* Sample Reproducer Project : 
- https://github.com/sejacobsen/jkube.git
- https://github.com/sejacobsen/jkube/blob/master/quickstarts/maven/zero-config/pom.xml

Happy to work on this, hints appreciated, as I am apparently pretty rusty :)

I am trying to write a test that will generate the correct resource files, can only find coverage for the #enrich method in AutoTLSEnricherTest.java class.

**Comment by rohanKanojia** [comment]
@sejacobsen : ah, that's strange. Were you able to see annotation getting added via that `service.editOrNewMetadata()` block when you were debugging this?

**Comment by sejacobsen** [comment]
@rohanKanojia no, I am having some trouble actually stepping into that particular anonymous function (and the one above - ContainerBuilder) using IntelliJ, though I suspect that is an IDE issue. The PodSpecBuilder anonymous class can be inspected, which is a bit strange. I will continue working on this for a bit.

**Comment by TueDissingWork** [comment]
Is there an example on how to use the autotls enricher? I am also not capable of getting this to work properly.
The init container are configured, but I seems to be missing the volume on the service container.

**Comment by sejacobsen** [comment]
OK, I think the problem may be that no visitables are available when calling the create method on AutoTLSEnricher. Ie., the builder will not add anything. However, when moving the code from #create to #enrich, both the serving-cert-secret-name annotation and the volume + volumemounts are generated (they were not before).

@rohanKanojia Do you think it is reasonable to simply move all builder code to the enrich method?

**Comment by rohanKanojia** [comment]
I don't see any problem in doing so if it's working. Please go ahead and create a PR :-)
