### ISSUE TITLE
Final output artifact file was not detected when War name is configured

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#369]
### Description

When trying to build a simple web application using eclipse jkube, I'm facing this issue. It's failing to detect when war's name is not equal to project artifactId. It's giving me this error:
```
os-sample-java-web : $ mvn oc:build
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< openshift:getting-started-tomcat >------------------
[INFO] Building getting-started-tomcat Maven Webapp 1.0-SNAPSHOT
[INFO] --------------------------------[ war ]---------------------------------
[INFO] 
[INFO] --- openshift-maven-plugin:1.0.0-rc-1:build (default-cli) @ getting-started-tomcat ---
[INFO] oc: Using OpenShift build with strategy S2I
[INFO] oc: Running in OpenShift mode
[INFO] oc: Running generator webapp
[INFO] oc: webapp: Using quay.io/jkube/jkube-tomcat9-binary-s2i:0.0.7 as base image for webapp
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.837 s
[INFO] Finished at: 2020-08-27T11:55:55+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jkube:openshift-maven-plugin:1.0.0-rc-1:build (default-cli) on project getting-started-tomcat: Execution default-cli of goal org.eclipse.jkube:openshift-maven-plugin:1.0.0-rc-1:build failed: Final output artifact file was not detected -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

However, when I remove `<warName>` configuration from `maven-war-plugin` it works as expected:
```
           <plugin>
               <artifactId>maven-war-plugin</artifactId>
               <version>2.6</version>
-              <configuration>
-                  <warName>ROOT</warName>
-              </configuration>
```

### Info

* Eclipse JKube version : 1.0.0-rc-1
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven
Java version: 14.0.1, vendor: Oracle Corporation, runtime: /usr/java/jdk-14.0.1
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.7.11-200.fc32.x86_64", arch: "amd64", family: "unix"
```
* Kubernetes / Red Hat OpenShift setup and version : v3.11.0+0cbc58b

* If it's a bug, how to reproduce : Clone reproducer project and try doing `mvn org.eclipse.jkube:openshift-maven-plugin:build`

* If it's a feature request, what is your use case :

* Sample Reproducer Project : https://github.com/OpenShiftDemos/os-sample-java-web

**Comment by manusa** [comment]
The configuration you are embedding allows the web application to be served from the root path `http://localhost:8080` as opposed to `http://localhost:8080/getting-started-tomcat`.

JKube already provides this functionality OOTB. If you want to configure the context path you can do so by using `jkube.generator.webapp.path` configuration.

So that plugin configuration (maven-war-plugin) can be removed altogether for the JKube profile.

However, there may be an underlying problem here related to our Maven to Java project conversion tools.

**Comment by manusa** [comment]
After a more thorough analysis, I'm not sure taking into account this `maven-war-plugin` configuration is something we want to consider.

This configuration collides directly with our own path configuration and opinionated defaults. Users with the intention of taking advantage of our WebappGenerator should remove (or set in a different profile) this specific maven-war-plugin configuration.

In addition, it doesn't make much sense in the context of a containerized self-contained web application to customize the name of the generated war artifact. Our [WebappGenerator already takes care](https://github.com/eclipse/jkube/blob/8ca3f342372128fe12ea1572db1e37d033406a94/jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/WebAppGenerator.java#L157) of the renaming in case we want to expose the web application in the root context or in a customized path.

See also:
- [WarMojo#68](https://github.com/apache/maven-war-plugin/blob/cd2867734e8fc0cb6d9a14e19601a3d6a476d683/src/main/java/org/apache/maven/plugins/war/WarMojo.java#L68)
- [war:war](https://maven.apache.org/plugins-archives/maven-war-plugin-2.4/war-mojo.html#warName)
