### ISSUE TITLE
Provide admin access to committers for this repository

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#37]
@eclipsewebmaster @eclipse/ecd-jkube-committers : Do you think it's possible to provide admin access to us for this repository? Right now we're not able to add labels to repository or even enabe github pages.

If not, Could you please do the following:
- Add the following topics to this repository like done in https://github.com/fabric8io/fabric8-maven-plugin
~- Enable github pages in this repository (with default configuration of `gh-pages`)~

**Comment by manusa** [comment]
Open an issue in Eclipse/Bugzilla/... to accomplish this.

**Comment by rohanKanojia** [comment]
I've filed this[0] issue on bugzilla.

[0] https://bugs.eclipse.org/bugs/show_bug.cgi?id=563129
