### ISSUE TITLE
Replace anonymous Runnables with lambdas in WatchService

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#370]
### Description

I see that we have some places in code where we're still using anonymous classes. Since we're already on Java 8, we can easily refactor these to make use of [lambdas](https://www.oracle.com/technical-resources/articles/java/architect-lambdas-part1.html). For example, I noticed these in WatchService:

https://github.com/eclipse/jkube/blob/8ca3f342372128fe12ea1572db1e37d033406a94/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/WatchService.java#L141-L156

https://github.com/eclipse/jkube/blob/8ca3f342372128fe12ea1572db1e37d033406a94/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/WatchService.java#L179-L201

https://github.com/eclipse/jkube/blob/8ca3f342372128fe12ea1572db1e37d033406a94/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/WatchService.java#L211-L223

**Comment by rohanKanojia** [comment]
@Shivkumar13 : Hi, are you still working on this issue?

**Comment by Shivkumar13** [comment]
@rohanKanojia yes I will update my findings in a day, I was busy in other tasks.

**Comment by itsarraj** [comment]
Hello sir ,
I am new to open source contribution.
I already know java , my tech stacks & tools includes C, C++ , Python , Java, JavaScript , HTML , CSS , SQL , Bootstrap, ReactJS, ExpressJS, NodeJS & Git . I need a little help from your side to contribute to these amazing projects.
