### ISSUE TITLE
Docker image root requirement

### ISSUE THREAD

**Issue by carljmosca** [eclipse/jkube#381]
I am using a custom Java Tomcat image which does not run as root.

When doing a mvn k8s:build I am seeing this error:

```
Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.0.0-rc-1:build (default-cli) on project jsf-primefaces-apache-tomcat: Failed to execute the build: Error while trying to build the image: Unable to build image [jsf-primefaces-demo] : "The command '/bin/sh -c chown -R root /tmp/28bb7591-77ce-4ff0-859b-38239fd8e519 && cp -rp /tmp/28bb7591-77ce-4ff0-859b-38239fd8e519/* / && rm -rf /tmp/28bb7591-77ce-4ff0-859b-38239fd8e519' returned a non-zero code: 1" -> [Help 1]
```

Is there currently any way to get around the requirement to change ownership to the root user?  

We generally run as unknown (not predictable UID) users which are in the root group as we have seen done in some of the Red Hat images which run on OpenShift with default security settings.

**Comment by carljmosca** [comment]
I did not have the understanding of the **assembly** section of the build section.  I am past this issue now so I will close it but I am wondering about the need for root.

**Comment by rohanKanojia** [comment]
Running images as a non-root user seem quite a common use-case to me. @manusa WDYT??

**Comment by manusa** [comment]
Hi,

In general, images are **not** run as any specific user by default. This is especially important for S2I built images since OpenShift doesn't allow to run containers as specific users [by default](https://docs.openshift.com/container-platform/4.5/openshift_images/create-images.html#use-uid_create-images).

Regarding the use of `root` for assembly purposes (when another user is provided in the configuration) you can read more in the [assembly section of our docs](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#build-assembly).

>User and/or group under which the files should be added. The user must already exist in the base image.It has the general format user[:group[:run-user]]. The user and group can be given either as numeric user- and group-id or as names. The group id is optional.
>
>If a third part is given, then the build changes to user root before changing the ownerships, changes the ownerships and then change to user run-user which is then used for the final command to execute. This feature might be needed, if the base image already changed the user (e.g. to 'jboss') so that a chown from root to this user would fail.
>
>For example, the image jboss/wildfly use a "jboss" user under which all commands are executed. Adding files in Docker always happens under the UID root. These files can only be changed to "jboss" is the chown command is executed as root. For the following commands to be run again as "jboss" (like the final standalone.sh), the plugin switches back to user jboss (this is this "run-user") after changing the file ownership. For this example a specification of jboss:jboss:jboss would be required.

So if you want to customize the assembly user you can use the following:

`<jkube.generator.webapp.user>1000:1000</jkube.generator.webapp.user>` (No run user)

`<jkube.generator.webapp.user>1000:1000:1000</jkube.generator.webapp.user>` (will add `USER 1000`)

The first pair is the user:group for assembly, the last is the run user. This will generate a Dockerfile with lines like:
```
COPY /deployments /tmp/2430f958-1bb2-44f0-9142-e608560f04bc/deployments/
USER root
RUN chown -R 1000:1000 /tmp/2430f958-1bb2-44f0-9142-e608560f04bc && cp -rp /tmp/2430f958-1bb2-44f0-9142-e608560f04bc/* / && rm -rf /tmp/2430f958-1bb2-44f0-9142-e608560f04bc
USER 1000
CMD /usr/local/s2i/run
```




**However**, if you are using a complete custom xml-configuration then maybe you're hitting into [this](https://github.com/eclipse/jkube/blob/9ce411df9aeff2be9e072f266fe879defee1c1d7/jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/AssemblyConfigurationUtils.java#L41), so just provide your own user for assembly purposes.

I'm not really sure why the `root` user is provided, this was [added](https://github.com/rohanKanojia/jkube/blob/f3849e48473625b9ba00aedfd2ed4d7990346b75/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java#L112) in #47.

I can see the `maven` [default](https://github.com/fabric8io/docker-maven-plugin/blob/1da5d292173ac26bb7820f8c9fbd2b9fcfacfa82/src/main/java/io/fabric8/maven/docker/config/AssemblyConfiguration.java#L29) in DMP, but can't see anything regarding this [user](https://github.com/fabric8io/docker-maven-plugin/blob/1da5d292173ac26bb7820f8c9fbd2b9fcfacfa82/src/main/java/io/fabric8/maven/docker/config/AssemblyConfiguration.java#L74). @rohanKanojia do you know where this came from?

**Comment by carljmosca** [comment]
Thank you @manusa 

The first part of your explanation is consistent with our practice.  I am sorry if that was not clear from my original text.

I am reopening as it seems that the origin of the root user should be tracked/removed.

**Comment by javastl** [comment]
jkube.generator.webapp.user fails to create the group or the user

pom contents below

------------------------
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.4</version>
		<relativePath/> 
	</parent>
	<groupId>com.javastl</groupId>
	<artifactId>csv-app</artifactId>
	<version>1.1</version>
	<name>csv</name>
	<description>Demo project for Spring Boot</description>
	<properties>

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>11</java.version>
		<docker.user>bwiwebsphere</docker.user>
		
		<jkube.version>1.5.1</jkube.version>
		<jkube.namespace>csv</jkube.namespace>
		<jkube.docker.registry>docker.io</jkube.docker.registry>
		<jkube.generator.webapp.user>1000:1000:1000</jkube.generator.webapp.user>
		<jkube.createExternalUrls>true</jkube.createExternalUrls>
		<jkube.generator.webapp.path>/csv</jkube.generator.webapp.path>

		<jkube.replicas>3</jkube.replicas>
		<jkube.enricher.jkube-service.type>NodePort</jkube.enricher.jkube-service.type>

		
		<jkube.enricher.jkube-service.expose>true</jkube.enricher.jkube-service.expose>
		
		<jkube.generator.name>${docker.user}/random-generator:${project.version}</jkube.generator.name>
		
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>javainetlocator</groupId>
			<artifactId>inetaddresslocator</artifactId>
			<version>2.18</version>
		</dependency>

	</dependencies>


	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.eclipse.jkube</groupId>
				<artifactId>kubernetes-maven-plugin</artifactId>
				<version>1.4.0</version>
			</plugin>
			<plugin>
				<groupId>org.eclipse.jkube</groupId>
				<artifactId>openshift-maven-plugin</artifactId>
				<version>1.4.0</version>
			</plugin>
		</plugins>
	</build>

</project>
__________________________

Content of dockerfile
___________________

FROM quay.io/jkube/jkube-java-binary-s2i:0.0.9
ENV JAVA_APP_DIR=/deployments
LABEL org.label-schema.description="Demo project for Spring Boot" org.label-schema.version=1.1 org.label-schema.schema-version=1.0 org.label-schema.build-date=2021-10-29T18:44:18.113720 org.label-schema.name=csv org.label-schema.vcs-ref=dfbee5837ffd660303963579044f69fedf3b2bb2 org.label-schema.vcs-url=https://github.com/javastl/csv.git
EXPOSE 8080 8778 9779
COPY /jkube-generated-layer-original/deployments /deployments/

__________________

**Comment by manusa** [comment]
https://github.com/eclipse/jkube/issues/1100#issuecomment-959777704

**Comment by javastl** [comment]
Here is my current configuration.  It runs but does not allow me to configure the path for "/hello" to be shown in the kubernetes-dashboard

                <configuration>
                    <images>
                        <image>
                            <name>${docker.user}/random-generator:${project.version}</name>
                            <build>
                                <from>openjdk:11</from>
                                <env>
                                    <JAVA_APP_DIR>/deployments</JAVA_APP_DIR>
                                </env>
                                
                                <ports>
                                    <port>8080</port>
                                    <port>9779</port>
                                </ports>

                                <runCmds>
                                    <run>groupadd -r appUser</run>
                                    <run>useradd -r -g appUser appUser</run>
                                </runCmds>
                                <user>appUser</user>
                                <workdir>/home/appUser</workdir>
                                <cmd>java -jar /deployments/${project.artifactId}-${project.version}.jar</cmd>
                                <assembly>
                                    <mode>dir</mode>
                                    <targetDir>/deployments</targetDir>
                                    <layers>
                                        <layer>
                                            <id>standard-assembly</id>
                                            <files>
                                                <file>
                                                    <source>target/${project.artifactId}-${project.version}.jar</source>
                                                    <outputDirectory>.</outputDirectory>
                                                </file>
                                            </files>
                                        </layer>
                                    </layers>
                                </assembly>
                            </build>
                        </image>
                    </images>
                    <resources>
                        <ingress>
                            <ingressRules>
                                <ingressRule>
                                    <paths>
                                        <path>
                                            <pathType>Prefix</pathType>
                                            <path>/hello</path>
                                            <serviceName>csv-app</serviceName>
                                            <servicePort>8080</servicePort>
                                        </path>
                                    </paths>
                                </ingressRule>
                            </ingressRules>
                        </ingress>
                    </resources>
                </configuration>
