### ISSUE TITLE
WildFly Bootable JAR - Add native support for slim Bootable JAR

### ISSUE THREAD

**Issue by jfdenise** [eclipse/jkube#385]
### Description
Thanks to JKube workflow, we have the opportunity to benefit from slim Bootable JAR (a Bootable JAR that doesn't contain JBoss modules artifacts) feature. slim Bootable JAR starts fast, this wil lreduce the server startup time.

The WildFlyJar Generator can detect the path to the generated maven repo cache configured in the wildfly-jar-maven-plugin and installs it in the Docker image in /deployments/[directory name].

In addition, the generator adds the -Dmaven.local.repo=/deployments/[directory name] in the JAVA_OPTIONS. That is required for the server to retrieve JBoss modules artifacts. NB: In order for this part to work properly we need a fix for https://github.com/eclipse/jkube/issues/384

### Info

* Eclipse JKube version :1.0.0

**Comment by manusa** [comment]
Hi @jfdenise 
#384 has been closed via #395.
Besides the aforementioned option, it would be nice to include the `-Djava.net.preferIPv4Stack=true` option too, so that project using the plugin don't need to manually add this.

**Comment by manusa** [comment]
Implemented in #398
