### ISSUE TITLE
Evolve WildFly Bootable JAR quickstart with support for slim server

### ISSUE THREAD

**Issue by jfdenise** [eclipse/jkube#399]
### Description
Evolve the existing quickstart once a release of JKube integrates the support.

**Comment by manusa** [comment]
As agreed in https://github.com/eclipse/jkube/issues/441#issuecomment-712753953

The plan is to create an additional example `wildfly-jar-slim` based on https://github.com/wildfly-extras/wildfly-jar-maven-plugin/blob/master/examples/slim/pom.xml
