### ISSUE TITLE
ConfigMap can't handle directory

### ISSUE THREAD

**Issue by Danipiario** [eclipse/jkube#405]
### Description
JKube can handle only file and not directory.
With kubernetes you can specify both file and directory with --from-file parameter. 

### Info

* Eclipse JKube version : 1.0.0
* Maven version (`mvn -v`) :  3.6.3
```

```
* Kubernetes / Red Hat OpenShift setup and version : 

* If it's a bug, how to reproduce :

* If it's a feature request, what is your use case :
When you have a directory with many files and you can't/won't specify all file names inside a custom yaml configuration
it would be better to have the possibility to specify only a directory inside yaml (with annotation) and having all regular files picked inside configmap with filename for key and content file for value

* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
Seems related to #249

**Comment by Danipiario** [comment]
#249 is related to multiple configmap, this request is for ability to handle directory like file.
The class is the same but IMO functionalities are different

**Comment by rohanKanojia** [comment]
ohk, Sorry. Seems like I misunderstood that each file would create it's own configmap.

**Comment by Danipiario** [comment]
Ah ok, I understand your point of view. 
I would like to have a functionality closest to kubernetes cli so one configmap with one key every regular file under the directory.
