### ISSUE TITLE
Recreate mode not honored

### ISSUE THREAD

**Issue by Danipiario** [eclipse/jkube#407]
### Description
Specify `<recreate>true</recreate>` inside configuration doesn't work when run k8s:apply task.
I've noticed that inside class `org.eclipse.jkube.maven.plugin.mojo.build.ApplyMojo` in method `executeInternal` is missing the set of the property when initializing `ApplyService`. Modify the code and building the plugin fix the error.

### Info

* Eclipse JKube version : 1.0.0
* Maven version (`mvn -v`) : 3.6.3
```

```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :

* If it's a feature request, what is your use case :

* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
@Danipiario : Would you like to submit a quick PR to fix this?
