### ISSUE TITLE
Upgrade quickstart to use WildFly JAR 2 Final release.

### ISSUE THREAD

**Issue by jfdenise** [eclipse/jkube#441]
### Description
We are still using a Beta release, need to upgrade to latest final release.

**Comment by manusa** [comment]
How does this one relate to #399

**Comment by jfdenise** [comment]
@manusa , I am thinking that #399 could be closed actually. This is an advanced usage of the plugin, not 100% sure that we should show it in the simplest quickstart. We have an example for it in https://github.com/wildfly-extras/wildfly-jar-maven-plugin/blob/master/examples/slim/pom.xml

**Comment by manusa** [comment]
Maybe we can create an additional example `wildfly-jar-slim` in our repo too (we have similar approaches for the other frameworks)

**Comment by jfdenise** [comment]
Yes, that would be great. Ok.
