### ISSUE TITLE
Simplify assertions in GoTimeUtilTest

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#461]
### Description

Right now Sonar is reporting some uses of assertj as code smells[0] in `GoTimeUtilTest#testConvertsion()` and `GoTimeUtilTest#testEmpty()`.

https://github.com/eclipse/jkube/blob/cb6801ce317901d34d6d9a60b3b626cb40a87da2/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/GoTimeUtilTest.java#L40-L49

Maybe we can try to refactor them so that Sonar doesn't detect them as code smell. To me this looks more readable than previous version:

```java
            assertEquals(expectations.get(i).intValue(), result.get().intValue());
        }
    }

    @Test
    public void testEmpty() {
        assertEquals(Optional.empty(), GoTimeUtil.durationSeconds(null));
        assertEquals(Optional.empty(), GoTimeUtil.durationSeconds(""));
        assertEquals(Optional.empty(), GoTimeUtil.durationSeconds(" "));
    }
```

[0] https://sonarcloud.io/project/issues?fileUuids=AXGmF2xZ7hhEzz-4P4Dn&id=jkubeio_jkube&open=AXM3qTkG2oiEP4VmGSai&resolved=false

**Comment by manusa** [comment]
Those tests need to be separated too.

> ...To me this looks more readable than previous version:

I find assertj tests more readable, and escalable. For this case it really doesn't matter.
