### ISSUE TITLE
Refactor occurrences across codebase to use isEmpty() 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#462]
### Description

I've seen some places across code where we explicitly compare a collection's `size() == 0` which is reported as a code smell by sonar, see full report here[0]. I think we should refactor these places to use `isEmpty()` instead:

- [ ] [ContainerTracker.java](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/ContainerTracker.java#L133)
- [ ] [ContainerCreateConfig](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerCreateConfig.java#L112)
- [ ] [ContainerHostConfig.java](https://github.com/eclipse/jkube/blob/master/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerHostConfig.java#L120)
- [ ] [EnvUtil.java](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java#L287)
- [ ] [OpenshiftHelper.java](https://github.com/eclipse/jkube/blob/master/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/OpenshiftHelper.java#L149)
- [ ] [ImageName.java](https://github.com/eclipse/jkube/blob/master/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java#L260)
- [ ] [MainClassDetector.java](https://github.com/eclipse/jkube/blob/master/jkube-kit/generator/java-exec/src/main/java/org/eclipse/jkube/generator/javaexec/MainClassDetector.java#L47)

[0] https://sonarcloud.io/project/issues?id=jkubeio_jkube&open=AW3z0M3CL3SSO-VMZS3n&resolved=false

**Comment by dengliming** [comment]
Hello~, I'd love to take this as first contribution for this repo.

**Comment by rohanKanojia** [comment]
@dengliming : cool, Thanks a lot! Just one minor note: This project is not participating in Hacktoberfest.
