### ISSUE TITLE
Replace usage of `java.net.URL` with `java.net.URI` in DependencyEnricher

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#469]
### Description

Right now we seem to be using `java.net.URL` in `DependencyEnricher` like this:
https://github.com/eclipse/jkube/blob/90439cb98fef038e8c991825d2a90ce414787fb6/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/DependencyEnricher.java#L58-L60

Sonar marks this as a code smell since we don't seem to be using `URL` specific functionality(like resolving hostname via DNS lookup) and `URI` can be used as a better and faster alternative. Check this Sonar rule on how to fix this[1]

[0] https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AXCb0VIMych7Ocxsbwim&open=AXCb0VIMych7Ocxsbwim
[1] https://sonarcloud.io/organizations/jkubeio/rules?open=java%3AS2112&rule_key=java%3AS2112

**Comment by manusa** [comment]
This one is not that straightforward and may have additional consequences.

Any implementation should add coverage to the complete class.

2 commits required, first should add coverage, second should perform the URL to URI refactor.

**Comment by maycap123** [comment]
I would like to try this

**Comment by manusa** [comment]
Fixed in #860
