### ISSUE TITLE
Refactor tests in `KeyStoreUtilTest` to avoid duplication

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#472]
### Description

We have these three tests in `KeyStoreUtilTest` which seem to be doing the same task but with different input values.

https://github.com/eclipse/jkube/blob/90439cb98fef038e8c991825d2a90ce414787fb6/jkube-kit/build/service/docker/src/test/java/org/eclipse/jkube/kit/build/service/docker/access/KeyStoreUtilTest.java#L46-L63

We should move this common logic into some a helper method and make tests call that method instead.

**Comment by deepak-gittyup** [comment]
Hi Rohan,
I am a newbie to open-source and would like to start with this project  
Can I pick this up ?

**Comment by rohanKanojia** [comment]
sure, feel free to pick this up.

**Comment by deepak-gittyup** [comment]
Hi,
I think I made the necessary changes to address this task and opened a PR request: https://github.com/eclipse/jkube/pull/476
It looks like, it failed 2 checks and I don't quite understand what to do next here
Can you help me out over here ?

**Comment by rohanKanojia** [comment]
@deepak-gittyup : You need to create an Eclipse Account and sign Eclipse Contributor Agreement[0] in order to contribute to any Eclipse Foundation project

[0] https://www.eclipse.org/legal/ECA.php
