### ISSUE TITLE
cacheFrom configuration parameter is missing

### ISSUE THREAD

**Issue by edrandall** [eclipse/jkube#484]
### Info

* Eclipse JKube version : 1.0.2
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/apache-maven-3.6.3
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```
* Kubernetes / Red Hat OpenShift setup and version :
```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
features: Basic-Auth

Server https://**REDACTED**:8443
openshift v3.11.69
kubernetes v1.11.0+d4cacc0
```

* If it's a bug, how to reproduce :
Migrated an existing working io.fabric8:fabric8-maven-plugin:4.4.1 configuration to org.eclipse.jkube:kubernetes-maven-plugin:1.0.2
Build configuration contains
```
							<configuration>
								<images>
									<image>
										<build>
											<cacheFrom>${image.cache-from.uri}</cacheFrom>
```

mvn install results in this error:
```
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.0.2:build (container-build) on project **REDACTED**-builder: Unable to parse configuration of mojo org.eclipse.jkube:kubernetes-maven-plugin:1.0.2:build for parameter cacheFrom: Cannot find 'cacheFrom' in class org.eclipse.jkube.kit.config.image.build.BuildConfiguration -> [Help 1]
```

The cacheFrom config element is described in jKube documentation at: https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#config-image
and was described in in fabric8-maven-plugin at: https://maven.fabric8.io/#config-image-build
However it seems to be absent from BuildConfiguration.java.

* If it's a feature request, what is your use case :
It's a defect, not a feature request, but the use-case is, when building within a per-job docker-tooling-container environment, such as GitLab docker-in-docker, there is no local docker cache containing prior builds of the same image.  Therefore it's necessary to "seed" the cache with the last-known good build from the main repository (a separate step in the gitlab pipeline) and then use "cacheFrom" to instruct fabric8/jkube/docker to use that image as a source of prior layers - this improves performance a great deal.

* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
ah, sorry for the inconvenience caused. We'll fix this.

**Comment by manusa** [comment]
Thx for reporting
