### ISSUE TITLE
<filter> with placeholders in Dockerfile is broken

### ISSUE THREAD

**Issue by edrandall** [eclipse/jkube#485]
### Info

* Eclipse JKube version : 1.0.2
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/apache-maven-3.6.3
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```
* Kubernetes / Red Hat OpenShift setup and version :
```
oc v3.11.0+0cbc58b
kubernetes v1.11.0+d4cacc0
```

* If it's a bug, how to reproduce :
It should be possible to use maven properties denoted by ${propertyname} within a Dockerfile (default \<filter\> feature)
Default configuration element\<filter\> delimiter is used, ie. ${*} 

For example, in maven pom.xml:
```
	<properties>
		<rev.rhel-atomic>7.8-367</rev.rhel-atomic>
		<project.base-image.uri>registry.access.redhat.com/rhel7-atomic:${rev.rhel-atomic}</project.base-image.uri>
```

In Dockerfile:
```
FROM ${project.base-image.uri} AS BUILDER
```

This works just fine with fabric8-maven-plugin;  Having switched to JKube, the filtering is clearly not happening:
```
[INFO] --- kubernetes-maven-plugin:1.0.2:build (image-build) @ myproject-builder ---
[INFO] k8s: Running in Kubernetes mode
[INFO] k8s: Building Docker image in Kubernetes mode
[INFO] k8s: Generators:
[INFO] k8s:  - quarkus
[INFO] k8s:  - spring-boot
[INFO] k8s:  - wildfly-swarm
[INFO] k8s:  - thorntail-v2
[INFO] k8s:  - wildfly-jar
[INFO] k8s:  - openliberty
[INFO] k8s:  - karaf
[INFO] k8s:  - vertx
[INFO] k8s:  - java-exec
[INFO] k8s:  - webapp
[ERROR] k8s: Failed to execute the build [Error while trying to build the image: Unable to check image [${project.base-image.uri}] : {"message":"no such image: ${project.base-image.uri}: invalid reference format"} (Bad Request: 400)]
```

* If it's a feature request, what is your use case :

* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
Does it work when you explicitly provide `<filter>`(`jkube.image.filter`) element for this ` <filter>${*}</filter>`?

**Comment by manusa** [comment]
> Does it work when you explicitly provide `<filter>`(`jkube.image.filter`) element for this ` <filter>${*}</filter>`?

I thought we left this one as the default, didn't we?

- #271

**Comment by edrandall** [comment]
@rohanKanojia could you be more specific, I don't quite understand the question.  `<filter>` is used when one wishes to change the default token delimiters and I only mentioned it because we are using the default setting, ie. we have  no  `<filter>` element in the pom configuration.  We are using `${variablename}` placeholders in our Dockerfile, which worked fine as-is under fmp.
