### ISSUE TITLE
Typo in demanded Filenames: "persisteMtvolumeclaim" instead of "persisteNtvolumeclaim"

### ISSUE THREAD

**Issue by mad6300** [eclipse/jkube#486]
### Info

* Eclipse JKube version : 1.0.1 Maven Plugin
* Maven version (`mvn -v`) : 3.6.3

I am using the JKube kubernetes-maven-plugin 1.0.1 with maven 3.6.3.
I want to deploy minio. Following https://github.com/kubernetes/examples/tree/master/staging/storage/minio

using the yaml files there I run in to this Error below.

the error asks for a file named persistemtvolumeclaim instead of persistentvolumeclaim.

renaming the file with the typo it works.

> [ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.0.1:resource (deploy-minio) on project isp-script: Execution deploy-minio of goal org.eclipse.jkube:kubernetes-maven-plugin:1.0.1:resource failed: Unknown type 'persistentVolumeClaim' for file isp-minio-persistentVolumeClaim.yaml. Must be one of : pr, lr, pv, project, replicaset, cronjob, ds, statefulset, clusterrolebinding, pvc, limitrange, imagestreamtag, replicationcontroller, is, rb, rc, ingress, route, projectrequest, job, rolebinding, rq, template, serviceaccount, bc, rs, rbr, role, pod, oauthclient, ns, resourcequota, secret, persistemtvolumeclaim, istag, customerresourcedefinition, sa, persistentvolume, crb, clusterrb, crd, deploymentconfig, configmap, deployment, imagestream, svc, rolebindingrestriction, cj, cm, buildconfig, daemonset, cr, crole, pb, clusterrole, pd, policybinding, service, namespace, dc -> [Help 1]

**Comment by rohanKanojia** [comment]
@ mad6300 : Thanks a lot for reporting this. Could you please submit a PR to fix this issue?

**Comment by mad6300** [comment]
@rohanKanojia will look into it

**Comment by rohanKanojia** [comment]
@mad6300 : Thanks a lot! Feel free to reach out to us for help on our gitter channel if you face any problems
