### ISSUE TITLE
jkube.enricher.jkube-controller.replicaCount cannot be set to 0

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#488]
### Description

When using the `jkube.enricher.jkube-controller.replicaCount` or enricher XML configuration element, 0 is not supported.

In order to allow 0 as a value on the property, the following XML configuration is required:
```xml
<plugin>
 <groupId>org.eclipse.jkube</groupId>
 <artifactId>openshift-maven-plugin</artifactId>
 <version>${jkube.version}</version>
 <configuration>
   <resources>
     <replicas>0</replicas>
   </resources>
 </configuration>
</plugin>
```

The problem seems to be this default value:
https://github.com/eclipse/jkube/blob/e11392a64b1f63ae64c9082e6a4dd9dad2bf420d/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java#L74

### Info

* Eclipse JKube version: 1.0.2

**Comment by manusa** [comment]
https://github.com/eclipse/jkube/blob/aa8d431bca1ad8031138fbc80b88dc960d75f230/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/BaseEnricher.java#L177

**Comment by rohanKanojia** [comment]
Hi, I'm not able to reproduce this issue. I tested on v1.0.2 and this seems to work as expected for me. I've tested it on my sample:
https://github.com/rohanKanojia/eclipse-jkube-demo-project . It just has basic zero configuration option like this:
```xml
            <plugin>
                <groupId>org.eclipse.jkube</groupId>
                <artifactId>openshift-maven-plugin</artifactId>
                <version>${jkube.version}</version>
            </plugin>
```

Here is what I did.

1. Deployed application using standard goals `mvn oc:build oc:resource oc:apply`. Application gets deployed:
```
jkube : $ oc get pods -w
NAME                           READY     STATUS      RESTARTS   AGE
random-generator-1-4d64q       1/1       Running     0          58s
random-generator-s2i-1-build   0/1       Completed   0          1m
```
2. Issue Stop Equivalent: `mvn oc:resource oc:apply -Djkube.enricher.jkube-controller.replicaCount=0` . Application Pod gets terminated:
```
jkube : $ oc get pods -w
NAME                           READY     STATUS      RESTARTS   AGE
random-generator-1-4d64q       1/1       Running     0          58s
random-generator-s2i-1-build   0/1       Completed   0          1m
random-generator-1-4d64q   1/1       Terminating   0         1m
random-generator-1-4d64q   0/1       Terminating   0         2m
random-generator-1-4d64q   0/1       Terminating   0         2m
random-generator-1-4d64q   0/1       Terminating   0         2m
```
3. Issue Start Equivalent: `mvn oc:resource oc:apply -Djkube.enricher.jkube-controller.replicaCount=1` . Application Pod gets created:
```
jkube : $ oc get pods -w
NAME                           READY     STATUS      RESTARTS   AGE
random-generator-1-4d64q       1/1       Running     0          58s
random-generator-s2i-1-build   0/1       Completed   0          1m
random-generator-1-4d64q   1/1       Terminating   0         1m
random-generator-1-4d64q   0/1       Terminating   0         2m
random-generator-1-4d64q   0/1       Terminating   0         2m
random-generator-1-4d64q   0/1       Terminating   0         2m
random-generator-1-l8x4w   0/1       Pending   0         0s
random-generator-1-l8x4w   0/1       Pending   0         0s
random-generator-1-l8x4w   0/1       ContainerCreating   0         0s
random-generator-1-l8x4w   0/1       Running   0         4s
random-generator-1-l8x4w   1/1       Running   0         20s
```

**Comment by manusa** [comment]
hmm, that's weird, I can't reproduce either with your project.
I'll check better later.

**Comment by manusa** [comment]
Issue is reproducible with spring-boot quickstart (I'm guessing because there is a `<resources>` XML element configuration)

**Comment by rohanKanojia** [comment]
ohk, let me check why it's not working as expected.

**Comment by manusa** [comment]
The problem is what I reported on the issue. Nevermind, I already started working on the fix
