### ISSUE TITLE
jkube-website: Create CI publishing automation script

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#51]
## Description

As a JKube project maintainer I need a CI script to automatically publish updates to [jkubeio/jkube-website](https://github.com/jkubeio/jkube-website).

The script builds the Gatsby project and copies the generated static files to the main root of the repo ([https://git.eclipse.org/.../jkube](https://git.eclipse.org/r/#/admin/projects/www.eclipse.org/jkube)) project in the master branch.

The script performs the following tasks;

1. `git clone <gerrit-url> gerrit-website-repository/`
1. `rm -rf gerrit-website-repository/!(.git)`
1. `npm install && npm run build`
1. `cp -avr public/* gerrit-website-repository/`
1. `cd gerrit-website-repository`
1. `git add .`
1. `git commit -m "CI website update"`
1. `git push origin master`

## AC

- [x] Script is stored in the following repo [jkubeio/jkube-website](https://github.com/jkubeio/jkube-website)
- ~CI Task can be run from jenkins ([ci.eclipse.org](https://ci.eclipse.org/jkube/))~
- [x] CI Task can be run from GitHub actions on tag

**Comment by rohanKanojia** [comment]
I remember I tried adding a jenkins pipeline with `eclipse-jkube-bot` github credentials but it doesn't work with it. We would need keys of some maintainer

**Comment by manusa** [comment]
We have 2 options then:
- Try to give push privileges to `eclipse-jkube-bot` -> will probably need webmaster to do that -> `group ldap/ecd.jkube` (Preferred)
- CI should at least create a patch that can then be reviewed by one of the maintainers. (backup plan)

More info: https://gerrit-review.googlesource.com/Documentation/intro-gerrit-walkthrough-github.html

**Comment by manusa** [comment]
Website is automatically deployed when a tag is pushed to the repo:

https://github.com/jkubeio/jkube-website/actions/runs/45583281
