### ISSUE TITLE
Update OpenShift Maven Plugin Compatibility Matrix for Openshift 4.5 and 4.6 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#510]
OpenShift 4.6 was GA-ed a month ago[0]. Has anyone tried out OpenShift Maven Plugin on Red Hat OpenShift 4.6? 

Eclipse JKube's Compatibility with OpenShift 4.6 was asked by a user. Although there hasn't been any breaking change user wise from 4.4 to 4.6 so I don't expect any problems for any user using OpenShift Maven Plugin on OpenShift 4.6. Anyway, We need to update the compatibility matrix[0] as per the latest OpenShift versions.

[0] https://www.openshift.com/blog/red-hat-openshift-4.6-is-now-available
[1] https://www.eclipse.org/jkube/docs/openshift-maven-plugin#openshift-compatibility

**Comment by manusa** [comment]
In order to make sure things work, deploy a local CRC cluster with OCP 4.6 and run tests for OpenShift in https://github.com/jkubeio/jkube-integration-tests/

```shell
### Every framework
$ ./mvnw -B -POpenShift verify -Djkube.version="$JKUBE_VERSION" -Djunit.jupiter.execution.parallel.config.fixed.parallelism=4
## Or by profile ('quarkus','springboot','webapp','other')
$ ./mvnw -B -POpenShift,quarkus verify -Djkube.version="$JKUBE_VERSION" -Djunit.jupiter.execution.parallel.config.fixed.parallelism=4
```

**Comment by rohanKanojia** [comment]
I've run integration tests on these versions of Crc profile-wise with Eclipse JKube v1.0.2 and 1.1.0-SNAPSHOT(master) and it seems to be running okay:
:heavy_check_mark: Crc 1.17.0 / OpenShift 4.5.14
:heavy_check_mark: Crc 1.21.0 / OpenShift 4.6.9

I'm updating the compatibility matrix now
