### ISSUE TITLE
Use `java.util.function.Function` instead of Guava's `com.google.common.base.Function`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#546]
Since we're already on JDK8 we can refactor these places to use `java.util.function.Function` instead. As pointed by Sonar[0], we should use native Java 8 features instead of guava. You can use this `grep` to find all the occurrences of guava's Function:
```bash
jkube : $ git grep -in "com.google.common.base.Function"
jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/ValueProvider.java:129:    public <T> T getObject(ConfigKey key, T fromConfig, final com.google.common.base.Function<String, T> converter) {
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java:16:import com.google.common.base.Function;
jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/ProcessUtil.java:16:import com.google.common.base.Function;
```

[0] https://sonarcloud.io/organizations/jkubeio/rules?open=java%3AS4738&rule_key=java%3AS4738

**Comment by abhijeetshuklaoist** [comment]
@rohanKanojia Is it okay of I work on this? If yes, could you please assign it to me.

**Comment by rohanKanojia** [comment]
@abhijeetshuklaoist : I'm assigning it to you. Thanks a lot!

**Comment by abhijeetshuklaoist** [comment]
Raised PR https://github.com/eclipse/jkube/pull/559
