### ISSUE TITLE
Define property for skipping cluster autodetect mode and go straight to the Kubernetes offline mode 

### ISSUE THREAD

**Issue by nightswimmings** [eclipse/jkube#548]
It would be nice if we could tell JKube to work offline on resources and push goals at least, 
so it skips the cluster autodetect mode, which can fail with ugly stacktraces if the  environment has a cluster but semiconfigured (for instant the aws credentials), and go straight to Kubernetes mode like the regular fallback does.
This prevents any unwanted interaction with the local cluster
  

Thanks mates!

**Comment by rohanKanojia** [comment]
Are you referring to this stacktrace:
```
[WARNING] k8s: Cannot access cluster for detecting mode: Unknown host kubernetes.default.svc: Name or service not known
```
This seems to be coming from here 
https://github.com/eclipse/jkube/blob/b7335940a71fe16581773da51f3d1b08f2050793/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/JKubeServiceHub.java#L96-L100

If we wrap this client initialization in an if-else block we should be able to get rid of these warnings
```java
if (shallConnectToK8sCluster) { 
  this.client = clusterAccess.createDefaultClient(); 
}
```
