### ISSUE TITLE
Document the usage of IngressEnricher

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#549]
### Description
`IngressEnricher` is lacking documentation.
Provide documentation for all configuration modes, and flags.

Relates to:
- #231
- #512
- https://github.com/fabric8io/fabric8-maven-plugin/issues/1813

**Comment by rohanKanojia** [comment]
We seem to have Ingress Generation related documentation https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#ingress-generation which was added inhttps://github.com/eclipse/jkube/pull/674
