### ISSUE TITLE
Upgrade Sonar CircleCI job to Java 11

### ISSUE THREAD

**Issue by ohbus** [eclipse/jkube#558]
Hi,

Is there any roadmap for this project to bump support to `JDK 11`.

I have been studying this project for a few days and found out that this Project is using [SonarCloud](https://sonarcloud.io/dashboard?id=jkubeio_jkube&branch=master) for Static Code analysis.
SonarCloud is set to **[phase out](https://sonarcloud.io/documentation/appendices/end-of-support/)** `JDK 8` support in favour of `JDK 11` **1st February, 2021.**

</br>

I will be very keen to help migrate this project to JDK 11 along with the GitHub Actions pipelines as well.

**Comment by abhijeetshuklaoist** [comment]
@ohbus  Jdk8 support is ending very soon i.e. on 1st Feb, 2021. So I believe we should increase the priority of this one to at least P2. 
WDYT?

**Comment by abhijeetshuklaoist** [comment]
@ohbus Let's take this up. I will be happy to work on this with you.

**Comment by manusa** [comment]
Hi, thx for reporting.
What needs to be fixed is the base Java version of these two jobs:
 - [Sonar](https://github.com/eclipse/jkube/blob/7107c0ce2f852b00c3570e94c5e35a8d21e207c6/.circleci/config.yml#L65)
 - [Sonar PR](https://github.com/eclipse/jkube/blob/7107c0ce2f852b00c3570e94c5e35a8d21e207c6/.circleci/config.yml#L78)
Feel free to open a PR with these changes ;)

**Comment by ohbus** [comment]
You can assign this issue to me.

**Comment by ohbus** [comment]
Why are we still using CircleCI which has got limited resources when we can move these jobs to GitHub Actions?
