### ISSUE TITLE
Replace usages of deprecated `org.apache.commons.text.StrSubstitutor` 

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#571]
We are using `StrSubstitutor` from apache commons-lang at these places. But according to documentation[0], it's been marked as deprecated:

https://github.com/eclipse/jkube/blob/a70b19b6776f4e0c570053cc38913e031db4b0df/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/WaitService.java#L150

https://github.com/eclipse/jkube/blob/a70b19b6776f4e0c570053cc38913e031db4b0df/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/ContainerCreateConfig.java#L90

We should replace it with `org.apache.commons.text.StringSubstitutor`[1] instead.

[0] https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/text/StrSubstitutor.html
[1] https://commons.apache.org/proper/commons-text/javadocs/api-release/org/apache/commons/text/StringSubstitutor.html

**Comment by theexplorist** [comment]
@rohanKanojia Hi rohan, please assign me this issue, will be sending the PR today itself.
Thank you

**Comment by rohanKanojia** [comment]
@theexplorist : Hi Kartik, welcome back!

**Comment by theexplorist** [comment]
@rohanKanojia Thank you, rohan! I am seeing to be a long time contributor here.
#611  All check are passed in this PR except eclipse even when i registered with it!
Please review!
