### ISSUE TITLE
Enhancement: add support to packaging and publishing helm chart

### ISSUE THREAD

**Issue by yaakov-berkovitch** [eclipse/jkube#576]
### Description
JKube doesn't support packaging and publishing  charts. It may be very useful to include those functionalities and so to avoid using additional maven plugin for this.

### Info

* If it's a feature request, what is your use case :
Add support for packaging and publishing helm chart.

**Comment by dloiacono** [comment]
I can do that

**Comment by manusa** [comment]
As agreed in the sync meeting, it would be good to implement this in similar way as [Helm Maven Plugin](https://github.com/kiwigrid/helm-maven-plugin) does it  via REST API.

We would be looking to implement the core logic in this package|module: https://github.com/eclipse/jkube/tree/master/jkube-kit/resource/helm/src/main/java/org/eclipse/jkube/kit/resource/helm

The implemented service should be then consumed by the HelmMojo and the future Gradle plugins.
