### ISSUE TITLE
Helm Chart within .tar.gz not deployable due to base directory error

### ISSUE THREAD

**Issue by vecima** [eclipse/jkube#587]
### Description
I can't deploy a helm chart from a .tar.gz generated by the k8s:helm goal. I've tried both the project I'm working on as well as the spring-boot-helm quickstart project and both produce .tar.gz files that look ok, but produce the error:

Error: chart illegally contains content outside the base directory: "Chart.yaml"

I'm not sure but I think this might be because helm install is expecting the files to be within a directory inside the .tar.gz file.

### Info

* Operating System: Windows 10 (Also tried with Ubuntu through WSL2)
* Eclipse JKube version : 1.1.1
* Java version: openjdk version "1.8.0_282"
* Maven version (`mvn -v`) : 3.6.3
* Kubernetes / Red Hat OpenShift setup and version :
k3d version v4.2.0
k3s version v1.20.2-k3s1 (default)

* If it's a bug, how to reproduce :
in the spring-boot-helm quickstart project run:
mvn k8s:resource k8s:helm -Pkubernetes
then run:
helm install spring-boot-helm target/spring-boot-helm-1.1.1-helm.tar.gz

* Sample Reproducer Project : https://github.com/eclipse/jkube.git

**Comment by manusa** [comment]
Relates to:
- https://github.com/helm/helm/issues/5552
- -https://github.com/helm/helm/pull/5610

> all contents of a packaged chart are expected to be in a base directory matching the chart's name
