### ISSUE TITLE
KubernetesClientException: Namespace mismatch error when specifying namespace in configuration

### ISSUE THREAD

**Issue by dzagagnoni** [eclipse/jkube#599]
### Info

* Eclipse JKube version : 1.1.1
* Maven version (`mvn -v`) : Apache Maven 3.6.3
```

```
* Kubernetes : v1.19.3 on Windows 10 with Docker Desktop

* If it's a bug, how to reproduce : mvn clean package k8s:deploy or k8s:apply

* If it's a feature request, what is your use case :

* Sample Reproducer Project : *[GitHub Clone URL]*

In my pom.xml I put namespace tag under my configuration, like this:

```
<plugins>
<plugin>
<groupId>org.eclipse.jkube</groupId>
<artifactId>kubernetes-maven-plugin</artifactId>
<version>${jkube.version}</version>
<configuration>
<verbose>true</verbose>
<namespace>mynamespace</namespace>
...
```

And this is the stacktrace:

There is the stacktrace:
[INFO] k8s: Using Kubernetes at https://kubernetes.docker.internal:6443/ in namespace default with manifest C:\Users\D.Zagagnoni\Workspaces\myservice\target\classes\META-INF\jkube\kubernetes.yml
[INFO] k8s: Creating a Service from kubernetes.yml namespace default name myservice
[ERROR] k8s: Failed to create Service from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Namespace mismatch. Item namespace:mynamespace. Operation namespace:default.

Thanks for the support to @rohanKanojia

**Comment by rohanKanojia** [comment]
What's strange is that `jkube.namespace` property seems to work fine but when we specify namespace in configuration like mentioned above, it throws this error

**Comment by dzagagnoni** [comment]
In fact for the moment I solved it by inserting the property as you suggest. Thanks for the support

**Comment by manusa** [comment]
Before #586 Namespace was read using properties in the service layer (#570 #582).

Are we sure this issue is still present in master?

**Comment by rohanKanojia** [comment]
Looks like this issue is not present in master. I'm not able to reproduce this with 1.2.0-SNAPSHOT

**Comment by manusa** [comment]
Should we close this then?

**Comment by manusa** [comment]
To be closed after 1.2.0 release.

**Comment by manusa** [comment]
Hi @dzagagnoni 
Could you please confirm that the issue is no longer present in the newer release ([1.2.0](https://github.com/eclipse/jkube/releases/tag/v1.2.0))?

**Comment by dzagagnoni** [comment]
Yes, I confirm! Thanks for the support!
