### ISSUE TITLE
Create (PVC) volume by xml mode

### ISSUE THREAD

**Issue by Christian-dev-ops** [eclipse/jkube#600]
### Description
Currently you can only create a persistent volume claim for fragments.
I propose that you can create the (pvc) and configure the deployment using xml mode. It would be necessary for both options to be independent, since it is possible that we only need to connect to a previously created pvc.

**Comment by manusa** [comment]
Could you please provide a sample of the expected YAML you'd like to be generated as a result of this XML based config?

**Comment by Christian-dev-ops** [comment]
Case 1 (Create PVC and deployment config):

deployment.yml:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - env:
        - name: spring.cloud.config.uri
          value: http://xxxx.xxx
        - name: spring.cloud.config.enabled
          value: "true"
        - name: spring.cloud.config.profile
          value: xxxx
        - name: spring.cloud.config.username
          value: xxxx
        - name: spring.cloud.config.password
          value: xxxxx
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: XXXX:0.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: productos-app1
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
        **volumeMounts:
        - mountPath: /pdfs
          name: volumen-pdf
      volumes:
      - name: volumen-pdf
        persistentVolumeClaim:
          claimName: pdfdirectorio**

Properties to add to xml config: 

- volumes.name
- persistentVolumeClaim.claimName
- volumeMounts.mountPath
- volumeMounts.name

pdfdirectorio-persistemtvolumeclaim.yml:

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: app1
  name: pdfdirectorio
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      **storage: 1Gi
  storageClassName: standard**

Properties to add to xml config: 

- name
- storage
- accessModes
- storageClassName

Case 2 (Creating an Additional deployment to Reference the Same PVC):

deployment.yml:

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - env:
        - name: spring.cloud.config.uri
          value: http://xxxx.xxx
        - name: spring.cloud.config.enabled
          value: "true"
        - name: spring.cloud.config.profile
          value: xxxx
        - name: spring.cloud.config.username
          value: xxxx
        - name: spring.cloud.config.password
          value: xxxxx
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: XXXX:0.0.1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: productos-app2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false
        **volumeMounts:
        - mountPath: /pdfs
          name: volumen-pdf2
      volumes:
      - name: volumen-pdf2
        persistentVolumeClaim:
          claimName: pdfdirectorio**

Properties to add to xml config: 

- volumes.name
- persistentVolumeClaim.claimName
- volumeMounts.mountPath
- volumeMounts.name

**Comment by manusa** [comment]
So for the Deployment part, current version should already work, just configure your volume as follows:
```xml
  <plugin>
    <groupId>org.eclipse.jkube</groupId>
    <artifactId>kubernetes-maven-plugin</artifactId>
    <configuration>
      <resources>
            <volumes>
              <volume>
                <name>volumen-pdf2</name>
                <type>persistentVolumeClaim</type>
                <claimRef>pdfdirectorio**</claimRef>
                <mounts>
                  <mount>/pdfs</mount>
                </mounts>
              </volume>
            </volumes>
      </resources>
    </configuration>
  </plugin>
```

So if I'm not mistaken, we're only missing the feature to create Persistent Volume Claims from XML.

The other part (creating an extra deployment -> 2 opinionated deployments for a single project), I'm not sure we can implement that.

**Comment by Christian-dev-ops** [comment]
ok thanks, but it doesn't work if you use a yml fragments together xml config like this example: 

deployment.yml:

spec:
 template:
   spec:
     containers:
       - env:
         - name: spring.cloud.config.uri
           value: http://xxxx.xxx
         - name: spring.cloud.config.enabled
           value: true
         - name: spring.cloud.config.profile
           value: xxx
         - name: spring.cloud.config.username
           value: xxxx
         - name: spring.cloud.config.password
           value: xxxx

pom.xml:

<plugin>
				<groupId>org.eclipse.jkube</groupId>
				<artifactId>kubernetes-maven-plugin</artifactId>
				<version>1.0.2</version>
				<configuration>
					<images>
						<image>
							<name>XXX/%a:%v</name>
							<build>
								<from>redhat/XXX:XXX</from>
								<tags>
									<tag>latest</tag>
									<tag>${project.version}</tag>
								</tags>
								<ports>
									<port>8080</port>
								</ports>
								<entryPoint>
									
									<exec>
										<arg>java</arg>
										<arg>-jar</arg>
										<arg>/deployments/${project.artifactId}-${project.version}.jar</arg>
									</exec>
								</entryPoint>
								<assembly>
									<targetDir>/deployments</targetDir>
									<inline>
										<fileSets>
											<fileSet>
												<directory>${project.build.directory}/deployments</directory>
											</fileSet>
										</fileSets>
									</inline>
								</assembly>
							</build>
						</image>
					</images>
					<resources>
						<volumes>
							<volume>
								<name>volumen-pdf2</name>
								<type>persistentVolumeClaim</type>
								<claimRef>pdfdirectorio**</claimRef>
								<mounts>
									<mount>/pdfs</mount>
								</mounts>
							</volume>
						</volumes>
					</resources>
					<enricher>
						<config>
							<jkube-service>
								<type>LoadBalancer</type>
							</jkube-service>
						</config>
					</enricher>
				</configuration>
			</plugin>

The result is:

kind: Deployment
......    
      spec:
      containers:
      - env:
        - name: spring.cloud.config.uri
          value: http://xxxx.xxx
        - name: spring.cloud.config.enabled
          value: "true"
        - name: spring.cloud.config.profile
          value: xx
        - name: spring.cloud.config.username
          value: xx
        - name: spring.cloud.config.password
          value: xxx
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        image: xxx/xx/xx:xxx
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 180
          successThreshold: 1
        name: xxxxx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 10
          successThreshold: 1
        securityContext:
          privileged: false

**without volume setting**

**Comment by manusa** [comment]
So you're providing a YAML fragment for deployment + XML config. Why not use one or (XOR) the other?

I guess there are merging issues, we'll investigate that too. But I really feel it's not the best approach to spread your config into different files.

**Comment by Christian-dev-ops** [comment]
ok, we will create the pvc via YAML fragment like a template and using "sed command"

**Comment by manusa** [comment]
> ok, we will create the pvc via YAML fragment like a template and using "sed command"

What do you mean by "sed command", you're aware that Maven properties are interpolated in your YAML fragments, right?

**Comment by Christian-dev-ops** [comment]
We have the code that merges the needs we need such as:

deployment.yaml:

spec:
 template:
   spec:
     containers:
       - env:
         - name: spring.cloud.config.uri
           value: xxx
         - name: spring.cloud.config.enabled
           value: true
         - name: spring.cloud.config.profile
           value: beta
         - name: spring.cloud.config.username
           value: xxx
         - name: spring.cloud.config.password
           value: xxx
         imagePullPolicy: Always
         volumeMounts:
           - mountPath: VOLUMEPATH
             name: VOLUMENAME
     volumes:
      - name: VOLUMENAME
        persistentVolumeClaim:
          claimName: PVCNAME


jenkinsfile:

	def volumeName = pom.getProperties().getProperty('plp.volume.name')
        def volumePVCName = pom.getProperties().getProperty('plp.volume.pvc.name')
	def volumeMountPath = pom.getProperties().getProperty('plp.volume.mount.path')
			
	sh 'sed -i "s, VOLUMENAME, '+ volumeName +',g" ${WORKSPACE}/deployment.yml'
	sh 'sed -i "s, PVCNAME, '+ volumePVCName +',g" ${WORKSPACE}/deployment.yml'
	sh 'sed -i "s, VOLUMEPATH, '+ volumeMountPath +',g" ${WORKSPACE}/deployment.yml'

**Comment by manusa** [comment]
Have you tried:
```yaml
spec:
 template:
   spec:
     containers:
       - env:
         - name: spring.cloud.config.uri
           value: xxx
         - name: spring.cloud.config.enabled
           value: true
         - name: spring.cloud.config.profile
           value: beta
         - name: spring.cloud.config.username
           value: xxx
         - name: spring.cloud.config.password
           value: xxx
         imagePullPolicy: Always
         volumeMounts:
           - mountPath: ${plp.volume.mount.path}
             name: ${plp.volume.name}
     volumes:
      - name: VOLUMENAME
        persistentVolumeClaim:
          claimName: ${plp.volume.pvc.name}
```

That should work.
