### ISSUE TITLE
oc:resource do not generate route

### ISSUE THREAD

**Issue by rafaeltuelho** [eclipse/jkube#602]
### Description

`oc:resource` do not generate openshift route

### Info
even explicitly configuring the `openshift-maven-plugin` with:
```xml
...
            <configuration>
              <verbose>false</verbose>
              <enricher>
                <config>
                  <jkube-openshift-route>
                    <generateRoute>true</generateRoute>
                    <tlsInsecureEdgeTerminationPolicy>Allow</tlsInsecureEdgeTerminationPolicy>
                    <tlsTermination>edge</tlsTermination>
                  </jkube-openshift-route>
                </config>
              </enricher> 
...
```

* Eclipse JKube version : 1.1.1
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/openjdk-11.0.2.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.6", arch: "x86_64", family: "mac"
```
* Kubernetes / Red Hat OpenShift setup and version : 
```
Client Version: openshift-clients-4.6.0-202006250705.p0-166-g299b6af53
Server Version: 4.6.3
Kubernetes Version: v1.19.0+9f84db3
```

* If it's a bug, how to reproduce :
```
mvn clean oc:resource -Popenshift
```
* If it's a feature request, what is your use case :

* Sample Reproducer Project : *[https://github.com/rafaeltuelho/my-business-automation-showcase/tree/master/business-application-service]*

**Comment by manusa** [comment]
_**WIP: I'm trying to reproduce the issue.**_

When I run `mvn clean oc:resource -Popenshift` with the project as is in https://github.com/rafaeltuelho/my-business-automation-showcase/blob/0fa29a20c99adbde48e456a00589ff29b7736ccc/business-application-service/pom.xml a route gets successfully created. :heavy_check_mark: 

If I remove the [route.yml](https://github.com/rafaeltuelho/my-business-automation-showcase/blob/0fa29a20c99adbde48e456a00589ff29b7736ccc/business-application-service/src/main/jkube/route.yml) fragment, the route is no longer created :heavy_multiplication_x: 


If I remove the [route.yml](https://github.com/rafaeltuelho/my-business-automation-showcase/blob/0fa29a20c99adbde48e456a00589ff29b7736ccc/business-application-service/src/main/jkube/route.yml) fragment, the route is no longer created :heavy_multiplication_x: 

If I remove the [pom.xml](https://github.com/rafaeltuelho/my-business-automation-showcase/blob/0fa29a20c99adbde48e456a00589ff29b7736ccc/business-application-service/pom.xml#L280-L288) route configuration and fragment, the route is no longer created :heavy_multiplication_x:

**Comment by manusa** [comment]
It's really clear that our documentation should be improved in this aspect. As I did the analysis I recall that other users stumbled across this before. We need to improve it.

**Comment by manusa** [comment]
Please @rafaeltuelho  confirm that the proposed fix (adding `<jkube.enricher.jkube-service.expose>true</jkube.enricher.jkube-service.expose>` to your pom.xml) fixes the issue for you.

**Comment by rafaeltuelho** [comment]
@manusa thank you for explaining that.
So, I put a route.yml fragment to kinda force the route generation which worked for me.
I removed that route fragment and tried the prop you pointed out and it also worked!
Yeah, this need to be highlighted in the docs because it seems I don't need this piece of config:

```xml
              <enricher>
                <config>
                  <jkube-openshift-route>
                    <generateRoute>true</generateRoute>
                    <tlsInsecureEdgeTerminationPolicy>Allow</tlsInsecureEdgeTerminationPolicy>
                    <tlsTermination>edge</tlsTermination>
                  </jkube-openshift-route>
                </config>
              </enricher> 
```

I just need to use the prop you pointed:

```
<jkube.enricher.jkube-service.expose>true</jkube.enricher.jkube-service.expose>
```

It's confusing :-/

**Comment by manusa** [comment]
> It's confusing :-/

Agreed. We'll keep this issue open to use it as a placeholder to improve our docs.

**Comment by rohanKanojia** [comment]
I'm adding a small note in [Route Generation](https://www.eclipse.org/jkube/docs/openshift-maven-plugin#resource-route-generation) section regarding expose labels required for Route generation.
