### ISSUE TITLE
jkube-healthcheck-karaf startup feature name is wrong

### ISSUE THREAD

**Issue by mcarlett** [eclipse/jkube#622]
hi, in the [documentation about jkube-healthcheck-karaf specific enricher](https://www.eclipse.org/jkube/docs/openshift-maven-plugin#jkube-healthcheck-karaf) is defined the karaf startup feature named jkube.karaf-checks. It should be jkube-karaf-checks

**Comment by rohanKanojia** [comment]
@mcarlett : Thanks a lot for reporting this. Would you like to submit a PR to fix this?

**Comment by ohbus** [comment]
@rohanKanojia where can I find the source of this doc?

**Comment by ohbus** [comment]
> @rohanKanojia where can I find the source of this doc?

Found it here `kubernetes-maven-plugin/doc/src/main/asciidoc/inc/enricher/_jkube_healthcheck_karaf.adoc`
