### ISSUE TITLE
Not able to override Image Name in Simple Dockerfile Mode with `jkube.generator.name`

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#624]
When using simple Dockerfile mode, we're not able to override the default image name using `jkube.generator.name` property. Seems like we always assume image name to be group:artifact:latest in zero dockerfile mode and don't consider whether `jkube.generator.name` property is set or not, we do pass a defaultImageName but somehow it seems to be passed as null:

https://github.com/eclipse/jkube/blob/fd9003cf04fd2bcd7407e87ffc30dbf41d8a24b7/jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/helper/DockerFileUtil.java#L249-L252

In order to reproduce this, you can go to quickstarts/maven/docker-file-simple and try overriding image name by adding some property. I noticed this when testing @ghassen1khalil sample: https://github.com/ghassen1khalil/jkube-error-reproducer

**Comment by rohanKanojia** [comment]
@ghassen1khalil : We just released v1.2.0 which should fix your issue. Could you please try it out and provide feedback?

**Comment by ghassen1khalil** [comment]
@rohanKanojia I confirm that the release 1.2.0 fixed my bug 👍🏼 
Thank you
