### ISSUE TITLE
Add support for Quarkus Fast Jar Packaging

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#632]
[Quarkus 1.12](https://quarkus.io/blog/quarkus-1-12-0-final-released/) was released last month which made Fast-jar packaging as default. Earlier we used to run `*-runner.jar` in previous versions, but now it's replaced by this:
```
java -jar target/quarkus-app/quarkus-run.jar
```
You can read more about it [here](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.12). 

Right now users can't use jkube in zero-configuration  mode with Fast Jar. JKube fails with not being able to find `-runner.jar`:
```
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.1.1:build (default-cli) on project rosa-fruits-app: Execution default-cli of goal org.eclipse.jkube:kubernetes-maven-plugin:1.1.1:build failed: Can't find single file with suffix '-runner.jar' in /home/rohaan/work/repos/rosa-fruits-app/target (zero or more than one files found ending with '-runner.jar') ->
```

 We would need to make changes to QuarkusGenerator to handle Fast-jar packaging as well. We just need to build ImageConfiguration like done in this [Dockerfile here](https://github.com/kameshsampath/rosa-fruits-app/blob/5dd38fd7bbe8ec05d76f175a56d1bb383f4062e8/src/main/docker/Dockerfile.jvm#L3)

### How to Reproduce:
- Try Cloning @kameshsampath 's repo https://github.com/kameshsampath/rosa-fruits-app 
- Remove Image XML configuration
- Try running `k8s:build` or `oc:build`

**Comment by manusa** [comment]
You can easily work around this issue by setting `<quarkus.package.type>uber-jar</quarkus.package.type>` as stated in the generated README.md when bootstraping a Quarkus project >= 1.12

**Comment by manusa** [comment]
Improvement is related to #425 when trying to optimize image builds.

From the generator perspective, we should identify possible assembly strategies (uber, native, fast-jar) and then create the assembly configuration based on that.

**Comment by kameshsampath** [comment]
@rohanKanojia @manusa  ^^ PR #649

**Comment by rohanKanojia** [comment]
@kameshsampath : Thanks a lot for the PR but there is one PR from @dloiacono to fix the same issue: https://github.com/eclipse/jkube/pull/638

**Comment by dloiacono** [comment]
@kameshsampath, @rohanKanojia I improved my PR with some of the @kameshsampath changes.
