### ISSUE TITLE
Bump jkube to JDK11

### ISSUE THREAD

**Issue by theexplorist** [eclipse/jkube#635]
### Description

Jkube for now supports JDK8. We should think of upgrading it to JDK11.

**Comment by manusa** [comment]
Could you please elaborate?
Default base images are based on Java 11.

**Comment by rohanKanojia** [comment]
I think he is talking about bumping jkube's jdk version 

https://github.com/eclipse/jkube/blob/85008d4274a9aa6f0d0a047370d8dcb8c696d7ac/jkube-kit/parent/pom.xml#L778-L779

**Comment by theexplorist** [comment]
@manusa @rohanKanojia  Yes I am talking about jkube's jdk version

**Comment by manusa** [comment]
To be considered in the mid term. Closing this issue for now as it won't be addressed in the short term.
