### ISSUE TITLE
ApplyMojo not considering namespace configured from XML configuration

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#671]
### Info
When I'm trying to do `k8s:apply` from a project where namespace is configured from XML rather than `jkube.namespace` property. I'm getting this error:
```
[INFO] k8s: Creating a ServiceAccount from kubernetes.yml namespace default name rokumar-serviceaccount
[ERROR] k8s: Failed to create ServiceAccount from kubernetes.yml. io.fabric8.kubernetes.client.KubernetesClientException: Namespace mismatch. Item namespace:rokumar. Operation namespace:default.. ServiceAccount(apiVersion=v1, automountServiceAccountToken=null, imagePullSecrets=[], kind=ServiceAccount, metadata=ObjectMeta(annotations=null, clusterName=null, creationTimestamp=null, deletionGracePeriodSeconds=null, deletionTimestamp=null, finalizers=[], generateName=null, generation=null, labels={app=jkube-xml-resourceconfig, provider=jkube, version=1.0.0-SNAPSHOT, group=org.eclipse.jkube}, managedFields=[], name=rokumar-serviceaccount, namespace=rokumar, ownerReferences=[], resourceVersion=null, selfLink=null, uid=null, additionalProperties={}), secrets=[], additionalProperties={}): io.fabric8.kubernetes.client.KubernetesClientException: Namespace mismatch. Item namespace:rokumar. Operation namespace:default.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
I think we're not considering namespace configured from ResourceConfig here:

https://github.com/eclipse/jkube/blob/3af6339ddfa16efbe42ef6e71687f583d74856ee/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/ApplyMojo.java#L235-L239
* Eclipse JKube version : v1.2.0
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/apache-maven-3.6.3
Java version: 11.0.9, vendor: Oracle Corporation, runtime: /usr/lib/java/jdk-11.0.9
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.14-200.fc33.x86_64", arch: "amd64", family: "unix"

```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :
  - Clone the reproducer project
  - create a namespace `rokumar` or change namespace configured in pom to your desired namespace
  - `mvn k8s:resource k8s:apply`

* Sample Reproducer Project : https://github.com/r0haaaan/jkube-xml-resourceconfig/tree/namespace-bug

**Comment by manusa** [comment]
How are the resources generated?
If the namespace is configured using ResourceConfig--->XML, during the resource phase, namespace should be added to the resources

**Comment by rohanKanojia** [comment]
Yes, resources are generated correctly. But it's the namespace used in ApplyService that is getting picked from ClusterAccess. so namespace in resource is correct but the namespace we provide in `inNamespace(..)` is picked from ClusterAccess

**Comment by manusa** [comment]
I think I'm not explaining myself correctly. Let's discuss it later on.
But just picture a scenario where you have several resources (might be provided via fragments--->raw fragments) and you want to target multiple namespaces.

**Comment by rohanKanojia** [comment]
ohk, I think I'm getting what you're saying now. We would need to refactor ApplyService to give precedence to namespace in resource rather than straightaway picking it from ApplyService.getNamespace

**Comment by manusa** [comment]
We need to deal with (at least) 3 possible scenarios:
- Resources have no namespace configured ----> Namespace should be picked from `clusterAccess.getNamespace()`
- Resources have namespace configured (maybe provided in XML configuration after a k8s:resource invocation. But could also be provided as raw fragments, etc.) ----> Namespace should be preserved
- As a user, I want to override this namespace (occasionally) for a given target cluster. I apply the `jkube.namespace` (maven property). ----> Declared namespace should take precedence over anything else.

**Comment by manusa** [comment]
Relates to #599 #586 #570 #582
