### ISSUE TITLE
Unused field in ResourceConfig

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#673]
While revisiting ResourceConfig, I discovered this field is not used anywhere:

https://github.com/eclipse/jkube/blob/3af6339ddfa16efbe42ef6e71687f583d74856ee/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java#L68

Shall we remove this field if it's not getting used anywhere?

**Comment by manusa** [comment]
Sure.
However, we should first see if this port is used in FMP and double check we won't have compatibility issues in case users upgrade from FMP to JKube.

**Comment by rohanKanojia** [comment]
I checked in FMP codebase and this field seems unused there as well. I think we should remove it

**Comment by manusa** [comment]
> I checked in FMP codebase and this field seems unused there as well. I think we should remove it

Go ahead ;)
