### ISSUE TITLE
Define Helm Chart dependencies

### ISSUE THREAD

**Issue by dloiacono** [eclipse/jkube#676]
### Description
Manage the dependencies of a chart.

Helm charts store their dependencies in 'charts/'. For chart developers, it is often easier to manage dependencies in 'Chart.yaml' which declares all dependencies.

The dependency commands operate on that file, making it easy to synchronize between the desired dependencies and the actual dependencies stored in the 'charts/' directory.

For example, this Chart.yaml declares two dependencies:

# Chart.yaml
dependencies:
- name: nginx
  version: "1.2.3"
  repository: "https://example.com/charts"
- name: memcached
  version: "3.2.1"
  repository: "https://another.example.com/charts"

A dependencies section could be added under the helm section:

```
<dependencies>
  <dependency>
    <name>ngnix</name>
    <version>1.2.3</version>
    <repository>https://example.com/charts</repository>
  </dependency>
</dependencies>
```

### Info

* Eclipse JKube version : 1.3.0
* Maven version (`mvn -v`) :
```

```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :

* If it's a feature request, what is your use case : It would be useful to define helm dependencies in the jkube configuration 

* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by manusa** [comment]
Fixed by #691
