### ISSUE TITLE
KarafGenerator misses jolokia port 8778

### ISSUE THREAD

**Issue by ffang** [eclipse/jkube#677]
### Info

* Eclipse JKube version :1.2.0
* Maven version (`mvn -v`) :
```
3.6.3
```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :

When building a Karaf based image with jkube plugin, there is no jolokia port 8778 in the auto-generated deploymentconfig.yml. But the jolokia port 8778 is important for Karaf based image, since other App like Fuse Console need to talk to jolokia agent via jolokia port
* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by rohanKanojia** [comment]
Are you using zero configuration mode or providing some XML configuration for building image? I see there is a webPort field in KarafGenerator but it's default value is 8181
https://github.com/eclipse/jkube/blob/3af6339ddfa16efbe42ef6e71687f583d74856ee/jkube-kit/generator/karaf/src/main/java/org/eclipse/jkube/generator/karaf/KarafGenerator.java#L45-L49

**Comment by ffang** [comment]
Hi @rohanKanojia ,

Thanks for your reply!

I know there's a 8181, this is for the http-servlet port. But we also need the jolokia port 8778, just like it in JavaExecGenerator.

Best Regards
Freeman

**Comment by rohanKanojia** [comment]
Thanks a lot for sending a quick PR. You just need to sign Eclipse Contributor Agreement and add a `Signed-off By ` footer in your commit message for ECA check to pass[0]

https://www.eclipse.org/jkube/contributing#legal

**Comment by ffang** [comment]
Thanks @rohanKanojia for the guidance! All done there.

Freeman
