### ISSUE TITLE
Do plugin support Helm push/publish to repo  

### ISSUE THREAD

**Issue by anand188** [eclipse/jkube#685]
Do plugin support Helm push/publish to repo

**Comment by rohanKanojia** [comment]
We already have this in master #636 Demo here[0] , Would you like to test our snapshot version?

[0] https://www.youtube.com/watch?v=RnjROID8qqc

**Comment by anand188** [comment]
i am currently using release version 1.2.0 and tried to use 1.3.0-SNAPSHOT it seems its not available in repo yet . is it available ?

**Comment by rohanKanojia** [comment]
Sorry, we don't publish snapshot versions. You can build it locally or use [JitPack.io ](https://jitpack.io/)

**Comment by anand188** [comment]
Its always best to publish snapshots so that everyone can use even if its not completely ready until unless it breaks .

**Comment by manusa** [comment]
We encourage to use JitPack instead of SNAPSHOT builds since you get a build of a specific ref:
```xml
        <dependency>
            <groupId>com.github.eclipse.jkube</groupId>
            <artifactId>kubernetes-maven-plugin</artifactId>
            <version>$yourRef|master|...</version>
        </dependency>

	<repositories>
		<repository>
		    <id>jitpack.io</id>
		    <url>https://jitpack.io</url>
		</repository>
	</repositories>
```

**Comment by anand188** [comment]
Also i would like to thank @rohanKanojia for prompt response . Yeah okay @manusa  let me try

**Comment by anand188** [comment]
Its pretty hard to build even with jitpack so many dependencies not found and variables @manusa

**Comment by rohanKanojia** [comment]
Umm, I think doing a build without tests `mvn clean install -DskipTests` should not take more than a minute. What problems are you facing?

**Comment by anand188** [comment]
Failure to find com.github.eclipse.jkube:kubernetes-maven-plugin:pom:

**Comment by manusa** [comment]
> Umm, I think doing a build without tests `mvn clean install -DskipTests` should not take more than a minute. What problems are you facing?

He is not building, he is trying to use jitpack.io

**Comment by manusa** [comment]
Can you share your pom details, I can only see one recent build in [JitPack](https://jitpack.io/#eclipse/jkube/master-SNAPSHOT)

https://jitpack.io/com/github/eclipse/jkube/master-SNAPSHOT/build.log

**Comment by anand188** [comment]
I tried both maven and jitpack.io neither of them had workout

**Comment by anand188** [comment]
When will be 1.3.0 released ?

**Comment by manusa** [comment]
JitPack issue relates to:
- https://github.com/jitpack/jitpack.io/issues/3998

**Comment by manusa** [comment]
Hi @anand188 
I think we managed to fix the JitPack issue in #687 

I tested, and the following setup worked for me:
```xml
  <repositories>
    <repository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>jitpack.io</id>
      <url>https://jitpack.io</url>
    </pluginRepository>
  </pluginRepositories>
  <profiles>
    <profile>
      <id>kubernetes</id>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.eclipse.jkube</groupId>
            <artifactId>kubernetes-maven-plugin</artifactId>
            <version>master-SNAPSHOT</version>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>openshift</id>
      <properties>
        <jkube.openshift.enrichAllWithImageChangeTrigger>true</jkube.openshift.enrichAllWithImageChangeTrigger>
      </properties>
      <build>
        <plugins>
          <plugin>
            <groupId>com.github.eclipse.jkube</groupId>
            <artifactId>openshift-maven-plugin</artifactId>
            <version>master-SNAPSHOT</version>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
```

**Comment by manusa** [comment]
Hi @anand188,
The [latest release](https://github.com/eclipse/jkube/releases/tag/v1.3.0) should already support pushing/publishing your Helm charts.

**Comment by manusa** [comment]
Hi @anand188 
Your issue should already be addressed, closing it. Feel free to reopen/create new issue if the current fix doesn't work for you
