### ISSUE TITLE
Remove quotes from helm chart values

### ISSUE THREAD

**Issue by dloiacono** [eclipse/jkube#711]
### Description
The Helm chart values are created with quotes due to a configuration used in the YAML object mapper:  ALWAYS_QUOTE_NUMBERS_AS_STRINGS

### Info

* Eclipse JKube version : 1.3.0
* Maven version (`mvn -v`) :
```
  Not Important 
```
* Kubernetes / Red Hat OpenShift setup and version : Not Important

* If it's a bug, how to reproduce :
```
- create a template file with a parameter with number value: like adding replicas_count: 2
- use the ${replicas_cout} into the replicas attribute of the deployment.yml
- generate the Helm chart
- apply the chart on the cluster
```

* If it's a feature request, what is your use case :

* Sample Reproducer Project : *[GitHub Clone URL]*

**Comment by manusa** [comment]
The Helm chart generation features have been refactored during the last couple of months:
- #1244
- #1124
- ...

This issue should no longer be applicable, as the requested end result is now achievable.

I'm closing the issue, please feel free to re-open or create a new one to cover additional requirements
