### ISSUE TITLE
Update Spring Boot Quickstarts to latest version

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#716]
Our Spring Boot Quickstarts are based upon spring boot versions that were released a year ago. We need to update them to the latest version of spring boot.

1. Update Spring Boot version in Quickstart to latest version
2. Check if Quickstart is building fine after version bump
3. Test if upgraded quickstart is working okay with jkube. Check `mvn k8s:build`, `mvn k8s:resource`, `mvn k8s:apply` goals with a local Kubernetes cluster(minikube/kind)

https://github.com/eclipse/jkube/tree/master/quickstarts/maven/spring-boot
https://github.com/eclipse/jkube/tree/master/quickstarts/maven/spring-boot-crd
https://github.com/eclipse/jkube/tree/master/quickstarts/maven/spring-boot-camel-complete
https://github.com/eclipse/jkube/tree/master/quickstarts/maven/spring-boot-dekorate
https://github.com/eclipse/jkube/tree/master/quickstarts/maven/spring-boot-with-jib
https://github.com/eclipse/jkube/tree/master/quickstarts/maven/spring-boot-watch

**Comment by manusa** [comment]
It would also be necessary to check the update works with OpenShift in those quickstarts where it's applicable.

**Comment by rohanKanojia** [comment]
In case testing on OpenShift is needed, use Red Hat Developer Sandbox[0]

[0] https://developers.redhat.com/developer-sandbox

**Comment by rohanKanojia** [comment]
@theexplorist : Please review if the issue description is clear enough. If it looks okay to you and you're interested in working on this, I'll assign it to you.

**Comment by theexplorist** [comment]
@rohanKanojia Assign me this issue!

**Comment by theexplorist** [comment]
Testing the build, will be submitting PR!

**Comment by theexplorist** [comment]
Apologies for the long delay, still working!
