### ISSUE TITLE
Upgrade HttpClient to 4.5.13 or later

### ISSUE THREAD

**Issue by tadayosi** [eclipse/jkube#725]
### Description

Simply, please merge #713!

### Info

n/a

**Comment by rohanKanojia** [comment]
someone needs to fix build issues https://app.circleci.com/pipelines/github/eclipse/jkube/1317/workflows/1ed90d23-9680-4aa8-911c-d2770c491dc5/jobs/7719

**Comment by tadayosi** [comment]
@rohanKanojia OK, let me try then. thanks!
