### ISSUE TITLE
chown problem when copying content into docker generator image

### ISSUE THREAD

**Issue by jfdenise** [eclipse/jkube#728]
### Description

I am writing a generator that, during assembly, copy a directory to the FROM image. My FROM image user is not root but jboss (185).

I want the user owning the copied directory (and sub directories) to be jboss:root. In the generator I am calling:

// preserve permissions
builder.mode(AssemblyMode.tar);
// set user
builder.user("jboss:root");

During k8s:build, I got the following exception:
[ERROR] k8s: Failed to execute the build [Error while trying to build the image: Unable to build image [plugins/jkube-app:latest] : "The command '/bin/sh -c chown -R jboss:root /tmp/f70812b3-7e99-4df0-89ea-9452af307301 && cp -rp /tmp/f70812b3-7e99-4df0-89ea-9452af307301/* / && rm -rf /tmp/f70812b3-7e99-4df0-89ea-9452af307301' returned a non-zero code: 1" ]

The generated Dockerfile attempts to call chown without being root and fails.

How should I proceed?

### Info

* Eclipse JKube version : Latest SNAPSHOT

**Comment by jfdenise** [comment]
[test-chown.zip](https://github.com/eclipse/jkube/files/6671604/test-chown.zip)
This is what is generated when I am setting the user "jboss:root" in the builder. 
* Unzip build.zip
* cd build
* docker build -t test .
* You will observe the ownership problem. My from image user is not root, but jboss, so can't change the ownership.

**Comment by manusa** [comment]
I think you're not specifying all arguments for user, you should do like in:

https://github.com/eclipse/jkube/blob/1958da9551a05acd67268ece655ee261ff98d205/jkube-kit/generator/webapp/src/main/java/org/eclipse/jkube/generator/webapp/handler/WildFlyAppSeverHandler.java#L115

And specify the user with 3 parts.

JKube will take care of running that specific chmod statement as root.
The output Dockerfile section should look like:
```dockerfile
COPY /opt/server /tmp/b7bd11c3-9f45-4f99-9cd0-9341d2ec3aa8/opt/server/
USER root
RUN chown -R jboss:jboss /tmp/b7bd11c3-9f45-4f99-9cd0-9341d2ec3aa8 && cp -rp /tmp/b7bd11c3-9f45-4f99-9cd0-9341d2ec3aa8/* / && rm -rf /tmp/b7bd11c3-9f45-4f99-9cd0-9341d2ec3aa8
USER jboss
```

**Comment by jfdenise** [comment]
@manusa , thank-you. That was it. I missed the "run user" part. I will close the issue.
