### ISSUE TITLE
Quickstart using Jitpack as plugin repository

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#732]
### Description

Testing the newly implemented features of Eclipse JKube prior to a release is critical to deliver a great product.

For users reporting bugs, it might be helpful to validate that an issue was effectively fixed by being able to use the latest SNAPSHOT from the main/master branch.

Since we don't provide nightly builds (Jitpack seems like a much more powerful option), we need to provide better instructions to use Jitpack instead.

### What to do

Provide a Maven quickstart that uses Jitpack as repository and pluginRepository using the [quickstarts/maven/zero-config](https://github.com/eclipse/jkube/tree/master/quickstarts/maven/zero-config) as reference.

Changes:
| | Change |
| - | - |
| location | quickstarts/maven/zero-config-jitpack |
| artifactId | jkube-maven-sample-zero-config-jitpack |
| name |  Eclipse JKube :: Quickstarts :: Maven :: Zero-Config (Jitpack) |
| description | How to use Eclipse JKube from Jitpack |

Add the following to the pom.xml

```xml
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>
<pluginRepositories>
  <pluginRepository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </pluginRepository>
</pluginRepositories>
```

Replace the plugin references:

From:
```xml
<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>kubernetes-maven-plugin</artifactId>
  <version>${jkube.version}</version>
</plugin>
<! -- ... -->
<plugin>
  <groupId>org.eclipse.jkube</groupId>
  <artifactId>openshift-maven-plugin</artifactId>
  <version>${jkube.version}</version>
</plugin>
```
To:
```xml
<plugin>
  <groupId>com.github.eclipse.jkube</groupId>
  <artifactId>kubernetes-maven-plugin</artifactId>
  <version>master-SNAPSHOT</version>
</plugin>
<! -- ... -->
<plugin>
  <groupId>com.github.eclipse.jkube</groupId>
  <artifactId>openshift-maven-plugin</artifactId>
  <version>master-SNAPSHOT</version>
</plugin>
```

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by rbrishabh** [comment]
I can help with this!

**Comment by manusa** [comment]
I'll assign to you. Let [us know](https://gitter.im/eclipse/jkube) if you need assistance.

**Comment by manusa** [comment]
Polite ping, are you still working on this issue?

**Comment by theexplorist** [comment]
@manusa @rohanKanojia Is the issue available?

**Comment by manusa** [comment]
I guess that after 2 weeks of silence you can work on this @theexplorist, thx!

**Comment by Onyinye91-ctrl** [comment]
Is this issue still available @manusa ?

**Comment by theexplorist** [comment]
> Is this issue still available @manusa ?

Working on it, you can see its assigned

**Comment by Devamparikh** [comment]
Hey is this issue still open to work on??

**Comment by Devamparikh** [comment]
Hey @theexplorist are you still working on this?

**Comment by daryl-micah** [comment]
hey @manusa is the issue still available? I would like to help!

**Comment by manusa** [comment]
Hi, there is already an open PR #1293 for this. However, I'm unsure if it works (we need to review).

Given the difficult setup, I'm reconsidering the option to provide nightly SNAPSHOT builds in the standard Sonatype repo. We followed this approach for the Fabric8 Kubernetes Client, and it's giving good results. So removing the complex setup friction point seems like a good idea (at the user's expense of consuming non-deterministic SNAPSHOT versions).

**Comment by Gairick52** [comment]
@manusa hey i am beginner in open source can you suggest me some beginner friendly issues to contribute to

**Comment by DhirajSardar** [comment]
is this issue still available ?

**Comment by gkprasanth** [comment]
Is this issue still open? I would like to look into this.

**Comment by sbouhaddi** [comment]
Let me know if this issue is still open please
Thank you

**Comment by rohanKanojia** [comment]
I think this issue is outdated now. We now publish [SNAPSHOT builds](https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/jkube/) on maven central snapshot repositories. 

Maybe we can add documentation about how to use it and then close this issue. The important thing to notice is that we need to enable snapshots for `<pluginRepositories>` not `<repositories>`:

```xml
  <pluginRepositories>
    <pluginRepository>
      <id>oss.sonatype.org</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <snapshots>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>
```

**Comment by manusa** [comment]
> I think this issue is outdated now. We now publish [SNAPSHOT builds](https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/jkube/) on maven central snapshot repositories.

From https://github.com/eclipse/jkube/pull/2253#issue-1789321300

> Publishing SNAPSHOTs avoid the need for https://github.com/eclipse/jkube/issues/732 which can be replaced by a quickstart that uses SNAPSHOTs instead.

We should create a new issue to prepare a quickstart to showcase it (replacing the purpose of this issue) that closes this one.

**Comment by SahanSamarakoon** [comment]
I'm happy to help if the issue is still open.

**Comment by rohanKanojia** [comment]
@SahanSamarakoon : This issue seems to be outdated now. We added our own SNAPSHOT repository recently #2254

**Comment by manusa** [comment]
Closing as this issue is no longer applicable
