### ISSUE TITLE
RunService.java: Use isEmpty() to check whether the collection is empty or not.

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#734]
### Description

The following statement is reported as a code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&open=AXCb0UvMych7Ocxsbwgc&resolved=false&types=CODE_SMELL):

https://github.com/eclipse/jkube/blob/8ca3f342372128fe12ea1572db1e37d033406a94/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/RunService.java#L411

Replace with `.isEmpty`:
```java
return !ret.isEmpty() ? ret : null;
```

### Bonus

Create a unit test to verify your changes (intermediate).

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by rbrishabh** [comment]
Sorry, just learning java, if it's OK, I can help with this too :)

**Comment by manusa** [comment]
[first-timers-only](https://github.com/eclipse/jkube/labels/first-timers-only) issues are intended for new contributors. If you have already committed to the project or are already working on an issue you shouldn't apply for these ones.

**Comment by Jayita10** [comment]
@manusa, I would love to work on this issue. can I?

**Comment by Jayita10** [comment]
Hi @manusa, I fixed the issue. Please review my work. Thanks :)

**Comment by manusa** [comment]
@Jayita10 thanks for contributing to Eclipse JKube, you've now become part of the extensive list of contributors to JKube and to the Eclipse foundation

As stated in this [comment](https://github.com/eclipse/jkube/issues/740#issuecomment-869704487), we'd be very happy if you stayed around and involved with the project. We'll try to label some new (a little bit more involved issues) with [`help wanted`](https://github.com/eclipse/jkube/labels/help%20wanted) for you to pick up. Contributing to Open Source is not just about coding, but also about contributing to the community. Talking about the project, writing a blog or an article, helping with documentation, etc. are also other ways to collaborate with us.
