### ISSUE TITLE
Does it support OpenShift 4？

### ISSUE THREAD

**Issue by mransonwang** [eclipse/jkube#74]
I know fabric8 maven plugin only supports OpenShift 3, not sure if jkube supports OpenShift 4?

**Comment by rohanKanojia** [comment]
@mransonwang : Both Fabric8 Maven Plugin and Jkube support Openshift 4(See https://github.com/fabric8io/fabric8-maven-plugin#openshift-and-kubernetes-compatibility). Are you facing any issue with FMP/Jkube's usage on Openshift 4?

**Comment by mransonwang** [comment]
Thanks for your quick reponse, will try on OpenShift 4 later :-)

**Comment by rohanKanojia** [comment]
@mransonwang : I'm keeping this ticket open till you try it out and provide feedback :-) . You can close it if you're able to use it successfully on Openshift 4

**Comment by mransonwang** [comment]
@rohanKanojia I spent one day to validate the plugin on OpenShift 4.3.3, almost done. However I need a customized route configuration in my Spring Boot project pom.xml, I dont kown how to produce it such as:

kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: hello-world
  namespace: demo-s2i
  selfLink: /apis/route.openshift.io/v1/namespaces/demo-s2i/routes/hello-world
  uid: c031f230-1f78-41d4-9652-c1ce8abbdc53
  resourceVersion: '68426'
  creationTimestamp: '2020-02-23T06:12:15Z'
  labels:
    app: hello-world
    app.kubernetes.io/component: hello-world
    app.kubernetes.io/instance: hello-world
    app.kubernetes.io/name: java
    app.kubernetes.io/part-of: hello-world-app
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: '11'
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: hello-world-demo-s2i.apps.ocp4.example.com
  to:
    kind: Service
    name: hello-world
    weight: 100
  port:
    targetPort: 8443-tcp
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None

Especially for sepc config, how plugin could generate the sepc that I want?

**Comment by rohanKanojia** [comment]
You can provide a custom route fragment in `src/main/jkube` directory and plugin would merge your fragment into the final generated route manifest

**Comment by mransonwang** [comment]
@rohanKanojia Where's detailed documentation?

**Comment by rohanKanojia** [comment]
I think it's this : https://htmlpreview.github.io/?https://github.com/eclipse/jkube/blob/master/kubernetes-maven-plugin/doc/index.html#resource-fragments

**Comment by mransonwang** [comment]
@rohanKanojia After did some configurations, the plugin worked well against OpenShift 4.4.3, thanks for your kindly help.

**Comment by rohanKanojia** [comment]
@mransonwang : Thanks a lot for trying our plugin out :)
