### ISSUE TITLE
ConfigKey.java: Make DEFAULT_PREFIX private and final

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#740]
### Description
The following statement is reported as a vulnerability by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&open=AW3z0M4hL3SSO-VMZS4E&resolved=false&types=VULNERABILITY):

https://github.com/eclipse/jkube/blob/bf88230a5c110d686ea02ffb45dba8a294f5e2e9/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/config/handler/property/ConfigKey.java#L153

should be changed to:
```java
    private static final String DEFAULT_PREFIX = "docker";
```

### Bonus

Create a unit test to verify your changes (intermediate).

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Jayita10** [comment]
I see no one assign for this issue yet. can I work on this?

**Comment by rohanKanojia** [comment]
@Jayita10 : This issue is for first time contributors. Would you like to pick up some other slightly involved issue?

**Comment by manusa** [comment]
Hi @Jayita10 
[first-timers-only](https://github.com/eclipse/jkube/labels/first-timers-only) issues are intended for newcomers.
Our intention is to provide also additional [`help-wanted`](https://github.com/eclipse/jkube/labels/help%20wanted) issues so that people who have already contributed to the project (just like you), can keep involved and helping out.

**Comment by Jayita10** [comment]
> @Jayita10 : This issue is for first time contributors. Would you like to pick up some other slightly involved issue?

Yeah sure :)

**Comment by param-thakker** [comment]
Hi, Can I please work on this? I'm a first time contributor.

**Comment by param-thakker** [comment]
I have created a pull request with the changes.
