### ISSUE TITLE
Add a private constructor to hide the implicit public ones in Utility classes

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#741]
Utility classes, which are collections of static members, are not meant to be instantiated. Even abstract utility classes, which can be extended, should not have public constructors.

Java adds an implicit public constructor to every class which does not define at least one explicitly. Hence, at least one non-public constructor should be defined. You can read more about this in SonarRule[0]

We need to update our utility classed pointed out by SonarCloud[1].

[0] https://sonarcloud.io/organizations/jkubeio/rules?open=java%3AS4042&rule_key=java%3AS4042
[1] https://sonarcloud.io/organizations/jkubeio/issues?projects=jkubeio_jkube&resolved=false&rules=java%3AS1118

**Comment by kristofnagyban** [comment]
I'll work on this.
