### ISSUE TITLE
KubernetesResourceUtil.java: Make SIMPLE_FIELD_TYPES private

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#746]
### Description
The following statement is reported as a vulnerability by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&open=AXGmF3jC7hhEzz-4P4Ej&resolved=false&types=VULNERABILITY):

https://github.com/eclipse/jkube/blob/b2a4fb833ba8e740bbd142a0ab94bcac0c87dc8f/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L111

should be changed to:
```java
    private static final Set<Class<?>> SIMPLE_FIELD_TYPES = new HashSet<>();
```

### Bonus

Create a unit test in [KubernetesResourceUtilTest.java](https://github.com/eclipse/jkube/blob/b2a4fb833ba8e740bbd142a0ab94bcac0c87dc8f/jkube-kit/enricher/api/src/test/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtilTest.java) for the method [`KubernetesResourceUtil#mergeSimpleFields`](https://github.com/eclipse/jkube/blob/b2a4fb833ba8e740bbd142a0ab94bcac0c87dc8f/jkube-kit/enricher/api/src/main/java/org/eclipse/jkube/kit/enricher/api/util/KubernetesResourceUtil.java#L562) that will cover the usage of the member variable you just changed.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by skpandey885** [comment]
Hey! I'm Interested! Can I work On this?

**Comment by skpandey885** [comment]
Hey! Can You Explain a Bit more.. I am a Beginner! Need Help! :)

**Comment by manusa** [comment]
You need to replace the line with the link on the description KubernetesResourceUtil.java#L111 with the suggested replacement.
- Fork the project
- Clone it in your machine
- Create a branch
- Do the suggested changes
- Create an Eclipse Account (if you don't own one)
- Sign the Eclipse Contributor Agreement
- Commit your changes singing-off your commit with the same email account you registered for Eclipse
- Push your branch
- Create a PR
- Done

**Comment by skpandey885** [comment]
I Forgot To Sign off! again I will generate a pr!

**Comment by skpandey885** [comment]
Hey, @manusa I need some guidance. Can you please help me?
