### ISSUE TITLE
Configuration mismatch between docs and code

### ISSUE THREAD

**Issue by sohrab-** [eclipse/jkube#75]
The XML configuration in the docs (even in Fabric8 ones), does not seem to match what the code does. This was a source of confusion when I started using these plugins initially (until I dug through the source code).

For example, the [XML Configuration](https://htmlpreview.github.io/?https://github.com/eclipse/jkube/blob/master/kubernetes-maven-plugin/doc/index.html#xml-configuration) outlines what `<resources>` item looks like but this does not match the [`ResourceConfig`](https://github.com/eclipse/jkube/blob/master/jkube-kit/config/resource/src/main/java/org/eclipse/jkube/kit/config/resource/ResourceConfig.java) class.

If I provide say the `<deployment>` child as outlined in that section, I get the following error:

```
[ERROR] Failed to execute goal org.eclipse.jkube:k8s-maven-plugin:0.1.1:resource (default-cli) on project pdfg: Unable to parse configuration of mojo org.eclipse.jkube:k8s-maven-plugin:0.1.1:resource for parameter deployment: Cannot find 'deployment' in class org.eclipse.jkube.kit.config.resource.ResourceConfig -> [Help 1]
```

But when I do follow the class structure, everything goes as expected.

Am I missing something here?

**Comment by rohanKanojia** [comment]
@sohrab- : Apologies for late reply. I think we need to align our docs with ResourceConfig class.
