### ISSUE TITLE
Arguments.java: Replace the call to "replaceAll()" by a call to the "replace()" method

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#755]
### Description
The following statement is reported as a critical code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&open=AXNtNJUkOwr8C6MdNZOQ&resolved=false&severities=CRITICAL&types=CODE_SMELL).

It's also a duplicate fragment of some core logic defined in the Class [EnvUtil#splitOnSpaceWithEscape](https://github.com/eclipse/jkube/blob/813074705147f9423dd807385c0d40e4670ddf9a/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/EnvUtil.java#L172).

The following block:
https://github.com/eclipse/jkube/blob/7544c736dc435e029d189930f28427721486a71c/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/build/Arguments.java#L113-L120

should be replaced with:
```java
        if (shell != null) {
            return Arrays.asList(EnvUtil.splitOnSpaceWithEscape(shell));
        }
```

### Bonus

Create a unit test to verify your changes.

- Test to be created in new file `src/test/java/org/eclipse/jkube/kit/config/image/build/ArgumentsTest.java` in the appropriate module.
- Assertions to be defined using AssertJ (`import static org.assertj.core.api.Assertions.assertThat`)
- The test should verify a case where an expected result of ["java", "-jar", "$HOME/name with space.jar"] is produced.

CC: @valaparthvi

**Comment by valaparthvi** [comment]
@manusa I would like to work on this one. Can you assign it to me?

**Comment by skpandey885** [comment]
If This Issue Is Open I would Like To Work On it!

**Comment by manusa** [comment]
This one is currently assigned. However, #746 is free, maybe you want to take a look 😉
