### ISSUE TITLE
LogRequestor.java: Add the missing @Override annotation

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#762]
### Description
The following statement is reported as a code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&open=AXCb0UiGych7OcxsbwfQ&resolved=false&severities=MAJOR&types=CODE_SMELL):

https://github.com/eclipse/jkube/blob/c15c4bb8b7cc4ea7502f8314b1e067b27f9a1dda/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/LogRequestor.java#L96

should be changed to:
```java
    @Override
    public void run() {
```

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Manjooth** [comment]
Could I be assigned this issue please?

**Comment by Manjooth** [comment]
@manusa Hey! Sorry to bother you but I'm getting a `fatal: unable to access 'https://github.com/eclipse/jkube.git/': The requested URL returned error: 403` when trying to push my changes. Do I need to do anything specific?
