### ISSUE TITLE
JKubeBuildTarArchiver.java: Remove unused import

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#773]
### Description
The following statement is reported as a code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&open=AXT4h68QMF49wDtJLNPb&resolved=false&types=CODE_SMELL):

https://github.com/eclipse/jkube/blob/969025bf6bd21f22ec02ef4a72174ae49aaad5bb/jkube-kit/build/api/src/main/java/org/eclipse/jkube/kit/build/api/assembly/JKubeBuildTarArchiver.java#L27-L28

These lines should be completely removed.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by skpandey885** [comment]
Can You Assign This To Me?

**Comment by maycap123** [comment]
is this still available? i would like to give it a try :)

**Comment by manusa** [comment]
Hi @maycap123  are you still working on this?

**Comment by Aaditi-S** [comment]
Is this task completed ? if not can I go for this

**Comment by mohitsaxenaknoldus** [comment]
Please assign to me if available.

**Comment by rohanKanojia** [comment]
@maycap123: Are you still working on this? If not, Could you please un-assign if yourself?

**Comment by maycap123** [comment]
I thought i did a pull request for my change. Apparently that didnt happen.

**Comment by rohanKanojia** [comment]
@maycap123 : Are you talking about https://github.com/maycap123/jkube/pull/1 ? I think you raised PR against your fork rather than JKube. Could you please create a new PR against jkube?

**Comment by maycap123** [comment]
Will do that! Sorry, new to github and the workflow :D

**Comment by maycap123** [comment]
hope i did it right this time! sorry again!

**Comment by rohanKanojia** [comment]
Umm, I'm a little confused. There is no file changed in your branch

**Comment by maycap123** [comment]
damn it! i am really sorry. i look into it

**Comment by rohanKanojia** [comment]
Thanks a lot. Feel free to ask for help on our gitter channel https://gitter.im/eclipse/jkube
