### ISSUE TITLE
VolumeService.java: Remove unused import

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#774]
### Description
The following statement is reported as a code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&open=AW3z0M_RL3SSO-VMZS7N&resolved=false&types=CODE_SMELL):
https://github.com/eclipse/jkube/blob/969025bf6bd21f22ec02ef4a72174ae49aaad5bb/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/VolumeService.java#L20-L21

These lines should be completely removed.

### Bonus points

There's an additional very easy to solve code smell reported for this class ([VolumeService.java](https://github.com/eclipse/jkube/blob/969025bf6bd21f22ec02ef4a72174ae49aaad5bb/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/VolumeService.java)).

Identify the code-smell and provide the fix.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by onFilm** [comment]
@manusa Please assign this to me 😊

**Comment by maycap123** [comment]
Is this still available? I would love to do it! :)
