### ISSUE TITLE
k8s:helm with template for integer values fails deserialization (Similar to https://github.com/fabric8io/kubernetes-client/issues/448)

### ISSUE THREAD

**Issue by rag-sapient** [eclipse/jkube#778]
### Description

Blocked by #802 

When trying to use Jkube for helm generation with template.yml getting deserialisation error for integer values in the template. On searching found it to be simiilar https://github.com/fabric8io/kubernetes-client/issues/448 (still open but a fabric8io issue) and also reference on https://github.com/eclipse/jkube/issues/327#issuecomment-666139528 (closed).

It can still to be replicated using the quickstart https://github.com/eclipse/jkube/tree/master/quickstarts/maven/spring-boot-helm and adding a integer to the template. 

Raising this as unsure if the issue is fixed now or still open as the JKube issue mentioning this is closed (https://github.com/eclipse/jkube/issues/327)

### Info

* Eclipse JKube version : 1.3.0
* Maven version (`mvn -v`) : 
```
Apache Maven 3.8.1
```

**Comment by manusa** [comment]
> Raising this as unsure if the issue is fixed now or still open ...

This issue hasn't been fixed yet, there was a recent discussion on the topic.

There's no easy generic solution for the problem.

**Comment by rag-sapient** [comment]
Thanks @manusa. I will close this for now as this is being tracked against the original issue.

**Comment by manusa** [comment]
I'll keep this issue open so we can keep track of this here too.

In the end it's likely that we have to implement some sort of work-around or partial fix on the JKube side.
