### ISSUE TITLE
AbstractNativeClientBuilder.java: Reorder the modifiers to comply with the Java Language Specification

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#783]
### Description
The following statement is reported as a code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&open=AW3z0MzpL3SSO-VMZS2l&resolved=false&types=CODE_SMELL):

https://github.com/eclipse/jkube/blob/c15c4bb8b7cc4ea7502f8314b1e067b27f9a1dda/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/util/AbstractNativeClientBuilder.java#L37

- [x] The order of the modifiers should be switched to:
```java
public abstract class AbstractNativeClientBuilder implements ClientBuilder {
```

### Bonus points

- [ ] The class constructor has an additional reported code smell related to it's visibility. Locate the code smell and change accordingly.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by gabriellaabdennabi** [comment]
Hi could you assign this to me?
