### ISSUE TITLE
EnvUtilTest.java: Replace hamcrest with AssertJ

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#784]
### Description
We are replacing the usage of Hamcrest assertions with AssertJ all over the project.

In [EnvUtilTest.java](https://github.com/eclipse/jkube/blob/813074705147f9423dd807385c0d40e4670ddf9a/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java), replace any usage of Hamcrest with the AssertJ (`org.assertj.core.api.Assertions.assertThat`).

e.g. 
https://github.com/eclipse/jkube/blob/813074705147f9423dd807385c0d40e4670ddf9a/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/EnvUtilTest.java#L401

should be changed to:
```java
        assertThat(timestamp).isEqualTo(new Date(1445385600000L));
```

### Bonus
Replace the rest of assertions (`org.junit.Assert.*`) with AssertJ too.

**Comment by himanshu007-creator** [comment]
Hi, i would like to work on this issue

**Comment by ramananrpn** [comment]
Hey, shall I pick it up if you didn't started ? @himanshu007-creator

**Comment by himanshu007-creator** [comment]
> Hey, shall I pick it up if you didn't started ? @himanshu007-creator

Sure!, @manusa please assign @ramananrpn  this issue. 🟩

**Comment by ramananrpn** [comment]
@manusa @himanshu007-creator  Could you please provide me write access ?

**Comment by ramananrpn** [comment]
@manusa @rohanKanojia Could you guys please review and merge this PR #789 ?
