### ISSUE TITLE
ExternalCommand.java: Change the visibility of constructor to "protected"

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#785]
### Description
The following statement is reported as a code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AXUG3pIvWOmtUdi5Nk1g&open=AXUG3pIvWOmtUdi5Nk1g):

https://github.com/eclipse/jkube/blob/5c745b9e8dd85d3a6889816c0e316078d34c6691/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/ExternalCommand.java#L43

It should be replaced by the following:

```java
    protected ExternalCommand(KitLogger log) {
```

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by RhnSharma** [comment]
I would like to take this one.
