### ISSUE TITLE
LazyBuilderTest.java: Replace hamcrest with AssertJ

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#786]
### Description
We are replacing the usage of Hamcrest assertions with AssertJ all over the project.

In [LazyBuilderTest.java](https://github.com/eclipse/jkube/blob/fe0a1d88ce6ac5f5e8f64d470c8a134f66b9bc60/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/LazyBuilderTest.java), replace any usage of Hamcrest with the AssertJ (`org.assertj.core.api.Assertions.assertThat`).

e.g. 
https://github.com/eclipse/jkube/blob/fe0a1d88ce6ac5f5e8f64d470c8a134f66b9bc60/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/LazyBuilderTest.java#L44-L45

should be changed to:
```java
        assertThat(result).isEqualTo(10);
        assertThat(count).isEqualTo(1);
```

**Comment by Tanner-Mindrum** [comment]
Hello, can I be assigned this? I've replaced hamcrest with AssertJ.

My statements are prefixed with Assertions. (e.g. `Assertions.assertThat(result).isEqualTo(10);`). Is that fine or do you need it as just assertThat?
