### ISSUE TITLE
TemplateUtilTest.java: Replace hamcrest with AssertJ

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#792]
### Description
We are replacing the usage of Hamcrest assertions with AssertJ all over the project.

In [TemplateUtilTest.java](https://github.com/eclipse/jkube/blob/414dbf4266005988c931513d7d7227a291eaf7d6/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/TemplateUtilTest.java), replace any usage of Hamcrest with the AssertJ (`org.assertj.core.api.Assertions.assertThat`).

e.g. 
https://github.com/eclipse/jkube/blob/414dbf4266005988c931513d7d7227a291eaf7d6/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/TemplateUtilTest.java#L26

should be changed to:
```java
    assertThat(escapeYamlTemplate("abcd")).isEqualTo("abcd");
```

### Bonus
This test is a good candidate for a [Parameterized test](https://github.com/junit-team/junit4/wiki/Parameterized-tests).

Change the test and make it parameterized. References:
- [MicronautUtilsGetMicronautConfigurationTest](https://github.com/eclipse/jkube/blob/387464ac559ee674d8372772ebaad10b8dcb78c6/jkube-kit/jkube-kit--micronaut/src/test/java/org/eclipse/jkube/micronaut/MicronautUtilsGetMicronautConfigurationTest.java)
- [JKubeServiceHubBuildServiceTest](https://github.com/eclipse/jkube/blob/96c706847bf2e87bdb9c28692e25312aa6d0fae0/jkube-kit/config/service/src/test/java/org/eclipse/jkube/kit/config/service/JKubeServiceHubBuildServiceTest.java)

**Comment by vlaetansky** [comment]
Can i be assigned on this?

**Comment by manusa** [comment]
> Can i be assigned on this?

Sure, but you first need to complete the work on #813

**Comment by vlaetansky** [comment]
Hi @manusa, the #813 issue is closed
