### ISSUE TITLE
AbstractNativeSocketFactory.java: Reorder the modifiers to comply with the Java Language Specification

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#803]
### Description
The following statement is reported as a code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AW3z0MzyL3SSO-VMZS2n&open=AW3z0MzyL3SSO-VMZS2n):

https://github.com/eclipse/jkube/blob/969025bf6bd21f22ec02ef4a72174ae49aaad5bb/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/util/AbstractNativeSocketFactory.java#L29

- [ ] The order of the modifiers should be switched to:
```java
public abstract class AbstractNativeSocketFactory implements ConnectionSocketFactory {
```

### Bonus points

- [ ] The class constructor has an additional reported code smell related to it's visibility. Locate the code smell and change accordingly.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Shatakshi0805** [comment]
Hi, for the visibility of constructor I believe the public constructor should be private so that this class and it's objects cannot be accessed by any other class?

**Comment by manusa** [comment]
> ...should be private...

Almost, take into account that subclasses need to access this constructor.

Do you want to give it a try?

**Comment by Shatakshi0805** [comment]
yes, please assign this to me.
