### ISSUE TITLE
KitLogger.java: Field may be final

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#805]
### Description
The following statement is a code smell :

https://github.com/eclipse/jkube/blob/0fe957a00e69b56eb8d797a4a931b87ca0eee5a1/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/KitLogger.java#L136

- [x] The field can be effectively declared `final`
```java
        private String category;
```

### Bonus points

- [x] The class has [several falsely reported code-smells](https://sonarcloud.io/project/issues?fileUuids=AXCb0TvXych7Ocxsbwbt&id=jkubeio_jkube&resolved=false&types=CODE_SMELL) regarding the use of `System.out` which is valid for this class (StdoutLogger). These warnings should be suppressed (hint, check for the usage of `@SuppressWarnings` annotation around the code-base)

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by kev197** [comment]
Hey, can I try this?
