### ISSUE TITLE
ClassUtilTest: Remove unused imports

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#807]
### Description
The class [ClassUtilTest](https://github.com/eclipse/jkube/blob/bc812977cc26684611552681ab336bc7f1b8c58c/jkube-kit/common/src/test/java/org/eclipse/jkube/kit/common/util/ClassUtilTest.java) contains multiple unused imports.

Locate those statements and remove them.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by manusa** [comment]
Please @vlaetansky, add a comment to this issue so we can assign to you.

**Comment by vlaetansky** [comment]
@manusa Assign comment. I am sorry for the late response, currently trying to get on the Eclipse site since it is still not fully functional after the last maintenance.

**Comment by manusa** [comment]
Yup, there's something wrong with the Eclipse infra, and this week they are closed :worried:

**Comment by vlaetansky** [comment]
I am waiting for an email to submit ECA form, i couldn't do it yesterday since the website was completely not functional :(

**Comment by maycap123** [comment]
is this available? would like to do it

**Comment by manusa** [comment]
> I am waiting for an email to submit ECA form, i couldn't do it yesterday since the website was completely not functional :(

Hi @vlaetansky , any news on this?

**Comment by vlaetansky** [comment]
Hi, I have submitted the form, but it still doesn't pass the ECA test.
