### ISSUE TITLE
Use `.equals()` for JKubeBuildStategy enum instead of extracting label

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#822]
## Description
In order to check whether we need to connect to docker daemon or not we seem to rely on this method. This method simply checks whether the current build strategy is NOT JIB.

https://github.com/eclipse/jkube/blob/86979df8c7d4bdda21d01fa8cf60266e231b45ee/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/build/AbstractDockerMojo.java#L591-L593

I think we're doing an unnecessary extraction of `getLabels()` here, since JKubeBuildStrategy is an enum. We can simply rewrite the method like this:
```java
protected boolean isDockerAccessRequired() {
     return !getJKubeBuildStrategy().equals(JKubeBuildStrategy.jib);
}
```

## How to verify my changes
1. Project should compile successfully after making the change `mvn clean install`
2. You can go to some quickstart and verify that provided buildStrategy is working as expected
    2.1 In presence of Docker `mvn k8s:build` should use Docker build strategy(it should be visible in logs)
    2.2 In presence of Red Hat OpenShift(You can get a free instance at [Red Hat Developer Sandbox](https://developers.redhat.com/developer-sandbox)) S2I build strategy should be picked
    2.3 When user specifies his own build strategy `mvn k8s:build -Djkube.build.strategy=jib` JIB should be picked

**Comment by maycap123** [comment]
I would like to try this.
