### ISSUE TITLE
Replace `StringBuffer` with `StringBuilder`  in IoUtil and TemplateUtil

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#823]
### Description

Early classes of the Java API, such as Vector, Hashtable and StringBuffer, were synchronized to make them thread-safe. Unfortunately, synchronization has a big negative impact on performance, even when using these collections from a single thread.

We should use unsynchronized update these places to use StringBuilder instead:
https://github.com/eclipse/jkube/blob/b25157bcafb4a9b6b738a0fce018fc3803e6b78e/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/IoUtil.java#L141

https://github.com/eclipse/jkube/blob/b25157bcafb4a9b6b738a0fce018fc3803e6b78e/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/TemplateUtil.java#L28

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Ash-KODES** [comment]
i am ready to work on the issue

**Comment by Onyinye91-ctrl** [comment]
Hello @Ash-KODES Is this issue still available? if yes, i will love to work on it

**Comment by rohanKanojia** [comment]
@Onyinye91-ctrl : Hi, Could you please check if you can work on https://github.com/eclipse/jkube/issues/854 instead?

**Comment by Onyinye91-ctrl** [comment]
@rohanKanojia Just checked it out. Can i go for it?

**Comment by rohanKanojia** [comment]
@Onyinye91-ctrl : Yes, Could you please add a comment on the issue so that I can assign it to you?

**Comment by Onyinye91-ctrl** [comment]
@rohanKanojia  I have already done that

**Comment by rohanKanojia** [comment]
Sorry for not being clear, I meant to comment on #854 . I can only assign users participating in specific issue conversations.

**Comment by tejassinghsital** [comment]
@rohanKanojia Greetings Sir, Sir I am looking for some simple issues that I can work on as my first ever contribution to open source. I''ve been actively looking for some beginner level issues but almost all are assigned already to others. I am little confused now so can you please put me in right direction? Really looking for your reply...

**Comment by rohanKanojia** [comment]
@Ash-KODES : polite ping, Are you still working on this issue? If not, Is it okay if I assign this to @tejassinghsital ?

@tejassinghsital : Thanks for showing interest in contributing to our project. Let me create some more good first issues by the end of today.

**Comment by Hell4U** [comment]
Hey, @rohanKanojia I am new to contributing. Can I get some simple issue for my way to first ever contribution to open source ? Since most of the `first-timers-only` issue were solved when I was finding them.

**Comment by manusa** [comment]
> Hey, @rohanKanojia I am new to contributing. Can I get some simple issue for my way to first ever contribution to open source ? Since most of the `first-timers-only` issue were solved when I was finding them.

https://github.com/eclipse/jkube/labels/first-timers-only

We tend to add new issues here every day, or when there are no more available.

**Comment by Ash-KODES** [comment]
> @Ash-KODES : polite ping, Are you still working on this issue? If not, Is it okay if I assign this to @tejassinghsital ?
> 
> @tejassinghsital : Thanks for showing interest in contributing to our project. Let me create some more good first issues by the end of today.

yes go ahead

**Comment by Ash-KODES** [comment]
> @Ash-KODES : polite ping, Are you still working on this issue? If not, Is it okay if I assign this to @tejassinghsital ?
> 
> @tejassinghsital : Thanks for showing interest in contributing to our project. Let me create some more good first issues by the end of today.

yes go ahead

**Comment by Hell4U** [comment]
So, I am just curious do I have to down mention below to this particular `jkube/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/IoUtil.java` file or all the files present in project.
```diff
- StringBuffer ret = new StringBuffer("["); 
+ StringBuffer answer = new StringBuffer(); 
```

**Comment by rohanKanojia** [comment]
This issue is only applicable to two files mentioned in issue description.

**Comment by Hell4U** [comment]
Thanks for clearing the doubt.

**Comment by ronnuriel** [comment]
is this issue still open ?
