### ISSUE TITLE
deps: Bump jib-core to 0.20.0 (or latest)

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#832]
### Description

Required for #31 

- Bump the jib-core version to latest release (ATM [0.20.0](https://github.com/GoogleContainerTools/jib/releases/tag/v0.20.0-core)).
- Fix convergence issues with maven-enforcer-plugin
- Check quickstarts work (especially Spring Boot with latest release, since there appears to be an issue https://github.com/GoogleContainerTools/jib/issues/2931)
- Create corresponding CQs

**Comment by maycap123** [comment]
would love to make this :)

**Comment by theexplorist** [comment]
I can work on it as I have bumped the quickstarts with latest version @manusa @rohanKanojia
