### ISSUE TITLE
KubernetesResourceTask: implement k8sResource for Dockerfile mode equivalent functionality for Kubernetes Gradle Plugin

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#834]
## Description

Child of #31 
Blocked by #835 

Implement resource generation for Dockerfile mode.

- Any configuration setting should be part of the KubernetesExtension class (Tasks should have no Inputs)
- Any logic present in the current Mojos should be moved to JKube-kit

## AC
- [x] Integration Test for Dockerfile resource generation
- [x] Resource generation works for dockerfile examples

**Comment by rohanKanojia** [comment]
Can we close this one?

**Comment by manusa** [comment]
I'm refactoring the test part
