### ISSUE TITLE
ResourceValidator.java: Use static access with "org.eclipse.jkube.kit.common.util.validator.ValidationRule" for "TYPE"

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#843]
### Description
The following statements are reported as a critical code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AXCbsQVhafTJU1n1scHy&open=AXCbsQVhafTJU1n1scHy).

https://github.com/eclipse/jkube/blob/bc812977cc26684611552681ab336bc7f1b8c58c/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/validator/ResourceValidator.java#L89-L92

should be replaced with:
```java
    private void setupIgnoreRules(ResourceClassifier target) {
      ignoreValidationRules.add(new IgnorePortValidationRule(ValidationRule.TYPE));
      ignoreValidationRules.add(new IgnoreResourceMemoryLimitRule(ValidationRule.TYPE));
    }
```

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Atharva321** [comment]
Hii @manusa , I want to work on this issue. 
Can I pick this up?

**Comment by manusa** [comment]
Hi @Atharva321 
@vinayakkumargupta has an incomplete PR (#845) but never requested to work on this issue.

@vinayakkumargupta are you working on this?

**Comment by Atharva321** [comment]
Sorry 😅 , I did't saw that PR.
Can you point out to me to any other beginner friendly issue on which I can work?
I am beginner in k8s and java.

**Comment by vinayakkumargupta** [comment]
@manusa Thank you For Asking i am very pleased to work on #845 issue I am a rookie Now But I will try to do this

**Comment by vinayakkumargupta** [comment]
@manusa I have done changes it has no conflict with the main repo I am waiting for review

**Comment by Onyinye91-ctrl** [comment]
Is this issue still open? @vinayakkumargupta

**Comment by arnab-2001** [comment]
Hi, @manusa I am a beginner in Open Source also new to the project, can you please point me some resources?

**Comment by manusa** [comment]
Hi,
Sorry for the late replies, I've been on PTO until today.

> Hi, @manusa I am a beginner in Open Source also new to the project, can you please point me some resources?

I'm not sure if you've checked the [first-timers-only](https://github.com/eclipse/jkube/labels/first-timers-only) issues. We'll be creating issues with that tag for newcomers (probably there aren't any left right now).
