### ISSUE TITLE
UserConfigurationCompare.java: Use the built-in formatting to construct this argument.

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#844]
### Description
The following statement is reported as a Major code smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AW3z0NevL3SSO-VMZTJ9&open=AW3z0NevL3SSO-VMZTJ9):

https://github.com/eclipse/jkube/blob/5ab611a35f72559b8a9dc072447e1e883a0927d9/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/UserConfigurationCompare.java#L185

- [ ] should be changed to:
```java
              LOG.warn("Invalid class {} when expecting {} for instance: {}", entity.getClass().getName(), clazz.getName(),
                  entity);
```

### Bonus

- [ ] Create a unit test to verify your changes (intermediate).

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by maycap123** [comment]
Can I do it? :)

**Comment by manusa** [comment]
Hi @maycap123  
[first-timers-only](https://github.com/eclipse/jkube/labels/first-timers-only) issues are intended for newcomers and users who haven't yet contributed to the project. You're already working on #822 -> #846.
There are also (more involved and complex) [`help-wanted`](https://github.com/eclipse/jkube/labels/help%20wanted) issues so that people who have already contributed to the project (just like you), can keep involved and helping out. I'll try to add a few more of those today.

**Comment by maycap123** [comment]
Sorry I didn't see the caption :D i will look for something else

**Comment by deepak-gittyup** [comment]
Can I pick this up ?

**Comment by deepak-gittyup** [comment]
Hi @manusa 
The first task of this ticket is pretty straight-forward 

I had a question about the 2nd task: _Create a unit test to verify your changes_

- Is the test simply suppose to ensure that the condition containing the LOG.warn statement is exercised ?
  ```
      if (entity != null) {
          LOG.warn("Invalid class {} when expecting {} for instance: {}",
                  entity.getClass().getName(),
                  clazz.getName(),
                  entity);
      }
  ```
- Or is the test expected to have a mechanism to intercept LOG.warn(...) and ensure that the expected message is indeed propagated to the handler

**Comment by manusa** [comment]
Hi @deepak-gittyup,

I'm really glad to see that you're interested in the bonus part of the issue.

The issue description is really vague, sorry for that. The lack of details is partly in purpose so that the contributor engages in a conversation to clarify, just like you did :trophy:.

If you check the `UserConfigurationCompareTest` class, there's no test for the method you just modified.

If you check the usages for castTo, it's only used internally, it really makes no sense to have this method exposed. :one:  Maybe it would be interesting to change its modifier from `protected static` to `private static`.

In case you perform the above change, the only way to test your changes is by testing the `configEqual` method (Hint, :two:  a test named `testConfigEqualWhenMapAndString` would cover your changes).

Extra ball, if you carefully check the `configEqual` method you might be able to spot something that's not OK.

> Is the test simply suppose to ensure that the condition containing the LOG.warn statement is exercised 

For the current changes, it should be enough. You could mock or spy the log and verify that the call was actually performed according to the changes, but it might not be worth the effort.

**Comment by deepak-gittyup** [comment]
Hi @manusa 
Thankyou for the clarification and for the quick reply

> If you check the usages for castTo, it's only used internally, it really makes no sense to have this method exposed. 1️⃣ Maybe it would be interesting to change its modifier from protected static to private static.

Is it okay if I make the `protected` to `private` change in the same commit that includes the change for the originally intended _Use the built-in formatting..._ change ? 
Or should it be treated as a separate commit ?

> In case you perform the above change, the only way to test your changes is by testing the configEqual method (Hint, 2️⃣ a test named testConfigEqualWhenMapAndString would cover your changes).

👍 

> Extra ball, if you carefully check the configEqual method you might be able to spot something that's not OK.

After staring at the code, this is what caught my attention
The code now is:
```
if (entity1 == entity2) {
    return true;
} else if (entity1 == null || entity2 == null) {
    return false;
} else if (entity1 instanceof Map) {
    return configEqualMap((Map) entity1, castTo(Map.class, entity2));
} else if (entity2 instanceof Map) {
    return configEqualMap((Map) entity1, castTo(Map.class, entity2));
} else if (entity2 instanceof ObjectMeta) {
    return configEqualObjectMeta((ObjectMeta) entity1, castTo(ObjectMeta.class, entity2));
} else if (entity1 instanceof Collection && entity2 instanceof Collection) {
    return collectionsEqual((Collection) entity1, (Collection) entity2);
}
.
.
.
```
My understanding is:
`else if (entity2 instanceof ObjectMeta) {`
should be changed to
`else if (entity1 instanceof ObjectMeta) {`

Also, I was wondering, if the below condition (3rd `else if ` block) is required
```
else if (entity2 instanceof Map) {
            return configEqualMap((Map) entity1, castTo(Map.class, entity2));
}
```
Even if entity2 is not a map, when it is passed down to `castTo` method, it will return null/false

After addressing these 2 cases, it reduces to 
```
if (entity1 == entity2) {
    return true;
} else if (entity1 == null || entity2 == null) {
    return false;
} else if (entity1 instanceof Map) {
    return configEqualMap((Map) entity1, castTo(Map.class, entity2));
} else if (entity1 instanceof ObjectMeta) {
    return configEqualObjectMeta((ObjectMeta) entity1, castTo(ObjectMeta.class, entity2));
} else if (entity1 instanceof Collection && entity2 instanceof Collection) {
    return collectionsEqual((Collection) entity1, (Collection) entity2);
}
.
.
.
```

**Comment by deepak-gittyup** [comment]
Hi @manusa 
A polite reminder :) 
Any inputs from the previous comment👆

**Comment by manusa** [comment]
Hi @deepak-gittyup,

Sorry for the late replay, I just came back from PTO.

> Is it okay if I make the protected to private... ...a separate commit ?

Just keep it in the same commit, sth like `refactor: fix sonar warnings` might make sense for this set of changes.


> Also, I was wondering, if the below condition (3rd else if block) is required

I'm not sure if it's required (tests are always helpful in these situations) but as you say, line 59 could  be changed to `entity1 instanceof Map || entity2 instanceof Map` and then use the `castTo` method for safety in both entities (also this considers that configEqualsMap does a null check again.

> should be changed to
> `else if (entity1 instanceof ObjectMeta) {`

Yes, there's a potential ClassCastException there. Just like with the Map case, maybe both entities should be checked to see if they are instances of ObjectMeta.
