### ISSUE TITLE
OpenShiftBuildTask: implement oc:build for XML configuration mode equivalent functionality for OpenShift Gradle Plugin

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#849]
## Description

Child of #31

Implement the Groovy DSL configuration  mode for ocBuild taks of the OpenShift Gradle Plugin -> `OpenShiftBuildTask`.

- Any OpenShift specific configuration setting should be part of the OpenShiftExtension class (Tasks should have no Inputs)
- Any logic present in the current Mojos should be moved to JKube-kit

## AC
- [x] Image can be built using S2I build strategy (cluster)
- [x] Image can be built using Docker build strategy (cluster)
- [x] Image can be built usig Jib build strategy (local)
- [x] doc: Provide a quickstart
- [x] doc: Create appropriate asciidoc entry

**Comment by rohanKanojia** [comment]
Can we close this issue?
