### ISSUE TITLE
`%n` should be used in place of `\n` to produce the platform-specific line separator.

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#854]
We have this use of `\n` in `String.format` statements here which is a line delimiter on Linux:

https://github.com/eclipse/jkube/blob/5a1828c0ece30567fdcf89ce7668bb8c2003211d/jkube-kit/config/image/src/main/java/org/eclipse/jkube/kit/config/image/ImageName.java#L269-L273

We should use `%n` instead which will be portable across different platforms.

#### Kubernetes

If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.

- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)

#### OpenShift

If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.

Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Onyinye91-ctrl** [comment]
Hello @rohanKanojia Can i task this?

**Comment by Onyinye91-ctrl** [comment]
@rohanKanojia i have worked on it. Can you see it or should redo?

**Comment by rohanKanojia** [comment]
Are your referring to https://github.com/Onyinye91-ctrl/jkube/commit/4da0e3c733cf1d8da1c9539ccc86f0cdf3fd1b71 ? I think it looks good. Could you please create a pull request against this repository so that it can be merged?
