### ISSUE TITLE
LogMojo : Rename variables in order to align with documentation

### ISSUE THREAD

**Issue by rohanKanojia** [eclipse/jkube#868]
Right now there is a mismatch between variable names in Mojos and in the [plugin documentation](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#jkube:log). Although it's harmless since variables are `private` and can't be directly used in XML configuration. 

But for avoiding confusion, it's better to rename them.
https://github.com/eclipse/jkube/blob/2bd55bcc7c830e50929b6ede5d0da242e42dda30/kubernetes-maven-plugin/plugin/src/main/java/org/eclipse/jkube/maven/plugin/mojo/develop/LogMojo.java#L37-L41

- [x] Rename `followLog` -> `logFollow`
- [x] Rename `podName` -> `logPodName`

**Comment by izzy-el** [comment]
Can I pick this up?

**Comment by izzy-el** [comment]
Thank you! This is my first open source contribution. Where can I see the rules for contributing to this repository?
And, just to be sure, I need to fork this repository and create a new branch, right?

**Comment by rohanKanojia** [comment]
Yes, you're right. You'd need to fork the repository, create a new branch and push it to your fork. After pushing it, you would need to create a PR from Github UI. Maybe this guide can help clear your doubts better: https://www.dataschool.io/how-to-contribute-on-github/.

In order to contribute to Eclipse, you would need to create an [Eclipse Account](https://accounts.eclipse.org/) and Sign [Eclipse Contributor Agreement](https://accounts.eclipse.org/user/login?destination=user/eca). Once you've created an eclipse account you would need to update your commit message with a `Signed-off-by:` footer. You can do it like this:
```
# (Optional): Configure Git User and Email
git config user.name "Your Name"
git config user.email "your_email@example.com"

# Amend your previous commit with signed off footer
git commit --amend --signoff
```

**Comment by izzy-el** [comment]
I appreciate it. Right now, I just finished my commit on my fork on a new branch that I have created. I am opening a PR right now and I was going through the checklist. Two of the items is to test my changes on the code in either Kubernetes or OpenShift. How can I test my code on them? I mean, even though I just changed the variables name, I feel like this is something I should do.

**Comment by tejassinghsital** [comment]
Hi I am a beginner and want to contribute to open source. I am looking for some simple issues that I can resolve. Please respond back.

**Comment by manusa** [comment]
Hi @tejassinghsital ,

> Hi I am a beginner and want to contribute to open source. I am looking for some simple issues that I can resolve. Please respond back.

https://github.com/eclipse/jkube/issues?q=is%3Aissue+is%3Aopen+label%3Afirst-timers-only

They are all taken right now. We'll be adding a few more later today.

**Comment by rohanKanojia** [comment]
@izzy-el: cool, In order to do this you would need to get access to a Kubernetes cluster. If you want to install it locally, you can use [minikube](https://minikube.sigs.k8s.io/) or [kind](https://kind.sigs.k8s.io/docs/). For OpenShift, you can get a free instance at Red Hat Developer Sandbox: https://developers.redhat.com/developer-sandbox

Once you have access to a Kubernetes Cluster; You need to build a SNAPSHOT version of jkube. You can do this by running this command (`mvn clean install` or `mvn clean install -DskipTests`(faster)) in jkube project directory.

You can go to some quickstart in `quickstarts/maven` folder, modify `jkube.version` property and then run:
```
# Run eval $(minikube -p minikube docker-env) first to expose minikube docker daemon to local session
mvn package k8s:build k8s:resource k8s:apply`
```
 In case of OpenShift it should be:
```
mvn package oc:build oc:resource oc:apply
```
This should deploy the application.
