### ISSUE TITLE
DockerAccessWithHcClient.java: Change this "try" to a try-with-resources.

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#878]
### Description
The following statement is reported as a Critical Code Smell by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AXCb0Ufhych7OcxsbwfL&open=AXCb0Ufhych7OcxsbwfL):
 
https://github.com/eclipse/jkube/blob/e5f1554e4a63b7aeda50f9ad1a8d5c13a72733f3/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/hc/DockerAccessWithHcClient.java#L179-L195
 
- [ ] should be changed to:
```java
            public Object handleResponse(HttpResponse response) throws IOException {
                try (InputStream stream = response.getEntity().getContent();
                    LineNumberReader reader = new LineNumberReader(new InputStreamReader(stream))) {
                    String line;
                    try {
                        callback.open();
                        while ( (line = reader.readLine()) != null) {
                            callback.log(1, new Timestamp(), line);
                        }
                    } catch (LogCallback.DoneException e) {
                        // Ok, we stop here ...
                    } finally {
                        callback.close();
                    }
                }
                return null;
            }
```
 
### Bonus
 
- [ ] This code block has an additional very easily solvable code smell or improvement. 
  - Identify the code smell (hint: λ)
  - Create the fix
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by praneethjreddy** [comment]
@manusa Can I pick this up ?

**Comment by praneethjreddy** [comment]
Here is the new code block after changing anonymous implementation to lambda:

`return response -> {
            try (InputStream stream = response.getEntity().getContent();
                 LineNumberReader reader = new LineNumberReader(new InputStreamReader(stream))) {
                String line;
                try {
                    callback.open();
                    while ( (line = reader.readLine()) != null) {
                        callback.log(1, new Timestamp(), line);
                    }
                } catch (LogCallback.DoneException e) {
                    // Ok, we stop here ...
                } finally {
                    callback.close();
                }
            }
            return null;
        };`

**Comment by rohanKanojia** [comment]
I'm perfectly okay with converting this to lambda as well if it breaks nothing

**Comment by shubham-singh-748** [comment]
Where to do change in code, it looks like to be same, i don't think, this code needs to change.....

**Comment by manusa** [comment]
> Where to do change in code, it looks like to be same, i don't think, this code needs to change.....

Don't worry, this issue is already being handled by @praneethjreddy and there's a PR (#879) that will be merged imminently.
