### ISSUE TITLE
Unreachable statement

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#88]
## Description

The following statement is unreachable:
https://github.com/eclipse/jkube/blob/8ccdddae80aeaf5ba849aefdd98e87197e12ced8/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java#L411

Analyze what happened to the logic in the following lines:
https://github.com/eclipse/jkube/blob/8ccdddae80aeaf5ba849aefdd98e87197e12ced8/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/core/assembly/DockerAssemblyManager.java#L403-L409

Perform necessary actions

**Comment by rohanKanojia** [comment]
Umm, I replaced maven specific `Artifact` with a `File` class. If you see this in Docker Maven Plugin source:

https://github.com/fabric8io/docker-maven-plugin/blob/master/src/main/java/io/fabric8/maven/docker/assembly/DockerAssemblyManager.java#L494

```
    private File ensureThatArtifactFileIsSet(MavenProject project) {
        Artifact artifact = project.getArtifact();
        if (artifact == null) {
            return null;
        }
        File oldFile = artifact.getFile();
        if (oldFile != null) {
            return oldFile;
        }
        Build build = project.getBuild();
        if (build == null) {
            return null;
        }
        String finalName = build.getFinalName();
        String target = build.getDirectory();
        if (finalName == null || target == null) {
            return null;
        }
        File artifactFile = new File(target, finalName + "." + project.getPackaging());
        if (artifactFile.exists() && artifactFile.isFile()) {
            setArtifactFile(project, artifactFile);
        }
        return null;
    }
```

I think we should remove this artifact assignment and assign `project.getArtifact()` directly to `oldFile`
