### ISSUE TITLE
busybox image name is hardcoded in VolumePermissionEnricher class, need to make it as config

### ISSUE THREAD

**Issue by kumar-cloud** [eclipse/jkube#891]
### Description

**busybox** image name is hardcoded in [VolumePermissionEnricher.java Line 115](https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java#L115).
Now a days every one have their own ECR registries maintained.Few people are using Dockerhub pro version to pull images.
Due to this , we are getting rate limiting issue from Dockerhub. So Please make this image name as config for enricher.

Where is this code :
```
return new ContainerBuilder()
                        .withName(ENRICHER_NAME)
                        .withImage("busybox")
                        .withImagePullPolicy("IfNotPresent")
                        .withCommand(createChmodCommandArray(mountPoints))
                        .withVolumeMounts(createMounts(mountPoints))
                        .build();
```

Thanks to @rohanKanojia for providing  hint on fix.
How to fix:
Maybe we can add another field in enricher configuration to override image name: https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java#L57

### Info

* Eclipse JKube version : master
* Maven version (`mvn -v`) : Apache Maven 3.6.3
```

```
* Kubernetes / Red Hat OpenShift setup and version :

* If it's a bug, how to reproduce :
* Use Dockerhub as registry without credentials. recently Dockerhub has introduced RateLimiting for Pulling images.

**Comment by manusa** [comment]
Hi @kumar-cloud,

Thanks for reporting.

> Maybe we can add another field in enricher configuration to override image name: https://github.com/eclipse/jkube/blob/master/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/VolumePermissionEnricher.java#L57

Yes, this is exactly what needs to be done. Would you be interested in contributing a fix?

**Comment by kumar-cloud** [comment]
Hi Team

Yes I would like to if possible. But I never contributed anything till now.
It would be a good experience for me.

If someone help me with steps...On process.

**Comment by rohanKanojia** [comment]
@kumar-cloud : We have this webpage regarding contributing to project[0]. Please review it and see if it helps(You're also welcome to provide feedback regarding improvements since you would have a fresh perspective).

In case of any doubt, you can always reach out to us on Gitter Channel[1] (like you previously did). Our channel is usually active during IST/CET timezones.

[0] https://www.eclipse.org/jkube/contributing 
[1] https://gitter.im/eclipse/jkube

**Comment by kumar-cloud** [comment]
Hi Marc

Can you please merge the fix.
