### ISSUE TITLE
JIB Image Build Regession in 1.4.0

### ISSUE THREAD

**Issue by rohanmars** [eclipse/jkube#895]
Seems like there has been a bug/side effect introduced in 1.4.0 with build jib images.
 
The same image build that worked in versions before now gets an error when I run mvn install:

[ERROR] Failed to execute goal org.eclipse.jkube:kubernetes-maven-plugin:1.4.0:build (default) on project jkube-java-builder: Failed to execute the build: Error when building JIB image: Failed to create directory: /home/user/s2i-test/target/docker/test/1.0.0-SNAPSHOT/build/ -> [Help 1]

What is strange, is after that build, the folder has been created and if you run mvn install again it works.

The config is:

<images>
          <image>
                   <name>test:1.0.0-SNAPSHOT</name>

**Comment by manusa** [comment]
Hi @rohanmars,
Thanks for your report. Could you please provide some way to reproduce this issue?

**Comment by manusa** [comment]
I managed to reproduce the issue (https://github.com/marcnuri-demo/202109-quarkus-cafe/runs/3650824725?check_suite_focus=true)

Problem in:
https://github.com/eclipse/jkube/blob/93a66d007ad1c6169ba804959c81c7d3e279b6f0/jkube-kit/common/src/main/java/org/eclipse/jkube/kit/common/util/FileUtil.java#L251

Directory is created but returns false (I think last canonical `/` messes the method).

Could be replaced by `FileUtils#forceMkdir`
