### ISSUE TITLE
Quickstarts: Port spring-boot-helm quickstart

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#900]
## Description

Child of #31 
Blocked by k8sHelm goal implementation

Port spring-boot-helm Maven quickstart to Gradle.

**Comment by rohanKanojia** [comment]
We already seem to have a [Spring Boot Helm Quickstart](https://github.com/eclipse/jkube/tree/master/quickstarts/gradle/spring-boot-helm). I'll address https://github.com/eclipse/jkube/pull/1071#discussion_r736614921 in the scope of this issue
