### ISSUE TITLE
The provider name appears to be hardcoded, it would need to be configurable

### ISSUE THREAD

**Issue by mborra** [eclipse/jkube#913]
### Description

The provider name appears to be hardcoded, it would need to be configurable.

I have changed the `<provider>` in the labels using `<resources><labels><all>`, now the selector does not find the match due to the fact that the `provider` in the `selector` cannot be changed. If I can change the label I don't see why I can't change the `provider` in the `selector`.

### Info

* Eclipse JKube version : 
```
1.4.0
```
* Maven version (`mvn -v`) :
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\opt\apache-maven-3.6.3\bin\..
Java version: 11.0.6, vendor: AdoptOpenJDK, runtime: C:\opt\jdks\adoptopenjdk.net\jdk-11.0.6+10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```
See also discussion on Gitter (@manusa)

**Comment by manusa** [comment]
This is handled in the ProjectLabelEnricher.

It could be tackled just like we do with the [`app` label](https://github.com/eclipse/jkube/blob/ca84ce4f59a60c3aef18afdfc1f28c06a6ffc421/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricher.java#L198) by adding a configuration.

So adding a configuration here:

https://github.com/eclipse/jkube/blob/ca84ce4f59a60c3aef18afdfc1f28c06a6ffc421/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricher.java#L68-L70

```java
      USE_PROJECT_LABEL("useProjectLabel", "false"),
      APP("app", null),
      PROVIDER("app", "jkube");
```

And replacing the following line

https://github.com/eclipse/jkube/blob/ca84ce4f59a60c3aef18afdfc1f28c06a6ffc421/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/ProjectLabelEnricher.java#L202

with:

```java
        ret.put(LABEL_PROVIDER, getConfig(Config.PROVIDER));
```

Documentation and tests for the enricher should be updated accordingly too.

#### Relates to
- https://gitter.im/eclipse/jkube?at=60fbe5767331d202b5c9e372

**Comment by nishantraut** [comment]
Hi @manusa,

Can i help on this

**Comment by rohanKanojia** [comment]
@nishantraut : This issue is tagged as help wanted. I think it's perfectly fine for you to pick this. If you're okay with it, I can assign you the issue.

**Comment by nishantraut** [comment]
Hi @rohanKanojia,
Yes please assign it to me. Thanks.
