### ISSUE TITLE
PortForwardService.java: "InterruptedException" should not be ignored

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#936]
### Description
The following statement is reported as a Bug by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AXhZi-z5MtwvSXpgYorx&open=AXhZi-z5MtwvSXpgYorx):
 
https://github.com/eclipse/jkube/blob/2a2c30a78dfb26afb89282c67e6c528429b9c34e/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/PortForwardService.java#L170
 
- [x] should be changed to:
```java
          } catch (InterruptedException e) {
            Thread.currentThread().interrupt();
          }
```
 
### Bonus
 
- [ ] A few lines before there is another code-smell. Identify it and propose a fix.
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by avikkundu** [comment]
want to work on it.

**Comment by avikkundu** [comment]
pull request created

**Comment by avikkundu** [comment]
I am new to open source. please let me know if the issue is solved.

**Comment by rohanKanojia** [comment]
@avikkundu Have you created an eclipse account and signed ECA? You'll also need to add a `signed-off by` footer to your commit message
