### ISSUE TITLE
JibBuildService.java: "InterruptedException" should not be ignored

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#937]
### Description
The following statement is reported as a Bug by [https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AXhZi-zZMtwvSXpgYorw&open=AXhZi-zZMtwvSXpgYorw):
 
https://github.com/eclipse/jkube/blob/96c706847bf2e87bdb9c28692e25312aa6d0fae0/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/kubernetes/JibBuildService.java#L103-L105
 
- [x] should be changed to:
```java
        } catch (InterruptedException ex) {
            Thread.currentThread().interrupt();
        } catch (Exception ex) {
            throw new JKubeServiceException("Error when building JIB image", ex);
        }
```
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by vignesh1992** [comment]
Hi @manusa, Can I pick it to work on?

**Comment by vignesh1992** [comment]
Hi, I have raised a PR #[948](https://github.com/eclipse/jkube/pull/948) for review. Request you to kindly let me know your feedbacks if there are anything more which I can add to it. Thank you so much!
