### ISSUE TITLE
PortForwardTask.java: Either re-interrupt this method or rethrow the "InterruptedException" that can be caught here.

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#966]
### Description
The following statement is reported as a Bug by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AXhZi-zIMtwvSXpgYorv&open=AXhZi-zIMtwvSXpgYorv):
 
https://github.com/eclipse/jkube/blob/af40c8f27af57f9651f8ebb1634df33eaf909f6a/jkube-kit/config/service/src/main/java/org/eclipse/jkube/kit/config/service/portforward/PortForwardTask.java#L49-L51
 
- [x] should be changed to:
```java
    } catch (InterruptedException ex) {
      Thread.currentThread().interrupt();
    } catch (Exception exception) {
      logger.warn("Not able to port forward: %s", exception.getMessage());
    } finally {
```

#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by siddhantdixit** [comment]
@manusa Can i work on this?

**Comment by manusa** [comment]
Hi @siddhantdixit 
Your help is greatly appreciated, but you already have a contribution for this repo (#953 / #962), let's keep it open so that others can contribute here too.

**Comment by Stellar-X** [comment]
@manusa , Can I contribute on this? I don't know the manually testing part though but I know Java Exception Handling.

**Comment by manusa** [comment]
Hi @Stellar-X 
That's the standard template for our first time issues. If you want to take full advantage of this learning path, you can build the project and then test that this feature is working.

In this case you should compile the project. Then you can go into the spring-boot quickstart and test the `k8s:debug` goal:
```shell
## Example in minikube
eval $(minikube docker-env)
mvn clean install -DskipTests
cd quickstarts/maven/spring-boot 
mvn -Djkube.version=1.5.0-SNAPSHOT -Pkubernetes clean package k8s:build k8s:resource k8s:apply
mvn k8s:debug
# A debug session port will be open, you can start a remote debug session from your favorite IDE
# Add a breakpoint in the quickstart code and invoke the endpoint.
# Your IDE should stop at the appropriate line
# Once this works, press ctrl+c to abort the debug session
```

**Comment by manusa** [comment]
It's really cool that you are going the extra-mile :clap: 

It took quite long for the build to finish, I guess it might be related to your Internet connection. Subsequent builds should take no more and 2 minutes.

When running with Minikube ( 'eval $(minikube docker-env)'), Docker desktop is not really needed, or at least doesn't count in the equation.

I think you might have not started your Minikube cluster, or that your kubectl config is not pointing to the right cluster.
However, on your second attempt it seemed to work (not sure if you changed anything there).
Make sure this works:
```shell
$ kubectl config use-context minikube
$ kubectl get nodes
NAME       STATUS   ROLES                  AGE   VERSION
minikube   Ready    control-plane,master   12h   v1.21.5
```

Last failure is my fault, you need to select the Kubernetes profile (I'll update my prior comment too)

```shell
mvn -Djkube.version=1.5.0-SNAPSHOT -Pkubernetes k8s:debug
```

**Comment by Attyuttam** [comment]
Hi @manusa, I can see that this issue is still open. Will it be okay if I pick up this issue ? I am new to contributing to open source and this might be my first contribution ever so I am not aware of the norms so please pardon me if the question is not suitable here.

**Comment by rohanKanojia** [comment]
@Attyuttam: Hi, it's been a month of inactivity by currently assigned user so I think it's okay for you to pick this. Please go through https://www.eclipse.org/jkube/contributing . You'd need to create an Eclipse Account and sign off your commit by `Signed-Off-By` footer (`git commit --signoff`).

**Comment by Attyuttam** [comment]
Sure @rohanKanojia

**Comment by rohanKanojia** [comment]
@Attyuttam : Feel free to contact us in case you have any questions on our Gitter public channel[0]

[0] https://gitter.im/eclipse/jkube

**Comment by Attyuttam** [comment]
> Hi @Stellar-X That's the standard template for our first time issues. If you want to take full advantage of this learning path, you can build the project and then test that this feature is working.
> 
> In this case you should compile the project. Then you can go into the spring-boot quickstart and test the `k8s:debug` goal:
> 
> ```shell
> ## Example in minikube
> eval $(minikube docker-env)
> mvn clean install -DskipTests
> cd quickstarts/maven/spring-boot 
> mvn -Djkube.version=1.5.0-SNAPSHOT -Pkubernetes clean package k8s:build k8s:resource k8s:apply
> mvn -Djkube.version=1.5.0-SNAPSHOT -Pkubernetes k8s:debug
> # A debug session port will be open, you can start a remote debug session from your favorite IDE
> # Add a breakpoint in the quickstart code and invoke the endpoint.
> # Your IDE should stop at the appropriate line
> # Once this works, press ctrl+c to abort the debug session
> ```

Hi, I was able to go through all the steps mentioned above by @manusa and then run the debug session which produced the following code:
 
```
 k8s: Using Kubernetes at https://172.28.50.128:8443/ in namespace default with manifest D:\projects\open-source\jkube\quickstarts\maven\spring-boot\target\classes\META-INF\jkube\kubernetes.yml
[INFO] k8s: Enabling debug on Deployment spring-boot
[INFO] k8s: Updating Deployment spring-boot with Debug variables in containers
[INFO] k8s: Updating Deployment from kubernetes.yml
[INFO] k8s: Updated Deployment: target\jkube\applyJson\default\deployment-spring-boot-9.json
[INFO] k8s: Debug Pod ready: spring-boot-669468599c-zg8dx
[INFO] k8s: Starting port forwarding to port 5005 on pod spring-boot-669468599c-zg8dx
[INFO] k8s: Port Forwarding started
[INFO] k8s: Now you can start a Remote debug session by using localhost and the debug port 5005
[INFO] k8s: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005

```
After that, I followed the steps given below but still encountered an issue:

1. Started the debug session with host: localhost and port 5005 
2. hit the application running on kubernetes by running the command "minikube service spring-boot"
3. Now, I have set the debug point at the controller code, but I am getting an error "Cannot find source" , I have added the Jar file as well.

Can you please suggest.

**Comment by rohanKanojia** [comment]
Could you please add a full stack trace of the error you're getting?

**Comment by Attyuttam** [comment]
its not an error but its not being able to find the jar file containing the code for HelloController.java I think

As you can see , since i have put a debug point at /jkube/quickstarts/maven/spring-boot/src/main/java/org/eclipse/jkube/maven/sample/spring/boot/HelloController.java(line 29) , it tries to hit the break point but since the jar is not available to the debug session in eclipse, its not being able to find the source.

i am not sure why the jar is not available.

<img width="457" alt="image" src="https://user-images.githubusercontent.com/21972645/143411582-407655d0-bf41-4054-a703-0cb197716c7b.png">

**Comment by rohanKanojia** [comment]
Do you have your branch somewhere which I can pull and try out?

**Comment by Attyuttam** [comment]
@rohanKanojia  sure. This is my branch: https://github.com/Attyuttam/jkube/tree/feature/attyutttam-issue-966
Thank you for looking into it

**Comment by Attyuttam** [comment]
Just my perspective.
I think this is an issue with me failing to add the jar properly in eclipse during debug, probably not with the code.
Please feel free to suggest.

**Comment by rohanKanojia** [comment]
I tried out testing `k8s:debug` on your branch and it's working as expected for me :+1:

**Comment by Attyuttam** [comment]
> I tried out testing `k8s:debug` on your branch and it's working as expected for me 👍

That's great. I was of the feeling I was getting the issue because of the incorrect placement of JARs in eclipse. Pardon me as I am using eclipse for the first time. I have raised the PR but its currently failing due to a check failure at codecov/patch. Can you please suggest if I would need to add a test for that part or not. I am aware of Sonar checks but not codecov.

here's my PR: https://github.com/eclipse/jkube/pull/1144

many thanks for your support.
