### ISSUE TITLE
SpringBootWatcher.java: Either re-interrupt this method or rethrow the "InterruptedException" that can be caught here.

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#967]
### Description
The following statement is reported as a Bug by [SonarCloud](https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AXhZi-7AMtwvSXpgYor1&open=AXhZi-7AMtwvSXpgYor1):
 
https://github.com/eclipse/jkube/blob/af40c8f27af57f9651f8ebb1634df33eaf909f6a/jkube-kit/jkube-kit-spring-boot/src/main/java/org/eclipse/jkube/springboot/watcher/SpringBootWatcher.java#L217-L219
 
- [x] should be changed to:
```java
                } catch(InterruptedException ex) {
                    Thread.currentThread().interrupt();
                } catch (Exception e) {
                    throw new RuntimeException("Failed to run RemoteSpringApplication: " + e, e);
                }
```

#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by inomag** [comment]
Can I work on this issue?
