### ISSUE TITLE
LogOutputSpec.java: Member variables can be declared final

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#972]
### Description
`LogOutputSpec` declares several class fields that are only initialized in the constructor. They can be declared final.

The following code fragment:

https://github.com/eclipse/jkube/blob/969025bf6bd21f22ec02ef4a72174ae49aaad5bb/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/access/log/LogOutputSpec.java#L44-L47

- [x] should be changed to:
```java
    private final String prefix;
    private final Ansi.Color color;
    private final DateTimeFormatter timeFormatter;
    private final String file;
```
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by mihirterna** [comment]
Hi @manusa , I would like to work on it. Can you please assign it to me?

**Comment by mihirterna** [comment]
Have created PR #973. Please review.

**Comment by mihirterna** [comment]
Hi @manusa , Requesting you to review PR #976 . Thanks.
