### ISSUE TITLE
IngressEnricher's opinionated path type is too restrictive

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#975]
### Description

While adding [configuration options](https://www.eclipse.org/jkube/docs/kubernetes-maven-plugin#jkube-ingress) to the IngressEnricher (#551), we also included new functionality to be able to convert Ingresses from one Api Group (`networking.k8s.io/v1` / `extensions/v1beta1`) (#723).

This change introduced the [`pathType` field](https://kubernetes.io/docs/concepts/services-networking/ingress/#path-types) which is mandatory in `v1`. However, as default value we added `Exact` which is too restrictive. We should replace this value so that we delegate the setting to the Ingress Controller (just like it happens in `extensions/v1beta1`). This means replacing `Exact` with `ImplementationSpecific`.

The following code fragment:

https://github.com/eclipse/jkube/blob/82319bd54a52a0525d0c889fe3bea6c1b99176ed/jkube-kit/enricher/generic/src/main/java/org/eclipse/jkube/enricher/generic/NetworkingV1IngressGenerator.java#L115

- [x] should be changed to:
```java
                            .withPathType("ImplementationSpecific")
```
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by Onyinye91-ctrl** [comment]
@manusa i want to take this
