### ISSUE TITLE
AwsSigner4.java: Reorder the modifiers to comply with the Java Language Specification.

### ISSUE THREAD

**Issue by manusa** [eclipse/jkube#986]
### Description
The following statement is reported as a Minor Code Smell by [https://sonarcloud.io/project/issues?id=jkubeio_jkube&issues=AXCb0Ulyych7Ocxsbwfu&open=AXCb0Ulyych7Ocxsbwfu):
 
https://github.com/eclipse/jkube/blob/969025bf6bd21f22ec02ef4a72174ae49aaad5bb/jkube-kit/build/service/docker/src/main/java/org/eclipse/jkube/kit/build/service/docker/auth/ecr/AwsSigner4.java#L43
 
- [x] should be changed to:
```java
    private static final char[] HEXITS = "0123456789abcdef".toCharArray();
```
 
#### Kubernetes
 
If you don't have a real Kubernetes cluster available (most probably), you can use Minikube or Kind to test with a local cluster.
 
- Minikube [get started guide](https://minikube.sigs.k8s.io/docs/start/)
- Kind (Requires Docker) [quick start](https://kind.sigs.k8s.io/docs/user/quick-start/)
 
#### OpenShift
 
If you don't have a real OpenShift cluster available (most probably), you can use [Red Hat's developer Sandbox for Red Hat OpenShift](https://developers.redhat.com/developer-sandbox). The only requirement is to have a Red Hat account.
 
Once you have your Sandbox environment, you'll need to download the oc tool from the cluster console.
(Press the `?` icon and from the context menu select `Command line tools`, you'll be redirected to https://$subdomain.openshiftapps.com/command-lines-tools where you'll be able to download the CLI for your platform)

**Comment by kanumalivad** [comment]
Kindly assign to me
